### ISSUE TITLE
Question - Best Practises for Hotkeys Values?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1004]
I've been sending my Hammerspoon script out to various people to test, and one of the things I've noticed is that I'll get back errors like:

```
*** ERROR: ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:408: Invalid key: /
stack traceback:
	[C]: in function 'error'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:23: in upvalue 'getKeycode'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:189: in function 'hs.hotkey.new'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:408: in method 'bind'
	/Users/Fleak/.hammerspoon/init.lua:218: in function 'loadScript'
	/Users/Fleak/.hammerspoon/init.lua:2608: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
	(...tail calls...)
```

Even though my system is fine with:

`hotkeys:bind({"ctrl", "option", "command"}, "/", function() colorBoardSelectPuck(5) end)`

...it seems to cause issues on other machines. I've tried changing it to:

`hotkeys:bind({"ctrl", "option", "command"}, hs.keycodes.map[44], function() colorBoardSelectPuck(5) end) -- /`

...so hopefully that helps.

However, I'm just curious... what's the best practise for hotkey naming if you're planning to use the script on lots of different keyboard layouts?

Thanks in advance!

**Comment by asmagill** [comment]
The hotkey's are based on the keycodes, which are more accurately thought of as "position on the keyboard" rather than as "such-and-such a character".  What the `hs.hotkey` code does is take the character you specify, in this case "\", look up it's keycode value for the current layout, and if it exists, use the number for the position that represents that character... as you've found, if the character does not have a position in the current layout, there is no number returned, and the keybinding fails.

When you use one, or very similar, keyboard layouts, the use of the string version of the character you want makes the intention more obvious; when you use widely differing keyboard layouts, it becomes error prone.

In your case, using `hs.keycodes.map[44]` (or even the simpler `44` -- the `hs.hotkey` functions can take a keycode number directly) makes more sense -- it is basically saying that you want to bind this function to whatever key is at position 44 on the keyboard.

https://github.com/Hammerspoon/hammerspoon/issues/984#issuecomment-247505020 shows a bare-bones example of how you could set things up if you actually want to specify a specific character based on the layout -- in the example given there using the number would actually be simpler, since the keys specified are in the same physical location in the target layouts, but the use of the keymap watcher shows how you could change things when the layout changes.

**Comment by latenitefilms** [comment]
Perfect, thank you! I'll just hardcode the numbers. Cheers!

**Comment by latenitefilms** [comment]
@asmagill - The table returned by **hs.keycodes.map** changes depending on what current keyboard layout you're using, which makes complete sense.

However, as I'm doing all my coding in English, but I have no idea what keyboard layouts people will be using when using my script - I was just wondering if there's a way to build a function that "translates" between different keyboard layouts. For example, something like:

```
-- keyCodeTranslator(input, inputKeyboardLayout, outputKeyboardLayout)
keyCodeTranslator("a", "Australian", "Russian")
> ф, 0
keyCodeTranslator("ф", "Russian", "Australian")
> a, 0
```

Thoughts?

**Comment by latenitefilms** [comment]
Actually... thinking about it... rather than "translating" everything, I could probably just do all my "calculations" in English. Will close this discussion for now, and see if it works...

```
function keyCodeTranslator(input)

	local englishKeyCodes = {
		["'"] = 39,
		[","] = 43,
		["-"] = 27,
		["."] = 47,
		["/"] = 44,
		["0"] = 29,
		["1"] = 18,
		["2"] = 19,
		["3"] = 20,
		["4"] = 21,
		["5"] = 23,
		["6"] = 22,
		["7"] = 26,
		["8"] = 28,
		["9"] = 25,
		[";"] = 41,
		["="] = 24,
		["["] = 33,
		["\\"] = 42,
		["]"] = 30,
		["`"] = 50,
		["a"] = 0,
		["b"] = 11,
		["c"] = 8,
		["d"] = 2,
		["delete"] = 51,
		["down"] = 125,
		["e"] = 14,
		["end"] = 119,
		["escape"] = 53,
		["f"] = 3,
		["f1"] = 122,
		["f10"] = 109,
		["f11"] = 103,
		["f12"] = 111,
		["f13"] = 105,
		["f14"] = 107,
		["f15"] = 113,
		["f16"] = 106,
		["f17"] = 64,
		["f18"] = 79,
		["f19"] = 80,
		["f2"] = 120,
		["f20"] = 90,
		["f3"] = 99,
		["f4"] = 118,
		["f5"] = 96,
		["f6"] = 97,
		["f7"] = 98,
		["f8"] = 100,
		["f9"] = 101,
		["forwarddelete"] = 117,
		["g"] = 5,
		["h"] = 4,
		["help"] = 114,
		["home"] = 115,
		["i"] = 34,
		["j"] = 38,
		["k"] = 40,
		["l"] = 37,
		["left"] = 123,
		["m"] = 46,
		["n"] = 45,
		["o"] = 31,
		["p"] = 35,
		["pad*"] = 67,
		["pad+"] = 69,
		["pad-"] = 78,
		["pad."] = 65,
		["pad/"] = 75,
		["pad0"] = 82,
		["pad1"] = 83,
		["pad2"] = 84,
		["pad3"] = 85,
		["pad4"] = 86,
		["pad5"] = 87,
		["pad6"] = 88,
		["pad7"] = 89,
		["pad8"] = 91,
		["pad9"] = 92,
		["pad="] = 81,
		["padclear"] = 71,
		["padenter"] = 76,
		["pagedown"] = 121,
		["pageup"] = 116,
		["q"] = 12,
		["r"] = 15,
		["return"] = 36,
		["right"] = 124,
		["s"] = 1,
		["space"] = 49,
		["t"] = 17,
		["tab"] = 48,
		["u"] = 32,
		["up"] = 126,
		["v"] = 9,
		["w"] = 13,
		["x"] = 7,
		["y"] = 16,
		["z"] = 6,
		["§"] = 10
	}

	if englishKeyCodes[input] == nil then
		return hs.keycodes.map[input]
	else
		return englishKeyCodes[input]
	end

end
```
