### ISSUE TITLE
Thoughts - Automatic Updates for Scripts?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1006]
Because I'm writing my Hammerspoon script to work on multiple machines by anyone who wants it, I'm considering adding some kind of automatic update feature for the script, so that users always have the latest version and features.

I could probably code something together fairly easily that just asks a web-server which is the latest version - however, I'm sure there's many security concerns with this - especially as I don't really know what I'm doing.

Given that Hammerspoon has "Check for Updates" already built into it's code - I'm wondering if there's anyway that its existing code could be used and applied to updating user scripts? Maybe pull the latest version from GitHub somehow, rather than off my personal server?

Would like to get some ideas or advice about this from people who actually know what they're doing!

Thanks in advance!

**Comment by asmagill** [comment]
At present, the automatic update feature is solely for the core application, and I don't see that changing soon or easily since it's tied to the build process and signing key used for the Hammerspoon application itself for obvious security reasons.

Off and on (even with the Hammerspoon predecessors Mjolnir and Hydra) talk of some method to provide automatic installation and updates of third party modules and code has been discussed -- at one point LuaRocks was being strongly considered, but proved a little fragile and hard to write a good wrapper for to make things seemless...

There are a lot of concerns with creating what amounts to a package manager with regards to versioning, security, etc... While I would certainly encourage anyone with the interest and experience to propose something and maybe work up an example, it's not something that I have the time or experience to focus on, and as far as I know most of the other regular contributors are probably in similar positions, though of course I invite their input and thoughts on the matter!

**Comment by latenitefilms** [comment]
No worries @asmagill! That all makes sense.

I had a quick look at the Hammerspoon source code, and it looks like you're using [Sparkle](https://sparkle-project.org) for updates - so I might have a look at that anyway. For security maybe rather than a ZIP containing the **.lua** script, I need to actually make a self-signed DMG package for delivery. Anyway... something I can ponder and experiment with.

**Comment by cmsj** [comment]
My general take has been that if something is generally useful, we can always consider it for inclusion in Hammerspoon itself - the idea was always to be a Batteries Included app. One of the main reasons for forking Hammerspoon from Mjolnir was that we didn't want people to have to install the app and then go digging around for all the modules to make it useful.

I wouldn't hate it if there were a well maintained community repository of scripts that somehow aren't suitable for inclusion in the main app, and we have a very low-grade version of this with the Sample Configurations page on our GitHub wiki. Something more than that would need a lot of thought and effort to make sure it was safe and high quality, unfortunately!

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - Thinking about it... As most of the people downloading my Hammerspoon script are using it basically as an application (i.e. just running it, rather than looking at code and modifying) - I wonder if there's any benefit of "packaging" and "forking" Hammerspoon with my script, so it essentially acts as a standalone application - or would this be frowned upon by the community? I have no idea if I have the skills to actually do this - but I'm thinking then, I could just use the existing Sparkle code within Hammerspoon to handle the updates - it would just be pointing to a different XML feed. I could then sign everything myself.

Is this taking things too far? Thoughts?

**Comment by cmsj** [comment]
@latenitefilms absolutely would not be frowned upon, we're open source with a permissive license (although note that the extensions generally assert their own licenses, and so far all are permissive).

Forking and sharing and deriving and cross-polination are all encouraged :)

**Comment by latenitefilms** [comment]
@cmsj - Awesome! Well, I might give it a shot sometime in the future! Thanks mate!
