### ISSUE TITLE
Question - hs.menubar Keyboard Shortcuts?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1014]
Is there anyway to indicate keyboard shortcuts for hs.menubar items?

**Comment by asmagill** [comment]
At present no... I experimented early on with adding these, and they did display in the menu, but they did nothing... with what I've learned since then, I'm sure it was because I hadn't set up a delegate to respond to the necessary messages or assigned the proper target and methods to the keys or something similar (it was one of my first forays into Objective-C programming!), but I never got around to revisiting the issue.  

Since you can setup your own hotkeys within Hammerspoon anyways, it never really seemed important, and since the menu itself can be dynamically generated by a function when the user actually clicks on it to open it, hotkeys handled by the OS level menu objects would only be possible for statically defined (i.e. table, not function) menus anyways.  Other than possibly as a visual reminder of the hotkey, I don't currently see any benefit to adding support for this.

**Comment by latenitefilms** [comment]
@asmagill - it's the visual reminder of the hotkey I'm after, as in the current version of my script, you can customise all the keyboard shortcuts, so having a visual reference in the menubar would be really handy.

**Comment by cmsj** [comment]
I've added an extra key to the hs.menubar menu table, `shortcut` which lets you specify a simple key to activate the menu item. These are fully distinct from hs.hotkey shortcuts, and they're fully handled by OS X to just activate the menu item in question.

For now I've skipped adding support for keyboard modifiers, because I didn't want to figure out the nested Lua table parsing stuff.

It might not be what you wanted, @latenitefilms , but I think it's all we're going to get. I don't think we're likely to modify the menubars such that they can display an arbitrary extra bit of text that happens to be some other hs.hotkey thing you've bound :)

**Comment by dasmurphy** [comment]
@cmsj I discovered Hammerspoon in late 2017 and it is awesome. Thanks.

Would it be possible to add the modifiers too to the menu items, since i like to display the global hotkeys in a menu i have? Thanks for a small answer?

**Comment by eddyg** [comment]
> _Would it be possible to add the modifiers too to the menu items_

I was also wondering about this, did some searching and found this issue.

I'd really like to be able to show ⌘ (Command), ⌥ (Option), ^ (Control) next to shortcuts like ←, →, ⌫, etc.

_(Thanks for an amazing tool!)_
