### ISSUE TITLE
Bug - Displaying Menubar Title & Icon at same time

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1015]
The documentation says: **If you set an icon as well as a title, they will both be displayed next to each other.**

However, this doesn't seem to be the case - if I specify an icon, then the text disappears.

Hammerspoon 0.9.48. macOS 10.11.6.

**Comment by asmagill** [comment]
What's the icon and the title?  When I do the following in 10.12:

~~~lua
a = hs.menubar.new():setIcon(hs.image.imageFromName(hs.image.systemImageNames.ColorPanel):copy()):setTitle("menuA")
b = hs.menubar.new():setIcon(hs.image.imageFromName(hs.image.systemImageNames.ColorPanel):copy():size{h=16,w=16}):setTitle("menuB")
~~~

I get 
<img width="168" alt="screen shot 2017-04-04 at 6 49 33 pm" src="https://cloud.githubusercontent.com/assets/8139480/24683885/bb3baa0e-1967-11e7-876d-d78102c28506.png">

(I use a copy of the image (`hs.image:copy()`) since an image referenced by name is a "link" or reference to the image, so if I change it in some way -- say its size or toggle the template flag, etc. -- the change *may* propagate to other uses of the same image... the copy makes sure each one is unique)

**Comment by latenitefilms** [comment]
I think maybe this was a macOS 10.11 bug, as I also can't reproduce on 10.12.3 either.

Thanks for testing @asmagill. I'll close this issue for now.
