### ISSUE TITLE
Bug? hs.menubar on multiple monitor

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1045]
I'm not sure if this is the intended functionality or a bug, but if I create a **hs.menubar**, then it will only "draw" on one screen at a time. For example, currently I have two monitors connected, and only the active monitor will contain my menubar. However, every other item in my menubar (i.e. Dropbox, Adobe Creative Cloud, etc.) is visible on both screens.

This wouldn't really be an issue, however, it seems to take a while for the **hs.menubar** to appear when you move your mouse between screens, so I think it would be better if the menubar just always appeared on ALL monitors.

Thoughts?

**Comment by asmagill** [comment]
I haven't noticed this behavior on my desktop, but I admit I haven't really looked that closely recently (I'm usually on a laptop which understandably only has the one monitor!)... did you recently upgrade the machine to Sierra, or is it still running 10.11?  And is it the latest Hammerspoon (version 0.9.48, which you can check by typing `hs.processInfo.version` into the Hammerspoon console)?  I'll see if I can replicate this behavior this weekend.

**Comment by latenitefilms** [comment]
Running macOS 10.11.6 and Hammerspoon 0.9.48.

**Comment by cmsj** [comment]
Odd, I have 2 monitors and my hs.menubar items have always appeared on both displays. AFAIK there isn't even a way to tell the underlying system menubar to only display items on one display.

**Comment by asmagill** [comment]
I have noticed occasionally that if I add a new menu, it may not always appear on the menubar of my secondary monitor until I have made something active on that monitor's display... and yet other times, the menu appears on both monitors more or less at the same time.

We do not specify a monitor in the code which adds these menu items (NSStatusBar doesn't even give us the option), so I can only assume that there is a cache somewhere that can sometimes take awhile to update until it is "necessary" because of the change in the "main screen".

In 10.10, Apple deprecated some of the methods we are using to manage the visual aspects of the status item and is now favoring putting all of that into a separately managed NSStatusBarButton... it may be that if we migrate to the preferred model that it will speed things up, since I think our calls are getting translated in the background to an internally generated button... but that is just a guess.  

Other than possibly migrating to the preferred approach, I don't think we can do anything about the delay... nothing we're able to access allows specifying or even preferring a specific display.

**Comment by latenitefilms** [comment]
I can't reproduce this anymore on macOS 10.12.3, so I'm going to close this issue for now.

**Comment by eagleamon** [comment]
Hi all, 

unfortunately I've got the same problem :(
Here's my hs version: 
```
> hs.processInfo.version
0.9.56
```

**Comment by cmsj** [comment]
@eaglemon which version of macOS are you running?

**Comment by eagleamon** [comment]
@cmsj, it is 10.12.6.

**Comment by eagleamon** [comment]
can i propose something else to help debug ?

**Comment by latenitefilms** [comment]
@eagleamon - It might be helpful to build a really simple Lua script example, and share a screen recording of the problem, so that @cmsj & @asmagill can see it happen?

**Comment by latenitefilms** [comment]
To keep things tidy, I'm going to close this issue in favour of #1530.
