### ISSUE TITLE
Advice on Error Handling?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1047]
I have the following function:

```
function isFinalCutProRunning()

	if hs.appfinder.appFromName("Final Cut Pro") == nil then
		return false
	else
		return hs.appfinder.appFromName("Final Cut Pro"):isRunning()
	end

end
```

Most of the time, it works fine. However, there's some cases where Final Cut Pro will be closing at exactly the same time as the 'else' line runs, throwing up a 'nil' error.

Is there anyway I can work around this?

Thanks in advance!

**Comment by asmagill** [comment]
By calling `appFromName` twice, you create a small window during which it's state can change... it would probably be safer to do something like this:

~~~lua
function isFinalCutProRunning()
    local FCP = hs.appfinder.appFromName("Final Cut Pro")
    if FCP then
        return FCP:isRunning()
    else
        return false
    end
end
~~~

Note that I haven't tested this, but I've experienced something similar... whenever you need the existence of something to remain constant, make sure to store it rather than invoke the function multiple times; otherwise you run the risk of it being "collected" out from underneath you.

**Comment by asmagill** [comment]
If you're willing to accept `nil` as an answer for `false`, you can shorten it even further with:

~~~lua
function isFinalCutProRunning()
    local FCP = hs.appfinder.appFromName("Final Cut Pro")
    return FCP and FCP:isRunning()
end
~~~

**Comment by latenitefilms** [comment]
Awesome, thank you!
