### ISSUE TITLE
Add LuaXML to Hammerspoon?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1048]
Is it possible to implement [LuaXML](http://viremo.eludi.net/LuaXML/) into Hammerspoon?

When I try to import the **.so** file I get the following error:

```
*** ERROR: error loading module 'LuaXML_lib' from file '/Users/latenitechris/.hammerspoon/LuaXML_lib.so':
	dlopen(/Users/latenitechris/.hammerspoon/LuaXML_lib.so, 6): no suitable image found.  Did find:
	/Users/latenitechris/.hammerspoon/LuaXML_lib.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:449: in function 'require'
	/Users/latenitechris/.hammerspoon/init.lua:8321: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
	(...tail calls...)
```

**Comment by asmagill** [comment]
Did you install it by copying the library file included in the zip file at the page your link refers to?  I suspect that the libraries included were compiled for a Linux operating system, not macOS... and it says it's written for Lua 5.2 (Hammerspoon uses Lua 5.3.3), so I'm assuming that it was compiled against the 5.2 lua libraries for whatever platform...

The Lua 5.3 vs 5.2 issue probably isn't a big one, but depending upon how it was written will probably cause all numbers to be treated as floating point (even those identified as integer in the xml file).  I'd have to look closer at the code to see how big of a change this would require to correct... probably not a huge change, but until I can look closer at this sometime next week, I can't say for certain.

I was able to get the current code to compile and load if you want to try it out and see if the number issue will be a problem... I had to do the following:

First, you need to have the XCode command line utilities installed, most easily accomplished by downloading XCode through the app store, though you can also download just the command line portion by either attempting to run `clang` from the command line and causing it to prompt you to download it or going to https://developer.apple.com/downloads and logging in with your apple id.

Then you need to have the Lua 5.3.3 headers installed... I use [Homebrew](http://brew.sh), so I installed it with `brew install homebrew/versions/lua53`, but you can download it from http://www.lua.org or use another package manager as long as you make sure it's Lua 5.3.

Then, I made the following changes to the Makefile:
* change line 5 to read `INCDIR = -I/usr/local/include/lua5.3`, where `/usr/local/include/lua5.3` is the location of the lua header files (if you're using the lua source from www.lua.org, just point to wherever you expanded it... I don't think you have to actually make and install it unless you want to)
* change line 21 to read `LFLAGS = -dynamiclib -undefined dynamic_lookup` (this replaces `-bundle`)
* change line 22 to read `LIBS          = $(LIBDIR) -L/usr/local/lib $(LIB)` (i.e. just remove `-llua`)

Now in the terminal type `make clean ; make`... you can ignore the warning about a missing directory.  Now `cp LuaXML_lib.so ~/.hammerspoon/` and then finally try `l = require("LuaXML_lib")` from the Hammerspoon console.

I've tested that it loads, but I haven't really tested its functionality beyond that... like I stated above, I suspect the only real issue will be distinguishing actual integers from floats and maybe how it handles (or more likely *doesn't* handle) 64-bit integers... most of the other 5.3 changes would cause problems compiling rather then change internal behaviors.

I'll take a closer look at this probably next week and see how big of an effort it will be to make it truly 5.3 compatible, and then I want to try it against the bridge support files provided by Apple's frameworks -- this is what I was using to test my own xml module code... since I was working with Apple's own NSXML subclasses, they parsed correctly, but the way the objects are organized is, in my opinion, very un-intuitive... if this can handle the bridge support files, then it should be able to handle almost anything a Mac user could likely want to throw at it and I'd probably recommend that it be added to the core Hammerspoon modules -- I've long thought that we should try to add XML support but didn't really like what I'd come up with thus far.

**Comment by asmagill** [comment]
Ok, that's what I get for not reading the full docs on the page you linked to...

You should also copy `LuaXml.lua` to your hammerspoon directory and try `l = require("LuaXml")` instead... my bad!

**Comment by latenitefilms** [comment]
Thanks @asmagill !

I ended up using [SLAXML](https://github.com/Phrogz/SLAXML) instead. Seems to work pretty well.

Keep me posted on your own XML code - as I've love to see "native" XML support in Hammerspoon one day!
