### ISSUE TITLE
hs.distributednotifications - More detail?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1049]
I've just started playing with **hs.distributednotifications** - which looks awesome.

However, it doesn't seem to return much useful information.

For example, the attached notification only returns:

`name: uploadSuccess
object: /Users/latenitechris/Desktop/Small Project.fcpbundle/.fcpcache/Assets/Shared Items/AP-2G716TLSVDXfnmjt+0g
userInfo: nil
`

Is there anyway to return the same information that's on the notification itself?
![screen shot 2016-10-22 at 5 00 26 pm](https://cloud.githubusercontent.com/assets/22286696/19617323/4512f31a-9879-11e6-9b3f-4f95ac650bbe.png)

**Comment by asmagill** [comment]
Probably not... the notifications picked up by `hs.distributednotifications` are *not* in any way related to the notifications displayed in the notification center... the former are inter- and intra-application notifications which allow one application to notify another (or another portion of itself) that they are doing something that might be of interest... the latter uses the notification center to provide visual notifications directed specifically to the user... `hs.notify` allows you to generate some of your own.

`hs.distributednotifications` can only return what is part of the notification posted... and while it supports a `userInfo` object which *can* be attached, most Objective-C notifications do not specify this, they just specify a notification label; and even when they do specify a `userInfo` value, Hammerspoon can only interpret them when we have a module which can understand the object type... I'll check to see if it logs the type when it can't identify it (it should, but it's been a long long time since I've looked at that code and I just don't remember) because that might suggest something which could be added to a future module and become useful to us, but... as I said, a large number of the notifications this module can detect never put anything into this variable at all.

**Comment by latenitefilms** [comment]
Ah right - I just assumed that **hs.distributednotifications** were related to the **Notification Center**, my bad!

Is there any API to access what's been added to the Notification Center?

**Comment by cmsj** [comment]
@latenitefilms not afaik, unfortunately. I'm going to close this issue because I don't think there's anything we can do :(
