### ISSUE TITLE
hs.chooser selected row background color

### ISSUE THREAD

**Issue by aJchemist** [Hammerspoon/hammerspoon#1053]
![hs chooser](https://cloud.githubusercontent.com/assets/1694505/19631311/b89c9946-99d5-11e6-8610-391ce6dbf52b.png)

It would be great if user can set background color of selected row

**Comment by junkblocker** [comment]
What @aJchemist said. That is sorely needed. Hardcoded transparency values make the text unreadable depending on what's behind the chooser. For now I'm making do with

```lua
                :fgColor({["red"]=0,["blue"]=0,["green"]=0,["alpha"]=1})
                :subTextColor({["red"]=0.3,["blue"]=0.3,["green"]=0.3,["alpha"]=1})
                :bgDark(false)
```

I've also had a need to change `hs.alert` colors/transparency similarly [Mainly to distinguish between a local and a remote server when doing remote management. Please let me know if that warrants a separate issue.

**Comment by cmsj** [comment]
AFAICT there's no way to set the background colour of a row selection in NSTableView, we'd have to override the entire `drawRect` method and render the table by hand.
The actual issue here is that AppKit is choosing poor colours when we're using the Dark vibrancy. I've played around with all of the various options here, and I think I have something that works better. Commit coming up shortly. If anyone has the facility to build from source, some testing would be much appreciated!

**Comment by junkblocker** [comment]
@cmsj, tested. Looks great to me!

**Comment by cmsj** [comment]
@junkblocker awesome, thanks!

**Comment by aJchemist** [comment]
@cmsj cool! much appreciated.
![screen shot 2016-10-27 at 3 14 40 pm](https://cloud.githubusercontent.com/assets/1694505/19756532/58b214e0-9c58-11e6-81e4-e025f39ef8c3.png)
