### ISSUE TITLE
Compatability with Microsoft Remote Desktop app?

### ISSUE THREAD

**Issue by writezhe** [Hammerspoon/hammerspoon#1056]
Hi and thanks!

I've got a basic setup in Hammerspoon for some key re-mapping. It works fine, with no console messages, on Mac OS Sierra. When I need to use a remote server via the Microsoft Remote Desktop app, the key re-mapping doesn't work. Instead, the key press results in an `a` being output. There are no Console messages when this happens.

Here is the simple code snippet that does not work (I'm only running this code to ensure this is the problem).

```
showUnderscore = function()
  hs.eventtap.keyStrokes('_')
end

showDash = function()
  hs.eventtap.keyStrokes('-')
end

swapMinus = hs.hotkey.bind({}, '-', nil, showUnderscore)
swapUnder = hs.hotkey.bind({'shift'}, '-', nil, showDash)
```

Thanks for any suggestions and apologies if this is a misplaced issue

**Comment by cmsj** [comment]
Have you previously used other keyboard remapping tools which have worked with Remote Desktop? My guess is that they're grabbing exclusive access to the keyboard and we're not seeing the events, or are getting some weird version of them.

**Comment by asmagill** [comment]
I do know that the remote access applications do their own thing with regards to events... The Apple Screen Sharing application will pass through keyUp/Down events without change, but appears to delay flag changes (I think to make sure it can't collapse them into keyUp/Down events) because I've had some timer issues with some of my watchers when working through Screen Sharing... it wouldn't surprise me if Microsoft's Remote Desktop is also doing its own thing...

I do know that 'a' corresponds to keyCode 0, and some of the eventtap functions seem to default to that when they get incorrect data or can't properly match a character from the keymap (this is being looked into as part of #1054).

You might try adding the code I've posted in https://github.com/Hammerspoon/hammerspoon/issues/1037#issuecomment-255639293 and then try changing your functions to:

~~~lua
showUnderscore = function()
  -- 27 corresponds to "-" in my keymap (hs.keycodes.map['-']); adjust if yours is different
  hs.eventtap.keyStroke({"shift"}, 27)
end

showDash = function()
  hs.eventtap.keyStroke({}, 27)
end
~~~

You may also run into the repeating of hotkeys, so take a look at https://groups.google.com/forum/#!topic/hammerspoon/GCaxnf1RN0M if you run into this

**Comment by writezhe** [comment]
Thanks @asmagill I think you're right that it has to do something with the program itself. Even without launching a remote desktop window, the key remapping does not work in the Microsoft Remote Desktop application (e.g. typing in the search bar, entering a new remote link).

In the past, I've had key remapping work on this same application and remote connection. I can't remember the exact setup, but I think it was using Karabiner before I upgraded to Mac OS Sierra. (Karabiner Elements does seem to work on the Microsoft Remote Desktop, but doesn't have the key swapping features.) I'll dig around some more.

PS I'm running Mac OS 10.12.0 and Hammerspoon 0.9.48

**Comment by cmsj** [comment]
@writezhe Karabiner would definitely work, because that's intercepting/modifying input events in the kernel, before they get up to userspace. It may well be that you're stuck waiting for Elements to get up to speed on Sierra (as many of us are!)

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Comment by maxsnts** [comment]
Hi, sorry to reopen this, but there is something particular about hammerspoon + Remote desktop
Simple example

hs.hotkey.new("", "\\", 
        nil, function() hs.eventtap.keyStroke("", "x", 0) end, 
        nil, function() hs.eventtap.keyStroke("", "x", 0) end)

hs.hotkey.new("shift", "\\", 
        nil, function() hs.eventtap.keyStroke("shift", "x", 0) end, 
        nil, function() hs.eventtap.keyStroke("shift", "x", 0) end)

If i set these to hotkeys (as an example)

- If accessing windows in a Parallels Virtual Machine
           - The modifier does not work, pressing "\\" i get a "x" (lowercase)
           - The modifier does not work, pressing "shift+\\" i still get a "X" (uppercase)

- If accessing windows using Remote Desktop
           - The modifier does not work, pressing "\\" i get a "x" (lowercase)
           - The modifier does not work, pressing "shift+\\" i still get a "x" (lowercase)

Thank you
