### ISSUE TITLE
Feature request: Style for hs.alert

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#1061]
The current style for the alert is pretty good but when looking at a different computer through screen sharing I realized I couldn't tell which machine the alert was supposed to be for. For such cases and for choice in general it would be good if we could add configurable colors, font, and maybe even border radius style facilities as are available in default macOS notifications. Since @asmagill very nicely converted alerts to lua code it can be tackled by most anybody now :) We'd need to figure out how we want the API to look like before someone tackles that.

**Comment by latenitefilms** [comment]
Great idea!

**Comment by asmagill** [comment]
As suggested above, this is easy enough to add... what types of components do we want to make "settable"?  Background color is an obvious choice... font and font size as well?  I also think that the solution should allow for a module level default as well as specific alert overrides -- the idea of being able to make specific alerts red versus the default, even on the same machine, appeals to me.

My personal feeling (but I'm open to discussion) is that anything beyond that (positioning decision, frame shape, etc.) gets into enough situation specifics that the user is better off overriding the alert module themselves or writing their own alert code for their specific need... since it's only lua code, this is easy for anyone to do with a few pointers that we can either put into the documentation or add to a wiki page.

**Comment by junkblocker** [comment]
@asmagill , agree completely. Color, font, background color are good enough for me and I wouldn't want to take layout calculations. For the rest we should make it extendable in lua code by user themselves.

**Comment by latenitefilms** [comment]
One thing that could be handy though is defining which screen the alert appears on?

**Comment by asmagill** [comment]
Have to think a little on that... I think we could probably easily calculate it based on the origin of `hs.screen.mainScreen`, but it will be later tonight before I can try this out.

**Comment by asmagill** [comment]
closed with #1064
