### ISSUE TITLE
Function to iterate over/find a menubar icon item(s)

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#1074]
I haven't heard from anyone regarding #1050. I think this is still missing. There seems to be no way to iterate or search over menubar icons (do not confuse this with the app specific menus in `hs.application:findMenuItem`). Could you add a function to `hs.menubar`? Thanks!

**Comment by asmagill** [comment]
At present, no there is no official way to search through status bar item menus.

You can maybe do it with my third party extension [hs._asm.axuielement](https://github.com/asmagill/hs._asm.axuielement) but it is still considered very experimental and while I hope it eventually makes its way into core, there is no projection of when at present... There have been other people who've successfully used it to solve specific problems, though... see the examples at the site specified or search for "axuielement" in the Hammerspoon issues tab (you'll need to include closed issues).

However, even with this, it will be somewhat hit-or-miss... here's what I've observed with a few initial tests...

First, once installed as described at the link above, load the module with: `ax = require("hs._asm.axuielement")`.

Starting with some status menu's that I know have running applications behind them:

For Dash, which is a documentation browser used by a lot of developers, if you look at it's element tree with `hs.inspect(ax.applicationElement(hs.application("Dash")):buildTree())`, you will see elements corresponding to the menu items, so it would probably work for this application.

However, for Duet, which allows using an attached iPad/iPhone as a secondary monitor, it's menu is created when you click on it, so no items appear in the output when you try `hs.inspect(ax.applicationElement(hs.application("Duet")):buildTree())`... this isn't completely surprising, since its menu is highly customized and graphical in its display, so if its using the NSMenuItem class, its probably using a subclassed version.

Finding system menus is harder since they don't always have an obvious application behind them... most (all?) of them seem to belong to an application titled "SystemUIServer", but looking at it with `hs.inspect(ax.applicationElement(hs.application("SystemUIServer")):buildTree())` shows menus, but no menu items.

If you look through the Hammerspoon issues as suggested above, you'll see that some accessibility items don't exist until they are explicitly created/viewed... I forget the issue number, but if you search for a closed issue with the terms "axuielement" and "Dock", you should find one where I describe having to activate an application icon's menu by "pressing" (`doPress`) the application icon before searching the menu itself... I suspect the system menus and possibly other dynamically generated menus may also require such an approach.

**Comment by cmsj** [comment]
I'm going to close this out - the menubar icons are visible as menu items in the application, but have no children because they are UI views and not menus. If axuielement lets you get what you need, then that's excellent and if/when that merges into the main Hammerspoon code, this issue will be automatically taken care of :)
