### ISSUE TITLE
Unify music player extensions

### ISSUE THREAD

**Issue by S1ngS1ng** [Hammerspoon/hammerspoon#1081]
Hi. Thanks for merging my PR on VOX music player.

I noticed that, the `extension/itunes`, `extension/spotify` and `extension/vox` are sharing some similar APIs. I would like to wrap them up in **one file**, making it something like `hs.player.play()` for example.

Would you think it is a good idea? Or does it worth to do this?

**Comment by asmagill** [comment]
If they can be closely integrated, then I think creating a single merged module makes good sense... and we should then encourage future player additions to extend that instead of creating yet another module name in the `hs` namespace.

For backwards-compatibility reasons, I'd also recommend replacing `itunes`, `spotify`, and `vox` (well, maybe/maybe not since its so new... your call) with "wrapper" modules... look at the code for `hs.javascript` and `hs.applescript` to see what I mean... they're both wrappers for `hs.osascript`.

**Comment by cmsj** [comment]
I'm in favour of unifying the code, so long as it exports backwards-compatible API for people using the old module names.

**Comment by cmsj** [comment]
I remain in favour of this happening, but it doesn't seem like anyone has the time to work on it (and this was actually the second issue we had open about this), so I'm going to close it out. If someone wants to work on this, please re-open :)
