### ISSUE TITLE
Memory management of naked ObjC userdata

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#1093]
Some time ago I proposed #747 as a way to neatly contain ObjC objects in Lua userdata objects, mainly because I am very concerned about the naked objects being reaped by either ARC or Lua GC, without the other side of the equation getting to know what's going on.

However, it didn't really get traction, and even though it is all wrapped up neatly in LuaSkin methods, it is a little bit of extra code that's really just doing some pointer indirection.

I was looking through @ewmailing 's slides from LuaConf 2016 (http://playcontrol.net/tempdownload/video/LuaCocoa.pdf) and it has some slides on memory management, which include the (embarrassingly obvious, in hindsight) way LuaCocoa solves this. When it puts an ObjC object into Lua as a userdata pointer, it calls `CFRetain()` on it, guaranteeing that ARC will not reclaim it. Then, in the Lua GC phase, it calls `CFRelease()` on it, allowing ARC to do its good work.

I think we should try and walk a line between the current way we do things, with retain/release added into the mix, and with as much of the boilerplate as possible moved into LuaSkin. This would include the ugly macro that most modules have to transform the userdata pointer into their particular kind of ObjC object.

Thoughts? (ping @asmagill :)

**Comment by asmagill** [comment]
I'll look over your pull again, as it's been a while, but I don't think this is as big of a problem as you think with the newer code being written (some of the older modules probably could use an update, and those that use CFType's rather than NSObject's... well, I agree, that could use some standardization) but for traditional NSObject type objects, I think there is a pretty stable approach now...

The CFRetain/CFRelease is basically what we are doing already but with `__bridge_retain` and `__bridge_transfer` as appropriate. The only time in recent memory that I recall having to do something "hacky" about ARC's own retain/release handling was with my own `hs._asm.objc` when NSInvocation returns an ID object (the returned pointer to an ID confuses ARC since NSInvocation doesn't "retain" what's pointed at -- ARC tries to release it at the end of the function but it was never retained in the first place).

As an example of what I generally do now, from `hs.location`'s internal.m:

~~~objc
#define get_objectFromUserdata(objType, L, idx, tag) (objType*)*((void**)luaL_checkudata(L, idx, tag))
// ...
static int pushCLGeocoder(lua_State *L, id obj) {
    CLGeocoder *value = obj ;
    void** valuePtr = lua_newuserdata(L, sizeof(CLGeocoder *)) ;
    *valuePtr = (__bridge_retained void *)value ;
    luaL_getmetatable(L, GEOCODE_UD_TAG) ;
    lua_setmetatable(L, -2) ;
    return 1 ;
}

static id toCLGeocoderFromLua(lua_State *L, int idx) {
    LuaSkin *skin = [LuaSkin shared] ;
    CLGeocoder *value ;
    if (luaL_testudata(L, idx, GEOCODE_UD_TAG)) {
        value = get_objectFromUserdata(__bridge CLGeocoder, L, idx, GEOCODE_UD_TAG) ;
    } else {
        [skin logError:[NSString stringWithFormat:@"expected %s object, found %s", GEOCODE_UD_TAG, lua_typename(L, lua_type(L, idx))]] ;
    }
    return value ;
}
// ...
static int clgeocoder_gc(lua_State* L) {
    CLGeocoder *obj = get_objectFromUserdata(__bridge_transfer CLGeocoder, L, 1, GEOCODE_UD_TAG) ;
    if (obj) {
        [obj cancelGeocode] ;
        obj = nil ;
    }
    // Remove the Metatable so future use of the variable in Lua won't think its valid
    lua_pushnil(L) ;
    lua_setmetatable(L, 1) ;
    return 0 ;
}
// ...
int luaopen_hs_location_internal(lua_State *L) {
    LuaSkin *skin = [LuaSkin shared] ;
// ...
    [skin registerPushNSHelper:pushCLGeocoder             forClass:"CLGeocoder"];
    [skin registerLuaObjectHelper:toCLGeocoderFromLua     forClass:"CLGeocoder"
                                               withUserdataMapping:GEOCODE_UD_TAG];
// ...
    return 1;
}
~~~

The only place the macro gets used is in the LuaObjectHelper function and in __gc, and the retain/release is handled by the PushNSHelper and the __gc.  Every where else just uses `[skin toNSObjectAtIndex:1]` or `[skin pushNSObject:object]` and relies on the helper functions to actually do the work.

In cases where the same object might get pushed more than once within its lifetime and has "cleanup" that occurs in the __gc function (remove callbacks, clear delegate, etc.), I've taken to adding a property `selfRefCount` which is just an integer initialized to 0 in the init function; then the `pushObject` function increments it by one each time it's called, the __gc function decrements it each time it's called, and only does the "cleanup" if `selfRefCount == 0`... otherwise it just removes the metatable for that particular userdata "version" of the NSObject.  The alternate approach of storing a reference to the userdata object in the registry results in objects which can never be collected without an explicit `delete` method, like `hs.drawing`.

At any rate, I'll review your pull again tonight, and await your comments on this... I may be missing your intended point entirely :-P

**Comment by cmsj** [comment]
Hmm, you make a good point about the `__bridge_retained` and `_transfer`. oops :)

I'd still like to explore how we might wrap more of this stuff up in LuaSkin though - it seems like something that would be nice to encapsulate.

If you do look at the PR, I think mainly the only part worth paying attention to is the API that LuaSkin exposes.

I'm going to close this issue out and open a new one for discussion about abstracting the userdata dancing, without the focus on memory management, since we're ok there.
