### ISSUE TITLE
Search for text/characters in current window only (not the entire document)

### ISSUE THREAD

**Issue by nikitavoloboev** [Hammerspoon/hammerspoon#1112]
I like to keep my workflow very keyboard centric and I often switch between the text editor and the browser. Right now if I want to select some text that I found, I am either forced to use the trackpad or do cmd + f search but that searches the entire document. 

I want to make a similar cmd + f search but one that will only search for the text that can currently be seen in the active laptop window. I can then search for the text, visually select it and do operations on it like copy or google for the text. This would be absolutely phenomenal if it could be implemented. 

For example, if I were reading an article like so : 

![2016-11-29 at 23 23](https://cloud.githubusercontent.com/assets/6391776/20731500/ed378f40-b68a-11e6-9fcc-db8fffe8a08b.png)

This search will only allow me to select the text that is present on the current screen.

@cmsj mentioned on irc that @asmagill is working on an updated AXUIElement interface. Perhaps this can be used to make this happen. 

I would so love for this to exist and would love to help make this happen.

Thank you for any help.

**Comment by asmagill** [comment]
Theoretically, axuielement should make this possible... I haven't really tried to do much with the text available through accessibility so I don't know yet if we can easily determine specifically what is visible versus what is available (i.e. in the entire textarea)... but I'll let you know when I next update the module -- I'm trying to work out a way to access visible elements more quickly than searching from the bottom up (i.e. application node) since most of what we're interested in is at the leaf level (topmost and visible)  and every application is different (sometimes even between versions) in how many levels their are in-between.

**Comment by cmsj** [comment]
I'm going to close this out because it will be solved or not based on the fate of hs.axuielement :)

**Comment by nikitavoloboev** [comment]
Oh wow that is exciting, I really wish this would work. :)
