### ISSUE TITLE
A setter for chooser:selectedRow (or workaround?)

### ISSUE THREAD

**Issue by mikaylathompson** [Hammerspoon/hammerspoon#1113]
Currently, `chooser:selectedRow()` is just a getter--would it be possible to add a setter? Something like `chooser:selectedRow(3)` or `chooser:selectRow(3)`.

My current workaround is that every time I want to change the selected item, I rotate the entire list of choices such that the element I want to be selected is now in position 1.  I'm pretty unhappy with this because it's both ugly and inefficient.

The workaround I'd be okay with is sending eventtap "down arrow" events. I would be totally happy with this, but it hasn't worked. (my code looks like `hs.eventtap.keyStroke({}, "down")`, but nothing happens)

Any other workarounds I should take a look at?

**Comment by latenitefilms** [comment]
That's an interesting idea! Curious... what's the scenario when you'd want to "highlight" a chooser row? Given that moving the mouse over the chooser will affect what's highlighted, do you want to override this default behaviour? What happens when the user changes the chooser's query?

Regardless of why you want to do it, I can't get `hs.eventtap.keyStroke({}, "down")` to work with the console either, which is interesting and confusing, as it's definitely working in other apps - so your code is certainly correct.

The only hacky workaround I can think of if you don't want to mess with the `hs.chooser` code is to move the mouse over the item you want, then instantly move it back to it's original position. This will work - but it's not ideal obviously.

I'm also curious... are you actually using `chooser:selectedRow()` function?

**Comment by mikaylathompson** [comment]
I'm trying to use it to make a cmd-tab app switcher replacement (which uses the functionality of the chooser, like searchability and the numerical shortcuts).  So I'd like to duplicate the functionality where if you press cmd-tab repeatedly, it moves down the list, and shift-cmd-tab moves up the list.

Good points on the mouse and the query. In my case, it would be totally fine to override the highlighted row with the mouse, and maybe to reset position on changing the query? I think on the query, I'd be fine with either keeping the position or resetting.

So my code would ideally be something like: `chooser:selectRow(chooser:selectedRow() + 1)`


Just another datapoint on the keyStroke not working: this line `hs.eventtap.keyStroke({"cmd"}, "1")`, works totally fine and selects the first item. And `hs.eventtap.keyStroke({}, "A")` is also fine and enters "A" into the query box. So it's something fairly specific to the arrow keys.

**Comment by cmsj** [comment]
This should be addressed by #1140 :)
