### ISSUE TITLE
Mac OS full screen split screen window management

### ISSUE THREAD

**Issue by dimitrieh** [Hammerspoon/hammerspoon#1119]
Is this already possible and if not could it be done?

The idea is that I want one command or app icon to launch 2 different applications in a split screen setup with native mac os full screen setup.

Say my atom editor and iterm terminal.

**Comment by cmsj** [comment]
Unfortunately there is no system API for us to use to work with the fullscreen splitscreen stuff :(

**Comment by iliyang** [comment]
Wow, what a shame! I found this issue when looking for a way to select two windows and put them side-by-side in full screen (rather than having to do this manually/painfully with the mouse). Any ideas for workarounds?

Btw, I accidentally discovered that, once the windows have been manually arranged in a split-screen mode, you can at least manipulate the position of the split line using the `hs.window` API.

**Comment by asmagill** [comment]
I discovered a while back that I can at least query some info about them through my [hs._asm.undocumented.spaces](https://github.com/asmagill/hs._asm.undocumented.spaces) module, but apparently this is crashing for some people with 10.12 (fwiw I have SIP partially disabled, but I don't know if that makes a difference).

That entire module is a hack to some degree, relying on private APIs and a whole lot of trial and error, and I've never been totally happy with it.  I doubt I'll have a chance to mess with it much anytime soon, but you're welcome to see if it spawns any ideas.

**Comment by zzamboni** [comment]
@iliyang not in full screen, but you can easily use Hammerspoon to position two regular windows side to side, for example using my [WindowHalfAndThirds](https://github.com/zzamboni/zzSpoons/tree/master/Spoons) spoon (not yet in the official repo, hopefully soon).

**Comment by iliyang** [comment]
@zzamboni Thanks! I actually already do this, but sometimes the split fullscreen mode is more convenient.

**Comment by oschrenk** [comment]
That would so great. When working through tutorials I often enjoy working with a full-screen browser on one side and a terminal on the other. Toggling this behaviour with a shortcut would be amazing. Let's hope Apple opens up that API (in High Sierra)

**Comment by jdtsmith** [comment]
I very much like SplitView, but I hate the interface.  Long ago I wrote some UI-event simulating code that enables automatic SplitView for named application/window (e.g. it actually clicks the green button).  I recently rewrote it as a much more functional Spoon, with an optional chooser-based UI: invoke the key, pick a companion window, and let the magic happen.  You can even make custom bindings for splitting the display with specific applications and/or window combinations. 

See https://github.com/jdtsmith/SplitView.

**Comment by zzamboni** [comment]
This looks really cool. Have you considered submitting a PR against
https://github.com/Hammerspoon/Spoons so that it gets included in the
official list at https://www.hammerspoon.org/Spoons/?

One potential problem would be that it needs the installation
of hs._asm.undocumented.spaces, but I think as long as that's properly
documented (and maybe with some checks and warnings from within the Spoon
if it's not installed), it should be OK.

Best,
--Diego

**Comment by latenitefilms** [comment]
@jdtsmith - I wonder if you can use `hs._asm.axuielement` to add some "logic" to get around the hardcoded delays?

**Comment by jdtsmith** [comment]
Thanks both.  The hardcoded delays are the most "sensitive" aspect, and I've had to tune them for my own system over time.  And sometimes (with many windows) the time it takes to hide and move everything around results in a failure.  I could probably fix this in most cases by delaying the unhiding of other windows/apps, but then if you switch back to your original space and find nothing that would be a surprise.  

I hadn't seen `hs._asm.axuielement`.  Any thoughts on how it could be used to activate SplitView?  If it were a bit more reliable for me, I'd be more inclined to add it to the official Spoon list.

**Comment by jdtsmith** [comment]
@latenitefilms I took a close look at `hs._asm.axuielement`, but couldn't find anything relevant.  It allows you to identify UI elements and press them, for example, but not (as far as I can tell) do a long press.  And once Mission Control takes over drawing the small versions of the windows, the window object itself (or its accessibility analog) doesn't know anything about where it is placed.  Maybe I'm missing something though?  That said, since I changed to "teleporting" irrelevant windows to another space from minimizing them, it is far more reliable.  Give a try.

**Comment by jdtsmith** [comment]
@latenitefilms Couldn't figure out how to use `hs._asm.axuielement` to eliminate those hard-coded delays, but I did manage to use it to solve another problem for `SplitView`: how to remove a fullscreen desktop by shortcut key.  It was a bit of a chore to figure out, but the accessibility-based method is working well for me in a new release. I increased the delays somewhat to be more conservative and might consider adding it as an official Spoon.  Let me know if you try it.

**Comment by jdtsmith** [comment]
By the way, I've eliminated most of the hard-coded delays and pixel offsets by using `axuielement` in [SplitView](https://github.com/jdtsmith/SplitView).  The latter is also useful for interacting with the new Zoom-button menu of Catalina (without hard-coded pixel offsets).   I'd be happy to see this included in the Spoons list, but since it uses not one but two "experimental" Hammerspoon modules (`axuielement` and `undocumented.spaces`) I'm not sure if that would disqualify it.  Has worked well for me for a year or two.

**Comment by Yang66120902** [comment]
https://github.com/Yang66120902/mac-spaces-simulator/tree/main
