### ISSUE TITLE
hs.pathwatcher change frequency?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1125]
How often does `hs.pathwatcher` check for changes? 

Is there anyway to increase the frequency? There seems to be a bit of a delay between when I update a file, and when Hammerspoon notices?

**Comment by cmsj** [comment]
it doesn't specifically poll for changes, it's using Apple's `FSEvent` system, which notifies us when things are changing. Perhaps it includes some kind of a delay so it can tell the difference between a partial update of a file and a complete update of a file, but it usually seems to respond pretty quickly when I change my config.

(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Comment by latenitefilms** [comment]
No worries - thanks @cmsj ! I'll do some more investigating!
