### ISSUE TITLE
Help with Wifi Watcher Function

### ISSUE THREAD

**Issue by nikitavoloboev** [Hammerspoon/hammerspoon#1131]
I have this function in hammerspoon that works really great : 

```Lua
-- _wifi watcher
wifiwatcher = hs.wifi.watcher.new(function ()
    net = hs.wifi.currentNetwork()
    if net==nil then
        hs.notify.show("wifi disconnected","","","")
    else
        hs.notify.show("wifi connected","",net,"")
    end
end)
wifiwatcher:start()
```

The only thing is that I find annoying how every time I login, I get two notifications on the top since it connects to wifi every time on login. Is it possible to extend this function of wifi watching to only work when logged in already and not have these notifications shown on the login screen as they are quite useless to me.

Thank you for any help.

**Comment by eoranged** [comment]
I don't undestand what *exactly* you're trying to achieve, but [hs.caffeinate.watcher](http://www.hammerspoon.org/docs/hs.caffeinate.watcher.html) should do the trick:

```
wifiwatcher = hs.wifi.watcher.new(function () ... end)
cwatcher = hs.caffeinate.watcher.new(function(state) 
   if state == hs.caffeinate.watcher.systemDidWake then
      wifiwatcher:start()
   elseif state == hs.caffeinate.watcher.systemWillSleep then
       wifiwatcher:stop()
   end
end)
cwatcher:start()
```

I haven't tested the code above and It might not work straight ahead, but It should give you the basic idea how this can be done.

**Comment by asmagill** [comment]
I think I've identified a problem with `hs.wifi.watcher`... If you have multiple wifi watchers defined, then the callback for each watcher is getting called for the notification each watcher has registered for... simplified, if I register 2 watchers, each watcher gets called twice for every change, if I register 4, then each watcher gets called four times, etc.

@nikitavoloboev, do you have another wifiwatcher running for some additional purpose? Or maybe you've setup more than one in the console during your testing?

At any rate, the ultimate fix is to figure out why and then correct for it, but at least now I know the "what".

**Comment by nikitavoloboev** [comment]
This are the only lines of code I have in my init.lua relating to hs.wifi.watcher

I also didn't type anything in the console related to it.

**Comment by asmagill** [comment]
Ok, it seems to have something to do with the number of times `[CWInterface interface]` is invoked...

Currently we use it in a couple of places in `hs.wifi` and for every new watcher in `hs.wifi.watcher`, and the system appears to generate the same number of callbacks as the number of times `[CWInterface interface]` has been used directly.  If I had to guess it's because direct access to CWInterface is deprecated and is being wrapped by the newer methods for backwards compatibility in a way that inadvertently causes this, but... that's a guess.

I'm working on a rewrite (the objects we're using were deprecated in 10.10 anyways) that should address this and use the newer, preferred methods to boot.  It should be ready sometime tomorrow so we can get it into 0.9.51.

**Comment by cmsj** [comment]
I think this can be closed?
