### ISSUE TITLE
Is it possible to do XMLHttpRequest call ? 

### ISSUE THREAD

**Issue by dharmapoudel** [Hammerspoon/hammerspoon#1133]
I'm trying to do  $.get('hammerspoon://test') from the webview and getting CORS error. Is there any workaround this? 

-TIA

**Comment by asmagill** [comment]
The webview module is based on Apple's WKWebView class.  If the Javascript support provided by WKWebView supports XMLHttpRequest, then it should, but I don't know Javascript well enough to know.  No specific special support for this was added, so it depends upon whether Apple supports it natively or not.

A brief googling suggests that it might be a nice protocol to support... if you have suggestions on an implementation spec or library which can provide such support within Apple applications, I'd be happy to take a look at it.

**Comment by pasiaj** [comment]
I've been writing a module that uses XHRs quite extensively and the do work. I do not know how CORS-rules work with custom protocols. With XHR-requests the protocol, hostname & port should all match, or the browser gives you a CORS-violation error.

**Comment by cmsj** [comment]
@asmagill I think the issue here is more about whether or not we can influence the CORS behaviour of the webview - it seems reasonable that it should be allowed to call hammerspoon:// URIs if possible

**Comment by asmagill** [comment]
@cmsj, per https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/webview/internal.m#L287-L295, `hs.webview` already will pass off an unsupported URL to `[[NSWorkspace sharedWorkspace] openURL:destinationURL]`, so I don't think this is a webview issue...

@pasiaj, sorry for the delay in getting back to this, but looking at the code at the link above, if I had to guess, the URL requested is getting rejected by javascript (JQuery?) before it reaches the actual underlying WKWebView object since our delegate will pass along URL's it can't handle to the macOS.  If this is still an issue for you, could you post a code snippet that I can work with?

**Comment by cmsj** [comment]
I'm going to close this issue due to a lack of response. Please feel free to re-open if if you can provide us with more information :)
