### ISSUE TITLE
hs.urlevent.httpCallback invocation broken

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#1142]
Since a few changes ago, the url handler is returning a table for the last "url" param to the callback.

 Here's an example ``hs.inspect`` dump of each parameter for sample URL ``https://github.com/Hammerspoon/hammerspoon/pull/1129``

```
             url_director: "scheme"
             url_director: "https"
             url_director: "host"
             url_director: "github.com"
             url_director: "params"
             url_director: {}
             url_director: "fullURL"
             url_director: {
  __luaSkinType = "NSURL",
  url = "https://github.com/Hammerspoon/hammerspoon/pull/1129"
}
```

**Comment by asmagill** [comment]
Most likely because you just made a build with hs.spotlight... this adds a handler for NSURL which apparently overrides a default or builtin behavior when coercing NSURL into a lua data type... <sigh> this is one of the reasons I want to put up a wiki listing all of the conversion functions we have and where they are defined and used.

I'll look into it and see if I can get a fix up later tonight.

**Comment by asmagill** [comment]
Ok, the latest manual tweak should fix it... let me know if that takes care of this for you.

**Comment by junkblocker** [comment]
Thanks, it works!
