### ISSUE TITLE
Crash on startup when non-latin input method activated

### ISSUE THREAD

**Issue by Zert** [Hammerspoon/hammerspoon#1163]
Hammerspoon crashes when non-latin input method activated (also had this problem with Mjolnir)

```
Welcome to the Hammerspoon Console!
You can run any Lua code in here.

-- Lazy extension loading enabled
-- Loading ~/.hammerspoon/init.lua
-- Loading extension: fnutils
-- Loading extension: hotkey
*** ERROR: ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:342: Invalid key: i - this may mean that the key requested does not exist in your keymap (particularly if you switch keyboard layouts frequently)
stack traceback:
	[C]: in function 'error'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:23: in upvalue 'getKeycode'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:190: in function 'hs.hotkey.internal.new'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:342: in function 'hs.hotkey.internal.bind'
	/Users/zert/.hammerspoon/init.lua:13: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:57: in function 'hs.fnutils.map'
	/Users/zert/.hammerspoon/init.lua:41: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
	(...tail calls...)
```

Steps to reproduce:
1. Quit Hammerspoon if already running
2. Open any application with input area, iTerm2 for example
3. Switch to non-latin input method, like Greek
4. Run Spotlight by hotkey
5. Input method in Spotlight is also Greek, so switch to English
6. Write `hammerspoon` and press Enter
7. You will see a window with the error message pasted above

This crash reproduced in 100% cases for any non-latin input method (Greek, Russian, Serbian, etc).

**Comment by asmagill** [comment]
This occurs because `hs.hotkey` is actually internally converting the "i" into the corresponding keycode by looking it up in `hs.keycodes.map`.  When the Greek layout is enabled, "i" is not a valid key:

~~~lua
> hs.keycodes.currentLayout(), hs.keycodes.map["i"], hs.keycodes.map[34]
U.S.	34	i

> hs.keycodes.currentLayout(), hs.keycodes.map["i"], hs.keycodes.map[34]
Greek	nil	ι
~~~

The simplest fix, if you want to map it to the physical location of the "i" key is to use its number instead of "i" -- 34.  If on the other hand you want it active when the layout is "U.S." but not when it's "Greek", take a look at the documentation for `hs.keycodes`, especially the `currentLayout` and `inputSourceChanged` functions.

You can read more about a similar issue at https://github.com/Hammerspoon/hammerspoon/issues/984#issuecomment-247505020.

@cmsj, and others:  I am open to ideas about either a more graceful way to handle this or better errors since it seems to occur somewhat regularly... some possible ideas off the top of my head:

* if the keycode doesn't exist for a key, internally switch to the U.S. (or another, it's just what I'm most used to and I think it's the closest match to the ANSI standard the internal map names come from) and check for that, only erring if both the current layout and the U.S. one return nil.
* provide a more descriptive error with suggestions to look at `hs.keycodes` and maybe point to a wiki article based on the solutions in these issues.

Other ideas?

**Comment by cmsj** [comment]
@asmagill I think probably the most complete solution would be for Hammerspoon to just know that `i` in the US layout maps to a particular other key in each and every other keyboard layout, so it can translate internally to do what the user meant to ask for. However, that seems like a terrifying piece of work that I have no intention of undertaking, and I don't expect anyone else to ;)

We could probably come up with a better error message though, that guides users to a solution, perhaps someone who uses multiple layouts could contribute a brief example using `inputSourceChanged` for the Getting Started Guide?

**Comment by cmsj** [comment]
your first suggestion comes closest to what I just said, so maybe we should experiment with that? It should log to the console when it's doing a "US Best Guess" so users know what happened if we somehow guess wrong.

**Comment by Zert** [comment]
> if the keycode doesn't exist for a key, internally switch to the U.S.

@asmagill this is a behaviour I expect in this case, U.S. layout is «default» de facto

**Comment by scarfacedeb** [comment]
@Zert I was able to circumvent the issue with the following hack:

```lua
if (hs.keycodes.currentLayout() ~= 'U.S.') then
  hs.keycodes.setLayout('U.S.')
  hs.reload()
else
  config()
  hs.alert.show("Config loaded")
end
```

It checks the current layout and switches it to U.S. if it's something else.

Unfortunately, we need to reload the hammerspoon again, because it will fail with the same otherwise.

**Comment by asmagill** [comment]
Thinking about this, I think it would be fairly easy to create a static table in the `hs.keycodes` module which just contains the lists for the "official" ANSI mappings found in `/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/Current/Headers/Events.h` and use that as a fallback if the current map can't find a character.  I'm pretty sure that the desired ANSI codes have remained fairly constant with only the occasional addition with OS updates rather than changes or deletions.

This might be a little less flexible then internally changing the layout, but will he a whole lot easier to code than to do an actual internal switch.

Additional thought... it should be possible to do something like `egrep '^\s+kVK_' /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/Current/Headers/Events.h` and build this fallback table at runtime making it a little less brittle to potential OS updates...

I'll add this to my list and try and get it in before the next release.

**Comment by latenitefilms** [comment]
What would be REALLY amazing would the ability to set a Keyboard Layout when calling `hs.hotkey.new()`  or `hs.hotkey.bind()`. For example, something like:

`hs.hotkey.new(mods, key, [message,] pressedfn, releasedfn, repeatfn, [keyboardlayout])`

This would be great for those sharing LUA scripts, where you have "default" shortcut keys built-in to the script. For example, the developer could setup all the default shortcuts using whatever their own keyboard layout is, then Hammerspoon "translates" this depending on what the end-user actually has.

Also, as discussed in #1004 - it could also be handy if you could define a Keyboard Layout in `hs.keycodes.map` as well (i.e. something like `hs.keycodes.map(keyboardlayout)`).

**Comment by asmagill** [comment]
since merged, am closing this.  reopen if you disagree.
