### ISSUE TITLE
hs.alert centre text

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1164]
If you have multiple lines of text, it would be great if you could centre things within a `hs.alert`.

Maybe something that can be added to `hs.alert.defaultStyle`?

**Comment by asmagill** [comment]
You can do this yourself by adding the following line of code into your `init.lua` file:

~~~lua
require("hs.alert").defaultStyle.paragraphStyle = { alignment = "center" }
~~~

Unless there is a differing consensus, I'm reluctant to make this the default behavior since it will differ from the historical behavior of `hs.alert` which predates the current model which supports this type of style modification.

**Comment by asmagill** [comment]
Ok, correction... this *won't* work... yet.

I forgot that I merged the text and the box styles into one table and don't use it as a straight `hs.styledtext` table... I'll get a fix up tonight that will allow this to work... sorry for the confusion!

**Comment by latenitefilms** [comment]
Thanks @asmagill !
