### ISSUE TITLE
Allow hs.http requested to be sent via a specific network interface

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#1166]
Currently I need to use the ``curl --interface`` command as the only way I know to force traffic through a certain interface. It would be good if ``hs.http`` had an option to do the same.

**Comment by cmsj** [comment]
AFAICT, NSURLConnection (which we currently use) does not support specifying a source address/interface, nor does NSURLSession (which we ought to switch `hs.http` to since NSURLConnection is deprecated). The only way to do this would be to use something lower level like GCDASyncSocket (which we do actually currently have for other reasons).

I can't help but wonder if there might be some value in an `hs.curl` that wraps libcurl. As one might expect, this sort of thing exists already, e.g. https://github.com/Lua-cURL/Lua-cURLv3 which might be of interest to you.

**Comment by cmsj** [comment]
I'm going to close this because I don't think we'll be able to do it - as I said above, NSURLConnection/NSURLSession don't offer this, and I think it would be a mistake for us to re-implement a whole HTTP request stack just for this feature. Sorry!
