### ISSUE TITLE
Inconsistent mouse click activity on Sierra

### ISSUE THREAD

**Issue by randomeizer** [Hammerspoon/hammerspoon#1180]
The following script as a test runner:

```lua
function drawBoxes()
	print("Drawing red and blue boxes.")
	redFrame = hs.geometry.rect({x=100, y=100, h=100, w=200})
	redBox = hs.drawing.rectangle(redFrame)
		:setFillColor({red=1.0})
		:setFill(true)
		:setClickCallback(function()
			print("Red clicked!")
		end)
		:show()
	blueFrame = hs.geometry.rect({x=350, y=100, h=100, w=200})
	blueBox = hs.drawing.rectangle(blueFrame)
		:setFillColor({red=0, blue=1.0})
		:setFill(true)
		:setClickCallback(function()
			print("Blue clicked!")
		end)
		:show()
end

function deleteBoxes()
	print("Deleting boxes.")
	redBox:delete()
	blueBox:delete()
end
	
function clickBox(box)
	local center = hs.geometry.rect(box:frame()).center
	hs.eventtap.leftClick(center)
end

function swapLocations(box1, box2)
	local frame = box1:frame()
	box1:setFrame(box2:frame())
	box2:setFrame(frame)
end

function redBlueClick()
	print("redBlueClick About to click red then blue box.")
	clickBox(redBox)
	clickBox(blueBox)
	print("redBlueClick Done.")
end

function redBlueClickSleep()
	print("redBlueClickSleep About to click red then blue box.")
	clickBox(redBox)
	clickBox(blueBox)
	hs.timer.usleep(1)
	print("redBlueClickSleep Done.")
end

function redBlueClickTimer()
	print("redBlueClickTimer About to click red then blue box.")
	clickBox(redBox)
	clickBox(blueBox)
	hs.timer.doAfter(0.000001, function()
		print("redBlueClickTimer Done.")
	end)
end

function redBlueClickSwapTimer()
	print("redBlueClickSwapTimer About to click red then blue box then swap them before the timer.")
	clickBox(redBox)
	clickBox(blueBox)
	swapLocations(redBox, blueBox)
	hs.timer.doAfter(0.000001, function()
		print("redBlueClickSwapTimer Done.")
	end)
end

drawBoxes()

hs.timer.doAfter(0.000001, function()
	redBlueClick()
	
	redBlueClickSleep()
	
	redBlueClickTimer()
	
	redBlueClickSwapTimer()
	
	hs.timer.doAfter(0.000001, deleteBoxes)
end)
```

On El Capitan, you get this result:
```
> Drawing red and blue boxes.

 > redBlueClick About to click red then blue box.
 > redBlueClick Done.
 > redBlueClickSleep About to click red then blue box.
 > redBlueClickSleep Done.
 > redBlueClickTimer About to click red then blue box.
 > redBlueClickSwapTimer About to click red then blue box then swap them before the timer.
 > Red clicked!
 > Blue clicked!
 > Red clicked!
 > Blue clicked!
 > Red clicked!
 > Blue clicked!
 > Red clicked!
 > Blue clicked!
 > redBlueClickTimer Done.
 > redBlueClickSwapTimer Done.
 > Deleting boxes.
```

This kind of makes sense, although honestly wasn't what I was expecting. However, on Sierra, you get this:

```
> Drawing red and blue boxes.

 > redBlueClick About to click red then blue box.
 > redBlueClick Done.
 > redBlueClickSleep About to click red then blue box.
 > redBlueClickSleep Done.
 > redBlueClickTimer About to click red then blue box.
 > redBlueClickSwapTimer About to click red then blue box then swap them before the timer.
 > Blue clicked!
 > Red clicked!
 > Blue clicked!
 > redBlueClickTimer Done.
 > redBlueClickSwapTimer Done.
 > Deleting boxes.
```

A whole bunch of clicks went MIA. Either they were delayed until after the boxes were deleted, or they never happened.

Any thoughts?

**Comment by randomeizer** [comment]
This is in Hammerspoon 0.9.52, by the way.

**Comment by asmagill** [comment]
Are both running 0.9.52?

If I had to guess I'd say that Apple changed the relative priority of mouse events and expired timers in Sierra so that a timer that is already past due is bumped to the front of the line as queued events are address during each iteration of the application runloop.  I know they've adjusted priorities before in efforts to make application run-loops seem more responsive, but I don't know where to check for a definitive answer or if we can "revert" the behavior...

What are you trying to actually accomplish?  It may be that there is a better/clearer way to go about it.

**Comment by randomeizer** [comment]
Yes, we're both on 0.9.52.

We are trying to do a series of UI activities via axuielement, and in the
middle of them do a mouse click. It seems to work in El Capitán, but in
Sierra the mouse click happens after all the axuielement actions finish.

**Comment by asmagill** [comment]
I played with this some... (I'm also running Sierra, fwiw)...

By changing the timer which deletes the boxes to `hs.timer.doAfter(1, deleteBoxes)` and modify the leftClick line so it no longer pauses between the down click and the release, `hs.eventtap.leftClick(center, 0)` (the default is 2/10 of a second), we get:

~~~lua
Drawing red and blue boxes.

redBlueClick About to click red then blue box.
redBlueClick Done.
redBlueClickSleep About to click red then blue box.
redBlueClickSleep Done.
redBlueClickTimer About to click red then blue box.
redBlueClickSwapTimer About to click red then blue box then swap them before the timer.
redBlueClickTimer Done.
redBlueClickSwapTimer Done.
Blue clicked!
Red clicked!
Blue clicked!
Red clicked!
Blue clicked!
Red clicked!
Blue clicked!
Red clicked!
Deleting boxes.
~~~

This suggests to me that Apple has in fact changed the priorities for expired timers and/or backlogged mouse events (note that the "redBlueClickTimer Done." and "redBlueClickSwapTimer Done." lines now appear before *any* of the click actions occur, but that all of the clicks, including the ones which occurred before the clickTimer and ClickSwapTimer are defined occur).

Since timers and events are posted to Hammerspoon's runloop and the runloop is only able to process one thing at a time, we're somewhat limited to Apple's priority choices unless we want to add a whole new level of complexity by adding support for different runmodes and modifying the runloop so it prioritizes or runs certain modes more often than others... and I know just enough about this subject to break things in a spectacular fashion :-)  It's an area I'm learning more about in an effort to make `hs.eventtap` more responsive when a lot of eventtaps are defined, but at the moment I know that I don't know nearly enough to propose a solution yet.

At the moment I can only suggest using longer times in your timers and maybe arrange the blocks differently or with more delays in between them... I'd stay away from `hs.timer.usleep` since that is a blocking delay which means the runloop doesn't get a chance to process anything while its in effect (this is what `hs.eventtap.leftClick` uses between the mouse down and the mouse up if you don't set it the delay to 0).

I'll keep this code around and try it from time to time as I get more comfortable with tweaking the runloop, but at the moment I don't have any better ideas.  Sorry!

**Comment by cmsj** [comment]
Do we think there is anything to be done here?
