### ISSUE TITLE
Hammerspoon hangs when trying to execute applescript

### ISSUE THREAD

**Issue by ryanseddon** [Hammerspoon/hammerspoon#1185]
I have some applescript that is ran via a hot key, `hs.caffeinate.watcher` and `hs.wifi.watcher` most of the time hammerspoon will hang and become unresponsive for anywhere between 10 - 60 seconds, hover over the hammerspoon icon will show the pin wheel of death. Sometimes this applescript runs fine bust mostly it causes hammerspoon to hang.

### Applescript in question

```applescript
hs.applescript([[
	ignoring application responses
		tell application "System Events" to tell process "VPN"
			click menu bar item 1 of menu bar 2
		end tell
	end ignoring
	do shell script "killall System\\ Events"
	delay 0.1
	tell application "System Events" to tell process "VPN"
		tell menu bar item 1 of menu bar 2
			if exists menu item "Connect to" of menu 1
				tell menu item "Connect to" of menu 1
					click
					click menu item "Region" of menu 1
				end tell
			end if
		end tell
	end tell
]])
```

I've also taken a sample of the process in activity monitor when it was unresponsive. You can see that [here](https://gist.github.com/ryanseddon/c173440d1c894b09c3ba742b31803edb).

**Comment by latenitefilms** [comment]
As a workaround, you could try running the AppleScript code via the Command Line and see if that makes any difference? At least that way you can rule out whether it’s a Hammerspoon issue or AppleScript issue.

Another thing you could try is running the AppleScript in a hs.timer so that it effectively runs in it’s own “thread”?

Another alternative to AppleScript would be to use this to select the menubar items using LUA scripting: https://github.com/asmagill/hs._asm.axuielement <https://github.com/asmagill/hs._asm.axuielement>

**Comment by ryanseddon** [comment]
It's seeming like more of an issue with the applescript, running it via `osascript` it will timeout which is probably what is causing hammerspoon to lockup.

I think I've narrowed it down to `do shell script "killall System\\ Events"` which can take more than the default 120s timeout applescript has in some cases.

My automation seems to be working now. Closing.
