### ISSUE TITLE
Reading SQLite Databases in Hammerspoon?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1186]
Does anyone have any experience in reading SQLite databases using LUA in Hammerspoon?

**Comment by asmagill** [comment]
See https://github.com/Hammerspoon/hammerspoon/issues/515#issuecomment-141691637

The luarocks version does work if you force it to link against the homebrew sqlite... the other option would be to compile the luarocks library yourself and disable extension support.

@cmsj, I do think we should probably decide on a solution and include it in Hammerspoon ourselves... this comes up every 6 months or so and since Apple uses and includes sqlite for its own purposes, supporting it makes a lot of sense.  IIRC losing extension support shouldn't impact most users of sqlite, so I'm in favor of compiling lsqlite3 ourselves without it and using that, unless someone else has a better suggestion or suggests a different library to use.

**Comment by latenitefilms** [comment]
I would love to have native Hammerspoon SQLite support - so if this is something you can add to the core, that would be amazing!

**Comment by cmsj** [comment]
@asmagill yep, let's get this done. I think we have two options:

 * Build lsqlite3 against Apple's sqlite3 library and wash our hands of whatever feature flag choices need to be made
 * Build lsqlite3-complete with its own sqlite3.c and make choices about which feature flags to enable.

I think the latter would be better, but I am in no position to make useful choices about the feature flags, so the best I could do would be to try and figure out which ones Apple used, and copy them, or copy the choices made somewhere like Debian.

**Comment by asmagill** [comment]
Unless someone can suggest a compelling reason to include features not included with Apple's library, I'm leaning towards just compiling against Apple's and be done with it.  One less thing to compile into Hammerspoon and have to worry about whether we should be upgrading it or not as it changes upstream.  Even homebrew installs theirs keg-only by default now, so I think its safe to assume that 99%+ of the time Apple's is sufficient unless you're doing some pretty specific things with your databases.

OTOH I don't use it much myself, so if anyone has other thoughts, I'm open to discussion.

**Comment by cmsj** [comment]
I have just pushed a basic hs.sqlite3 to master which links against Apple's library. The modifications to lsqlite.c were very minimal. I have done a super basic smoketest and it seems to work, but I would appreciate some feedback from folk who have more of an idea of what they want to do with this :)

**Comment by cmsj** [comment]
I'm going to close this issue in favour of #515 - let's continue any discussions over there.
