### ISSUE TITLE
Prevent hs.webview from giving Hammerspoon focus?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1193]
Similar to #1190 - is there anyway to create a `hs.webview` that doesn't actually give Hammerspoon focus when clicked on? I basically want to make it so a `hs.webview` appears (to the end user) as if it's appearing as part of another application.

Any ideas @asmagill or @cmsj ?

**Comment by asmagill** [comment]
If the webview is for display only (i.e. the user does not interact with it in any way), then it should be possible though I will have to look up the exact settings to set.

If the user can interact with the web view (type text, click on buttons, etc.) then no, HS takes focus because one of its windows becomes active... it's the macOS way.

You can minimize the visual/user impact of this in a couple of different ways...
* use hs.application watcher to detect what the previous application/window was and immediately switch back to it when the webview loses focus or their action is completed
* remove Hammerspoon's icon from the dock with `hs.dockIcon`

**Comment by latenitefilms** [comment]
Sorry for the delayed reply - thanks for this! All makes sense.
