### ISSUE TITLE
How to set 'right shift' = 'Command + Space'？

### ISSUE THREAD

**Issue by jinjian1991** [Hammerspoon/hammerspoon#1199]
```lua
hs.hotkey.bind({"cmd", "right_shift"}, "W", function() // (right shift, right-shift, rifht_shift, shift right, shift-right, shift_right) all invalid
  hs.alert.show("Hello World!")
end)
```

**Comment by latenitefilms** [comment]
It's not possible in `hs.hotkey` to bind a specific shift button.

The only supported modifier keys are:

- "cmd", "command" or "⌘"
- "ctrl", "control" or "⌃"
- "alt", "option" or "⌥"
- "shift" or "⇧"

See: http://www.hammerspoon.org/docs/hs.hotkey.html#new

You will have to use `hs.eventtap.event` instead. 

See: http://www.hammerspoon.org/docs/hs.eventtap.event.html#newKeyEvent

**Comment by jinjian1991** [comment]
@latenitefilms Thanks.

I just need the right shift not all shift(left and right), it looks like cannot accomplish.

**Comment by latenitefilms** [comment]
It's possible - here's an example of only using the left option button:

https://github.com/asmagill/hammerspoon_asm/blob/master/touchbar/Examples/touchbar.lua

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Comment by zestyping** [comment]
I'd like to reopen this issue.

The link to touchbar.lua in https://github.com/Hammerspoon/hammerspoon/issues/1199#issuecomment-274242356 is broken, so I can't figure out how to do it.  I assume there's still some way to hack around this that I can't fathom, but it would be a lot easier if you could simply specify left-shift or right-shift (or left-command, left-option, etc.) when you bind a hotkey.

Thanks for considering it!

**Comment by asmagill** [comment]
The link moved, it should be https://github.com/asmagill/hs._asm.undocumented.touchbar/blob/master/Examples/touchbar.lua

It's also described here https://github.com/Hammerspoon/hammerspoon/issues/1025#issuecomment-1011435207

We can't set the hotkey's to respond only to left or right modifier only because the underlying API being used for hotkeys doesn't support the distinction. However, you could use [hs.eventtap.checkKeyboardModifiers(true)](https://www.hammerspoon.org/docs/hs.eventtap.html#checkKeyboardModifiers) and check the `_raw` key in the same manner as described in the above links to make the hotkey do something different depending upon whether it was triggered by the right or left modifier.

**Comment by ColoursofOSINT** [comment]
I think this would be a very useful hotkey as it and the right alt key are very rarely used. Infact, [rcmd](https://lowtechguys.com/rcmd/), uses this for quick switching between apps.

**Comment by asmagill** [comment]
*sigh*...

Let me repeat, the underlying API being used for `hs.hotkey` **CAN NOT** be invoked in such a way to distinguish left from right modifiers. It uses the Carbon API and works at a pretty low level which is why it is very fast and very reliable and works even when an application has enabled secure keyboard entry. But it does not distinguish between left and right and nothing we do can change that. We *can* check, once in the hotkey callback, if the right or left one has been pressed, but *both* will *always* trigger the callback. And it's challenging to conditionally pass the key which invoked the hotkey callback (if it's the left modifier, for example) via `hs.eventtap.keyStroke` because it just re-triggers the hotkey unless you disable it within the callback and send the keystroke within a timer so that the Hammerspoon event loop can progress, followed by another timer to re-enable the hotkey -- each step *must* be a separate event in the application run-loop.

Rewriting the entire `hs.hotkey` module to use `hs.eventtap` sounds like a solution until you realize that it would mean that **every single key typed on your keyboard at all times** would have to trigger the callback (thus making it slow) and it would abruptly stop anytime an application enabled secure keyboard entry.

You could set up an eventtap which *just* detects when modifier keys have been pressed and then determine if the left or right version(s) have been pressed and activates (or deactivates when the callback shows that the modifier(s) has been released) a set of hotkeys, but it would also stop working abruptly when secure keyboard entry is enabled. This would be more responsive than totally switching `hs.hotkey` to an eventtap, but might still suffer from occasional slowdowns when Hammerspoon gets busy (definitely) or other applications tie up resources (not as sure, but I do know that eventtaps with complex callbacks can be unreliable at times for difficult to identify reasons).

But there is no solution which easily makes `hs.hotkey` distinguish between left and right modifiers that will work all the time in all situations.

**Comment by latenitefilms** [comment]
You might be able to use the Karabiner-Elements's API as a trigger?

**Comment by asmagill** [comment]
Actually, I just ran a test with Terminal set to secure entry, and it looks like flag change events *do* still get passed through, so the last example I posted becomes more likely doable, e.g.

>You could set up an eventtap which just detects when modifier keys have been pressed and then determine if the left or right version(s) have been pressed and activates (or deactivates when the callback shows that the modifier(s) has been released) a set of hotkeys, but it would also stop working abruptly when secure keyboard entry is enabled. This would be more responsive than totally switching hs.hotkey to an eventtap, but might still suffer from occasional slowdowns when Hammerspoon gets busy (definitely) or other applications tie up resources (not as sure, but I do know that eventtaps with complex callbacks can be unreliable at times for difficult to identify reasons).

If I get a chance this coming weekend (I'm flying to London tomorrow -- my daughter is graduating soon, but I should have some free time once I've adjusted to the time difference and figured out our schedule for the next couple of weeks) I think I can mock up an example of how this might be implemented. No promises that it won't still be slow and potentially unreliable at times, but it is the first thing that's shown any promise...

**Comment by asmagill** [comment]
Ok, I've created a spoon that I think should do what we've been talking about here... it's minimally tested, so let me know your experiences with it and I'll try and do some more testing before formally submitting it.

You can see the code at https://github.com/asmagill/hammerspoon-config-take2/tree/master/_Spoons/LeftRightHotkey.spoon or download a zip file for local installation at https://github.com/asmagill/hammerspoon-config-take2/blob/master/_Spoons/LeftRightHotkey.zip

**Comment by asmagill** [comment]
Added stacking, deleteAll, and disableAll support at the same URLs

**Comment by ColoursofOSINT** [comment]
Thanks! I will give a shot and report back.

**Comment by muescha** [comment]
@asmagill the folder in the repo `LeftRightHotkey.spoon` is not anymore available. Is there a new home for this spoon?

**Comment by asmagill** [comment]
It's part of the official spoon repository now.  You can find it at https://github.com/Hammerspoon/Spoons/raw/master/Spoons/LeftRightHotkey.spoon.zip.
