### ISSUE TITLE
State persistence over reloads

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#12]
caffeinate would like this, also probably some other modules.

**Comment by Habbie** [comment]
Based on IRC discussion: how about one table that persists over reloads (but not restarts?), plus a flag to setup.lua (visible from init.lua) that tells the user whether this is a fresh start or not? Users/extensions would just save state to this table on any change (thus avoiding an 'on reload' hook).

**Comment by cmsj** [comment]
+1. I'd go for a table that persists over reloads, but not restarts. We have hs.settings for that, if people want to do that sort of thing.
I think ideally the flag would indicate "reload", "restart", "first" (the latter meaning that this is the first time HS has been launched since the computer was booted)

**Comment by cmsj** [comment]
Do we have any idea how we would persist a Lua table across a reload? Given that the table could contain almost anything!

**Comment by Habbie** [comment]
What's the problem with limiting it to basic types (float, string)?

**Comment by cmsj** [comment]
I don't think anyone is going to work on this issue - it can be worked around trivially by using hs.settings to store some ephemeral data and then clearing it as soon as it's been used.
