### ISSUE TITLE
hs.wifi.associate without passphrase

### ISSUE THREAD

**Issue by TheLocehiliosan** [Hammerspoon/hammerspoon#1214]
Is it possible to make `passphrase` an optional parameter for `hs.wifi.associate()`?

My MacBooks remember the passphrase for networks they already know about. I'm looking to automate the process of clicking on the wifi menubar icon, and selecting a known wifi network. Using the MacOS GUI interface for that doesn't require entering a passphrase. I'd really like to leave the passphrase out of my hammerspoon configuration so I can share it with others.

**Comment by cmsj** [comment]
@TheLocehiliosan looking at the underlying CoreWLAN documentation from Apple, it seems like the passphrase is a required parameter :/

@asmagill any ideas that might prove me wrong? :)

**Comment by asmagill** [comment]
Off the top of my head no, I don't think such a method exists.

Known network security keys are stored in the keychain, and I've toyed with creating a way to interact with the keychain within hammerspoon, but at present you'll have to query for it from the shell using `hs.execute` or `hs.task`.  In this case, I recommend `hs.task` because:

1. It's non-blocking and this will prompt you for user credentials and thus block if the user takes a while to type in their info
2. The password itself is sent to `stderr`, not `stdout`, so you have to use redirection if you use `hs.execute` and even then you'll have to filter out some info that you don't want.

The shell command you'll want to use is `security find-generic-password -ga SSID` where SSID is the network you want to connect to.

See http://blog.macromates.com/2006/keychain-access-from-shell/ for more info and an example of redirecting `stderr` and suppressing `stdout` if you want (but point 1 still remains if you use `hs.execute`).

**Comment by TheLocehiliosan** [comment]
Thanks for taking a look and offering ideas. I was really hoping for a solution which didn't require user input. I was just guessing it might be possible given that no input is required when selecting it from the wifi menubar menu.

Cheers

**Comment by asmagill** [comment]
In the case of the Wifi menu, it's supporting app created the keychain entry so it doesn't require credentials to query for it... you might see if someone has an AppleScript snippit which can select an item in this menu and then execute it with `hs.osascript`, but at present I think that's the best bet.

**Comment by latenitefilms** [comment]
If you don't want to use AppleScript, you could also try using @asmagill's excellent [hs._asm.axuielement](https://github.com/asmagill/hs._asm.axuielement) to select what you want via GUI Scripting.

Or if you do want to use AppleScript try:

```
hs.osascript.applescript([[
tell application "System Events"
    tell process "SystemUIServer"
        click (menu bar item 1 of menu bar 1 whose description contains "Wi-Fi")
        click menu item "NETGEAR" of menu 1 of result
    end tell
end tell]])
```

**Comment by cmsj** [comment]
I'm going to close this issue because I don't think it's possible to do. It seems very strange to me that Apple wouldn't have API for joining passwordless networks, but unless someone can prove me wrong, that does appear to be the case.

**Comment by TheLocehiliosan** [comment]
@cmsj Thanks for looking at it. Cheers.
