### ISSUE TITLE
Allow users to execute Lua asyncronously?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#122]
@asmagill @Habbie you guys know far more about this than me - how reasonable/possible is it to set up a new Lua instance for a particular function to run? Say the user wants to do something they know will block, or take a long time, so it runs on a separate thread?

**Comment by cmsj** [comment]
I'm going to close this, since I've not come up with a concrete use-case for it yet.

**Comment by szymonkaliski** [comment]
Sorry for bumping old thread, but I just tried idea of having notifications for online/offline, checking with `ping -c3 8.8.8.8` and comparing with last value, this worked fine, but blocks hs while ping is happening, so another thread would be nice for this.

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - I just came across Lua Lanes, and was about to post a new issue about it, but found this thread.

I'm currently using a lot of `hs.timer`'s that are constantly checking GUI elements for changes (which can sometimes can slow other things Hammerspoon is doing). This could be really handy to run on another thread. Possible? Should this issue be reopened?

**Comment by latenitefilms** [comment]
Related: http://lualanes.github.io/lanes/comparison.html

**Comment by asmagill** [comment]
@latenitefilms, every few months I revisit this idea, and it has been a while, so I should probably do so again.  However, let me add some notes as to the difficulties and concerns, partially so you understand why it hasn't been fully tackled yet, but also so that anyone (including myself) who does have a hankering to take a crack at it has a bit of a checklist for some of the issues that have already been identified that will have to be addressed in one way or another...

* Strictly speaking, this isn't what the original question was about, but I want to put it out there in case some enterprising individual points out the presence of lock function wrappers in the lua source code: The core lua engine (as I understand it) isn't designed to be accessed from multiple threads simultaneously.  The wrappers are empty placeholders at present, and as far as I know would only allow for a given thread to block other threads while the "active" thread manipulates the stack... the other threads are essentially blocked and you would have *one* lua engine that could run from multiple threads, but only *on one thread at a time*.

* Multiple indépendant lua states can exist at the same time in the same application. Each state has its own stack, so it has it's own global variables, etc. In theory you can run these from the main thread, but the main thread can only do one thing at a time -- unless the lua code running in a given state yields (through co-routines), is written as short functions no single one of which takes very long to complete, or has some application code designed to "interrupt" one state and then parcel out time to another state, this doesn't gain us asynchronous execution... independent variable space, which may be of interest to some coders, but again not what the question was about.

* So, we're faced with having different lua states on different threads; I've only tried this with the macOS's NSThread class, though in theory any of the BSD/*nix threading libraries that macOS supports (or can be compiled for macOS) should be similar. The issues:
  * Separate variable spaces -- you need some mechanism for transferring data between the threads which, depending upon the method chosen blocks at least one of the threads (and maybe both) or limits the type of data which can be shared (concrete types like number, string, boolean, etc. are easy... userdata objects are either possible with some limitations (reset callback functions, modified __gc functions that are aware of other threads to skip OS side cleanup unless all threads are done with it, etc.) or out-right impossible.
  * LuaSkin is designed to run with a singleton instance on the main thread only.  I have a modified version of LuaSkin so that it runs a separate singleton on each unique NSThread, so this limitation isn't a deal breaker, but it does require modification to *every* module that uses LuaSkin because even if you modify the `[LuaSkin shared]` class method to detect the thread and return the correct object, you have to address the fact that the `refTable` reference returned when a module is loaded is likely to be different on each thread -- and the modules as written expect a single static value.
  *  In fact almost every static variable in every module that doesn't have a deterministic value has to be modified to be thread aware (or at least looked up in a dictionary which stores each threads version of the variable).
  * Modules that do something that causes the OS to issue a callback at a later time rely on knowing that the main thread is where to invoke the lua callback... now you need to know *which* thread is the "main" thread to perform the callback on -- more changes to the module code.
  * Some macOS classes aren't safe to use on an alternate thread -- in many cases they may be safe as long as a given instance is only ever accessed from the thread it was created on; in others even trying to use the object on an alternate thread can cause unexpected issues or ultimately a crash. I wish I could tell you that the macOS documentation is clear on this for *every* class.  It is for some (especially the older stuff), and not for others... let's leave it at that before I tell you what I really think about the quality of the documentation on this subject.

Making a module which allowed *only* lua code to run on an alternate thread would be pretty easy, once you decide on the method for transferring data between the two, and if there is interest, this can be done. But how much of the code you generally want to run in a separate thread is *just* lua code (i.e. no modules other than maybe `fnutils` since it is pure lua, or those installed through LuaRocks, since none of those use LuaSkin)? In my case I've always found it easier, if less re-usable, to go ahead and code the complex pieces in Objective-C instead and handle the alternate threads through GCD (Grand Central Dispatch I think) with callbacks on the main thread.

Just my observations/experiences; I know I'll try again at some point, but unless I make any major breakthroughs or come up with any unexpected insights, I don't expect much to change on this front.

**Comment by asmagill** [comment]
@latenitefiles, WRT your specific issue of the timers checking the GUI elements... can you give examples?  Are these elements created/maintained by Hammerspoon itself or elements of other applications you're checking via `hs._asm.axuielement`?  If the later, one thing I haven't added to that module yet is watchers... in theory this would remove the need for polling.

 I'm in the middle of getting guitk to a point where I can think about integrating it into core (the additional changes I want to make to canvas, menubar, and webview really make more sense when guitk is part of core), but once that's done, I haven't decided if I want to tackle touchbar or axuielement next... this could influence my ultimate decision.

**Comment by latenitefilms** [comment]
> Are these elements created/maintained by Hammerspoon itself or elements of other applications you're checking via `hs._asm.axuielement`? If the later, one thing I haven't added to that module yet is watchers... in theory this would remove the need for polling.

Correct - we're using `hs._asm.axuielement` and `hs.timer`'s to check that certain panels are open or closed, buttons are selected, etc. in Final Cut Pro. If you could add watchers to `hs._asm.axuielement` this would be MASSIVE for us! I know we discussed this briefly before, as [UI Browser](http://pfiddlesoft.com/uibrowser/) offers the ability to "observe notifications", so it's definitely possible. And you're probably right, if we had this functionality, then we probably won't have a need for asynchronous scripts.

> I'm in the middle of getting guitk to a point where I can think about integrating it into core (the additional changes I want to make to canvas, menubar, and webview really make more sense when guitk is part of core), but once that's done, I haven't decided if I want to tackle touchbar or axuielement next... this could influence my ultimate decision.

Well, we're using both your `hs._asm.undocumented.touchbar` and `hs._asm.axuielement` extensions in the shipping beta of CommandPost, and so far the feedback has been fantastic - so THANK YOU! CommandPost certainly wouldn't be possible without `hs._asm.axuielement`, and the stuff we've done recently with `hs._asm.undocumented.touchbar` has been a game changer. So again, we HUGELY appreciate all your amazing work!!

If I was able to influence your priority list, for me, I'd go with:

1. Finish & Add `hs.guitk` to Hammerspoon (originally `hs._asm.guitk`)
2. Add watchers/notifiers to `hs._asm.axuielement`.
3. Add `NSArchivedObject` support to `hs._asm.cfpreferences`
4. Finish & Add `hs.axuielement` to Hammerspoon (originally `hs._asm.axuielement`)
5. Finish & Add `hs.preferences` to Hammerspoon (originally `hs._asm.cfpreferences`)
6. Rewrite `hs.menubar`
7. Holiday.
