### ISSUE TITLE
Feature Request - hs.updateAvailable? 

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1221]
In addition to `hs.automaticallyCheckForUpdates()`, `hs.canCheckForUpdates()` and `hs.checkForUpdates()`, it would be great if there was a `hs.updateAvailable()` so that we can determine if there's actually a new update or not.

The reason I would like this feature is so that I can add an "Update Available" button on our menubar.

**Comment by junkblocker** [comment]
See if this code fragment I use helps you

```lua
    local function doit(resp_code, resp_body, _)
        if hs.canCheckForUpdates() then
            hs.checkForUpdates()
            return
        end
        if resp_code < 0 then
            print(resp_body)
            return
        end
        local resp_json = hs.json.decode(resp_body)
        local this_version = hs.processInfo.version
        local remote_version = resp_json.tag_name
        if remote_version and this_version ~= remote_version or manual then
            hs.alert("Running: " .. this_version .. "\nAvailable: " .. (remote_version or 'Unknown'), 2)
        end
    end
    hs.http.asyncGet("https://api.github.com/repos/Hammerspoon/hammerspoon/releases/latest", nil, doit)
```

**Comment by latenitefilms** [comment]
Legend, thanks @junkblocker - I didn't think about doing it that way! Very helpful.

However, I still feel like this would be handy in the HS core. Thoughts @asmagill & @cmsj ?

**Comment by asmagill** [comment]
I looked into this a little bit when adding the current commands to Hammerspoon and didn't find an easy way to do it... The updates are handled by the [Sparkle framework ](https://sparkle-project.org) and I didn't find an obvious method that would return this information for us without triggering some the dialog prompting the user to see if they want to perform the update... of course I may have missed something (@cmsj, you understand that part of Hammerspoon way better then I do, so chime in if you have any thoughts) and since I work off of custom builds (which don't include Sparkle because it complains about a key-mismatch anyways if they do), I couldn't really test it anyway.

I wouldn't be against adding a variation of the above code into the `hs` namespace of Hammerspoon, though... perhaps have it query on a schedule and set a key like `availableVersion` in `hs.processInfo`, maybe.  @cmsj?

**Comment by latenitefilms** [comment]
If you decide to do something similar to @junkblocker's example, it might be better to refer to `appcast.xml` rather than GitHub's API?

**Comment by cmsj** [comment]
@latenitefilms yeah I would consider the appcast.xml to be the canonical source of truth here.

@asmagill Sparkle has a `- (void)checkForUpdateInformation;` that checks without triggering UI, and there are delegate methods that get called when an update is found.

I'm fine with having this stuff exposed, I think what I would suggest we do here is add Lua api for calling the above method, and checking if an update is available. I don't want to put it in hs.processInfo() because that's a static table created when Lua is initialised.

I've got a commit inbound for this, but it's almost entirely untested because I don't easily have a private/fake appcast.xml setup and I just wanted to land the code for now. I'll milestone this issue for the next release to remind me we need to test it :)

**Comment by latenitefilms** [comment]
@cmsj - `hs.updateAvailable()` only seems to return the correct value AFTER `hs.checkForUpdates()` has been run.

For example:

```
> hs.updateAvailable()
false

> hs.updateAvailable()
false

> hs.checkForUpdates()


> hs.updateAvailable()
true
```

**Comment by cmsj** [comment]
@latenitefilms correct, it's a cached value. I suppose the docs should make that clearer. There is no synchronous way to check for updates and get an answer, this has to be async, so either the normal update check timer, or a call to `checkForUpdates()` will be required, to make that value change.

**Comment by latenitefilms** [comment]
No worries! I wonder if it's worth remembering the value using `hs.settings`, so that Hammerspoon remembers that there's a new update available (without having to show the user the Sparkle update screen) after restarting the app? I guess however, I could just do this in my own script - rather than needing to complicate the core application.

Regardless, thanks so much for adding!!

**Comment by cmsj** [comment]
@latenitefilms note that I also added an boolean option to `checkForUpdates()` - if you pass `true`, it should avoid presenting the UI when an update is available. Doesn't help for restarts showing the dialog, but I'm not sure I really want to do anything about that, people who don't want that can turn off the automatic update check and use their own `checkForUpdates(true)` timer.

**Comment by latenitefilms** [comment]
@cmsj - Ah, right - sorry, no, I didn't notice that. That's perfect! Problem solved! Thank you!!

**Comment by cmsj** [comment]
(I want to keep this open for now, to make sure I test it properly before releasing 0.9.53)

**Comment by latenitefilms** [comment]
When you do a fresh install of Hammerspoon, is "Check for Updates" off by default?

**Comment by latenitefilms** [comment]
All good. It looks like `SUEnableAutomaticChecks` is `YES` by default.

While you're at it, I wonder if it's worth "exposing" `SUScheduledCheckInterval` as well?

**Comment by latenitefilms** [comment]
Also, is there a way to get new version number via the Sparkle API? It would be awesome if `hs.updateAvailable()` returned both `true` and `0.9.53`.

**Comment by latenitefilms** [comment]
Legend, thank you!!!

Is it worth also exposing 'SUScheduledCheckInterval' so everything can be done by API?

**Comment by latenitefilms** [comment]
@cmsj - Also, not sure if it matters, but Xcode tells me:

`Hammerspoon/MJAppDelegate.m:49:26: Incompatible pointer types assigning to 'NSString *' from 'NSNumber *'`

**Comment by cmsj** [comment]
@latenitefilms good catch, thanks!
