### ISSUE TITLE
Ability to "refresh" menubar-menu

### ISSUE THREAD

**Issue by Fabbi** [Hammerspoon/hammerspoon#1229]
Hi,

would it be possible to have the menu of hs.menubar instantly showing changes made to it?
This would be helpful for things like "show cpu usage" or everything that quickly changes over time.

**Comment by asmagill** [comment]
`hs.menubar` cannot currently update a menu which is currently being displayed (i.e. open); however you can change its title with `hs.menubar:setTitle` and this will be updated immediately.  The contents of the menubar can also be generated by a function (see `hs.menubar:setMenu`) so that each time it is opened, it is regenerated based upon new data.

Updating a currently open menu (like the finder does when you have the File menu open and hold down the option key, for example) is something I've considered, but as I understand it would require a complete re-write of `hs.menubar` and while this is on the roadmap for the future to replace deprecated methods and code, no time frame has been set yet to my knowledge.

**Comment by sudochop** [comment]
+1

**Comment by cmsj** [comment]
I'm going to close this out because it's not possible with the current hs.menubar, but if/when we do rewrite hs.menubar, it'll be covered.
