### ISSUE TITLE
hs.host.cpuUsage() memory leak and invalid idle reporting

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#1238]
Per some other examples that use host_processor_info(), we seem to be missing a call to vm_deallocate(), I think.

See https://gist.github.com/mmisono/351441

**Comment by asmagill** [comment]
It's entirely possible... iirc, the original source of the code this grew from was a cmd line utility and I've noticed that these often don't clean up properly after themselves assuming that the normal task tear-down will take care of it for them.

**Comment by asmagill** [comment]
I was thinking of the memory statistics... the cpuUsage stuff comes from http://stackoverflow.com/questions/6785069/get-cpu-percent-usage and they do perform a vm_dealloc in the code snippet; sorry I missed that!

**Comment by asmagill** [comment]
Changing this to address google issue at https://groups.google.com/forum/#!topic/hammerspoon/SbhLIQoW9Zw as well.

A side by side comparison of top versus hs.host.cpuUsage confirms that our code is indeed wrong... the samples I've seen all show a differential between runs because `host_processor_info` reports everything in ticks, and I *thought* that as long as we calculated the percentages against the current total, it would work out... and my earlier tests were just single snapshots against what was a fairly idle machine so the numbers were actually close to what top reported.  A continuous test (see https://github.com/asmagill/hammerspoon-config/blob/master/_scratch/idleWatcher.lua if your curious about the code I'm using now) shows that our function does not track properly at all.

I've downloaded Apple's top implementation source code and will see exactly how they're doing it since this seems to be what most of us (myself included) are comparing against.

**Comment by asmagill** [comment]
Ok thinking about it now, that was pretty stupid of me... what its currently reporting is the percentage the cpu(s) have spent in such states since the machine was started up, not a snapshot in time... The tick counts are constantly being incremented and never decremented.

Got a fix in mind and came across `host_statistics` which looks like it might result in cleaner code and take care of the dealloc for us.  I should have a pull up this weekend.

Top uses a 1 second delay between samples, which is too long for Hammerspoon to block for something like this... I'm thinking 1/10 of a second (initial tests suggest that this gives good results that don't jump around *too* much -- smaller delays tend to jump quite a bit) but I'll add a parameter to the function so you can decide on a case by case basis if you're willing to block longer) unless someone has other thoughts on what the delay between samples should be by default?

**Comment by asmagill** [comment]
Sorry for the delay in this.  I am working on a version of this that should be available later this week which will allow you to specify a delay between samples in microseconds, if you want an "immediate" response, or a delay in seconds with a callback function to accept the results (i.e. it's non-blocking and works more like `top` does, providing results that, for me, are usually within 1% of top's.).  In addition, a new function which reports the raw tick values will also be provided (since the updated `hs.host.cpuUsage` requires this).

I'm hoping to have the pull ready tomorrow (as well as one for eventtap re #1235), but definitely by the end of the week.
