### ISSUE TITLE
Remapping Cmd + cursor keys doesn't work

### ISSUE THREAD

**Issue by Rajveer86** [Hammerspoon/hammerspoon#1257]
I'm trying to remap Cmd + cursor keys to Opt + cursor keys and I'm using the following line to create an event and post it:

`hs.eventtap.event.newKeyEvent(modifiers, string.lower(key), pressed):post()`

which doesn't seem to be working. I've tried hard coding the line to the following:

`hs.eventtap.event.newKeyEvent({}, "left", pressed):post()`

to force a left cursor move in a text editor but again it doesn't work. If I change "left" to another character (e.g. "p") then it works fine. I'm doing this with hotkey bindings.

**Comment by cmsj** [comment]
So, one thing you're always going to run into when you try to use hotkeys to emit other hotkeys, is that from the OS' point of view, the original keys are still held down. We don't get to remove those from the input layer of the kernel.

This means that the OS is seeing Cmd+Opt+Cursor.

One way to avoid this is to do the `newKeyEvent` in the `releaseFn` callback in `hs.hotkey` rather than the `pressedFn` one, but it's not a perfect solution, because there really isn't a perfect solution.

Karabiner is much better at this sort of thing, although its currently going through a complete rewrite to be compatible with Sierra, so YMMV.

**Comment by Rajveer86** [comment]
I'm a bit confused, maybe I'm misunderstanding this. Let's say I have the following hotkey binding and function:

```
local function keyCode(key, pressed, modifiers)
  modifiers = modifiers or {}

  return function()
	  keyEvent = hs.eventtap.event.newKeyEvent(modifiers, string.lower(key), pressed)
	  keyEvent:post()
	  print("Key: ", key, "Modifiers: ", modifiers, ", Pressed: ", pressed)
  end
end

hs.hotkey.bind({"cmd"}, "p", keyCode("left", true, {"alt"}), keyCode("left", false, {"alt"}), keyCode("left", true, {"alt"}))
```

In this case typing Cmd+p causes the cursor to behave like Opt+left (skipping whole words in a text editor), not Cmd+Opt+left i.e. with "p" this works. Replacing the "p" with "left" in the bind function makes this fail. So in theory if what you are saying is correct then when using "p", the OS should see Cmd+Opt+p which doesn't act like Opt+p when I type that normally.

**Comment by cmsj** [comment]
@Rajveer86 to some extent it will depend on the app, and how it examines key events, but when you're emitting keystrokes while keys are being held down, the overall stream of events looks very different to normal.

**Comment by quickdraw6906** [comment]
I've also had some progress tagging events with user data, then looking for that data in the keyUp tap to then set a timer for a new event. You need to do that if you are using hotkey.bind.
