### ISSUE TITLE
RegisterEventHotKey failed: -9878

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1261]
I've had a few people contact me when using our Hammerspoon script with errors like:

```
Hammerspoon Version:            0.9.52
macOS Version:                  10.12.3
Final Cut Pro Version:          10.3.2
Final Cut Pro Language:         en
FCPX Hacks Locale:              ru_RU
Current Keyboard Layout:        ABC

2017-03-16 00:51:20: ********
 > ERROR:   LuaSkin: hs.hotkey:enable() keycode: 49, mods: 0x1000, RegisterEventHotKey failed: -9878 [00:51:20]
2017-03-16 00:51:20: ********
2017-03-16 00:51:57: ********
 > ERROR:   LuaSkin: hs.hotkey:enable() keycode: 49, mods: 0x1000, RegisterEventHotKey failed: -9878 [00:51:57]
2017-03-16 00:51:57: ********
2017-03-16 00:54:28: ********
 > ERROR:   LuaSkin: hs.hotkey:enable() keycode: 49, mods: 0x1000, RegisterEventHotKey failed: -9878 [00:54:28]
2017-03-16 00:54:28: ********
```

...and:

```
Hammerspoon Version:            0.9.52
macOS Version:                  10.11.6
Final Cut Pro Version:          10.3.2
Final Cut Pro Language:         en
FCPX Hacks Locale:              es_ES
Current Keyboard Layout:        Spanish - ISO

2017-02-17 13:46:04: ********
 > ERROR:   LuaSkin: hs.hotkey:enable() keycode: 4, mods: 0x1900, RegisterEventHotKey failed: -9878 [13:46:04]
2017-02-17 13:46:04: ********
2017-02-17 13:46:19: ********
 > ERROR:   LuaSkin: hs.hotkey:enable() keycode: 4, mods: 0x1900, RegisterEventHotKey failed: -9878 [13:46:19]
2017-02-17 13:46:19: ********
2017-02-17 13:48:41: ********
 > ERROR:   LuaSkin: hs.hotkey:enable() keycode: 4, mods: 0x1900, RegisterEventHotKey failed: -9878 [13:48:41]
2017-02-17 13:48:41: ********
2017-02-17 13:48:47: ********
 > ERROR:   LuaSkin: hs.hotkey:enable() keycode: 4, mods: 0x1900, RegisterEventHotKey failed: -9878 [13:48:47]
2017-02-17 13:48:47: ********
```

Is there anyway to "catch" these `RegisterEventHotKey` errors, and do some kind of workaround, rather than triggering an error which stops the code?

Thoughts @asmagill or @cmsj ?

**Comment by cmsj** [comment]
my guess is that all of the people who get that, are using non-english keyboard layouts. You might want to check `hs.keycodes.currentLayout()` early in the script and tell them that they need to edit some keybindings to match the physical keys their keyboard has (perhaps you could store all of the keybinding keys in a table that they can easily edit?)

This is a fundamental tension in Hammerspoon - these sorts of errors are supposed to let the user know that their config is wrong, in a very visible way, but it turns out to not be so helpful where people are distributing Hammerspoon configs as units of functionality.

As I've said in the Spoons discussions, I think my preferred option here is that units of functionality should have a hook for injecting keybinding information, thus forcing users to consider their own keybinding choices, but I know you're trying to go for a more integrated approach.

I'm not sure what the right thing to do here, is.

**Comment by latenitefilms** [comment]
Yes, it's definitely people using non-English layouts - which makes it tricky for me to re-produce.

However, it looks like this error is "blocking" rather than "warning" - which is the annoying part. Ideally, I'd like it if `hs.hotkey` reported a warning, skipped that `hotkey` and moved onto the next one - rather than stopping the whole process. Maybe that's something that could be easily actioned?

We are actually working on a shortcut manager (see attached) - but it will still have the issue, as all our default shortcuts are in English. Having said that... maybe I just need to add a check to make sure that a `hotkey` value exists in `hs.keycodes` before trying to enable?

Either way, I'm happy for Hammerspoon to "skip" a hotkey if it's not sure of the keyboard shortcuts, but I would prefer it not error out if that makes sense?

Thoughts?

![screen shot 2017-03-24 at 12 49 12 am](https://cloud.githubusercontent.com/assets/22286696/24250700/e6523bc6-102b-11e7-9782-c2d8579465b7.png)

**Comment by asmagill** [comment]
The message being displayed says Error because its being issued by LuaSkin at the error log level; however it's not actually generating a lua error, so execution should be continuing on to the next command:

For this example, know that `ctrl-1` is defined on my machine in Keyboard-Shortcuts->Mission Control but since I don't have 4 separate spaces at present, `ctrl-4`, while defined there as well, is not active:

~~~lua
> l = hs.hotkey.bind({"ctrl"},"1",function() print("yay") end)
k = hs.hotkey.bind({"ctrl"},"4",function() print("yoo") end)
2017-04-03 21:47:00: ********
21:47:00 ERROR:   LuaSkin: hs.hotkey:enable() keycode: 18, mods: 0x1000, RegisterEventHotKey failed: -9878
2017-04-03 21:47:00: ********

-- I tap ctrl-1 and ctrl-4 to test them out -- nothing for ctrl-1, but for ctrl-4:

yoo

> l:disable(), k:disable()
table: 0x600002079040	table: 0x600000a7f200
~~~

As you can see, the `ctrl-4` still worked, even though the first line was what generated the error message.

You could suppress these errors from reaching the console by adding `hs.luaSkinLog.level = 0`, but note that this will supress *ALL* log messages issued by LuaSkin from appearing in the console (you can still see them with `hs.logger.printHistory`), e.g.

~~~lua
> hs.luaSkinLog.level = 0


> l = hs.hotkey.bind({"ctrl"},"1",function() print("yay") end)
k = hs.hotkey.bind({"ctrl"},"4",function() print("yoo") end)

-- I tap ctrl-1 and ctrl-4 to test them out -- nothing for ctrl-1, but for ctrl-4:

yoo

> l:disable(), k:disable()
table: 0x600001261000	table: 0x60800107c5c0
-- Loading extension: logger

> hs.logger.printHistory(nil,nil,"hotkey")

-- a bunch of stuff deleted for brevity --

21:51:02     hotkey:         Created hotkey for ⌃1
21:51:02 ERROR:   LuaSkin: hs.hotkey:enable() keycode: 18, mods: 0x1000, RegisterEventHotKey failed: -9878
21:51:02     hotkey: Enabled hotkey ⌃1
21:51:02     hotkey:         Created hotkey for ⌃4
21:51:02     hotkey: Enabled hotkey ⌃4
21:51:13     hotkey: Disabled hotkey ⌃1
21:51:13     hotkey: Disabled hotkey ⌃4
~~~

**Comment by latenitefilms** [comment]
@asmagill - Legend, thanks so much for the detailed reply!

I can reproduce exactly what you're saying on my machine, so I'm going to close this issue for now, and will re-open if needed. Thanks again!

**Comment by focusaurus** [comment]
I'm just going to add a quick comment for folks finding this issue after a web search (that's how I found it). Just FYI it seems keybindings configured in `System Preferences > Keyboard > Shortcuts` will conflict **even if they are disabled**. So to avoid a conflict I had to temporarily enable a shortcut in system preferences, change it to something else to get it out of the way, then disable it, and then I was able to bind that key in hammerspoon.

**Comment by stubar** [comment]
> I'm just going to add a quick comment for folks finding this issue after a web search (that's how I found it). Just FYI it seems keybindings configured in `System Preferences > Keyboard > Shortcuts` will conflict **even if they are disabled**. So to avoid a conflict I had to temporarily enable a shortcut in system preferences, change it to something else to get it out of the way, then disable it, and then I was able to bind that key in hammerspoon.

Thank you so much @focusaurus I was going crazy trying to workout why I couldn't assign f11 even though I unticked it in sys prefs.
