### ISSUE TITLE
Automating the screencasting setup

### ISSUE THREAD

**Issue by cksachdev** [Hammerspoon/hammerspoon#1262]
I use Hydra for launching applications, and automating other tasks. I want to automate the screencast setup. I am looking for a way to automate following:
1. Hide the Menu bar on the top (Hide, not Auto hide)
or
Cleanup all the icons in the menu bar, something similar to Bartender app
2. Hide the Dock in the bottom (Hide, not auto hide)
or
have only certain apps listed in dock (Configurable)
3. Hide the icons on the Desktop and probably set a specific wallpaper(configurable)
4. Set the screen resolution to a specific dimension(configurable)
5. Launch chrome with following
    * Hidden bookmarks
    * Incognito mode or a different user
6. Start recording using screenflow

Is it possible to achieve this using hammerspoon or mjolnir? If yes, could someone please point me to resources/apis and how can I achieve it.

@sdegutis @cmsj @asmagill

**Comment by latenitefilms** [comment]
Because Hammerspoon Extensions can either be pure Lua or a mixture of Lua and Objective-C (although since they are just dynamically loaded libraries, they could ultimately be compiled in almost any language) - the only real limits to what Hammerspoon can do is your time coding!

In answer to your questions:

> 1. Hide the Menu bar on the top (Hide, not Auto hide)
> or
> Cleanup all the icons in the menu bar, something similar to Bartender app

[hs.menubar](http://www.hammerspoon.org/docs/hs.menubar.html) only allows you to create and manipulate your own menubar items - it doesn't have the ability to do anything to non-Hammerspoon menubar items.

If you have a set of very specific menubar items that you want to hide (i.e. a couple of system icons like WiFi & Sound, and maybe a third party one like Dropbox), you could just script something to "manually" disable these items. For example, you could use [hs.osascript](http://www.hammerspoon.org/docs/hs.osascript.html#applescript) to use AppleScript to open up System Preferences and turn off the Wifi & Sound icons, and force-quit Dropbox.

> 2. Hide the Dock in the bottom (Hide, not auto hide)
> or
> have only certain apps listed in dock (Configurable)

You could use [this terminal command](https://www.quora.com/How-can-I-completely-hide-or-remove-the-Dock-in-Mac-OS-X-Yosemite) to forcefully hide the dock using [hs.execute()](http://www.hammerspoon.org/docs/hs.html#execute).

> 3. Hide the icons on the Desktop and probably set a specific wallpaper(configurable)

You can use [this terminal command](http://www.cultofmac.com/272595/quickly-hide-icons-desktop-os-x-tips/) to hide your desktop contents. 

You can use this AppleScript to change the desktop background:

`tell application "Finder" to set desktop picture to POSIX file "/path/to/picture.jpg`

> 4. Set the screen resolution to a specific dimension(configurable)

See: [hs.screen:setMode(width, height, scale)](http://www.hammerspoon.org/docs/hs.screen.html#setMode)

> 5. Launch chrome with following
> Hidden bookmarks
> Incognito mode or a different user

Use [hs.application.launchOrFocus](http://www.hammerspoon.org/docs/hs.application.html#launchOrFocus) to launch Chrome, then use [hs.application:selectMenuItem(menuitem)](http://www.hammerspoon.org/docs/hs.application.html#selectMenuItem) to trigger the Chrome menu items you want to do things.

> 6. Start recording using screenflow

Same as above.

You can also use AppleScript or [hs._asm.axuielement](https://github.com/asmagill/hs._asm.axuielement) to do more advanced GUI Scripting.

Hope this helps!

**Comment by cmsj** [comment]
I think @latenitefilms covered everything here. If not, please feel free to re-open this issue :)
