### ISSUE TITLE
hsdocs launches a server open to the world

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#1293]
Only figured this when shodan came knocking and LittleSnitch alerted me. The documentation gives the impression that it is listening on local interfaces only when it is not true. ``hsminweb`` documentation is cautious enough but ``hsdocs`` doesn't really connect the two. Also, rather than or maybe in addition to an ``accessList`` to do filter based deny, I'd prefer an option to listen on ``::1/127.0.0.1``. ``hsdocs`` doesn't currently give me a public API to do access control either.

**Comment by asmagill** [comment]
i don't think the current hs.httpserver allows us to bind to a specific interface/address; hs.httpserver.hsminweb, which the docs are based on, does support an access filter which can block/allow by ip address -- which i thought i had enabled but apparently not. i'll get this added as the default and add a function for toggling/editing it.

**Comment by cmsj** [comment]
@junkblocker you have your Mac on a public IP? Brave :)

**Comment by junkblocker** [comment]
@cmsj, well, it's an old laptop I thought was running minimal stuff sufficiently protected but yeah :) I should switch over to the linux box.

**Comment by cmsj** [comment]
Fixed (in that we can now get/set the interface. It's still going to listen on all interfaces by default)

**Comment by asmagill** [comment]
looks like hsdocs will still need to invoke this (and this call is simpler then the access list specification i was considering).

if no one beats me to it, i can do it later tonight.

**Comment by junkblocker** [comment]
Same for hsminweb.

**Comment by asmagill** [comment]
As far as I can tell from looking at the server code, only one interface can be specified, so it's all of them or just one.  @cmsj, can you confirm or correct this, since you know the code better than I do?

Questions:

* should `hs.httpserver.hsminweb` default to localhost interface only?  Since `hs.httpserver` defaults to open, I'm leaning towards this also defaulting to open since `hsminweb` is just a more standards compliant wrapper to `hs.httpserver`.

* should `hs.doc.hsdocs` default to localhost interface only?  Since this is a specific application of `hs.httpeserver.hsminweb` and is for Hammerspoon documentation, I'm leaning towards it being restricted by default.

* the docs do mention that the interface needs to be set before the web server is started; however `setInterface` will allow you to set an interface after the server has started without warning (and `getInterface` will report the changed value.  Should a warning be issued?  At least we should probably add to the `setInterface` docs that if you change the interface on a running server, you will need to stop and restart it before the change goes into effect.

**Comment by cmsj** [comment]
@asmagill @junkblocker one interface only, I'm afraid.

@asmagill my votes would be keep hsminweb on all interfaces, move hsdocs to localhost, and for the setInterface/getInterface, I suppose we could issue warnings, and maybe refuse to setInterface if the server has started.

**Comment by junkblocker** [comment]
@cmsj , sounds good to me.

**Comment by cmsj** [comment]
Closed by #1297

**Comment by junkblocker** [comment]
```
> abc = require('hs.doc.hsdocs')

2017-04-04 13:02:27: -- Loading extension: fnutils

> abc:interface('localhost')
interface must be nil or a string
stack traceback:
	[C]: in function 'error'
	...app/Contents/Resources/extensions/hs/doc/hsdocs/init.lua:395: in function 'hs.doc.hsdocs.interface'
	(...tail calls...)
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:326: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:306>
```

**Comment by asmagill** [comment]
`abc.interface("localhost")` -- function, not method.

**Comment by asmagill** [comment]
To be more clear cause I just read that and realized it's a little terse... you only use `:` when you're invoking a method on an object which has a unique "self" (in fact that `self` is an implicit first argument to the method when it is executed -- the object on which you are invoking the specific method)... a specific hotkey you want to enable or disable, a specific window you want to move, etc.  

`hs.doc.hsdocs` is providing a set of functions and hiding the specific implementation, so there is no "object" or "self" you need to keep track of.  So, use `.` instead of `:` and it should work fine for you.
