### ISSUE TITLE
F4 and F11 cannot be binded

### ISSUE THREAD

**Issue by lip2up** [Hammerspoon/hammerspoon#1296]
This cannot work:

> hs.hotkey.bind({}, 'f11', function() ... end)

But this can:

> hs.hotkey.bind({}, 'f12', function() ... end)

And this also can:

> hs.hotkey.bind({'cmd'}, 'f11', function() ... end)

Thanks!

**Comment by lip2up** [comment]
And this can work:

> hs.hotkey.bind({'cmd'}, 'f11', function() ... end)

**Comment by asmagill** [comment]
`hs.hotkey.bind` cannot override system defined shortcuts.  Check System Preferences->Keyboard->Shortcuts to see if you have F11 assigned to something, e.g.

<img width="780" alt="screen shot 2017-04-01 at 1 56 33 pm" src="https://cloud.githubusercontent.com/assets/8139480/24581551/3f081584-16e3-11e7-9ec6-f7c1c26f592a.png">

I've noticed that it can be inconsistent about reporting an error about this, but even when no error is returned, it won't prevent the system version from being triggered instead of ours.

**Comment by lip2up** [comment]
Thank you very much! My problem has been solved.

I found when I just set the shortcut of the Mission Control as F4, but I don't check the check box to enable it, it also takes up the F4, then, cause the `hs.Hotkey.bind` for F4 cannot work! 

![image](https://cloud.githubusercontent.com/assets/1510746/24588264/848a7e70-17f7-11e7-82c7-ff6a36d0af69.png)

When I enable it, change it to another key, re-disable it, reload the Hammerspoon, and `hs.Hotkey.bind` for F4 can work

![image](https://cloud.githubusercontent.com/assets/1510746/24588274/a9bcc446-17f7-11e7-851e-d49e4b4cd1d6.png)
