### ISSUE TITLE
hs.webview.toolbar priority?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1300]
Has anyone else run into issues using the `hs.webview.toolbar` `priority` key?

Maybe I'm missing something, but I would assume that when you create a new `hs.webview.toolbar` it would sort the toolbar items by the `priority` value? It seems to just always sort the icons in a random priority for me, even if the `priority` is set for all the items?

Any ideas @cmsj or @asmagill ?

**Comment by asmagill** [comment]
Toolbar priority affects what gets pushed into the overflow menu when too many items are in the toolbar for the current window width.  From the docs for NSToolbarItem:

> Item Priority
> When a toolbar does not have enough space to fit all its items, it must push some items into the overflow menu. These values allow you to suggest a priority for a toolbar item.
> 
> Constants
> NSToolbarItemVisibilityPriorityStandard
> The default visibility priority.
> 
> Available in OS X v10.4 and later.
> NSToolbarItemVisibilityPriorityLow
> Items with this priority will be the first items to be pushed to the overflow menu.
> 
> Available in OS X v10.4 and later.
> NSToolbarItemVisibilityPriorityHigh
> Items with this priority are less inclined to be pushed to the overflow menu.
> 
> Available in OS X v10.4 and later.
> NSToolbarItemVisibilityPriorityUser
> Items with this priority are the last to be pushed to the overflow menu. Only the user should set items to this priority.
> 
> Available in OS X v10.4 and later.
> Discussion
> To suggest that an item always remain visible, give it a value greater than NSToolbarItemVisibilityPriorityStandard, but less than NSToolbarItemVisibilityPriorityUser. In configurable toolbars, users can control the priority of an item and the priority is autosaved by the NSToolbar. These values are used by the visibilityPriority property.

Your next comment should be "well that's not quite what the hammerspoon docs say!" and... you're right. I need to correct that...

**Comment by latenitefilms** [comment]
Thanks for the detailed reply! That all makes sense, but I guess my question now is... if priority isn't the answer, how do I order things in the toolbar?

**Comment by latenitefilms** [comment]
It looks like when you use `hs.webview.toolbar.new(toolbarName, [toolbarTable])`, the toolbar items take the order as they appear in `toolbarTable`. Given this, maybe all that is needed is some more clarification in the documentation, or maybe something like:

`table.sort(toolbarTable, function(a, b) return a.priority < b.priority end)`

...should be added so that the order of the toolbarTable is always sorted by priority?

Thoughts @asmagill & @cmsj ?

**Comment by cmsj** [comment]
I think it probably makes sense to use the priority field and add a sort there. Milestoning for 0.9.53.

**Comment by asmagill** [comment]
Toolbar items are initially inserted in the order they are assigned, as long as they have the "default" attribute set to true.  The priority has nothing to do with this -- it is solely for determining which toolbar items to move to the submenu and in what order when the window width shrinks and not all of the toolbar items that are visible can fit.  Fixing the documentation to make this clearer *is* on my list of things to do this weekend.

You can move them around with `hs.webview.toolbar:insertItem` (it will insert a toolbar item that is not currently in the toolbar or move one if it is).

I hesitate to change this because the entire point of toolbars is that, in *most* applications, the order is strictly a "suggestion" and the user can modify them at will -- pulling some out, putting others in, moving them around, etc.  The order is then saved in the application's defaults so that the next time the same toolbar with the same ID and toolbar items is attached to a window, the *user's* preferences are honored, not the programmers. (see `hs.webview.toolbar:customizePanel`, `hs.webview.toolbar:canCustomize` and `hs.webview.toolbar:autosaves`

**Comment by latenitefilms** [comment]
No worries - I guess as long as the documentation clearly explains that the order of the toolbar items when using `hs.webview.toolbar.new(toolbarName, toolbarTable)` is based on the order of the `toolbarTable`, then that all makes sense, and it's up to the user to sort this table, prior to creating the new toolbar. The way I originally interpreted the documentation is that the toolbar is sorted by the priority - which is obviously not the case.

Yes, I completely get that toolbars can be customised by the end user, and that any user customisations will "overrule" the order of the `toolbarTable` - but again, this would be handy to have in the documentation as well for clarify.

Thanks @asmagill !

**Comment by cmsj** [comment]
@asmagill thanks for the explanation. So this is just a docs issue then :)
