### ISSUE TITLE
hs.webview - Dark UI option?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1321]
Is it possible to create a dark UI (i.e. coloured close/minimise buttons, black menubar, transparent body) using `hs.webview` exactly like the attached?

![screen shot 2017-04-12 at 3 46 49 pm](https://cloud.githubusercontent.com/assets/22286696/24942931/6b5882a6-1f97-11e7-8f08-ce364441adff.png)
![screen shot 2017-04-12 at 3 46 56 pm](https://cloud.githubusercontent.com/assets/22286696/24942932/6b5a275a-1f97-11e7-823a-9cd94b454af7.png)

**Comment by latenitefilms** [comment]
Note to self: [NSAppearanceNamedVibrantDark](http://devstreaming.apple.com/videos/wwdc/2014/220xx01yweszmjv/220/220_adopting_advanced_features_of_the_new_ui_of_os_x_yosemite.pdf) might be relevant?

**Comment by asmagill** [comment]
The built in web server which serves the Hammerspoon documentation provides this though javascript.  The relevant code can be found at https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/doc/hsdocs/common.lp#L37-L51

Line 50 would need to have `<%= invertLevel %>` changed to the "inversion" level you want (though 100 and 0 are the only values that make real sense.

**Comment by latenitefilms** [comment]
@asmagill - I assume that code only changes the background? Is there anyway to change the title bar colour as well (and make the close button red, etc.)?

**Comment by asmagill** [comment]
Unfortunately not that I am aware of... It may be possible by subclassing NSWindow or NSPanel replacing some of the drawing methods (I've seen code for some weird things out there like oval shaped windows -- the window itself was an oval, not just a rectangle with transparent portions) but it's beyond the scope of anything we've done or plan with Hammerspoon.

The closest I can suggest is to change the window style with something like `hs.webview:windowStyle(hs.webview:windowStyle() | hs.webview.windowMasks.utility | hs.webview.windowMasks.HUD)` (HUD is only available when utility is also set, and the `:windowStyle()` invocation without an argument is to get the current value so we're "adding" to it, rather than replacing it)  But that changes the close button to a grey circle with a black x in it, not red).

**Comment by latenitefilms** [comment]
Yeah, I'm currently using `hs.webview.windowMasks.HUD` which looks fine - but I would still love it to match the look of Apple's Final Cut Pro windows if I can work out how. I'll keep investigating. Thanks @asmagill !

**Comment by latenitefilms** [comment]
Possibly relevant:

http://stackoverflow.com/questions/20016022/how-to-change-color-of-nswindow-title-bar-in-osx

**Comment by latenitefilms** [comment]
Note to self - this might be relevant:

```
rbx = [[NSAppearance appearanceNamed:*_NSAppearanceNameVibrantDark] retain];
[self->_window setAppearance:rbx];
[rbx release];
[self->_window setTitlebarAppearsTransparent:0x1];
var_48 = self;
```

**Comment by latenitefilms** [comment]
Seeing as you're online @asmagill - does the above pseudo code mean anything to you?

**Comment by asmagill** [comment]
`NSWindow` conforms to the [NSAppearanceCustomization](https://developer.apple.com/documentation/appkit/nsappearancecustomization?language=objc) protocol, which means it can be assigned an [NSAppearance](https://developer.apple.com/documentation/appkit/nsappearance?language=objc) object.  What the various appearances look like and whether or not a web view would honor them (the WKWebView object fills the NSWindow contentBounds, so it's the view that primarily determines how the window looks) I don't know... you'd need to play around and see.

The pseudo code looks like it is from a disassembler so it includes some things we don't really need to code for (ARC takes care of retain/release for us, properties can be written in dot notation, etc.)... I'd write it something like this:

~~~objc
theWindow.appearance = [NSAppearance appearanceNamed: NSAppearanceNameVibrantDark] ;
theWindow.titlebarAppearsTransparent = YES ;
~~~

**Comment by latenitefilms** [comment]
Legend - thanks @asmagill ! I'll have a play and let you know how I go.

**Comment by asmagill** [comment]
Take out `theWindow.titlebarAppearsTransparent = YES ;` -- I included it before because your sample code did, but I don't think it's what you want in general because we're not providing a custom titlebar, so we do want it to be drawn.  

I'm not sure why it doesn't matter for the preferences or console, maybe because those are actual NSWindow objects while webview is an NSPanel object (a subview of NSWindow) -- this is done because it gives us some additional options when dealing with hovering non-activating content, but also means that it may be using slightly different drawing code, not sure.

**Comment by latenitefilms** [comment]
Sweet - thanks @asmagill !

I'll try implement all of the above in a new branch, and submit for your review. Hopefully we can get into Hammerspoon in the next update!
