### ISSUE TITLE
hs.drawing seems didn't correctly release memory occupation

### ISSUE THREAD

**Issue by ashfinal** [Hammerspoon/hammerspoon#1336]
I found even deleting hs.drawing object doesn't give the memory back. Or I did something wrong?  (which may be the possiblity, but I can't figure out why … )

Below is some scripts which I wrote intend to preview application windows and switch to them. But since the memory occupation kept growing wild, soon enough it spoils everything.

``` lua
function drawOrDeletePreview()
    if preview_canvas then
        preview_canvas:delete()
        preview_canvas = nil
    else
        preview_canvas = hs.canvas.new({x=0,y=0,w=400,h=600}):show()
        allwins = hs.window.visibleWindows()
        local filted_wins = {}
        for idx,val in pairs(allwins) do
            if allwins[idx]:id() then table.insert(filted_wins, allwins[idx]) end
        end
        some_win = allwins[math.random(#filted_wins)]:snapshot()
        preview_canvas[1] = {type="image", image=some_win}
    end
end

bad_timer = hs.timer.doEvery(3, drawOrDeletePreview)
```
The script may be dirty, but it works. By pasting into Hammerspoon Console it should run properly. The problem is the memory occupation keeps growing. As I assume, when hs.drawing object is deleted and set to nil, it should give the memory back. But obviously that is not the fact …
So where I did it wrong? Help much appreciated. :)

**Comment by cmsj** [comment]
`hs.drawing` is on a slow road to being removed from Hammerspoon in favour of `hs.canvas`, so I would suggest looking at http://www.hammerspoon.org/docs/hs.canvas.html#drawingWrapper and seeing if you still run into issues with `hs.canvas` doing the work.

**Comment by ashfinal** [comment]
Thank you for your reply. :) 
I did use hs.canvas to create snapshot for windows, but the same problem remains. 
I also update the above code for your reference. Help still needed.

**Comment by asmagill** [comment]
I'm not surprised canvas behaves the same -- the garbage collection routine is almost identical.

If it's truly a problem with the NSWindow/NSPanel objects not being fully released, it may be sufficient to just re-enable releaseOnClose before the final close in garbage collection... I'll have to check out the logic and make sure this doesn't break something else.

However, I wonder if it's not more because of the images... and I recall an issue a year or so ago where it was concluded that due to the way macOS caches images, we *can't* completely release them without completely quitting the application.

I'll put together a pull which re-enables releaseOnClose during collection and put it out for testing.

**Comment by ashfinal** [comment]
@asmagill Thank you. 
`hs.canvas` is wonderfull staff, it would be a pity if we couldn't heavily rely on this module.

**Comment by cmsj** [comment]
We should probably look more closely at the NSImage options that relate to caching. I get the impression from a quick search, that you don't always get the caching behaviour you want, but it might be worth experimenting with.

**Comment by cmsj** [comment]
@ashfinal it's also perhaps worth experimenting with Lua's `collectgarbage()` - I know you're explicitly calling `:delete()` on the canvas objects, but it may also be helpful to force Lua to collect garbage.

(between Lua's lazy garbage collecting, and the often unpredictable nature of Cocoa's memory handling, this sort of issue is tons of fun to track down fully ;)

**Comment by ashfinal** [comment]
@cmsj `collectgarbage()` works! 👍 
After adding it below `preview_canvas = nil`, the memory occupation stops increasing endlessly.
But I guess too often calling `collectgarbage()` is weird, setting a global timer to do this may be a good idea.
Although I assumed grabage collection should be automatically excuted, I'm still happy to know a way to carry on my little script. :)
Thanks again!

**Comment by cmsj** [comment]
@ashfinal glad that helped :)

I'm going to close this issue out, since it doesn't seem like there is a specific issue with hs.drawing/canvas, but we may want to look (again again again ;) at whether we tweak the Lua GC defaults.

**Comment by asmagill** [comment]
@ashfinal, @cmsj -- just so it's in the history should this be revisited, I did try adding `window.releasedOnClose = YES ;` before the actual close in `hs.canvas`'s gc code... and Hammerspoon proceeded to crash immediately.  Seeing that a forced garbage collection fixes the immediate issue, I didn't dig any further at this time.

Re garbage collection, lua does perform garbage collection on its own schedule and can be tweaked somewhat, though to be honest I've never played with the parameters so I can't make any recommendations other than to start here: https://www.lua.org/manual/5.3/manual.html#2.5

Generally, though, if you know your code has just done something that may have released a significant amount of memory, it is not uncommon for lua programmers to invoke `collectgarbage()` directly at that point -- twice in succession if you're really concerned (this is because Lua uses a two step process -- simplified, it's one pass to mark things that are eligible for collection and a second pass to actually do the collection as long as nothing has "resurrected" the previously marked item because it's still needed for something else to be collected first)
