### ISSUE TITLE
Prevent Console from Getting Focus

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1351]
I've tried looking through the Hammerspoon code, but can't see anything obvious.

Currently, if I have an AppleScript alert tied to a hotkey, when I trigger the hotkey, the Console will come to front as well as the alert.

This is with the Dock Icon hidden.

Ideally, I would prefer it if the Console remained at it's current level (i.e. if it's hidden behind a Safari window, I would prefer it NOT come to front when the AppleScript alert is triggered).

Any ideas @asmagill or @cmsj ?

**Comment by cmsj** [comment]
FWIW, for precisely reasons of focus issues, I never leave the Console window open unless I'm looking at it, I have a hotkey bound to `hs.toggleConsole()`

**Comment by asmagill** [comment]
If the console window is open, it is next to impossible to prevent it from coming forward if some element that is considered a part of Hammerspoon becomes `key` but does not also become `main` -- see https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/WinPanel/Concepts/ChangingMainKeyWindow.html for more info on Key versus Main.

Like cmsj, I have the console bound to a hotkey and then also have an application watcher so that as soon as Hammerspoon is no longer the frontmost application, the console is closed (hidden).

**Comment by latenitefilms** [comment]
@asmagill - That link says something that might be relevant? Thoughts?

> Not all windows are suitable as key or main windows. For example, a window that merely displays information and contains no objects that need to respond to events or action messages can completely forgo ever becoming the key window. Similarly, a window that acts as a floating palette of items that are only dragged out by mouse actions never needs to be the key window. Such a window can be defined as a subclass of NSWindow that overrides the methods canBecomeKeyWindow and canBecomeMainWindow to return NO instead of the default of YES. Defining a window this way prevents it from ever becoming the key or main window. Although the NSWindow class defines these methods, only subclasses of NSPanel typically refuse to accept key or main window status.

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - And yes, like you both I have a shortcut for the Console, and keep it hidden a lot of the time for testing. But if we could work out a way that it could be left open but stayed out of the way, that would be ideal.

**Comment by asmagill** [comment]
Maybe... you'd have to programmatically adjust canBecomeKey/Main for MJConsoleWindow according to some logic which determines when you want the console versus when you don't... and if your logic guessed wrong, you might end up with a console that you couldn't type into.

It's one of the reasons that way back when in #567 I switched drawing to using NSPanel rather than NSWindow since it allowed creating non-activating panels (i.e. you could click on them without bringing the console forward).

Since you're dealing with a dialog (specifically an alert) created by Applescript, I really don't know... I found the workaround I needed and haven't really messed with it much since then :-)

**Comment by latenitefilms** [comment]
Possibly a dumb question, but... in that case, could the Console just be an `NSPanel`?

[This](http://stackoverflow.com/a/21822633) might be relevant?

**Comment by asmagill** [comment]
As to whether or not the console can be an NSPanel... it would probably not be a trivial undertaking since it's all defined within the XCode specific files and interface builder stuff... I don't know much about it other then the few methods defined in MJConsoleWindow.m.  I suppose eventually I'll have to learn the interface builder and how to properly use Xcode, but... not happening today!

I don't know what else it might break or what expected behaviors it might change... with the proper flags set, probably not many... but that's only a guess based on what I found when I did the changes to `hs.drawing` and `hs.webview`.

What kind of alerts are you generating?  Just the standard warning/informative/critical? or ones with additional fields (i.e. other buttons or text input)?  I have a partially written `hs._asm.alert` module I can dust off and see if I can get it working... I originally stopped because I realized that anything more complex then these default alert types was going to require an NSView builder, so I figured I'd hold off until I worked on that first (I want to pattern it after python's tkinter so that it's somewhat familiar to some of our existing supporters, but... that means I have to actually learn to code in python first, since my current experience is limited to just modifying other people's scripts.)

However, if there is an interest, I'll see how hard it would be to get the basics going sooner.  Since it would be completely within Hammerspoon, it might be easier to keep the console from coming forward... or it might not, but I can probably find out pretty quickly.

**Comment by asmagill** [comment]
Ok, after some experimentation, I think this is what is happening:

What appears to be happening is that when the modal NSAlert (which IIRC is what AppleScript is using) becomes active, it makes the entire application (Hammerspoon) the foreground application.  You answer the dialog and it goes away, but Hammerspoon is *still* the foreground application so it raises the next available window of the application and you get the console.

Not sure what can be done...

A possibility comes to mind, but I don't know if it will work for your case or not:  If you're triggering the applescript which creates the alert from your own lua code, store the frontmost application or window with `hs.application.frontmostApplication` or `hs.window.frontmostWindow` (you'll have to experiment to see which is most reliable in your case), trigger the applescript, then immediately switch back to the other application/window with `hs.window:focus` or `hs.application:activate`

I'm going to experiment with this module a little more and see if creating a placeholder window and showing the alert as a sheet of that window instead of as a dialog works any different, but it may be a couple of days before I can get back to it.

**Comment by latenitefilms** [comment]
@asmagill - Did you ever get a chance to play with this some more, or should I just close this issue?

**Comment by latenitefilms** [comment]
I'm going to close this issue for now.

**Comment by molliejaeron** [comment]
In case anyone runs into this problem now ("Warning: grid: Cannot get frontmost window" in console), I had the same issue and resolved it by making sure the box for Hammerspoon was checked under System Preferences > Security & Privacy > Privacy tab > Accessibility. You may have to click the lock icon in the bottom left corner to make changes. 

Restarted computer after checking the box and I can now move my windows based on my config as expected.
