### ISSUE TITLE
port of Hammerspoon

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1355]
Hi, i am building an application based on hammerspoon. What files/ icons etc should I change to make sure no one confuses it for the original hammerspoon.

Also how do i go about changing the notification icon. Thank you

**Comment by latenitefilms** [comment]
Check out our fork history to see what we changed:

https://github.com/CommandPost/CommandPost-App

**Comment by cmsj** [comment]
All of the icons should be covered by the `Images.xcasset` bundle in the Hammerspoon/Extras group in Xcode. As for the name, you could go through and change everything, but that's probably unreasonable amounts of work to maintain as a patch, so just changing the app name in the Xcode project should be fine :)

**Comment by latenitefilms** [comment]
@cmsj - On this note, I have pondered whether it would be worthwhile to [localise](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html) Hammerspoon, so that the "Hammerspoon" text value could just be stored in a "translation" file, and therefore could be easily changed without having to go back and mess with any Objective-C code. Thoughts?

**Comment by cmsj** [comment]
Yes, we should localise, it's in the same bucket as adding more tests - something we really should do, but don't often have the time to do :/

**Comment by latenitefilms** [comment]
@cmsj - No worries. I might give it a bash myself sometime!
