### ISSUE TITLE
Bindings to § stop working on 0.9.53

### ISSUE THREAD

**Issue by unnamed777** [Hammerspoon/hammerspoon#1366]
I have a couple binding on paragraph key:
```
function getCurrentLayout()
    if (hs.keycodes.currentLayout() == "U.S.") then
        return "en"
    else
        return "ru"
    end
end

function swapBackquote()
    if (getCurrentLayout() == 'en') then
        hs.eventtap.keyStrokes("`")
    else
        hs.eventtap.keyStrokes("ё")
    end
end

function swapTilda()
    if (getCurrentLayout() == 'en') then
        hs.eventtap.keyStrokes("~")
    else
        hs.eventtap.keyStrokes("Ё")
    end
end

hs.hotkey.bind(nil, '§', swapBackquote, nil, swapBackquote);
hs.hotkey.bind('shift', '§', swapTilda, nil, swapTilda);
```

After updating to 0.9.53 they stop working - callbacks aren't called.

**Comment by asmagill** [comment]
What does `hs.keycodes.map["§"], hs.keycodes.map[hs.keycodes.map["§"]]` return in your Hammerspoon console?

I get `95 pad,` which I am pretty sure is wrong (if I'm reading Events.h correctly, it should be `10 §`) but since I don't have that key on my keyboard and have never really checked it out before, so I'm not positive...

As a short term fix, try putting 10 (the number, not a string) into your `hs.hotkey.bind` lines instead of '§' and let me know if that makes a difference.

I'll review the code changes made to `hs.keycode` tomorrow... the changes I recall *shouldn't* have caused this, but I've been wrong before 😆

**Comment by unnamed777** [comment]
Yep, ```§```  in 0.9.52 is 10, in 0.9.53 is 95. I've replaced the char to code 10 and now it works as supposed to.

**Comment by cmsj** [comment]
`keycodes_cachemap()` seems to be pushing multiple values for §. I added some logging:

```
2017-04-25 08:38:00.079481+0100 Hammerspoon[72852:18600323] pushing 10:§
2017-04-25 08:38:00.079554+0100 Hammerspoon[72852:18600323] pushing 93:§
2017-04-25 08:38:00.079657+0100 Hammerspoon[72852:18600323] pushing 94:§
2017-04-25 08:38:00.079708+0100 Hammerspoon[72852:18600323] pushing 95:§
```

**Comment by cmsj** [comment]
So the first one is correct, then the additional § and a couple of subsequent values (`\^P`) correspond to:

```
kVK_JIS_Yen, kVK_JIS_Underscore, kVK_JIS_KeypadComma, kVK_JIS_Eisu, kVK_JIS_Kana
```

**Comment by knu** [comment]
I think you need to check if UCKeyTranslate() succeeds before calling pushkeycode().
