### ISSUE TITLE
hs.fs.safeFilename()

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1392]
It would be great to have a function in `hs.fs` that allows you to input any string, and it returns a string that is safe to use as a filename.

For example if you give it:

`input = "This: is not safe"`

or 

```
input = [[this is 
not safe]]
```
...it will return:

`output = "This is not safe".`

It should take into account the file system limitations too. Maybe even have a attribute that allows you to tell the function what file system you're using, as I'm sure HFS has different rules than exFAT for example.

**Comment by asmagill** [comment]
This is a highly subjective thing because, under certain circumstances, both of those can be valid:

~~~sh
$ touch "This: is not safe"
$ ls -l
total 152
-rw-r--r--  1 amagill  staff      0 May  2 20:36 This: is not safe
~~~

But in a Finder window, it reads "This/ is not safe"

And the one with an embedded newline does something similar (but the finder shows it as ?)

The only real test is to create a file and see if it errors... you can find some regular expressions online that can attempt to clean up file names (and could probably be fairly easily ported to lua's partial regex support), but even they note that they either have limitations or impose restrictions that are not actually invalid, just uncommon.

**Comment by latenitefilms** [comment]
Interesting! Well in that case, I'm going to close this issue. Thanks @asmagill !
