### ISSUE TITLE
failed autoload returns true, would expect nil

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#140]
Presumably this is because 

> If the loader does not return a non-nil value and has not assigned any value to package.loaded[modname], then require assigns true to this entry.

**Comment by cmsj** [comment]
I think if an autoload fails, we should emit a very visible error at the least. If we can somehow get package.loaded[modname] to be nil, great, if not, well at least we emitted an error.

I think we ought to be able to get a nil in there - we are in control of the require(), so we should be able to see that it has just put "true" in the table, replace it with nil and show an error. Thoughts?

**Comment by asmagill** [comment]
Their is nothing that prevents True from being the actual return value of a require()... in fact I've used it in some of my personal work files to indicate whether the file completed some action successfully or not...

It would probably be better (or at least more "correct") to wrap the actual require in the autoload mechanism in a pcall or xpcall and then reset package.loaded[x] and the return value to nil if the pcall indicates that the require failed... otherwise, the return value of the require is the correct one, unlikely as a non-table value might be for something we include as an autoload module.

--
A-Ron

**Comment by cmsj** [comment]
In the ~3 years since this was filed, I don't think we've really had any significant issues with autoload failing, so I'm inclined to close this (we have ~200 issues open at the moment, which is clearly an untenable workload for so few people to deal with, therefore I am gardening the issues aggressively).
