### ISSUE TITLE
Better Error Handling for hs.fs.tagsAdd()

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1402]
Currently `hs.fs.tagsAdd(filepath, tags)` doesn't return anything. If a path or tag is invalid, it will just generate a LuaSkin error. It would be much better if it returned `nil` on error, and `true` if successful.

**Comment by asmagill** [comment]
Couple of ways this could be done:
1. leave or remove (I'm in favor of leaving) the error messages but modify the tag functions to return true/nil upon success or failure
2. remove luaSkin error messages and cause the tag functions to return lua errors on failure.

Your specific request favors choice 1, but an argument can be made that choice 2 is more "lua like" since you can always wrap `hs.fs.tags...` in `pcall` if you want to capture the error and have your own error handling take place.

On the other hand an awful lot of third party lua stuff just returns nil with no message at all upon failure... in my opinion this is a bad programming practice, but... what behavior would you prefer?

**Comment by latenitefilms** [comment]
I'm happy with option 2. Thanks @asmagill !

**Comment by asmagill** [comment]
Should be addressed in #1515, reopen if you discover outstanding issues.
