### ISSUE TITLE
Detecting User Inactivity?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1407]
Is there any API already built into Hammerspoon to detect user inactivity?

If, not it might be a useful callback for `hs.host`?

Thoughts @asmagill & @cmsj ?

This might be relevant? http://www.xs-labs.com/en/archives/articles/iokit-idle-time/

**Comment by asmagill** [comment]
Looks pretty straightforward to query the idle time... I don't know much about IOKit, but I don't think we'd be able to leverage the OS to generate a callback when it exceeded a specific value (if someone knows otherwise, please correct me if I'm wrong!).

Like pasteboard changes, you'd need to write your own timer to check at whatever granularity you cared about and then perform whatever action.

**Comment by latenitefilms** [comment]
Awesome! Well, I'd be very happy to just use a `hs.timer` if someone smarter than me is able to add the idle time to `hs.host`. Thanks @asmagill !
