### ISSUE TITLE
hs.notify.warnAboutMissingFunctionTag - as a callback instead?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1415]
Rather than printing to the console, it would be awesome if `hs.notify.warnAboutMissingFunctionTag` was a callback instead.

**Comment by asmagill** [comment]
That portion is actually pure lua, so you can take a crack at it if you're interested.  Look around line 100 of notify's init.lua `module.__tag_handler`.

My recommendation would be to test if it's a function and if so, call the function; otherwise test for truthiness to print or falseness to be silent.

**Comment by latenitefilms** [comment]
Sweet - yeah, I'll give this a bash!

Sorry - yes, a lot of the issues I've posted recently are more "notes to self", rather than expecting other people to do. Generally I'll only tag other people if it's something that I don't think I can do myself.
