### ISSUE TITLE
Add hs.eventtap.event.newGesture() to simulate gestures

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1434]
On my MacBook Pro, in Final Cut Pro, it's possible to use the Trackpad to "Zoom in or out" (i.e. Pinch with two fingers). However, what I'd like to be able to do is do the same thing using the scrollbar on my mouse (i.e. use the scroll wheel on my mouse to do exactly the same thing hat "pinch to zoom" currently does on my Trackpad).

Is there anyway to "simulate" the Trackpad's "Zoom in or out" function using `hs.eventtap`?

I'm assuming `hs.eventtap.event.types.NSEventTypeMagnify` is what I need, but I don't know how I actually "trigger" it.

Any ideas @asmagill or @cmsj ?

**Comment by latenitefilms** [comment]
Sorry to pester, but does anyone know if this is possible? 

@asmagill @cmsj @zzamboni ?

**Comment by zzamboni** [comment]
@latenitefilms looking at http://www.hammerspoon.org/docs/hs.eventtap.event.html#types, there's NSEventTypeMagnify, NSEventTypeRotate, NSEventTypeSmartMagnify and other trackpad-related events that look like they might do what you want :)

**Comment by latenitefilms** [comment]
Thanks @zzamboni - but as explained in the original post, I did spot `hs.eventtap.event.types.NSEventTypeMagnify` in the API Documentation - but I'm just not sure how exactly I implement it? Any ideas?

**Comment by latenitefilms** [comment]
After playing around, it looks like `hs.eventtap.event.types.NSEventTypeMagnify` can be used for DETECTING "pitch to zoom", but there's currently no way to SIMULATE "pitch to zoom" - is that correct?

Maybe this issue should be closed in favour of #322? Thoughts @cmsj ?

**Comment by latenitefilms** [comment]
Sorry to keep pestering... but any ideas @asmagill or @cmsj ?

**Comment by asmagill** [comment]
I am not aware of a method to generate gesture events programmatically.  And even if we could, since they are defined through the NSEvent framework rather than the CoreGraphics event framework, I don't think we could target them at applications other than our own (i.e. Hammerspoon) due to restrictions of the NSEvent framework.

Since Apple's design guidelines specify that every action that can be performed by a gesture should also be doable through another method (i.e. keyboard shortcut or regular mouse movement), I would see Hammerspoon can perform the action this way. Of course this relies on the application actually following those guidelines :-)

You could also look into `hs._asm.axuielement` to see if an accessibility action has been defined for the action you're interested in -- specifically look at the actions defined for the target (window, control, etc).  (see https://github.com/asmagill/hs._asm.axuielement if you want to check out this experimental approach).  Using this approach takes a lot of trial and error, but I have occasionally found that it provides controllable actions that are difficult or impossible any other way.

**Comment by latenitefilms** [comment]
> I am not aware of a method to generate gesture events programmatically. And even if we could, since they are defined through the NSEvent framework rather than the CoreGraphics event framework, I don't think we could target them at applications other than our own (i.e. Hammerspoon) due to restrictions of the NSEvent framework.

Not sure if you saw my links in #322, but is Sesamouse relevant?

See: https://github.com/calftrail/Touch & https://github.com/calftrail/Sesamouse

> You could also look into hs._asm.axuielement to see if an accessibility action has been defined for the action you're interested in -- specifically look at the actions defined for the target (window, control, etc). (see https://github.com/asmagill/hs._asm.axuielement if you want to check out this experimental approach). Using this approach takes a lot of trial and error, but I have occasionally found that it provides controllable actions that are difficult or impossible any other way.

Yeah, we use `hs._asm.axuielement` for a HUGE amount of our GUI Scripting - it's awesome. Thank you.

We've currently solving this particular issue by triggering a menu item that does the zooming for us, which works fine on mice with mechanical scroll wheels - but it's really glitchy if you have a mouse with a touch interface (such as Apple's newer mice). Annoyingly, although there is a "zoom" slider in the Final Cut Pro interface - it's not visible all the time, and is only accessible if you click a button (which pops up a sub-menu). So to do this, we'd need to open the popup menu first then slide the slider based on the mouse scrolling, which may or may not work.

**Comment by asmagill** [comment]
I haven't had a chance to review the links too closely, but if I'm reading it correctly, aren't the links about detecting gestures and not simulating already defined ones?  I'll try and take a close look this week and give a more formal answer then.

**Comment by latenitefilms** [comment]
@asmagill - Legend, thank you!!

**Comment by asmagill** [comment]
Just an update... generating the touch events is turning out a lot harder than I had hoped, but I have a module to detect touches on the magic mouse and magic and internal trackpads that should be ready in a day or so.

I think the problem with generating the touch events is because the examples I've found are all using the pre-64 bit version of the IOHidFamily header files... these are not installed with XCode, but I did find them on the Apple Open Source site and the latest version does show some changes that will require code adjustments.

**Comment by latenitefilms** [comment]
AMAZING - thank you @asmagill !

I'll keep an eye out for your code to play with.

**Comment by asmagill** [comment]
Regarding touch detection, feel free to check out https://github.com/asmagill/hammerspoon_asm.undocumented/tree/master/touchdevice

Regarding touch gesture synthesis, no real progress on simulating gesture events... it looks like the synthetic events require a modified form of the touch data to be appended to the CGEvent structure... unfortunately the additional touch data structures are not documented; simply updating IOHidFamily headers to the current 64bit version isn't sufficient or I'm missing something else.  I don't know when I will have time to dig deeper into this, though if there is interest I can upload what little I've tried for someone else to take a look at, or if you can find an open source example that works under 10.12, we can take a look at it -- so far the examples referenced above don't work on my machine even before trying to migrate the code into Hammerspoon.

**Comment by latenitefilms** [comment]
Any suggestions @calftrail ?

**Comment by daniel5151** [comment]
@asmagill I'm working on a macOS touchscreen driver, and one of my stretch goals are things like pinch-and-zoom gestures. As such, i'd love to see any code you've hacked together 😄

**Comment by latenitefilms** [comment]
@asmagill - Whilst I remember, would it be possible to add something in `hs._asm.undocumented.touchdevice` to determine if there's any built-in Touch Devices versus external Touch Devices? For example, I'd like to apply certain functions to things that are done with an external Magic Mouse that's connected to a MacBook Pro - but I don't want to affect the built-in Touchpad. Thoughts?

**Comment by latenitefilms** [comment]
@asmagill - I've just started playing with `hs._asm.undocumented.touchdevice`. Awesome work!

I've tried looking at your examples, but can't see anything obvious. Any suggestions on how best to use this incredible new extension to detect when a user is using a Touchpad to scroll up and down (i.e. using two fingers to move up and down the Touchpad)?

**Comment by natevw** [comment]
@latenitefilms Thanks for the mention. Yes, it is still possible to inject generated gestures as of Sierra (and presumably High Sierra but I haven't tested). Sounds like @asmagill is on the right track, although I don't think the IOHID structures are particularly relevant.

The IOHID stuff you might have seen in my calftrail/Touch code is primarily for sending the actual *touches*, i.e. corresponding to the [NSTouch](https://developer.apple.com/documentation/appkit/nstouch) objects an app might also receive. These structures do change across OS releases iirc, and also trying to inject them seemed not to work anymore on recent releases when I briefly tested.

What should still work is the higher-level gesture stuff. Take a look e.g. https://github.com/calftrail/Touch/blob/63a056f237f5bfd66bb4db3d1e986183e35a23c2/TouchSynthesis/TouchSynthesis.m#L291 where a dictionary of different keys is sent to a helper for conversion to CGEvent "fields".

The exact patterns changed a bit (there's a new kTLInfoKeyGesturePhase key in https://github.com/calftrail/Touch/blob/master/TouchSynthesis/TouchEvents.h now) and so you may need to take a look at what a real MBP trackpad sends on newer releases. To do that, I used my TouchRecorder plus TouchExtractor stuff also in that repository (which is very "works on my machine" with hardcoded paths and junk) but might help. Otherwise it sounds like you've found a way to log as well.

Hope this is helpful! Looks like an interesting automation project.

**Comment by natevw** [comment]
Oh, one more thing: please do keep in mind the TouchSynthesis code is GPLv2 so you won't be able to use it directly since I still occasionally license it for commercial projects :-/

We could discuss further, but honestly it sounds like you're a ways along. In retrospect, the dictionary approach might be a bit expensive for tight loops, and some of the structures might benefit from pre-allocation — so maybe just the sample of what does work can just help guide you.

**Comment by latenitefilms** [comment]
@natevw - AMAZING! Thanks so much - HUGELY appreciated!

Hope this is helpful @asmagill !

**Comment by cmsj** [comment]
(FWIW, we are MIT licensed, so we are compatible with GPLv2, meaning we could include @natevw 's code, but it would then mean that whichever extension that was pulled into, would implicitly be covered by the GPLv2 - which I am not opposed to, but it's worth bearing in mind)

**Comment by latenitefilms** [comment]
Will be addressed in #2512 if merged.
