### ISSUE TITLE
Possible to detect if screen sharing, to disable notifications temporarily?

### ISSUE THREAD

**Issue by mikecrittenden** [Hammerspoon/hammerspoon#1437]
I want to disable all system notifications while screen sharing (whether through a Google hangout or whatever) and re-enable them when screen sharing ends. Is this possible with Hammerspoon? I can't find anything about screen sharing in the docs.

**Comment by cmsj** [comment]
This isn't completely possible in Hammerspoon right now, but it would be possible with a fairly small new extension. I'm going to close this issue and file a new one with some details about what we'd need, and we'll see when we can get to implementing it :)

**Comment by asmagill** [comment]
FWIW, I'm using code similar to the following to detect when Screen Sharing is being used on my machine to disable some watchers... it's specific to the macOS screen sharing setup so probably wouldn't help with Google Hangouts, etc. but in case someone else searches in the future:

~~~lua
remoteAccessWatcher = hs.distributednotifications.new(function(n,o,i)
    local vn = i and i.ViewerNames or nil -- ViewerNames if present is an array of IP addresses
    if not vn then
        print("~~ com.apple.remotedesktop.viewerNames with unknown details: object = " .. tostring(o) .. ", info = " .. tostring(i))
    else
        if #vn > 0 then
            print("Remote Viewer(s) Detected")
        elseif #vn == 0 then
            print("Remote Viewer Left")
        end
    end
end, "com.apple.remotedesktop.viewerNames"):start()
~~~

The only real issue is that it doesn't detect if screen sharing is already in effect when Hammerspoon starts/reloads... haven't figured that one out yet.

**Comment by rsefer** [comment]
FWIW I've been searching for a solution to this (detect ALL screen sharing, including Google Hangouts) in 2022 with no luck. I have not been able to find anything via AppleScript to detect when a screen is being shared, either. One bit of a hack that sort of works: detect if a microphone is being used. In my usage, the microphone is being shared along with the microphone nearly every time. If anyone has a more robust solution, please share.

```lua
shouldShow = true
for i, device in ipairs(hs.audiodevice.allInputDevices()) do
    if device:inUse() then -- don't show updates if microphone is being used
        shouldShow = false
        break
    end
end
```
