### ISSUE TITLE
How to release the memory occupied by drawing image

### ISSUE THREAD

**Issue by mpco** [Hammerspoon/hammerspoon#1446]
My Code:
```
function imgPlay()
    imgObj = hs.image.imageFromPath(imgPath)
    imgSize = imgObj:size()

    imgRect = hs.geometry.rect(1920 - imgSize.x,10,imgSize.x,imgSize.y)

    if imgDrawObj then
        imgDrawObj:setImage(imgObj)
        imgDrawObj:setFrame(imgRect)
    else
        imgDrawObj = hs.drawing.image(imgRect, imgObj)
        imgDrawObj:setLevel(hs.drawing.windowLevels.desktopIcon + 1)
        imgDrawObj:setClickCallback(imgClickFunc, nil)
        imgDrawObj:show()
    end
end

hs.timer.doEvery(10, imgPlay)

```
After running several hours, hammerspoon process will occupy hundreds M of memory.
Thank you!

**Comment by latenitefilms** [comment]
You could try:

```
local image = require("hs.image")
local geometry = require("hs.geometry")
local drawing = require("hs.drawing")

imgObj = nil

function imgPlay()

	if not imgObj then 
	    imgObj = image.imageFromPath(imgPath)
	end
	
    imgSize = imgObj:size()

    imgRect = geometry.rect(1920 - imgSize.x,10,imgSize.x,imgSize.y)

    if imgDrawObj then
        imgDrawObj:setImage(imgObj)
        imgDrawObj:setFrame(imgRect)
    else
        imgDrawObj = drawing.image(imgRect, imgObj)
        imgDrawObj:setLevel(drawing.windowLevels.desktopIcon + 1)
        imgDrawObj:setClickCallback(imgClickFunc, nil)
        imgDrawObj:show()
    end
end

hs.timer.doEvery(10, imgPlay)
```

**Comment by asmagill** [comment]
I have never been entirely happy with the garbage collection in `hs.image` because NSImage (which is what it is based on) cache's image representations in the Application cache and we can't ever completely purge them until the application quits.

Looking at your code, I'm guessing you're trying to display an image that is pulled from somewhere and changes every so often?  Try `hs.pathwatcher` instead of a timer since you only really need to recreate it when the file changes rather then on a schedule:

~~~lua
imageWatcher = hs.pathwatcher.new(imgPath, imgPlay):start()
imgPlay() -- because the above won't get called until a change actually occurs
~~~

It will still cache, but probably not as often.

Extra notes in case someone more familiar with Objective-C and NSImage wants to take a look at it or suggest something I've missed:  Every so often I revisit it and see if I can come up with something I've missed in the past, but usually with very minimal results.

My current thinking is that everything should be moved to CIImage objects, but then we'll still need a convertor to NSImage for use in things like menus, etc. since NSImage is what they expect... it would help with drawings/canvas, though.

**Comment by asmagill** [comment]
Depending upon *how* the file changes, you might get even better results with:

~~~lua
imageWatcher = hs.pathwatcher.new(imgPath, function(paths, flags)
  if flags[1].itemCreated  or flags[1].itemRenamed then imgPlay() end
end):start()
~~~

`itemCreated` will be true if your source actually writes its data directly to the destination file; `itemRenamed` will be true if your source does what some programmers recommend -- create a tmp file then "move" it to the final destination in case the transfer is interrupted prematurely.

This version also has the benefit that it doesn't create multiple images if a single file change/replacement causes multiple events (this often occurs due to the way file attributes are updated during file changes -- the OS treats them as distinct, even though to the user it seems simultaneous, so pathwatcher sees the separate events as well.)

**Comment by mpco** [comment]
@latenitefilms 
@asmagill 
Thank you!
