### ISSUE TITLE
Can't bind to `fn` button only

### ISSUE THREAD

**Issue by AdamCanady** [Hammerspoon/hammerspoon#1451]
This may be related to #901, but I can't get this to work:

```lua
hs.hotkey.bind({}, "fn", function() hs.alert("pressed fn") end)
```
Is this behavior supported? Any ideas?

This does work, btw:

```lua
hs.hotkey.bind({}, "f10", function() hs.alert("pressed f10") end)
```

**Comment by knu** [comment]
It is a known issue (feature) and being worked on in #1396.

**Comment by asmagill** [comment]
Modifier keys are not supported as independent hotkey targets by `hs.hotkey`.  The `fn` key is considered a modifier (along with `shift`, `cmd`, `alt`, and `ctrl`)

The only way to detect when a lone identifier is being pressed is to use `hs.eventtap` to create a watcher on `hs.eventtap.event.types.flagsChanged` and then checking which combination of modifiers are being pressed in the event passed to the callback function.

#1396 doesn't change this -- that pull just adds some additional functions which make generating (not detecting) specific key related events within Hammerspoon that were previously more complex or not possible.

Every so often I attempt a rewrite of `hs.hotkey` that relies solely on `hs.eventtap` (more accurately the CoreGraphicsEvent infrastructure that `hs.eventtap` uses) but because of dropped keys and application lockups, I've never been comfortable offering it as an alternative or replacement.

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
