### ISSUE TITLE
Reading contents of a UTF-16 Little-Endian Encoded Text File?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1452]
I have a UTF-16 Little-Endian Encoded Text File that I'd like to read via Lua code. Normally I'd just use `io.lines(file)` however, that just gives me garbage.

Any ideas how I can achieve this? @asmagill or @cmsj ?

**Comment by latenitefilms** [comment]
For anyone who runs into a similar issues, David's come up with a workaround:

https://github.com/CommandPost/CommandPost/blob/feature/issue-667-david/src/extensions/cp/utf16/init.lua

**Comment by asmagill** [comment]
Lua works strictly in 8-bit bytes for strings; their is some support for UTF8, but the lower level string functions are still unicode unaware.

I haven't looked at the workaround presented here yet, but likely any solution that recognizes UTF16 byte sequences as independent entities would require similar workarounds.  I'll review his code this weekend -- it may be worth adding it or some variant of it into Hammerspoon directly.  macOS does support unicode encodings other than UTF8 (though UTF8 seems to be recommended in most of the examples/documentation I've seen), so we may be able to include some objective-c methods to speed it up some as well.

**Comment by latenitefilms** [comment]
Pinging @randomeizer - as he knows way more about this than me.

**Comment by asmagill** [comment]
Perusing the NSString and NSData documentation, it looks like it should be trivial to add functions which convert byte sequences to/from UTF16 and UTF8 (and UTF32 and UTF8) so that you could manipulate the strings as UTF8 then write them back in the format preferred... an initial reading of the Unicode definition for each format suggests that all three cover the same character set, so it should be lossless unless I'm missing something.  Would this be worth adding?

**Comment by latenitefilms** [comment]
Absolutely! Thank you!

**Comment by randomeizer** [comment]
It would definitely help, but I also had to write alternative versions of the various 'string' functions, to enable comparisons, character counting, etc., which are currently written in LUA, so there is a performance penalty.

These are the more complex bits of code I ended up writing to support it:

https://github.com/CommandPost/CommandPost/tree/develop/src/extensions/cp/text

Essentially, a replacement for string that uses a (typically) 64-bit integer for each 32-bit character, along with a separate (reusable) 'matcher' class that does pattern matching.

These would definitely be faster as native code. I'd love to have a unicode-friendly 'matcher' class similar to this built in, because it is expensive doing matches via 'string.match' currently, and I think a lot of that expense is in parsing the pattern.

**Comment by latenitefilms** [comment]
Related: http://gigliwood.com/blog/to-hell-with-utf-16-strings.html

**Comment by randomeizer** [comment]
In practical terms, geting able to read in UTF-16 and having them converted to UTF-8 probably makes the most sense in Lua. Otherwise, additional code such as in the library Chris referenced earlier would have to be written to add similar functionality for UTF-16 strings. Currently, those are written in Lua, so there is definitely a performance penalty. There is probably some downside when working with large text files, but my guess is that very few would be large enough to compensate for the pain caused by trying to work with UTF-16 directly in Lua...

**Comment by asmagill** [comment]
Ok, I completely forgot about this and will try to review the above mentioned library later this weekend and see what might be involved in creating a dedicated module.

Objective-C does provide a way to deal with UTF-16 directly, but as mentioned above, LUA is limited to 8-bit bytes and doesn't really know (or care, outside of the `string` and `utf8` built in modules) what a single byte or sequence represents.

So, to narrow down what we might want to provide through Obj-C, (1) what do you potentially lose in a conversion from UTF-16 to UTF-8 and back? (2) what specific functions/methods that deal in UTF-16 *only* (no internal or explicit conversion) would be useful?

**Comment by randomeizer** [comment]
I don't think there are any specific functions that we need that require UTF-16. I'm trying to remember if there was any specific reason I wasn't doing that with my own library, rather than creating an array of integers, as the library does currently. My guess is that I was avoiding memory use by converting again, although an array of integers will not be exactly memory efficient anyway.

To answer your question more specifically, it would be great to have some functions that convert between UTF varieties in native code.

**Comment by latenitefilms** [comment]
Closing in favour of #2215.
