### ISSUE TITLE
Implementing rearrangement of physical displays

### ISSUE THREAD

**Issue by tofagerl** [Hammerspoon/hammerspoon#1462]
It's currently not possible to rearrange displays in orientation to each others. (Like you do in Settings -> Display -> Arrangement natively.)
Since I keep having to do this every damn time I reconnect my laptop, I would love to be able to simply hit a hotkey and get the same arrangement I always use. @cmsj believes this is possible in the macOS api, and asked to create this ticket.

**Comment by lukecyca** [comment]
Me too...

I have the exact same external monitor at home and at work, but in one place it's to the right of my macbook and in the other place it's on the left.

The monitors have the same name, but different UUIDs. I've got hammerspoon detecting which place I'm in based on the secondary monitor UUID, but no way to actually change the arrangement!

**Comment by latenitefilms** [comment]
In the meantime, you could use `hs.execute` and this application as a workaround:

https://github.com/jakehilborn/displayplacer

**Comment by lukecyca** [comment]
@latenitefilms 100 Internet points to you, sir.

That solution works well. Thank you! For anyone else playing along at home, here is what worked for me:

```lua
function screenLayoutWatcher()
  local secondScreen = hs.screen'HP 24es'
  if secondScreen then
    print(secondScreen:getUUID())
    if ((secondScreen:getUUID() == "5CC6FB8F-3734-D299-ECC5-F59D949A32AD") and (secondScreen:fullFrame().x ~= 1440)) then
      print("Setting screen layout: Office")
      print(hs.execute('/Users/luke/Code/displayplacer/displayplacer "id:F466F621-B5FA-04A0-0800-CFA6C258DECD res:1440x900 color_depth:4 scaling:on origin:(0,0) degree:0" "id:5CC6FB8F-3734-D299-ECC5-F59D949A32AD res:1920x1080 hz:60 color_depth:4 scaling:off origin:(1440,-485) degree:0"'))
    end
    if ((secondScreen:getUUID() == "7D83487D-DF1C-74DB-9DDB-0BD63E163B20") and (secondScreen:fullFrame().x ~= -1920)) then
      print("Setting screen layout: Home")
      print(hs.execute('/Users/luke/Code/displayplacer/displayplacer "id:F466F621-B5FA-04A0-0800-CFA6C258DECD res:1440x900 color_depth:4 scaling:on origin:(0,0) degree:0" "id:7D83487D-DF1C-74DB-9DDB-0BD63E163B20 res:1920x1080 hz:60 color_depth:4 scaling:off origin:(-1920,-485) degree:0"'))
    end
    print(secondScreen:position())
  end
end
screenWatcher = hs.screen.watcher.new(screenLayoutWatcher)
screenWatcher:start()
screenLayoutWatcher()
```

**Comment by latenitefilms** [comment]
Great news!

Given [`displayplacer`](https://github.com/jakehilborn/displayplacer) is open source and looks fairly straight forward, I don't think it would be too hard for someone like @cmsj or @asmagill to integrate this functionality into `hs.screen` at some point in the future.

I had a quick look into this, and given we already have `hs.screen:setOrigin()`, `hs.screen:setMode()` and `hs.screen:rotate()` - I'm not actually sure what's missing to implement this already using the existing `hs.screen` tools? Maybe I'm missing something?

**Comment by tofagerl** [comment]
Excellent, I should update my workflows to use this :)

**Comment by mattmattmatt** [comment]
I too was looking for a way to set the "physical" position of a screen through Hammerspoon (like you would do from OS X's "Displays" System Preferences), and couldn't quite figure out how to work the coordinate system. 
`hs.inspect(hs.screen.screenPositions())` returned 
```
{
  [<userdata 1> -- hs.screen: DELL S2722QC (0x600006000)] = {
    x = 0,
    y = 0
  },
  [<userdata 2> -- hs.screen: Built-in Retina Display (0x600005000)] = {
    x = 0,
    y = 1
  }
}
```
yet running e.g. `hs.screen.allScreens()[2]:setOrigin(1, 1)` ended up moving my secondary screen into the top left position, not bottom right.

It turns out the [`setOrigin`](https://www.hammerspoon.org/docs/hs.screen.html#setOrigin) coordinate system is based on screen pixels of the primary screen – so to move the secondary screen right of the primary, you want to find out how many pixels the primary is wide and add 1 to the secondary's new X position.

Example:
```
> hs.inspect(hs.screen.allScreens()[1]:currentMode())
{
  depth = 7.0,
  desc = "3008x1692@2x 60Hz 7bpp",
  freq = 60.0,
  h = 1692,
  scale = 2.0,
  w = 3008
}

> hs.screen.allScreens()[2]:setOrigin(3009, 500)
```
The first line returns the "physical" dimensions of the first screen.
The second line moves the second screen right of the first screen and down by 500 pixels.

This enabled me to use pure Hammerspoon to arrange my displays in relation to each other, plus assign shortcuts to each layout configuration.

I thought I'd leave this here, since this issue is one of few Google results that came up when looking for a solution.

**Comment by philtibby** [comment]
don't know if this is helpful to anyone, but I had the issue that I have two identical monitors to the left and right of my laptop, which is in the middle. they would constantly flip backwards, and I used this code to just flip them back:

`
function flipScreens()
  x = hs.screen{x=1,y=0}
  y = hs.screen{x=-1,y=0}
  x:setOrigin(-1920,-98)
  y:setOrigin(1920,-98)
end
`
