### ISSUE TITLE
Private Api Documentation

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1469]
Hey all I am very interested in creating alternative window managers in macOS but can't seem to find much in the ways of documentation. As I understand it these types of applications use private APIs? Is there documentation for these APIs anywhere?  As far as I can tell it seems that Apple just tries to make it really hard to customise work flows in such a manner?

**Comment by latenitefilms** [comment]
Can you give some examples of what you're trying to achieve?

**Comment by z3t0** [comment]
@latenitefilms Well for example let's say I want to be able to get information about a window object and then set its position using C/C++ (not Hammerspoon). I'm not sure where to start. Essentially I am asking how does Hammerspoon solve these problems? I looked into the source code and found usage of things like carbon but then again where is the documentation for the Carbon API? Or other APIs used to access features not officially documented. 

Thanks for taking the time to reply!

**Comment by asmagill** [comment]
Apple's documentation for the Carbon and Cocoa APIs can be downloaded from within XCode or viewed on the web at https://developer.apple.com/documentation/.  Mac OS development is expected to be done mostly in Objective-C or Swift, and I've heard of Objective-C++, but I don't know much about it.  If you're coding in pure C/C++, using the Cocoa API's may be difficult... I've never really looked into it and it may require some sort of bridge; but the pure Carbon API's should work fine, though.  An easy way to determine if a given library is Carbon vs Cocoa is to look at the header files in `/System/Library/Frameworks` (if you've installed the OS X command line tools) or `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks` (if you've just installed the XCode application)... if the header file just contains function declarations, data types, etc. then it's likely Carbon; if it contains classes (e.g. `@class NSWindow` as found in the `NSWindow.h` file) then it's Cocoa.

From what you've described, I suspect you'll be most interested in the `hs.window` and `hs.application` extensions which are in the `extensions/window` and `extensions/application`folders off of the main code repository.

As far as I recall, the only private function being used in there is  `_AXUIElementGetWindow ` which you can "add" to your code by declaring `extern AXError _AXUIElementGetWindow(AXUIElementRef, CGWindowID* out);` at the top of your code or in an included header.

This function converts the accessibility object for a window into a window ID which is used by some of the functions found in the Carbon CoreGraphics API.  You'll probably also want to look into the Carbon accessibility library AXUIElement since manipulating the windows of other applications is only possible through the Accessibility API.

Most of `hs.window` uses AXUIElements but wraps them into useful chunks so you don't need to know the gory details;  I've written a module at https://github.com/asmagill/hs._asm.axuielement which gives a more direct mapping from Hammerspoon to the AXUIElement functions which you may also want to take a look at... it's pretty raw at this point but does show how to do a few things that `hs.window` and `hs.application` can't do.

**Comment by asmagill** [comment]
I should add that a private function (in the sense that we mean here) means that it's undocumented by Apple... officially it "doesn't exist" and may go away in a future OS release.  However, most of the private functions we use in Hammerspoon have been around since at least 10.5 and haven't changed or been removed (an exception to this can be found in `hs.menubar` where the priority setting methods *did* disappear in 10.11).

Apple doesn't document them, but many find their way onto the internet anyway and you can google for current lists (I used to have a github link that someone was keeping pretty current, but I don't recall it at present... It may be referenced in the source code for one of my other modules -- I tend to try and put links into the code itself as reminders and acknowledgements.  Check out my repositories at https://github.com/asmagill if you're interested.

It should also be noted that if you have any intention of ever possibly submitting your code to Apple's App Store, you must *NOT* use private functions -- that's a sure way to get your code rejected.

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
