### ISSUE TITLE
hs.application:stop() & hs.application:continue() 

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1512]
@asmagill & @cmsj - Is it possible to add `stop` and `continue` to `hs.application`?

Basically, the same thing as the Terminal commands:

```
kill -STOP PID
kill -CONT PID
```

Source: http://osxdaily.com/2013/05/30/pause-resume-app-process-mac-os-x/

Thoughts?

**Comment by knu** [comment]
I'm not sure if it's a safe operation to perform because stopping an application sometimes renders other apps that try to communicate with it to stall.  Maybe you should try `hs.execute("kill -STOP "..app:pid())` and see if it works as expected.

**Comment by latenitefilms** [comment]
Thanks, yeah, will have a play - but I think the Terminal commands do what I want. I was more just wondering if the same thing could be achieved in Objective-C land?

**Comment by asmagill** [comment]
`hs.application:kill` and `hs.application:kill9` use objective-c methods to basically send specific signals to the process -- SIGTERM and SIGKILL.  The `NSRunningApp` class has specific methods for these two signals.  The current code doesn't support sending other signals so using the terminal methods is the only way to do it at present.

FYI, because you don't need the output of the terminal command and don't need to include your default shell's login files, using `os.execute` instead of `hs.execute` will be slightly faster since it's native to lua.

I've considered adding such a function to Hammerspoon, but since the work-around is so simple, I haven't felt the need... if the consensus is to add it, though, it can be. (If someone wants to try out coding a solution themselves, checkout `man 2 sigaction` (for a list of signal names) and `man 2 kill` (for the function you'd actually use) in a terminal window... it should be fairly easy to add.)

**Comment by latenitefilms** [comment]
Sweet, thanks @asmagill ! If I get time, I'll try and do a Hammerspoon commit to add these things, just because we can - but might not be for a little while, so if you have time to do it, go for it - as you'll be quicker and better at it an I anyway!

**Comment by latenitefilms** [comment]
You were right absolutely right @knu - because I have so many watchers, etc. looking at Final Cut Pro, as soon as I freeze Final Cut Pro - it also freezes Hammerspoon! Not sure a way around this, so I think it probably falls into the too hard basket.

**Comment by cmsj** [comment]
That seems sensible to me, SIGSTOP makes a lot more sense in a command line world than it does in a dynamic GUI world.

**Comment by latenitefilms** [comment]
No worries. Is it worth adding `hs.application:stop()` & `hs.application:continue()` anyway, that trigger   `os.execute` command for completeness?
