### ISSUE TITLE
Add callback option to hs.mouse.scrollDirection()

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1549]
As discussed in #1536, it would be great if there was the option to feed `hs.mouse.scrollDirection()` a function to act as a callback, as this wasn't solved in either #1536 or #1542.

Currently I'm using:

```
mod.preferencesWatcher = pathwatcher.new("~/Library/Preferences/", function(files) 
	local doReload = false
	for _,file in pairs(files) do
		if file:sub(-24) == ".GlobalPreferences.plist" then
			doReload = true
		end
	end
	if doReload then			
		mod.scrollDirection = mouse.scrollDirection()
	end
end):start()
```

...which works ok, but is a bit slow to trigger, and probably uses way too many resources for what it does.

**Comment by asmagill** [comment]
Minor suggestion: make the pathwatcher check for the specific file (i.e. "~/Library/Preferences/.GlobalPreferences.plist")

It won't change the responsiveness of the underlying file watching mechanism, so it won't make a significant difference in speed, but it will reduce callbacks that are ultimately useless because they refer to files you don't care about.

**Comment by latenitefilms** [comment]
Great suggestion @asmagill - I had absolutely no idea you could feed `hs.pathwatcher` file names - maybe this should be clearer in the documentation, as I got the impression it only accepted folders.

However, in this case, it's not ideal, because of the way macOS works, `.GlobalPreferences.plist` doesn't necessarily update straight away, something like `.ak8a.GlobalPreferences.plist` will be created and updated first, as part of macOS's caching.

**Comment by latenitefilms** [comment]
Given there's been no traction on this issue, I'm just going to close it for now.
