### ISSUE TITLE
Detect external mouse?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1587]
Is there any easy way to detect whether or not an external mouse is connected?

I thought about using `hs.usb.attachedDevices()`, but that won't work as a lot of external wireless mice have a USB receiver.

Thoughts @asmagill ?

**Comment by cmsj** [comment]
In theory it would be possible to use IOKit to enumerate HID devices and what kind of bus they are connected to, but it would need some C code to do.

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - Would it be possible for `hs.eventtap` to also return the name of the HID device that's causing the event?

**Comment by asmagill** [comment]
To my knowledge, no. A similar question has come up before about determining which keyboard a key event came from and no one came up with a solution that I am aware of for that, either.

**Comment by latenitefilms** [comment]
Maybe relevant? https://github.com/signal11/hidapi

**Comment by cmsj** [comment]
FWIW I think you'd run into issues with multiple things trying to talk to the HID device at once.

**Comment by latenitefilms** [comment]
@asmagill - Would it be possible to use `hs._asm.btle` to get a list of Bluetooth devices, and somehow detect if any of the connected devices is a mouse (then do the same for USB `hs.usb`)? Basically I want to work out if the MacBook Trackpad is the ONLY mouse device or not - possible?

**Comment by asmagill** [comment]
I honestly don't know... it's been a while since I've messed with that code because I was running up against the fact that everything I wanted to talk to either used proprietary encryption (FitBit) or didn't seem to work correctly with the Mac's BTLE implementation (Bluno, though surprisingly it works with the iOS implementation, so I don't know what Apple's engineers were smoking that day). I kept meaning to get back to it to at least get it working with the Arduino 101, but then Intel went and shelved that, so ... it became a low priority.

The two stumbling blocks I can see are (1) the btle module only detects devices which advertise as BTLE devices... I think the trackpad/mouse utilizes the Bluetooth 4 specification, not the Bluetooth Low Energy specification... unless maybe it advertises through both (the iPhone and iPad do); and (2) it won't "discover" devices which are already attached to another device (though if you know the UUID, you can connect to an already attached device if it allows multipoint(? I forget the actual label used)... and even though the mouse/trackpad is connected to the same computer, it *is* connected.

I don't recall detecting my external devices when I last tested the module, but I don't always have them turned on, so that may not mean anything. I can give it a shot sometime, but this month is already getting hectic and I'm trying to get some other things finished so I can start adding things like guitk, etc. so I can't give a good idea when I'll get to it right now.

If you or someone else feel like working on it in the mean time, the method `- (NSArray<CBPeripheral *> *)retrieveConnectedPeripheralsWithServices:(NSArray<CBUUID *> *)serviceUUIDs;` looks promising as it is described as returning "A list of the peripherals that are currently connected to the system and that contain any of the services specified in the serviceUUID parameter."... it's currently commented out in `manager.m` because it didn't like being given a null array and I was hoping to find a way to easily get *all* devices without having to know what services they provide first... while the bluetooth consortium provides a long list of recommended service UUIDs, devices are free to use their own and often do... you kind of have to know what you're looking for to look for something if it isn't specifically advertising... and connected devices don't advertise, even if they allow simultaneous connections.

**Comment by cmsj** [comment]
I'm pretty sure the only reliable way to do this would be with IOKit, which is a giant pain to work with, sadly :)

**Comment by latenitefilms** [comment]
No problemo! I’ll have a play and see if I can find any example code to steal.

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - This might be worthwhile bringing across to `hs.mouse`?

http://icculus.org/manymouse/

It's a cross-platform library for detecting the number of mice attached to a computer. On macOS it uses `HIDManager` to detect mice. Once it's built getting the number of mice attached to the system is a one-liner:

`const int available_mice = ManyMouse_Init();`

Thoughts?
