### ISSUE TITLE
Configurable fade speed for alerts

### ISSUE THREAD

**Issue by pbdeuchler** [Hammerspoon/hammerspoon#1600]
Is it possible to change the function signature of `hs.alert.show` to control the speed of fade out/fade in for alerts? I'm pretty proficient with lua but I couldn't figure out where to make the change, if someone points me in the right direction I could probably whip up a PR in the next couple of days.

**Comment by cmsj** [comment]
Modifying `hs.alert.show()` will be tricky because its final parameter is an optional number, so if we add another optional number it will be impossible to tell which one the user meant.

If you take a look at `extensions/alert/init.lua` you'll see that `0.15` is used throughout as a constant value for the fade time. My suggestion would be to make that a module level variable that users can override. See `hs.alert.defaultStyle` for a reasonable indication of how we declare/document module variables (although obviously for the fade time it would be a number not a table :)

I'm going to close this because I think I've covered what you want, but please feel free to re-open it if you want to discuss this further 🙂
