### ISSUE TITLE
In `hs.layout.apply`, pass window to screen callback

### ISSUE THREAD

**Issue by vjpr** [Hammerspoon/hammerspoon#1607]
I want to place windows of the same app on different screens depending on their tab count (a tab count of `nil` means it is a Chrome Bookmark App).

**Comment by cmsj** [comment]
That's a really good use case, but I'm not sure if it's going to be sane to do in hs.layout. It's already grown from a very simple static table into a bit of a monster, and the only way I can think of to do this without changing the current semantics, would be for the screen callback to return a function that gets called for each window.

I can't help but wonder if it might make sense to re-imagine the module as a Spoon that takes way less information up-front, and instead passes information to callbacks for the user's code to make a decision about where to place each window.

Does that sound like something you'd be interested in working on? Spoons are pretty easy to write, and since hs.layout is pure Lua, you could take a fair bit of the basic code from that.
