### ISSUE TITLE
Converting String into Table?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1611]
@asmagill - Sorry for the very basic question, but is there something already built into Hammerspoon that will allow me to convert the below string into a table?

`{"user":"invalid","errors":["user key is invalid"],"status":0,"request":"ce488a77-8be5-41f2-82e4-d94e4d3ce94b"}`

Thanks in advance!

**Comment by deryni** [comment]
Seeing as how that appears to be a serialized json value [hs.json.decode](http://www.hammerspoon.org/docs/hs.json.html#decode) should be able to handle converting it into a table I think (and a quick test seems to work).

If it was valid lua directly then it could be `load`ed but that's a slightly more complicated operation (and won't work here because of the [] array).

**Comment by asmagill** [comment]
~~~lua
> hs.inspect(hs.json.decode('{"user":"invalid","errors":["user key is invalid"],"status":0,"request":"ce488a77-8be5-41f2-82e4-d94e4d3ce94b"}'))
{
  errors = { "user key is invalid" },
  request = "ce488a77-8be5-41f2-82e4-d94e4d3ce94b",
  status = 0,
  user = "invalid"
}
~~~

"Proper" JSON strings should be fully compatible and convertible. There are some variants and edge cases that may be problematic (I've not found any that didn't also break other non-proprietary decoders), but if your source is a MacOS application, odds are it's using NSJsonSerialization, which is exactly what the `hs.json` module uses, so it shouldn't be a problem.

**Comment by latenitefilms** [comment]
Legends - thanks @asmagill & @deryni ! I knew it looked familiar!
