### ISSUE TITLE
AXColorWell Question

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1642]
Happy New Year @asmagill !

I'd love your help with something if you have a chance.

The new color wheels in Final Cut Pro are actually AXColorWell's in terms of Accessibility - see screenshot:

<img width="1166" alt="screen shot 2018-01-04 at 3 38 20 pm" src="https://user-images.githubusercontent.com/22286696/34550504-8c620e4a-f165-11e7-84cc-3d2661da75c5.png">

It's basically the same as a standard macOS color picker wheel, except it's been rotated anti-clockwise so that green is in the bottom left corner rather than top left.

<img width="258" alt="screen shot 2018-01-04 at 3 43 20 pm" src="https://user-images.githubusercontent.com/22286696/34550554-06be1a1c-f166-11e7-8068-ded210a29e88.png">

I would like to add a shortcut that allows you to move the "puck/controller" for the Color Board straight Left, Right, Up, Down - however the only value I have to modify is the AXValue, which is the RGB values stored within a string (for example "rgb 0.0215686 0.117647 0 0"). So to move the "puck/controller" straight up, I need to modify both the Red and Blue values in a non-linear way.

So, my question is, is there any way to easily do this maths? Thoughts?

Thanks in advance!

**Comment by latenitefilms** [comment]
I should note, that whilst it is possible to use the R/G/B text boxes under the Color Wheel to change the RGB values (as opposed to using the AXColorWell), they’re hidden by default so whilst I can easily code things to make them visible before manipulating or reading, it would be a better user experience if I didn’t have to change the active interface layout. I also would have the same underlying issue anyway - how do I move the puck in a straight line when I need to account for R, G and B.

**Comment by asmagill** [comment]
Hmm... I like that visual, wonder how they did it... I wonder if they just overrode `drawWellInside:` or if it's an actual custom picker (PAEColorWheel sounds like a custom class, so most likely)... got too much on my plate to seriously look into it any time soon, but I'll keep it in the back of my mind.

If you set the value to something like the string "rgb 1 0 0 0" (I'm assuming it's red green blue alpha where it's ignoring the alpha of the NSColor and using an alpha determined elsewhere) does it move to a solid red position? That will confirm if we even can modify it sufficiently through that property.

The first step is to determine specifically *what* is changing when you move in each cardinal direction.

You can change the RGB values to HSB values, if that helps, by parsing the string into the appropriate variables and using `hs.drawing.color.asHSB` (and then `hs.drawing.color.asRGB` to convert them back when assigning the value).

If it's modifying the color temperature, I haven't worked with that myself, but http://www.tannerhelland.com/4435/convert-temperature-rgb-algorithm-code/ looks promising as a start.

If it's using the CIE XYZ color space, unfortunately the MacOS doesn't include built in conversion tools (at least not that I've found) so you'll need to check out something like the code linked to from http://colormine.org/convert/rgb-to-xyz.

Hope this gives you some ideas!

**Comment by latenitefilms** [comment]
Legend, thanks!

Yes, setting AXValue to "rgb 1 0 0 0" moves the puck to 100% red, so that’s all good!

I just need to work out the maths to make it move “straight”. I figured as it’s just a normal AXColorWell (apart from the visual look), you might have some tricks up your sleeve.

I’ll check out those links, although I’m not sure they’re helpful. I did play with converting the RGB to HSB, but I couldn’t work out if it’s useful.

Will keep playing. Thanks heaps!

**Comment by asmagill** [comment]
It looks like there are a fair number of details about the color listed in the dialog... if you can determine which items change when you move in a given direction, it might suggest a specific equations or a color mapping to use.  Do the FCP docs give any idea as to what the movements might mean?

Somewhere there is a model that says "a change of 1 unit in the X direction means the following color change"... if we know the internal model that the circle is supposed to represent (and hopefully it is a well defined one that makes sense to people who work in color/film/etc. and not just something one of the developers "felt made sense"), it should suggest what you need to convert the RGB values to/from to do the same.

**Comment by latenitefilms** [comment]
Sorry, I should have explained my first screenshot in a bit more detail.

The centre puck/controller in the middle of the colour wheel is mapped to the Master Color R, G and B text boxes - that’s it.

You can ignore all the other options, as they don’t affect the colour wheel. For example, changing the Master tint, hue have no impact on the Color Wheel/RGB Textboxes.

FYI: the Master Saturation and Brightness sliders are actually mapped to those two arrow looking sliders on either side of the Color Wheel - they’re actually AXSliders - independent of the AXColorWell.

I can actually map a shortcut key in Final Cut Pro to make the puck move up/down/left/right (although it’s not set by default), so what I could do is write down how the RGB values change as the puck moves up and try and build a formula around that?

**Comment by asmagill** [comment]
I'm wondering if it's an HSB model, based on the similarity to the image at https://graphicdesign.stackexchange.com/questions/18719/what-is-hsb-really/18741#18741.

In which case, you'd need to convert the RGB value to HSB, then, treating the Hue value as an angle, you can figure the "x" and "y" of the knob with something like

~~~lua
x = sat * math.cos(math.pi * 2 * hue)
y = sat * math.sin(math.pi * 2 * hue)
~~~

Then adjust x/y and then convert back:

~~~lua
hue = math.atan(y, x) / (2 * math.pi)
sat = math.sqrt(x * x + y * y)
~~~

My trigonometry is rusty (I had to look at to even get this close), and this may not even be the right model, so not sure, but...

**Comment by asmagill** [comment]
Was working on that last before your next post, so I figured I'd finish it first.  Tracking the RGB changes might give an idea, but it may look completely random as well because I really think the circle is representing a different color model and you need to figure out what it is.

I thought of the ideas I posted above because HSB is commonly represented as a cylinder, but we can ignore brightness (value) when determining *what* the color is... and even if it is HSB, looking at those numbers might not be obvious because you're wanting to move the knob in an x, y plane while HSB is a rotational based model.

**Comment by asmagill** [comment]
(I meant to include http://tutorial.math.lamar.edu/pdf/Trig_Cheat_Sheet.pdf two posts ago as the reminder of basic trig relationships I had to look up)

**Comment by latenitefilms** [comment]
Legend, thanks so much @asmagill - HUGELY appreciated!

Yeah, I originally had a play with converting the RGB values to HSB, but it wasn't doing what I thought it should do. For instance, I'd except this to give me a different result? Am I doing something wrong?

```lua
> hs.inspect(hs.drawing.color.asRGB({
  alpha = 1.0,
  brightness = 0.0,
  hue = 0.0,
  saturation = 10.0,
}))
{
  alpha = 1.0,
  blue = 0.0,
  green = 0.0,
  red = 0.0
}
```

**Comment by asmagill** [comment]
With the HSB(V) model, brightness (or value) can be thought of as a measure of "how much black is making the color darker" (this is a simplification, but close enough for our purposes).

While the saturation and hue specify the color, a brightness of 0 means that hue and saturation don't matter -- it's effectively black, which is what you got in your example above.

~~~lua
> inspect(hs.drawing.color.asHSB({ red = 1 }))
{
  alpha = 1.0,
  brightness = 1.0,
  hue = 1.0,
  saturation = 1.0
}

> inspect(hs.drawing.color.asHSB({ green = 1 }))
{
  alpha = 1.0,
  brightness = 1.0,
  hue = 0.33333333333333,
  saturation = 1.0
}
~~~

In both of these cases, since I specified a *full* red and a *full* green, the brightness is 1.0.  Modifying your example slightly:

~~~lua
> hs.inspect(hs.drawing.color.asRGB({
  alpha = 1.0,
  brightness = 0.5,
  hue = 0.0,
  saturation = 1.0,
}))
{
  alpha = 1.0,
  blue = 0.0,
  green = 0.0,
  red = 0.5
}
~~~

Notice I changed the brightness to 0.5, so I get a red that's at half value with the same hue and saturation you specified.

I may have mislead you a little above when I said we can ignore the brightness -- we can, as long as we specify it as the magnitude of the largest of the Red, Green, or Blue values -- since the conversions I suggest above convert the RGB values from the AXUIElement to HSB, and the trig is modifying the hue and saturation only, just hold the brightness value it returns, modify the hue and saturation as specified, and then assign the original brightness before converting the new HSB to RGB and writing the new value to the element.

**Comment by asmagill** [comment]
I’m not 100% on the trig conversions bit as its been a while and its hard to test without having the control in front of me for manual tweeking... let me think if i can come up with a short set of teats you can run for me after i mull over your images a little while.

**Comment by asmagill** [comment]
Ok, take a look at https://github.com/asmagill/hammerspoon-config-take2/blob/master/_scratch/hsbWheel.lua

To use it, download the file and put it in your config directory, then do:

~~~lua
hw = dofile("hsbWheel.lua") -- adjust path as necessary
hw.setXY(x, y) -- adjust x and y to various values between -1 and 1 and see how it moves
-- when done, hw._C:delete() will clear it out
~~~

I've had to make some adjustments to the orientation because it looks like FCP and the macOS treat the hue angle slightly differently.

With the adjustment, a positive Y value moves the knob *down*, while a negative one moves it up... not what I normally expect when using something with a centered origin point, but consistent with the way Hammerspoon treats screen coordinates, so... I'm curious to hear if the knob color as you try different x and y values even slightly resembles what you see in FCP.

**Comment by latenitefilms** [comment]
Wow. Amazing. Thanks so much!

Your example code works awesome, although I'm still trying to work out how to translate it into my own code for Final Cut Pro. Will keep you posted how I go.

**Comment by latenitefilms** [comment]
@asmagill - Thanks so much for all your help. Your example is fantastic. I'm still trying to get my head around how to make it work within Final Cut Pro - but I'm slowly getting there I think. I think it's just my code that's screwing me up - your logic and assumptions seem spot on.

I was wondering though, looking back at those screenshots above, any idea how I can accurately translate the `AXValue` RGB string into something that matches what Final Cut Pro shows in it's interface?

<img width="1189" alt="rgb" src="https://user-images.githubusercontent.com/22286696/34646997-7fe7d6f6-f3ca-11e7-81c0-2e61102b083a.png">

**Comment by latenitefilms** [comment]
@asmagill - Thanks so much for your help with this HUGELY appreciated! Just to keep you in the loop, I think we're slowly getting there! We realised that even though providing an AXValue of "rgb 1 0 0 0" will move the puck to the red position (which is expected), when you read back the AXValue, it's a completely different value. So basically - setting and getting need to be treated with different maths - one respects the position of the red as it appears in the UI, and one thinks the red is where it would normally be in an AXColorWell.

I'm going to close this issue for now, but I'll open it up if we still run into brick walls.

Thanks again!!

**Comment by randomeizer** [comment]
Hey there. Thanks a tonne for the head-start on this. Here is the final implementation for `toXY` and `fromXY` that I ended up with:

```lua
-- the hue shift currently being output from AXColorWell values.
local HUE_SHIFT = 4183333/6000000

-- The outer edge of the color wheel
local BRIGHTNESS_CLAMP = 85/255

-- toXY(c, frame, clamp) -> table
-- Function
-- Converts a color to a position to the centre of the provided color well frame.
-- The color well only shows movement to 85 out of 255 possible values. If `clamp`
-- is `true`, the returned XY position will be clamped inside the circle. If `false`,
-- the XY position will be where the
--
-- Parameters:
-- * c		- The hs.drawing.color to position
-- * frame	- The frame for the outer boundary of the color well cirle.
-- * clamp	- If true, the returned position will be clamped to the color well circle.
--
-- Returns:
-- * The position of the color, relative to the centre of the color well.
local toXY = function(c, frame, clamp)
	c = asHSB(c)

	local ctr = centre(frame)
	local radius = min(frame.w/2, frame.h/2) / (clamp and 1 or BRIGHTNESS_CLAMP)
	local h = 1 - c.hue + HUE_SHIFT
	local b = clamp and min(BRIGHTNESS_CLAMP, c.brightness)/BRIGHTNESS_CLAMP or c.brightness
	local a = h * math.pi * 2
	local x, y = b * cos(a), b * sin(a)

	local pos = {x = round(ctr.x + x*radius), y = round(ctr.y + y*radius)}
	-- _highlightPoint(pos)
	return pos
end

-- fromXY(pos, frame) -> table
-- Function
-- Converts an XY position to a color, relative to the provided color well circle `frame`.
-- The return value should be multiplied by the radius of the particular color well.
--
-- Parameters:
-- * pos	- The {x=?, y=?} position of the location.
-- * frame	- The frame for the outer boundary of the color well cirle.
--
-- Returns:
-- * The `hs.drawing.color` for the position, relative to the color well.
local fromXY = function(pos, frame)
	local radius = min(frame.w/2, frame.h/2) / BRIGHTNESS_CLAMP
	local ctr = centre(frame)
	local x, y = pos.x - ctr.x, pos.y - ctr.y

	local h, b = atan(y, x) / ( math.pi * 2), sqrt(x * x + y * y) / radius
	_, h = modf(1 - h + HUE_SHIFT)
	b = min(1.0, b)
    return asRGB({hue=h, saturation=1, brightness=b})
end
```

The `min`, `cos`, etc. functions are all imported from `math`.

Thanks again!

**Comment by latenitefilms** [comment]
Thanks SO MUCH @asmagill & @randomeizer - you're both absolute legends. THANK YOU!
