### ISSUE TITLE
battery watcher: indicate which attribute changed

### ISSUE THREAD

**Issue by marksantcroos** [Hammerspoon/hammerspoon#166]
When writing a watcher function for the battery, it would be nice if the function would be called with the changed attribute as an argument.

Possibly also provide the previous value?

I'm not sure what is the guarantee of the delivery of status updates ... and whether that is under control of Hammerspoon at all.

Further, I can imagine this request also applies to other watcher functions.

**Comment by cmsj** [comment]
I'm going to close this out because it would seem that nobody has the time to work on it.
Given that we now support Spoons, I would suggest that people who still care about this feature, either implement it as a Spoon and submit a PR on the Spoons repo, or at least file an issue there suggesting it be created :)
