### ISSUE TITLE
Hammerspoon doesn't release memory on reload?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1662]
When working on crazy complex Lua scripts, Hammerspoon can start to seriously eat up memory. Looking at Activity Monitor, I can easily get it up to the 1GB range. However, I'd expect when you do a reload, that the memory would all be released, and go back to the same level as when you first loaded Hammerspoon. Does Hammerspoon not do garbage collection on reloads? Could it be that some extensions are not doing garbage collection properly and holding onto things across reloads?

Thoughts @cmsj or @asmagill ?

**Comment by latenitefilms** [comment]
Given we're using `hs.midi` quite a lot too, I wonder if the garbage collection in `hs.midi` is working correctly across reloads? Is there anyway I can test @asmagill ?

**Comment by SaKiEQ** [comment]
I garbled up this much from a starting 200-300mb.. within hours of just standing idle, while i was working on other stuff. This time with only 'two' of my own modules running... Will have to play around to see what provokes this...

![screen shot 2018-01-28 at 10 46 59 pm](https://user-images.githubusercontent.com/35499064/35487255-9d6e7b64-048a-11e8-82a8-dd9c99312818.jpg)

**Comment by cmsj** [comment]
Memory is a complex beast. It’s worth noting that the virtual size of an app is not equal to how much actual RAM it’s using. There’s a column in activity monitor for the Real Size, however, multiple GB virtual is still way too big.

A Lua reload actually destroys the lua_State object and creates a new one, so all objects that Lua knows about, get their `__gc` method called. That should release all of their memory unless there are bugs somewhere. Even if there are unresolvable GC situations, they still get freed because Lua knows it’s being torn down.

It’s possible that the GC methods are not doing the right thing and are leaking C/ObjC variables.
