### ISSUE TITLE
hs.wifi.watcher does not invoke callback function

### ISSUE THREAD

**Issue by Phosphor303** [Hammerspoon/hammerspoon#1679]
I'm really at a loss. I'd expect this code to display a notification every time I change my wifi network as ""SSIDChange" is watched for by default" according to the docs. But nothing happens:

```Lua
function callback()
    hs.notify.new({title='Hammerspoon', informativeText='Entered callback'})
end

wifiWatcher = hs.wifi.watcher.new(callback)
wifiWatcher:start()
```

macOS 10.13.3
Hammerspoon 0.9.60

**Comment by cmsj** [comment]
I think the issue here might not be the wifi watcher - `hs.notify.new()` creates a new notification, but doesn't display it immediately. You'd either need to capture the return value of that function and call `:send()` on it, or use `hs.notify.show()` (http://www.hammerspoon.org/docs/hs.notify.html#show) to create and immediately send a notification.

Please feel free to re-open this issue if this doesn't help :)
