### ISSUE TITLE
USBWatcher possibly interfering with wake and sleep?

### ISSUE THREAD

**Issue by sjml** [Hammerspoon/hammerspoon#1694]
I have a 13" MBP with TouchBar that I've been running Hammerspoon on for a while. Lately it's had trouble waking from sleep if it's connected to a USB hub. (Sadly not uncommon with these machines, but nobody can seem to pinpoint a problem.) 

HOWEVER, I've found that if I'm not running Hammerspoon, it works fine. 

My best guess would be that [this](https://github.com/sjml/dotfiles/blob/d2f19477c48b5aec59b5fe525dc5ccfcf88f7b6f/hammerspoon.symlink/hub-handler.lua) is the offending script, something with the `usb.watcher`. (The script looks for my hub and places an eject button in the menu bar to spit out all its disks.) 

Obviously I like Hammerspoon and would like to keep using it. I'm a _little_ skeptical about this being the problem, but it does seem to have mitigated it for the time being. My question is: is there something obvious in this script that I'm doing which is egregiously wrong? More likely it's something in macOS that's acting up, but it's getting triggered by something Hammerspoon or I are doing.

**Comment by asmagill** [comment]
I agree that I'm not sure how/why the watcher should make a difference since it's using the IOKit to do the actual monitoring and that's got its hooks into just about all peripherals of any type for the machine, but in the mean time, you might want to check out `hs.caffeinate.watcher` which can get a notification when the system is about to go to sleep (`systemWillSleep`) and when it wakes up (`systemDidWake`) and have it disable/enable your USB watcher and see if that helps.

**Comment by sjml** [comment]
Yep, I can confirm that with [this change](https://github.com/sjml/dotfiles/commit/3f863c1708753e697b1b47ce159b6e27b060a5e1#diff-e99d88202b05fbcd15eeff46ce9b3c86), the system wakes from sleep with no problems. Without it, it locks up and requires a reboot. 

This is definitely not Hammerspoon's fault; the OS is screwing up somehow. But this does *surface* the problem. 

I'll close this as an issue, but hopefully anyone googling "high sierra sleep wake failure" will find this and, if they're running Hammerspoon, have an avenue to explore.
