### ISSUE TITLE
suggests for hs.hints

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#170]
First, a bug or at least a ui oddity that should be noted and maybe throw up a notice:  If I have no apps with open windows (or at least with visible ones), then my keyboard is still tied up in selection mode until I hit escape... in the case of zero icons, it should probably either flash an alert or auto-release.

And second, any way short of recompiling to change the font size of the hints?  I admit I haven't looked at the code yet, but I'm certainly not seeing it in the Dash docs.  Mainly I want them a little smaller so I can see more of the icon, but it might also be nice to have the second chars (in vimperator mode or with 26+ windows)  (i.e. not the character it is currently waiting for) smaller as well.

Otherwise, love the module!

**Comment by cmsj** [comment]
+1 not entering a modal state if there are no icons. 

I'm also +1 on the idea of configurable fonts, if it doesn't make the code horribly complex. 

If nobody else beats me to it, I'll have a look at these items soon.

**Comment by cmsj** [comment]
This is almost fully addressed now in master. We don't enter the modal keyboard state if there are no applicable windows, and we now offer hs.hints.fontName and hs.hints.fontSize variables to configure the text styling.

There is one caveat with the latter right now, which is that the frame the text is drawn in, is pretty much a fixed size, in relation to the icon. This looks pretty silly if the font size if really small or really large, but I'm hoping nobody will want to do either of those things, because fixing that will be a much deeper change!

I'll open a new issue about that though.
