### ISSUE TITLE
IPC program does not work.

### ISSUE THREAD

**Issue by raguay** [Hammerspoon/hammerspoon#174]
I was migrating my Mjolnir Alfred Workflow to use Hammerspoon. I was able to move the configuration file over to using the Hammerspoon API, but I can not get the IPC program hs to run. It only says: error: can't access Hammerspoon; is it running?. 

Hammerspoon is running and has system access. All of my key bindings work, but I can not interface Alfred with it without the IPC program working.

**Comment by asmagill** [comment]
My first thought is to the autoloader of Hammerspoon... since Hammerspoon uses a lazy autoloader for the core included modules, you don't actually have to require a module for it to autoload... this is nice, but has the side affect that the preliminary creation of the IPC channel doesn't occur until something within Hammerspoon (not something outside of it, like the command line tool) tries to access the module.

The simplest test of this is to try 'hs.ipc.cliStatus()' from within the Hammerspoon console and then see if the hs command works from the command line.

If that's the case, then add either 'require("hs.ipc")' or 'hs.ipc.cliInstall()' to your init.lua file, whichever suits your style.  The cliInstall command can be invoked as many times as you like -- if it's installed correctly already, it does nothing (but forces the autoloader to load the module, thus starting the IPC channel) and if it's not installed, it will attempt to do so.

If this doesn't fix it, let me know... something else weird might be going on then...

**Comment by cmsj** [comment]
Good point. If it is that, I would propose we mention this in the API docs and in the cli binary's error message.

**Comment by raguay** [comment]
yep, that works now. Thanks.

Yes, this should be in the documents. You could mention the workflow as well. I am publishing it now and it allows for an expose of windows that is very helpful. You can watch for it on Packal.com. I am still re-writing the docs for it.

**Comment by raguay** [comment]
Just finished the new Alfred Workflow for Hammerspoon:  http://www.packal.org/workflow/hammerspoon-workflow

**Comment by cmsj** [comment]
@raguay thanks very much for doing that! I added an Integrations page on our wiki and linked to your workflow from it :)

**Comment by raguay** [comment]
No problem. I will keep Mjolnir's and Hammerspoon's Alfred workflow consistent with each other. If there is come functionality that you think should be there, just let me know. I am using Hammerspoon everyday with that workflow and have not had any issues.
