### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by daviehh** [Hammerspoon/hammerspoon#1746]
Since the [release note](http://www.hammerspoon.org/releasenotes/0.9.65.html) says more crash may happen now, here's one that I encountered: hammerspoon now crashes when the menubar item callback function is itself, e.g. a function that refreshes the menu item. 

Example code:

```
tm = hs.menubar.new():setTitle("test")

function set_tm()
    tm:setMenu({
                {title= os.date(),
                fn = set_tm}
                })
end

set_tm()
```

before, the item will change to the new date after clicking; now hammer spoon crashes.

Thanks!

**Comment by cmsj** [comment]
@daviehh thanks very much for reporting the crash and including Lua to reproduce it. Super helpful and the fix is checked in. In case you need it, I've attached a Release build of 0.9.65 with the fix applied.

[Hammerspoon.app.zip](https://github.com/Hammerspoon/hammerspoon/files/1904588/Hammerspoon.app.zip)

**Comment by daviehh** [comment]
@cmsj thanks a lot for this super quick fix!
