### ISSUE TITLE
hs.settings to use Core Data instead of NSUserDefaults?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1785]
Currently `hs.settings` uses `NSUserDefaults`, which is perfect if you only want to store a small amount of data in your settings, and only have to do a small amount of setting and getting - but for more complex configurations, `NSUserDefaults` can start to be a bit of a bottleneck.

How tricky would it be to migrate `hs.settings` so that it uses Core Data instead of `NSUserDefaults`?

I know @asmagill has pondered this in the past, but not sure if he ever tried it out?

Another possibility would be use to `hs.sqlite3` instead or Core Data? Thoughts @cmsj ?

**Comment by latenitefilms** [comment]
Or maybe it's better to just add a completely new extension, such as `hs.coredata` that could be used INSTEAD of `hs.settings`?

**Comment by asmagill** [comment]
Sorry I haven't been more active of late... it doesn't look like I'll have much chance to change that until mid summer but I am happy to see that Hammerspoon is progressing nicely and I try to keep an eye on current developments.

I never did get a chance to do much with core data, but my thought is that it probably deserves its own module, especially if you can come up with a good way of setting up NSPredicate objects -- there is a lot more that can be done with core data and predicate objects then settings offers.  If it turns out that the new module can easily perform everything that `hs.settings` does and we want to simplify or consolidate, a wrapper can be written then.

As to whether creating a core data module is worth the effort or whether sqlite3 should be used kind of depends upon your needs, but a lot of what I did with some of the earlier modules was "because I could" and "it was the Mac way"... and because of that some of them easily allowed extending other modules (think `hs.image` and `hs.styledtext`) or led to other features or modules because we already had a way to represent a lot of objects in a way compatible with Objective-C classes.

OTOH, Sqlite3 is cross platform compatible, so... like I said, depends a lot upon your needs and reasons for looking into it.

But that's just my 2 cents.

**Comment by cmsj** [comment]
I think CoreData is probably massive overkill, and I'm not even sure if you can define the models at runtime. We have hs.sqlite3 if you really need to store a lot of information.
