### ISSUE TITLE
open collective?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1789]
@cmsj - Have you ever considered something like [open collective](https://opencollective.com) for Hammerspoon? There's a lot of remaining issues in the Hammerspoon repository, so you could use any budget in an open collective account to pay for someone to tackle these problems, and also reimburse any development expenses yourself or @asmagill have? Thoughts?

**Comment by cmsj** [comment]
I've always resisted bringing money into Hammerspoon - I never want to feel like I owe my time to the project because people are paying. I want to feel like I'm doing this all for fun :)

You're right that we have a lot of issues open, and I'm very grateful for you and @asmagill and others who work on HS, but ultimately if people want more issues to be fixed, they need to step up and do the work.

**Comment by asmagill** [comment]
I tend to agree; when I have the time to work on Hammerspoon, it's because I want to -- and have the time.  Having money offered, even in the form of a bounty, would make it feel more like an obligation or a requirement -- or at the very least that I'm letting someone down.

I don't *need* income from this project; I'd like to think that maybe I get a little name recognition for what I hope is mostly some pretty decent code, but even that isn't really what I care about -- it's my interest in trying out and learning new things and adding/fixing features that I want to use myself that drives me.

I've had paid programming jobs before and I end up hating them pretty quickly, but that's just me...

**Comment by latenitefilms** [comment]
Understood - thanks heaps @cmsj & @asmagill ! And thanks SO MUCH for all your incredible work - HUGELY appreciated!
