### ISSUE TITLE
Add hs.styledtext.validFont(name)

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1804]
If you type `hs.styledtext.fontInfo("asdf")` into the Console, it will generate a LuaSkin warning, and return the default system font. This isn't overly helpful if you're trying to determine if a font exists or not. I feel like it would be more useful if it just returned `nil` if a font doesn't exist?

```lua
> hs.styledtext.fontInfo("asdf")
2018-05-27 01:09:01: 01:09:01 ** Warning:   LuaSkin: invalid font specified: asdf
ascender           12.568359375
boundingRect       h=17.6337890625 w=21.099609375 x=-3.9736328125 y=-3.63720703125 
capHeight          9.15966796875
descender          -2.7421875
displayName        System Font Regular
familyName         .AppleSystemUIFont
fixedPitch         false
fontName           .AppleSystemUIFont
italicAngle        0.0
leading            0.0
maximumAdvancement h=0.0 w=16.8974609375 
numberOfGlyphs     2596
pointSize          13.0
underlinePosition  -1.9677734375
underlineThickness 0.76171875
xHeight            6.8427734375
```

**Comment by asmagill** [comment]
I believe the thinking was that when requesting a font, at least in some cases (especially when rendering something), it would be better to default to the system font rather than no font at all... and IIRC the LuaSkin conversion code which creates the NSFont object is where it determines if the font details provided are valid or not -- since I don't think we want to change that behavior where an NSFont object is required (e.g. when rendering text for drawing or canvas), it would probably be easier to make a list of the specific functions/methods which should return nil or an empty table and modify those rather than try to make the conversion code more intelligent.

**Comment by latenitefilms** [comment]
No worries! Maybe something like `hs.styledtext.validFont(name)`?
