### ISSUE TITLE
inconsistent behaviour when doubly registering hotkeys

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#184]
When I do:
```lua
h1=hs.hotkey.bind({"cmd", "ctrl", "alt"}, 'y', function() hs.alert.show(1) end) h2=hs.hotkey.bind({"cmd", "ctrl", "alt"}, 'y', function() hs.alert.show(2) end) h1:disable()
```

I expect the hotkey to alert '2', but instead nothing happens at all.

If I then do
```lua
h2:disable() h2:enable()
```

The '2' starts to work.

Also, when I do `h1=nil` while `h1` is enabled, the hotkey still triggers a '1' and I can't do anything about it other than reloading/restarting Hammerspoon.

@cmsj mentioned "we don't check the return values of the OS X register/unregister hockey calls, which would probably help there."

**Comment by cmsj** [comment]
(FWIW I think the right thing to do here is to burp a lua error and refuse to register a second hotkey with the same exact things as a previous one)

**Comment by asmagill** [comment]
This will be a notable departure from Mjolnir... not that I disagree, as I once wrote a wrapper for exactly this (and documentation of assigned hotkeys, but that's waiting for something like dialog...)

We should probably have a doc listing notable differences or "Things you might have to change".

**Comment by oskarols** [comment]
Related:

```
h1 = hs.hotkey.bind(hyper, "C", function()
	print('h1')
end)

h1:disable()

h2 = hs.hotkey.bind(hyper, "C", function()
	print('h2')
end)
```
Pressing `C` will not do anything either. I have to do `h2:disable() h2:enable()` to properly enable it.

**Comment by asmagill** [comment]
See #313.

Currently the code suggests (and my testing agrees) on a couple of things that apply here...

If a hotkey is defined **and** enabled, then a subsequent defining and enabling (or bind, which combines both) of the same hotkey will be ignored until the first is disabled and the second is re-enabled (disabled then enabled again).

If the first is disabled before defining the second, then the second will work fine, but enabling the first one *before* disabling the second one won't do anything -- the second stays enabled.

And we can't just refuse to accept (issue an error) the re-definition of a hotkey because modal hotkeys also exist in the same pool -- they are just disabled initially, so using the same modal keys in different sets works because only one set is (usually) active at a time.

@oskarols -- I wonder if that's a timing issue because it works for me when I enter similar in via the console.  Was your example in a file (i.e. executed quickly)?

At any rate -- follow up in #313, as I'm in the process of doing a possible replacement for hs.hotkey, so addressing issues like this now is a good time.

**Comment by oskarols** [comment]
@asmagill Curiously I can no longer reproduce this issue.
