### ISSUE TITLE
Potential Leaks?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1894]
Do these mean anything @cmsj or @asmagill ?

<img width="684" alt="screen shot 2018-06-30 at 9 59 30 am" src="https://user-images.githubusercontent.com/22286696/42119141-61e33686-7c4c-11e8-911a-456ef20279aa.png">

**Comment by cmsj** [comment]
The IPC ones are inscrutable, I've stared at those for many hours and I cannot figure out how one would use the relevant `CFMessagePort` APIs without a leak. The `hs.window` one is a type error not a leak, and I'm also not sure it's possible to fix that. We arguably should hint to the analyzer to ignore these, but I think I'd rather leave them in because maybe one day I'll understand how to fix them properly :)
