### ISSUE TITLE
Question - hs._asm.axuielement.observer selfRefCount?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1921]
@asmagill (or @cmsj) - If you get a chance, I'd love your wisdom in regards to how `hs._asm.axuielement.observer` works behind the scenes.

Each time I execute `hs.inspect(require("hs._asm.axuielement").observer._internals())`in the Hammerspoon Console, I note that the `selfRefCount` increases.

For example:

```lua
2018-08-19 16:56:58: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2018-08-19 16:57:00: -- Lazy extension loading enabled
2018-08-19 16:57:00: -- Loading extension: notify
2018-08-19 16:57:00: -- Loading extension: fnutils
2018-08-19 16:57:00: -- Can't find ~/.hammerspoon/init.lua; create it and reload your config.

> ax = require("hs._asm.axuielement")
o = ax.observer.new(hs.application("Safari"):pid())
    :callback(function(...) print(hs.inspect(table.pack(...), { newline = " ", indent = "" })) end)
    :addWatcher(ax.windowElement(hs.application("Safari"):allWindows()[1]), "AXTitleChanged")
    :start()
2018-08-19 16:57:06: -- Loading extension: application
2018-08-19 16:57:06: -- Loading extension: uielement


> hs.inspect(require("hs._asm.axuielement").observer._internals())
2018-08-19 16:57:13: -- Loading extension: inspect
{
  [<userdata 1> -- hs._asm.axuielement.observer: (0x600000254f68)] = {
    callbackRef = 1,
    isRunning = true,
    selfRefCount = 2,
    watching = {
      [<userdata 2> -- hs._asm.axuielement: AXWindow (0x600000251758)] = { "AXTitleChanged" }
    }
  }
}

> hs.inspect(require("hs._asm.axuielement").observer._internals())
{
  [<userdata 1> -- hs._asm.axuielement.observer: (0x608000641408)] = {
    callbackRef = 1,
    isRunning = true,
    selfRefCount = 3,
    watching = {
      [<userdata 2> -- hs._asm.axuielement: AXWindow (0x6080006413a8)] = { "AXTitleChanged" }
    }
  }
}

> hs.inspect(require("hs._asm.axuielement").observer._internals())
{
  [<userdata 1> -- hs._asm.axuielement.observer: (0x608000654ae8)] = {
    callbackRef = 1,
    isRunning = true,
    selfRefCount = 4,
    watching = {
      [<userdata 2> -- hs._asm.axuielement: AXWindow (0x60800045c258)] = { "AXTitleChanged" }
    }
  }
}

> hs.inspect(require("hs._asm.axuielement").observer._internals())
{
  [<userdata 1> -- hs._asm.axuielement.observer: (0x60000024e188)] = {
    callbackRef = 1,
    isRunning = true,
    selfRefCount = 5,
    watching = {
      [<userdata 2> -- hs._asm.axuielement: AXWindow (0x60000024f2c8)] = { "AXTitleChanged" }
    }
  }
}

> hs.inspect(require("hs._asm.axuielement").observer._internals())
{
  [<userdata 1> -- hs._asm.axuielement.observer: (0x60c001441ac8)] = {
    callbackRef = 1,
    isRunning = true,
    selfRefCount = 6,
    watching = {
      [<userdata 2> -- hs._asm.axuielement: AXWindow (0x60c001441eb8)] = { "AXTitleChanged" }
    }
  }
}

```

Is this by design/intentional/the way it works?

I would have ASSUMED that the `callbackRef` and `selfRefCount` would stay consistent for the life of the `hs._asm.axuielement.observer` object?

Am I missing something obvious?

**Comment by latenitefilms** [comment]
@asmagill - My testing my be flawed, however, it SEEMS like `hs._asm.axuielement.observer` objects are using up RAM, but not releasing it after garbage collection?

https://gist.github.com/latenitefilms/fefd8d1ae995f65d1d10251b64a48ba7

Thoughts?

**Comment by latenitefilms** [comment]
@asmagill - Given you've been online recently, I just wanted to ping you again on this one in case you have any thoughts. Thanks mate! No stress at all if you're too busy.

**Comment by asmagill** [comment]
It's been so long since I've looked at this module that I hesitate to state anything about it with conviction without doing a full review first (maybe next week -- I've been feeling the itch to dive into Hammerspoon again and I think I may be able to make some time soon, though no promises!)

However, in regards to the selfRefCount seeming to only increase, it should be noted that this is increased within `observer.m` every time a new userdata object for the observer CFObject is created -- note that the address portion of the userdata string is different each time `inspect` is called -- this is because the module isn't using the same identical userdata but rather creating it dynamically each time it is required in `pushAXObserver` (also in `observer.m`).  This is by design and simplifies some operations as we don't have to add code in `pushAXObserver` to try and figure out if the specific observer already has a corresponding userdata within the Lua state... add `collectgarbage()` between your inspections and you should see the `selfRef` stay pretty constant.

Which in no way means that the module doesn't have leaks... just that I don't think this particular behavior indicates one.

**Comment by latenitefilms** [comment]
Legend, thanks @asmagill !
