### ISSUE TITLE
hs.webview - Fix "Lua execution is happening on a non-main thread" Crash

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1930]
Any ideas @cmsj ?

http://crashes.to/s/87e24460ba9

**Comment by asmagill** [comment]
Digging into the crash, it appears that the `windowDidBecomeKey` method of `HSWebViewWindow` (hs.webview's internal.m line 121) is the culprit... Off the top of my head I think I remember reading somewhere that window delegate callbacks are supposed to happen on the main thread, which is why the code isn't checking, but I can't remember where I might have read this, so I may be remembering incorrectly or we may have just been lucky so far...

The fix is relatively simple for delegate calls which invoke Lua but don't expect a return value -- wrap  lines 121-128 with `dispatch_async(dispatch_get_main_queue(), ^{` ...* lua callback code *... `} ;` (and if you wrap this one, you should probably do the rest just to be safe).

The cases where the return value of the lua callback is needed to determine what the delegate callback should do next are more complex... if you *know* you're not in the main thread, doing a `dispatch_sync` would work -- but if execution happens to be occurring in the main thread, this would lock up Hammerspoon, so other tricks have to be used -- `performSelectorOnMainThread:` or checking `[NSThread isMainThread]` and duplicating code are common so check other extensions with callbacks like `hs.timer` and `hs.httpserver` just to name a few...

**Comment by latenitefilms** [comment]
Awesome, thanks for the detailed explanation! Very helpful!

However, I might leave this for @cmsj to action so that I don’t accidentally break things. I’ll have a play regardless and see if doing what you suggested has any side effects.

**Comment by latenitefilms** [comment]
Fixed in #1939
