### ISSUE TITLE
LuaSkin Nullability Issues in Xcode 10.0

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1944]
Any ideas @cmsj or @asmagill ?

<img width="2487" alt="screen shot 2018-09-25 at 3 58 17 pm" src="https://user-images.githubusercontent.com/22286696/45995558-dba20780-c0db-11e8-9d0a-9411e49a54d5.png">

**Comment by latenitefilms** [comment]
Maybe related? https://oleb.net/2018/@keypath/

**Comment by latenitefilms** [comment]
FYI: this is outside my skillset, so I'm going to leave @asmagill or @cmsj to address this issue.

**Comment by asmagill** [comment]
@cmsj since LuaSkin was your creation, I defer to your preferences.

Basically the compiler is complaining because keys to dictionaries can't be nil, but the shortcut `@(cstring)` to create an NSString object is now marked nullable.

The fixes as I see it are as @latenitefilms suggest and to change the warnings, at least for this part of the project, or to create place holder vars, e.g. `NSString *placholder = @(cstring)`, verify that it's not nil, and then use placeholder instead of the shortcut.

I'm leaning towards the second approach because while some of the cases do already verify that the cstring isn't NULL (not all do, though), it is theoretically possible that an invalid UTF8 sequence beginning the cstring could also cause the NSString version to be nil, so the proper approach is to do the conversion and verification ourselves.

I'm fine doing the work, but as I said, LuaSkin was your creation and I don't know if/what plans you might have for it outside of Hammerspoon, so I'll defer to your preference.

**Comment by latenitefilms** [comment]
Creating place holder vars sounds like a much better idea to me! Thanks for reviewing @asmagill !

**Comment by latenitefilms** [comment]
@asmagill - Given we might not get a reply from @cmsj for a little while, what are the chances of you doing a pull request in the meantime as a temporary workaround?

**Comment by asmagill** [comment]
Most of the cases were in the LuaSkin registration of helper functions, so to trigger them, you'd have to be building an external module... a couple, though, could be triggered by user data at run time.

In any case, see #1953 and let me know how it works for you. You'll still need #1943 though, figured we can keep issues separate for now unless they involve overlapping files.

**Comment by latenitefilms** [comment]
Woohoo! That all works now - thanks heaps @asmagill !

FWIW - I did also have to run `pod update` to get the release script to work properly, as it looks like there's been a COCOAPODS update to give compatibility to Xcode 10.0. I believe this is fixed in #1929.

**Comment by cmsj** [comment]
These are fixed. Sorry, I hadn't realised that my github notifications were broken, so I didn't see messages for about the last month :/
