### ISSUE TITLE
Key signing dialog box appears now

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#197]
I just pulled from the repo and built.

Unlike the first time I cloned the repo and built, the result of this build is such that when I launch the .app, I get a dialog box saying:
````
Insecure update error!
````
along with some text about "code signing".

How can I make this go away?  Why did it suddenly start appearing?

EDIT: Issue title should say "Code signing", not "Key signing".

**Comment by cmsj** [comment]
The Sparkle update framework doesn't check for updates the first time it's run, AFAIR.
If you switch to build Debug instead of Release, it will be built without linking Sparkle :)

**Comment by chdiza** [comment]
Sorry to be a pain, but how do I do that?

````
xcodebuild -workspace Hammerspoon.xcworkspace -scheme Debug clean build
````
results in:
````
xcodebuild: error: The workspace 'Hammerspoon' does not contain a scheme named 'Debug'.
````

**Comment by cmsj** [comment]
Gah, sorry, the scheme is called "Hammerspoon", not Debug. My bad :)

**Comment by javigon** [comment]
I might be missing something, but compiling with in debug mode still brings the Sparkle warning. Any ideas?
I use: 
xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon clean build
Thanks!

**Comment by cmsj** [comment]
@javigon I'll try and check on this today. It's possible I broke something, because that command looks like it should work!

**Comment by javigon** [comment]
Thanks @cmsj!

**Comment by javigon** [comment]
Hi @cmsj, did you have time to look into this?
Thanks! :)

**Comment by cmsj** [comment]
@javigon I had a go, and it seems to work fine for me. Could you maybe throw up the output of the build into a pastebin or similar?

**Comment by cmsj** [comment]
@javigon also, do you get the error if you run from xcode?

**Comment by javigon** [comment]
@cmsj It works from xcode.
I guess what I want is to be able to compile (preferably from command line :)) and link from /Applications to $HS_DIR/build/Hammerspoon.app so that my compiled version is in production for testing, accessibility to new features, etc. I cannot seem to get that from Xcode. I am creating a new module, so that would be very interesting :)

I guess you have a workflow for that, can you share? I am mainly a C developer - I still need to learn how to get around Xcode...

For completeness, I modify these tow lines in the Makefile. Compilation succeeds but the warning remains.

PRODUCT_DIR = $(shell xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -showBuildSettings | sort | uniq | grep " BUILT_PRODUCTS_DIR =" | awk '{ print $$3 }')

xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon clean build > build/release-build.log

Thanks!

**Comment by asmagill** [comment]
I too prefer building from the command line... faster turn around for me when working on new code.  I made the necessary changes from Release to Hammerspoon in the Makefile, but also had to change the PRODUCT_DIR line to:

PRODUCT_DIR = $(shell xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -showBuildSettings | sort | uniq | grep " BUILT_PRODUCTS_DIR =" | awk '{ print $$3 }' | sed 's/\/Release/\/Debug/')

That's more of an FYI... what I wanted to report is that running this debug version, I don't get prompted that Accessibility is disabled (and it is, after a new build, but I expect this) and even though I've deselected 'Send Crash Data' in the preferences, and `defaults read org.hammerspoon.Hammerspoon HSUploadCrashData` returns 0, upon restarting HS, the checkmark is still in place (the value remains 0 in the preferences file, though).

Is this expected behavior in the Debug build?  I'll test later in the release and a 'Release' build done locally, but I prefer not to use a Release build because it includes the Sparkle code I don't want during my testing.

I guess I'm asking... is their a list of known/expected differences between Release and Debug builds?

**Comment by cmsj** [comment]
@asmagill There's no clearly defined list anywhere, and it's weird that the crash data checkbox shows as on for you - it's supposed to be forced to off and the widget made unclickable if your machine doesn't have the Crashlytics API key (which it doesn't, because that lives in a file that's outside the git repo!)
