### ISSUE TITLE
Read and write Safari cookies

### ISSUE THREAD

**Issue by andreiborisov** [Hammerspoon/hammerspoon#1995]
I would like to be able to write Safari cookies using Hammerspoon to automate settings for websites I use.

As far as I understand in recent macOS releases, each app has it's own cookie storage, so setting Safari cookies using `hs.webview` isn't possible.

There is [`NSHTTPCookieStorage` class](https://developer.apple.com/documentation/foundation/nshttpcookiestorage?language=objc) in Foundation framework which seems to do just that, but it requires to use JXA with Objective-C bridge which is rather complicated.

Another solution is to write `binarycookies` format parser myself using Lua, but unfortunately this format is poorly documented.

What's the proper way to tackle this problem? Is Hammerspoon community interested in such functionality? Should I make a spoon for it?

**Comment by asmagill** [comment]
Generally, if there is an objC class for something, rather than use a bridge we've actually written our own code in Objective-C to provide functions directly to lua using the Lua C API and the LuaSkin helper class written primarily by @cmsj.  Check out the `extensions` directory in the Hammerspoon repository and you can see how most of the modules are structured.  Also, while it's pretty dated and doesn't follow the current "best" practices, I took a stab at a module writer's walkthrough a while back which can be found at https://github.com/asmagill/HS_ModuleWalkthrough, but it will probably require some changes/updates to work with the current version of Hammerspoon.

All that said, I dug a little into `NSHTTPCookieStorage` and I'm not sure that it would be worth accessing cookies through it (Note: last I knew, Hammerspoon targets the three most current macOS versions, so 10.12, 10.13, and 10.14 as of this writing; while it may compile/run in earlier versions, it's not tested) --

> Sharing Cookie Storage
> 
> The persistent cookie storage returned by sharedHTTPCookieStorage may be available to app extensions or other apps, subject to the following guidelines:
> 
> iOS — Each app and app extension has a unique data container, meaning that they have separate cookie stores. You can obtain a common cookie storage by using the sharedCookieStorageForGroupContainerIdentifier: method.
> 
> macOS (non-sandboxed) — As of macOS 10.11, each app has its own cookie storage. Prior to macOS 10.11, a common cookie store is shared among the user's apps.
> 
> macOS (sandboxed) — Same as iOS.
> 
> UIWebView — UIWebView instances within an app inherit the parent app's shared cookie storage.
> 
> WKWebView — Each WKWebView instance has its own cookie storage. See the WKHTTPCookieStore class for more information.

The ones that apply to us (macOS and WKWebView for `hs.webview`) suggest that using `NSHTTPCookieStorage` would limit Hammerspoon to just its own cookie store, not anything used by Safari or its extensions.

So, it looks to me like the binary format parser is probably going to be the way to go... The `NSHTTPCookie` documentation states that the cookies follow `RFC 6265, HTTP State Management Mechanism`, so perhaps https://tools.ietf.org/html/rfc6265 might help or at least be a starting point.

**Comment by asmagill** [comment]
Sorry didn't mean to close this...

**Comment by schrodincat** [comment]
Thanks for such detailed response!

> I dug a little into `NSHTTPCookieStorage` and I’m not sure that it would be worth accessing cookies through it
It seems [initWithStorageLocation](https://developer.apple.com/documentation/foundation/nshttpcookiestorage/1807248-initwithstoragelocation?language=objc) method makes possible to read and write arbitrary `binarycookies` file on disk.

**Comment by latenitefilms** [comment]
@schrodincat - Unfortunately, it sounds like `initWithStorageLocation` was silently removed in macOS 10.7.

See: https://stackoverflow.com/questions/7942152/nshttpcookiestorage-sandboxing

**Comment by schrodincat** [comment]
After a brief investigation, it seems writing `binarycookies` parser should be feasible.

Some people claim that at the end of a file supposed to be a checksum with unknown nature which prevents modifying file without reverse engineering checksum algorithm, but after fiddling around a bit and changing a couple of cookie values by hand, it seems either they are wrong or checksum was removed some time down the road.

I'll keep you posted about the progress.

**Comment by cmsj** [comment]
Doesn't macOS 10.14 block access to the local Safari data files?

**Comment by schrodincat** [comment]
@cmsj you’ll probably need to grant Hammerspoon full disk access, but it should work

**Comment by schrodincat** [comment]
On the other topic, what's the best way to debug spoon/config? I haven't managed to find anything about this. `print` is working fine for me, but obviously it's quite simplistic and clunky way to debug.

Any tips or links would be appreciated.

**Comment by latenitefilms** [comment]
I use [`hs.logger`](http://www.hammerspoon.org/docs/hs.logger.html) instead of `print`, as it's much easier to write `log.df("result: %s", result)` than `print(string.format("result: %s", result))` to write debugging code to the Console.

There's also standalone tools that also work with Hammerspoon such as [ZeroBrane Studio](https://studio.zerobrane.com/doc-lua-debugging).

Here's plenty of other tools: http://lua-users.org/wiki/DebuggingLuaCode

**Comment by latenitefilms** [comment]
This looks handy too: https://github.com/ignacio/StackTracePlus

**Comment by cmsj** [comment]
I think we should probably accept that we're not likely to do this, but it may be possible to do entirely in Lua?
