### ISSUE TITLE
Feature Request: hs.yaml

### ISSUE THREAD

**Issue by jeffmikels** [Hammerspoon/hammerspoon#1999]
Would anyone be able to build a simple yaml parser into hammerspoon. JSON is nice, but yaml is easier for configuration files.

**Comment by latenitefilms** [comment]
This will work with Hammerspoon: https://github.com/gvvaughan/lyaml

I'm not sure what @cmsj or @asmagill thoughts would be bringing this code into Hammerspoon as `hs.yaml` - it might be too much work to keep the projects in-sync?

**Comment by cmsj** [comment]
hs.json has a significant advantage that we're just doing some very light work around a macOS framework, which keeps the maintenance overhead pretty low. Pulling in a reasonably complex Lua library for YaML means extra maintenance efforts for us.

I'm not completely opposed to the idea, but I'd prefer there to be a compelling argument as to why it belongs in HS rather than dropped into ~/.hammerspoon/ by people who need it.

(Also if there is a simpler Lua yaml library going, I'd also be happy to look at that)

**Comment by jeffmikels** [comment]
It's honestly not worth that much effort. And, I didn't know I could just drop lua code into ~/.hammerspoon. For some reason, I thought I had to use luarocks and get all the configurations set up. Don't worry about it.
