### ISSUE TITLE
Make userdata objects more introspect able?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#201]
I tried to add __type data to a userdata object and Lua seemed to ignore it, but the general question stands as to whether we can add something to the meta table for userdata objects to make them more introspect able for users?
Maybe @Habbie or @asmagil know if this is possible? (Sorry to always be bugging you guys :)

**Comment by asmagill** [comment]
Off the top of my head... don't know.  The metatable of a userdata is like any other metatable -- it can contain any lua values we want -- the metamethods just have special uses; other variables could be stored in there, like descriptions, etc. but they would still be hidden until retrieved via getmetatable(userdata).

Lua 5.3 adds some metamethods to tables (and userdata?) but I think it's more in line with making the metamethods more consistent across all possible types of access to the table (I recall that metamethods for tables are supported in pairs() and ipairs() under 5.3, where in 5.2, there weren't -- or at least not fully.  I'll look into 5.3 more deeply, but it would likely be a noticable change -- all integers are 64 bit, requiring changes in anything bit based and probably in values passed back and forth between lua and C... true distinctions between float and integer, etc.

I did come across debug.setuservalue():

debug.setuservalue (udata, value) <>
Sets the given value as the Lua value associated to the given udata. value must be a table or nil; udata must be a full userdata.

Returns udata.


but I'm not 100% what that means... I'll pull my reference book tonight and see if I can get more detail.

**Comment by cmsj** [comment]
Hmm, yeah I think making stuff only visible to getmetatable() is not that awesome, I was mostly just wondering if we could improve the experience of playing in the REPL, getting some strange object back from an extension, and not being able to inspect it very usefully.

Never mind, thanks! :)

**Comment by asmagill** [comment]
You might check out:

tostring (v) <>Receives a value of any type and converts it to a string in a reasonable format. (For complete control of how numbers are converted, use string.format <file:///Users/amagill/Library/Application%20Support/Dash/DocSets/Lua_5.2/Lua.docset/Contents/Resources/Documents/www.lua.org/manual/5.2/manual.html#pdf-string.format>.)
If the metatable of v has a "__tostring" field, then tostring calls the corresponding value with v as argument, and uses the result of the call as its result.


Since the REPL converts any response to string, this might be useful.   I'm not sure if this would have implications with passing the data into other functions, though, since it would now survive a lua_tostring() call... a lua_checkstring() or lua_checkudata() would still work correctly, but we'd have to check all our code to make sure lua_tostring is only used after validating the data type...

**Comment by asmagill** [comment]
BTW, this seems to work: I added the following to hs.notify on my machine (I'm actually remote right now, so I'm limited to what I can do via the hs command, thus I can't test the crashing yet)...

static int notification_displaystring(lua_State* L) {
    notification_t* notification = luaL_checkudata(L, 1, USERDATA_TAG);
    lua_pushstring(L, [[NSString stringWithFormat:@"Notification: %s", [((__bridge NSUserNotification *) notification->note).title UTF8String]] UTF8String]);
    return 1;
}


Then in the mettable for the returned object, I added

{"__tostring", notification_displaystring},


Now, when I do:

a = hs.notify.new(f, {title="Hello"})
a

I get:

Notification: Hello


So, it looks like we can do this, as long as we're careful about lua_tostring methods and always use the check versions when data type actually matters.

--
A-Ron
