### ISSUE TITLE
hs.notify crasher in 0.9.18

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#202]
We're seeing a crash in the chain of notification_gc. The public URL of the crash report is:

http://crashes.to/s/da30d75153d

(in case that's not working usefully, try: https://www.dropbox.com/s/q6hffjipj6p0x3r/Screenshot%202015-01-21%2020.04.36.png?dl=0 )

@asmagill - this is weirdly similar to the one I was running into before we merged the PR for the new hs.notify, but I'm sure I had tested your fix before landing the PR.

**Comment by asmagill** [comment]
I'll check it out tonight when I get home, but just so I can test correctly, what are the specific steps you're taking before the crash?

**Comment by cmsj** [comment]
That's one of the downsides of Crashlytics - we don't actually know what's happening in Lua to get to the crash in the C code :/
(this is a crash report gathered from a user, and we have no way of knowing who)

**Comment by asmagill** [comment]
Part of the problem (but I don't know if it's related to this particular crash or not yet) I've been working with is that I've been trying to deal with possibly chained notification delegates... the HS app itself may put up a notification from a lua code error, the hs.notify (pre the updated version) has it's own, and then (when testing) hs._asm.notification... all of which create their own delegate, but the app itself doesn't create it's delegate until it needs it (i.e. it isn't created unless and until HS needs to put up it's own notification) and I don't remember about the original hs.notify, but it had at least rudimentary checks for the core app delegate.  The new version creates its own delegate when the module is actually loaded, whether a notification has been presented yet or not.

I've tried to get around this by checking to see if the core app delegate exists, and if it doesn't, then force it to be created, then create our own. An invoked notification will fall back to it the core one if an active notification doesn't contain a recognizable callback tag.

I've been considering that a better solution is for me to completely redo the way the way the core app handles it's own notifications, and merge it with the new code making this new version tightly integrated into HS itself and less of a stand-alone module... I'd lose the compatibility with Mjolnir doing this, but we've diverged enough now that that's not as big of a concern as it was when I first started this months ago...  I'll give it some serious thought, as it may be time to actually do it this way.

--
A-Ron

**Comment by cmsj** [comment]
so, we've now had a release out with the old hs.notify API deprecated, which is more than we've done for any other API changes, so I'm happy for the old API to go away entirely. We're still 1.0 and it seems very reasonable to me that we not leave the old API around for very long, lest people think I'm not serious when I ask them to port their configs in the release notes :)

I'd also be fine with notifications moving the supporting code more into the main app as well as removing the old API.

**Comment by asmagill** [comment]
Ok, I know that hs.notify has been sort of an annoying module (at least for me) to get right, partially because of nested notification delegates and partly because the original interface was severely limited, but I have come to realize that it has one strength which my current approach lacks... the ability for a callback function, as long as it is re-introduced before activating (clicking on) the notification (by creating it via init.lua, for example) to work, even if the hammerspoon environment has been reloaded or even exited and restarted.

I think a merging of the two is called for, and that is what I am currently working on -- we'll still have more access to the specifics of the notification -- button titles, etc. and soon scheduled notifications (i.e. set to appear at some future point, rather than "right now"), but function handling will be at the lua level, rather than as userdata which persists only as long as a given lua state does.

This simplifies the C-side coding immensely because now we can call a hs function that will always either exist or not in the *active* lua state, rather than try and figure out if the lua state for the specified callback is still valid or not.

In doing this, however, some other possibilities come to mind that I thought I'd bounce off the group...

A user notification center delegate receives three messages:
    didActivateNotification
    shouldPresentNotification
    didDeliverNotification
    
Now the whole mess around the callback function has been about didActivateNotification, so we need consider it no further than we already do.

shouldPresentNotification is only queried if the notification center determines that it shouldn't present the notification -- mainly this comes up because the application (Hammerspoon) is in the foreground, as the normal behavior is to only show notifications from an application if it isn't in the foreground.  We currently allow the setting of a boolean flag for this, but it can only be set before the notification is sent.  Once the notification is sent, or Hammerspoon is reloaded, we can't change it.

didDeliverNotificiation is always sent when the notification is delivered, but before the user has had a chance to click on it.  At present, this would be of little benefit to us, since we can only create notifications that appear immediately, but it could be of use if/when we add the ability to schedule notifications for the future.  It would provide a way for the hammerspoon environment to be aware that a notification has actually been shown, even though the user hasn't clicked on it yet.

So, I guess I'm asking if I should allow lua function callbacks for shouldPresentNotification and didDeliverNotification as well?  I don't think either will be too difficult with this new approach, though I am still working out what the callback register and unregister functions will look like, as I can't decide if we should tag the function or the notification with the unique identifier... for didActivate, I can go either way, but for didDeliver and shouldPresent, I'm thinking registering a unique ID for the notification itself makes more sense...

Thoughts?

--
A-Ron

**Comment by asmagill** [comment]
Oh, and another benefit of this approach would be that, since we're ditching cross-compatibility with Mjolnir, I may also be able to get it to wait until after init.lua is done so that we can handle activated notifications which launch Hammerspoon if it is not currently running... will have to see how difficult this is since it relies on the applicationDidFinishLaunching: method in the application class that implements the NSApplicationDelegate protocol.

**Comment by cmsj** [comment]
I'm not sure I'd ever use those additional callbacks, but someone will want to, so if we can add it fairly simply, I'd say lets do it :)

+1 dispatching the callbacks from Lua. Much less risky!

Thanks :)

**Comment by cmsj** [comment]
@asmagill I'm wondering if we can figure out a fix for the crash here, separately from refactoring/rewriting the extension (this is our top crasher atm, but not dramatically so)

**Comment by cmsj** [comment]
I've been digging into this and the issue is that the NSUserNotification object is being over-released (verified with the Zombies feature of Instruments.app).

However, what I haven't yet figured out is why it's happening!

I do have a very reliable reproduction method though, which is to do a :new():send():release() chain. It crashes pretty much every time. 

So it seems like the crash happens when release()/__gc is called before the notification has been delivered.

**Comment by cmsj** [comment]
ok, so I seem to be able to stop it from crashing, although I have a suspicion that we might now be leaking NSUserNotification objects.

@asmagill something I'm curious about, is why did/shouldDeliverNotification have:

    thisNote->note = (__bridge_retained void *) [notification copy];

in them - does the delegate protocol expect that the notifications are going away, and thus reduce their refcount?

I'm going to commit what I have, because leaking a few hundred bytes each notification, if that's what we're doing, seems vastly preferable to crashing :)

**Comment by asmagill** [comment]
IIRC this was added because the notification object which is sent to each method of the delegate is not the same actual object that was originally sent -- in order to check flags of the notification directly (deliveredTime, etc.) we have to replace the stored copy in the lua userdata; otherwise the lua methods report old information.

I'll look at your changes tonight and see how they impact my current work -- I'm about halfway to redoing things with most of the logic being handled in Lua... however, the delegate methods haven't changed much, so I'll appreciate any updates or corrections to the current base.  I still want to move forward with my current changes because they pave the way for allowing callback functions to work even after a reload or restart.

--
A-Ron

**Comment by cmsj** [comment]
@Asmagil ah, good point about the [ copy] thing.

Please do keep going on yours, my interest here is an emergency band aid to prevent crashing, I'd still love to see a shinier version of the module :)

Btw, I did some testing with Instruments.app and I think that my "fix" probably doesn't cause a leak. If I do a :new():send():release() it registers no leak. It does if I skip the :release(), which seems odd because I would have expected the __gc to take care of it (and I think it does), so maybe it just means that Instruments can't cope with objc losing all refs to the NSUserNotification while Lua has one.
