### ISSUE TITLE
Crash - hs.json

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2020]
Crashlytics: http://crashes.to/s/ca58e8e2677

```
crash_info_entry_0: abort() called
crash_info_entry_1: *** error for object 0x608000638100: Invalid pointer dequeued from free list
```

**Comment by latenitefilms** [comment]
This crash seems to be happening here:

**Source:** https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/json/internal.m#L75
```objc
 if (obj) {
            [[LuaSkin shared] pushNSObject:obj] ;
            return 1;
        } else {
            lua_pushstring(L, [[error localizedDescription] UTF8String]);
            lua_error(L);
            return 0; // unreachable
        }
```

Maybe a bug in LuaSkin's translation of the `NSObject`?

**Comment by asmagill** [comment]
Without seeing the json string that it's trying to decode, it's hard to say for certain... I do find it odd that we're testing `obj` and assuming if it's not nil then `error` must be...  it's been a long long time since I worked on the json module, but if I were coding it today, I would have done something like:

~~~objc
    if (error) {
        return luaL_error(L, "%s", [[error localizedDescription] UTF8String]);
    } else if (obj) {
        [[LuaSkin shared] pushNSObject:obj] ;
        return 1;
    } else {
        return luaL_error(L, "json input returned nil") ;
    }
~~~

Is this a one-off or is it worth making these changes to see if they make a difference? The documentation from Apple for `NSJSONSerialization JSONObjectWithData` does state:

> Return Value
>
> A Foundation object from the JSON data in data, or nil if an error occurs.

so maybe when this was written I (or whoever wrote the original; I think I may have just ported it from Mjolnir to Hammerspoon) took that as gospel...

**Comment by latenitefilms** [comment]
This was just a one-off crash as far as I can tell, so it could be yet another timing issue, when restarting Hammerspoon/CommandPost, or it could have just been malformed JSON data - not sure.

I've pushed some code changes, but it'll need reviewing to make sure I haven't screwed anything up.

Thanks team!
