### ISSUE TITLE
hs.mouse.set should also have a paramater to pass the screen

### ISSUE THREAD

**Issue by deepumukundan** [Hammerspoon/hammerspoon#206]
When in a multi monitor environment, it will be easier to move the mouse to active application's screen using hs.mouse. But currently it will only move the cusrsor inside the main display monitor.

**Comment by cmsj** [comment]
It is actually possible to move the pointer to a different monitor at the moment - the x/y co-ordinates are relative to the entire display, so if you had two 1920x1080 monitors, setting {x=1920,y=0} would actually place it on the top left corner of the right monitor (because the left monitor would be 0-1919, the right monitor would be 1920-3839).
To illustrate this, you can display the co-ordinates of the top left of each monitor with this snippet in the Hammerspoon Console:
    `hs.fnutils.each(hs.screen.allScreens(), function(monitor) rect=monitor:fullFrame() ; print(monitor:name().." x:"..rect["x"].." y:"..rect["y"]) end)`

However, I do think we can improve the hs.mouse API to be easier to use with screens. Certainly the docs for .get()/.set() need to be improved to reflect what they actually do. I'll start with that, and then think about what we can add by way of convenience functions that help people deal with the cursor in relation to physical monitors rather than the single virtual display that's rendered across them :)

Thanks for the bug report!

**Comment by deepumukundan** [comment]
Thanks Chris. With the new implementation and the ability to pass screen, I was able to set the mouse exactly where I wanted it!
