### ISSUE TITLE
Could a global isAnimating() function be exposed?

### ISSUE THREAD

**Issue by jdtsmith** [Hammerspoon/hammerspoon#2079]
I have a Spoon [SplitView](https://github.com/jdtsmith/SplitView) which automates opening two windows in side-by-side split view.  It works by directly pressing on buttons.  I have it working well for both primary (hard) and secondary (harder) screens.  For the latter, this required making use of the Dock's accessibility buttons (e.g. the "Add Space" button).  A typical operation might be:

1. Open Mission Control
2. Wait for it to build its accessibility tree (`hs.timer.waitUntil`)
3. Find and press the Dock's "add space" button
4. Wait a bit for the new space to appear, and then hit ESC
5. Wait a bit and long-press the green zoom button (after hiding all other apps/wins)
6. Wait a bit and click on the RHS of the screen
7. Wait a bit and restore all the hidden apps/wins

All of the _waiting a bit_'s come down to hand-tuned delays, or order 0.1-1 second.  Most of them are of the category _waiting for an animation provided by Mission Control to finish_.  Spaces has an `isAnimating()` function, but it is very specific and doesn't cover other types of animations.  If there were a generic `isAnimating()` that covered other screen/window/mission control/etc. animations, it would be far easier to just wait for those to complete before proceeding, without having to hand-tune delays and risk breakage.  Any chance there is somewhere more generic to tie into?

Thanks for Hammerspoon; it's a fantastic tool.

**Comment by latenitefilms** [comment]
Rather than hard-coding in delays, can you add in checks to wait until an AX item is created, destroyed or changed value?

**Comment by jdtsmith** [comment]
In some cases I do that.  For example, the close ‘X’s on the small desktop spaces at the top of MC and associated `doRemoveDesktop` method don’t appear until MC is fully loaded.  So I can wait for that (step 2 above).  But AFAIK there is no generic accessibility context for windows, menu bars, etc, so you have to go application by application.  And some things, e.g. split view, don’t have any accessibility context I can find.  Maybe it’s possible to find a few more things to wait on, but the usual idea is “wait for this animation to complete” so a generic method would be powerful.

**Comment by latenitefilms** [comment]
Looking at `hs._asm.undocumented.spaces`, it looks like the `isAnimating()` function is using the undocumented `CGSManagedDisplayIsAnimating` - which seems to be only related to Spaces.

I've tried Googling around, and I can't see any other method for detecting macOS animations sadly.

Maybe @asmagill has some ideas however?

In regards to step 4, rather than "waiting a bit", you could just wait until the new `AXButton` appears for the new space?

In regards to step 5, rather than "waiting a bit" you could just wait until the Mission Control app is closed?

In regards to step 6, this is a little bit hard to test without jumping into code, but it looks like the screen becomes a single `AXWindow` object by Finder? You could wait until this `AXWindow` is the same size as the screen it's on?

I use [UI Browser](https://pfiddlesoft.com/uibrowser/) for navigating the Accessibility trees for applications - I find it more useful than Xcode's own Accessibility Inspector.

<img width="771" alt="Screen Shot 2019-04-24 at 11 01 58 am" src="https://user-images.githubusercontent.com/22286696/56625668-ac5b7500-6681-11e9-9d3e-56a2efe25261.png">
<img width="784" alt="Screen Shot 2019-04-24 at 11 09 32 am" src="https://user-images.githubusercontent.com/22286696/56625691-c6955300-6681-11e9-950f-9f822a1a4821.png">

Also, these two CommandPost extensions might be of interest:

- [`cp.just`](https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/just/init.lua)
- [`cp.rx`](https://github.com/CommandPost/CommandPost/tree/develop/src/extensions/cp/rx)

**Comment by jdtsmith** [comment]
Thanks, some good ideas.  I've just been outputting `buildTree` results and formatting in Emacs and diffing with `git diff --no-index --word-diff --color-words`.  Your extensions look very interesting.  Callback hell is quite real with Lua at the moment.  I found myself really missing Javascript's various Promises interfaces, especially the handy new built-in `async` keyword (truly magic).  How do your extensions work at a low level?  Using `hs.timer.waitUntil`?  What's an appropriate check interval?  

BTW, `Mission Control` doesn't seem to be a real application, but rather a "Docklet".  As such it doesn't actually open and close, and you interface with it via the Dock's accessibility UI, which updates with MC is open.  I also haven't found any exposed AX interfaces (on Dock or elsewhere) when invoking Split View, which seems to run something else altogether.   

I'll report back if I manage to use accessibility waiting to remove any hard-coded delays.

**Comment by latenitefilms** [comment]
Yes, both `cp.just` and `cp.rx`(in `cp.rx.go.Statement`) use `hs.timer` internally.

If you have a look at CommandPost's [code](https://github.com/CommandPost/CommandPost/tree/develop/src) - we use both these extensions extensively. We also have [`cp.ui`](https://github.com/CommandPost/CommandPost/tree/develop/src/extensions/cp/ui) which adds a Lua interface to AX objects.

[`cp.ui,axutils`](https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/ui/axutils.lua) might also be of interest to you.

Yes, sorry, Mission Control is not a standalone application. You could however use [`hs._asm.axuielement.observer`](https://github.com/asmagill/hs._asm.axuielement/blob/master/Reference_Observers.md) to detect when the "Mission Control" `AXGroup` is created or destroyed.

**Comment by jdtsmith** [comment]
What a major codebase!  I took a look at the plugins and learned a few things.  I haven't used Observers, but your prodding has produced some good results that should eliminate most if not all hard-coded delays; I'll report back when I have them working.  In the meantime, I wonder if you'd be willing to use UIBrowser during the middle of a SplitView operation (I don't have that tool)?  Long click on green button, then collect UI data from one of the miniature windows on the other side of the screen.  I haven't managed to find anything with e.g. `ax.systemElementAtPosition`, and since I don't know what application if any is controlling SplitView, I can't figure out how to find accessibility controls for the SplitView interface (or even if it has any).

**Comment by jdtsmith** [comment]
Well that's frustrating.  By comparing the full trees before and after, I had identified the `fullScreen` attribute as a likely candidate to eliminate hard-coded delays, as both windows of the SplitView go from `false` to `true` in this.  But it turns out, that attribute is set _as soon as the operation commences_, before the animation occurs.  I.e. too soon. The frame is also set to be its target value before the animation occurs.  So sadly I just can't find a way to "wait" for the animation to be complete in terms of accessibility availability.

**Comment by jdtsmith** [comment]
> Yes, sorry, Mission Control is not a standalone application. You could however use [`hs._asm.axuielement.observer`](https://github.com/asmagill/hs._asm.axuielement/blob/master/Reference_Observers.md) to detect when the "Mission Control" `AXGroup` is created or destroyed.

Can you comment on how to do this?  It seems the observer needs an existing accessibility object to observe, so I'm having trouble seeing how you could request notification of a new `AXGroup` coming into existence. Maybe I'm missing something simple.  Thanks.

**Comment by latenitefilms** [comment]
@jdtsmith - Unfortunately it seems that the Dock doesn't actually produce many notifications, which is annoying.

Using this code:

```lua
ax = require("hs._asm.axuielement")
dock = hs.application("Dock")
dockAX = ax.applicationElement(dock) 
o = ax.observer.new(dock:pid())
    :callback(function(...) print(hs.inspect(table.pack(...), { newline = " ", indent = "" })) end)

for _, notification in pairs(ax.observer.notifications) do
    local status, err = pcall(function() o:addWatcher(dockAX, notification) end)
    if not status then
        --print(string.format("Failed to add notification observer for: %s", notification))
    else
        print(string.format("Added notification observer for: %s", notification))
    end
end    
    
o:start()
```

...the only notifications you can observer for the Dock Application AX are `AXFocusedUIElementChanged`, `AXUIElementDestroyed`, `AXSelectedChildrenChanged` and `AXCreated` - however none of them seem to trigger when Mission Control is activated.

I was HOPING that when Mission Control is activated some `AXCreated` notifications would trigger.

The notifications I'm seeing are:

- `AXSelectedChildrenChanged` when you hover over a dock icon or Mission Control thumbnail.
- `AXUIElementDestroyed` when you close Mission Control. There's also a `AXSelectedChildrenChanged` notification when Mission Control closes.

However, this doesn't actually matter, as in your case, you're manually triggering the showing of Mission Control, so we can request the AX elements when you launch it. For example:

```lua
hs.application.launchOrFocus("Mission Control")

ax = require("hs._asm.axuielement")
dock = hs.application("Dock")
dockAX = ax.applicationElement(dock) 

print(string.format("Dock Children: %s", hs.inspect(dockAX:attributeValue("AXChildren"))))
print(string.format("Dock Group Children: %s", hs.inspect(dockAX:attributeValue("AXChildren")[2]:attributeValue("AXChildren"))))
print(string.format("Dock Group Children: %s", hs.inspect(dockAX:attributeValue("AXChildren")[2]:attributeValue("AXChildren")[1]:attributeValue("AXChildren"))))
print(string.format("Dock Group Children: %s", hs.inspect(dockAX:attributeValue("AXChildren")[2]:attributeValue("AXChildren")[1]:attributeValue("AXChildren")[1]:attributeValue("AXChildren"))))
```

FYI - You might find these tools helpful for messing around with GUI Scripting: [cp.dev](https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/dev/init.lua)

In regards to [UI Browser](https://pfiddlesoft.com/uibrowser/), it has a fully functional free trial, so I highly recommend checking it out.

Also... sometimes you just have to hard code in delays to make GUI Scripting work. However, rather than guessing times, something you can actually find out how long things should take. For [example](https://developer.apple.com/documentation/appkit/nswindow/1419655-animationresizetime?language=objc):

> The NSWindow implementation uses the value from the NSWindowResizeTime user default as the time in seconds to resize by 150 pixels. If this value is unspecified, NSWindowResizeTime is 0.20 seconds (this default value may be different in different releases of macOS).

Hope this helps!

**Comment by jdtsmith** [comment]
@latenitefilms Thanks for all these suggestions.  I tried UI Browser, and discovered something quite bizarre, easily seen with this code running during a SplitView operation:

```lua
ax=require("hs._asm.axuielement")
timer=hs.timer.doEvery(2,
		       function()
			  hs.console.clearConsole()
			  local mp=hs.mouse.getAbsolutePosition()
			  local b=ax.systemElementAtPosition(mp)
			  if not b then return end
			  print(b,hs.inspect(b:allAttributeValues()))
end)
```

During the middle of a Split View (after long-pressing the green button but before selecting a companion), `systemElementAtPosition` absolutely _knows_ where all the miniature versions of the windows on half the screen are located!  When you mouse in and highlight one of those mini windows, it reports the correct window.  

But here the bummer: it returns `AXWindow` objects that have their original, incorrect `frame`, `position`, `size`, etc. attributes.  But somehow it still knows where they are.  It's like coordinate positions are being translated at some lower level.  `systemWideElement()` doesn't have any particular content I can see.  So I have no idea how it knows what it knows.  But I could cut out most of the hand-coded timing non-sense if I could invert the operation that `systemElementAtPosition()` performs in the above snippet.  I.e. it tells me which (minified) window is at a given mouse position, and I'd like to ask the reverse: at what position a given small-representation window is!  I even considered a desperate measure like tiling half the screen window every 50 pixels to search for the right window, but surely there must be a less hackish way to go in reverse.  Thanks for any ideas!

**Comment by jdtsmith** [comment]
In case anyone is tuning in here, I managed to remove all the timing delays but two by completely changing how `SplitView` works: in fact I did resort to (intelligently) tiling half the screen searching for the target window, with adaptive refinement until it is found.  You can search a few thousand positions if needed in just a couple seconds.  That would be an issue only for very high window counts.

One funny wrinkle: `systemElementAtPosition()` knows where the mini-windows are, but also gives spurious hits in a 5-10 pixel buffer zone around mini-windows (where the boundary would light up if your mouse were on it). This caused random failure since clicking in that buffer zone doesn't actually select the window. To fix this, I _refine_ the discovered position by searching a 3x3 grid around it, looking for mini-window edges and corners, and moving towards the interior. I could still use a solid `isAnimating()` method, but I've managed workarounds.  The fact that accessibility objects seem to be updated in most cases _before_ animations commence truly limits the utility of monitoring the ax tree for UI completion.
