### ISSUE TITLE
Add hs.webview.toolbar.get?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2109]
Currently when you use `hs.webview.toolbar.new` you need to assign each toolbar object with a unique name. However, currently there's no way to check that name isn't already in use.

**Comment by latenitefilms** [comment]
Thoughts on this @cmsj & @asmagill ? This should be an easy issue to address?

**Comment by latenitefilms** [comment]
FYI: I tried doing this myself, but failed, so will have to leave to someone smarter to tackle.

**Comment by asmagill** [comment]
What exactly are you wanting? To get a toolbar object based on it's identifier (or nil, if it doesn't exist)? Or just a way to see if a specific identifier is already in use?

Not sure how to do the former, but the later would be simple since we track in-use identifiers in `identifiersInUse` in the `toolbar_internal.m` file.

**Comment by latenitefilms** [comment]
@asmagill - Awesome, thanks! I'll have another look at this and see what I can come up with.

**Comment by asmagill** [comment]
Take a look at the constructor for the module, around line 808 of `toolbar_internal.m` -- basically you could return true or false based on `[identifiersInUse containsObject:identifier]` which is what we check when creating a new toolbar.
