### ISSUE TITLE
Network (http, ping) extension

### ISSUE THREAD

**Issue by nocivus** [Hammerspoon/hammerspoon#219]
It would be nice to be able to access the network via the app.

This would allow things like checking whether your internet connection is working (by pinging a certain server, for instance), requesting data from the internets, etc.

**Comment by cmsj** [comment]
Agreed, these would be useful to have. Thanks!

**Comment by asmagill** [comment]
At what level of abstraction?

We can already access things like ping, curl, etc. via the builtin io.* functions, though some wrappers in lua would be nice...

I've got a start on a HTTP request module that would support SSL, Authentication, Cookies, etc., but ran into problems with it not being cancelable or surviving a restart without a crash, so put it on the back burner while I worked on some other things.  A wrapper to curl via io.popen() would probably be simpler, though.

I've also given some thought to writing a module to support NSPipe in preparation for an NSTask module -- the NSPipe portion would allow direct connection to sockets, both local and remote..

While I am totally onboard with wanting network access, let's throw around some use cases and see which approaches we might consider...

To start:

use HTTP(S) to query web services that return XML or other formatted data

retrieve files via HTTP(S)/FTP/SSH, etc.

receive Bonjour (Avahi/ZeroConf) announcements filtered by type/hostname that trigger a callback... maybe send some announcements of our own too?

ping with a callback when it succeeds (or fails? makes sense for a oneshot, though when it transitions makes sense if it hangs around) so we can tell when a specific machine is available/not available or when the internet is available/not available.  Might need to look closer at how Apple detects when you've got to log in via a portal to prevent false readings... I know they do at least a few HTTP GETs to various of their servers, but I think it checks other stuff as well, in case DNS is slow or transparent proxies intercept traffic.

open a socket and listen (similar to what netcat can do), then call a Lua function when something actually connects to it

smb?

Most of this could be done via scripts or command line calls with Lua wrappers, but we should probably decide up front which deserve a obj-C module for completely internal handling... The listening and responding to sockets via NSPipe is a good example where that makes the most sense, I think...

**Comment by nocivus** [comment]
The reason i suggested this was because both approaches i tried when doing a ping don't quite measure up. With apple script like this, i can't seem to get the result (i get nil instantly, like it doesn't care about the result of the script):

```
local succcess, result = hs.applescript.applescript([[
>> repeat with i from 1 to 2
>>   try
>>     do shell script "ping -c 1 google.com"
>>     set r1 to true
>>     exit repeat
>>   on error
>>     delay 5
>>     if i = 2 then set r1 to false
>>   end try
>> end repeat
>> set r2 to r1]])
hs.alert.show(success)
hs.alert.show(result[0])
```

With io.* i tried this, and it turns out to be super slow :(

```
function os.capture(cmd, raw)
  local f = io.popen(cmd, 'r'))
  local s = f:read('*a')
  hs.alert.show(s)
  f:close()
  if raw then return s end
  s = string.gsub(s, '^%s+', '')
  s = string.gsub(s, '%s+$', '')
  s = string.gsub(s, '[\n\r]+', ' ')
  return s
end
os.capture('ping -c 1 google.pt')
```

**Comment by cmsj** [comment]
@asmagill some interesting ideas there.

I'm a little bit on the fence about the shelling-out argument, but I think what's troubling me the most is that it, unless I'm missing something, it makes the calls blocking (at least until we have an NSTask extension). I like that it means a lot less code for us to maintain, but it feels more rigid and fragile.

I hadn't really thought things through beyond implementing an HTTP client, which I was intending on doing using AFNetworking, starting out with little more than very simple GET/POST calls. Something roughly like:

```
AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
[manager GET:@"SOME_URL_HERE"
  parameters:nil
     success:^(AFHTTPRequestOperation *operation, id responseObject) {
    // lua_pcall() to the user's specified success callback
} failure:^(AFHTTPRequestOperation *operation, NSError *error) {
    // lua_pcall() to the user's specified failure callback (or maybe just have one callback that has a success/failure parameter
}];
```

It's an interesting balance. On the one hand it means adding another framework and increasing the size of our codebase, but I think the huge huge benefit is that we get a really simple onramp and lots of flexibility later if we want it.
The objc part of an httpclient extension would be tiny to start with, because AFNetworking has already solved all of the quirks we'd run into. However, further down the road, we could extend the extension very significantly when we need more request types, cancellation of requests, etc, etc.


To speak to some of your other suggestions:
 * I love the idea of having an HTTP server, that leads to all sorts of fun possibilities in extending the IPC mechanism into mobile apps, IFTTT webhooks, etc, etc.
 * Bonjour notifications would be very cool. I have written a little bit of Bonjour related code before, but on Linux (so against Avahi) and it was a hellish nightmare ;)
 * Doing anything with SSH/SFTP scares me because a good ssh config is complex and behaves in very subtle ways that ssh libraries/frameworks are never able to express. Maybe the simple 80% case is sufficient though.
 * ping with callbacks seems like an interesting idea, but I'm not sure if we can do it properly - I haven't checked if OS X requires one to be privileged to construct the raw sockets required. I note that ping(1) doesn't seem to be setuid, so there is hope :)
 * Reachability - seems like a useful thing to have, SCNetworkReachability should make it fairly simple
 * smb - I think having this in objc seems like a terrible idea :D (I would argue it makes much more sense to instruct Finder to mount an smb share and then walk it like a normal filesystem)

**Comment by dereulenspiegel** [comment]
As a new user to Hammerspoon I also missed HTTP support. So I started to develop an extension (https://github.com/dereulenspiegel/hammerspoon/tree/http). Currently only synchronous requests are supported and more testing is needed, but for my current use cases (interfacing with my home automation) it seems to work fine. Also no new library was added to the code base. Let me know what you think and if you would like to integrate the extension.

**Comment by Habbie** [comment]
That's some awesome work! Right now I feel the synchronous nature of your implementation would be a problem, unless @cmsj feels sync is better than having nothing at all :)

**Comment by dereulenspiegel** [comment]
It should be pretty easy to also create an async version where you can specify two callbacks (one for success, one for exceptions), but since I'm new to Objective-C and to Lua, I wanted to create something simple that works. For my scripts synchronous execution is fine.
After I documented the Lua parts of my extension I will have a look at how to call callbacks from C.

**Comment by nocivus** [comment]
Hi Till, how can i install you extension?

**Comment by dereulenspiegel** [comment]
Hi nocivus,

I don't if this is the easiest way, but you can clone my fork, checkout the http branch and then execute make in the cloned repo.
After that you can copy the extension from build/Hammerspoon.app/Content/Resources/extensions/hs/http to your Hammerspoon app directory. Then restart Hammerspoon and the extension should work. Currently there are no public builds for this.

**Comment by nocivus** [comment]
K, will try, thanks :)

Till Klocke wrote:

**Comment by nocivus** [comment]
Build currently fails at this shell command:

find . -type f \( -name '*.lua' -o -name '*.m' \) -not -path '*/sample-extensions/*' -not -path './build/*' -not -path './extensions/.build/*' -exec cat {} + | scripts/docs/bin/gencomments | scripts/docs/bin/genjson > build/docs.json

error: couldn't find module for  (Produce human-readable representations of Lua variables (particularly tables)) (This extension is based on inspect.lua by Enrique García Cota
https://github.com/kikito/inspect.lua)

Does it build on your machine?

**Comment by dereulenspiegel** [comment]
On my machine I was able to build the project just a few minutes ago. Does the master branch fail with the same error message?

**Comment by nocivus** [comment]
Master branch builds fine.

Till Klocke wrote:

**Comment by dereulenspiegel** [comment]
Ok, if I understand the build system correctly this failure happens when code comments are scanned for documentation and documentation is generated from these comments. 
I had a similar error because Sublime Text generated some (binary?) files in the extension folder which matched the find expression but weren't parseable. Probably something similar happend on your machine.

**Comment by nocivus** [comment]
I'm using XCode, and can't seem to find any weird files anywhere in the extensions folder :(

Till Klocke wrote:

**Comment by nocivus** [comment]
The text it complains about is in this file: inspect/init.lua

**Comment by nocivus** [comment]
Oh well, I'll just comment out the Makefile line that builds the docs.

**Comment by nocivus** [comment]
Can you post an example usage of the extension?

**Comment by dereulenspiegel** [comment]
Interesting, I didn't change anything in the inspect extension. 
Using the extension is pretty easy. A few hours ago I pushed additional documentation. But you can simply do
````
status, data, headers = hs.http.get("http://example.com")
````

**Comment by cmsj** [comment]
@nocivus The build failure might be related to the required Ruby Gems for building the docs, but I wouldn't worry too much, commenting out the docs bit of the Makefile is fine :)

(Unless you want to be building from the command line a lot, in which case we should dig into what's going on, but we should do that in a new, separate Issue please :)

**Comment by cmsj** [comment]
@dereulenspiegel looking good so far, thanks! I do think that we should shoot for async though. We already have one or two synchronous calls in our API and I think it's a bad idea to proliferate the concept any further.

Having said that, I would think it would be fine to have sync API in addition to async, for the http module, so long as we discourage the use of the sync calls in the docs :)

**Comment by asmagill** [comment]
I'm glad to see someone pick up the mantle on this... I do hope you have better luck than I did trying to get async to work properly when HS is restarted or quit before the callback occurs... I think we have better cleanup and error catching code in place now that should help as well.

My thoughts on  synchronous use is that at present, it's better than nothing, so I would vote for.  How hard would it be to put a user setable time out as an additional option parameter?  I can think of cases where I'd use it to query the state of home automation or similar and if it doesn't respond within a couple of seconds or so, it's down, whereas downloading something or retrieving a news page for parsing would obviously require a larger timeout value.

At any rate, looks good so far and I look forward to seeing how this evolves!

--
A-Ron

**Comment by nocivus** [comment]
Hey Till, when i try these as the last lines of my config:

    status, data, headers = hs.http.get("http://example.com")
    hs.alert.show(status)
    hs.alert.show(data)

I get "0" and empty in the alert boxes. Am i doing something wrong?

**Comment by dereulenspiegel** [comment]
Looks ok so far. I'm currently working on the async support, but the synchronous calls should still be working. 0 as a status code could be something coming from the NSUrlConnection. I have to look at the docs.

**Comment by dereulenspiegel** [comment]
I updated my fork with async methods and error reporting for these methods. It seems to work. I hope that this version works better now.
If you think that this extension can live up to the necessary standards I will create a pull request.

**Comment by asmagill** [comment]
Add the following to the top of init.lua or internal.m to get doc building to work...

--- === hs.http ===
---
--- Primitive http requests

(change --- to /// if in internal.m, and expand description in any way you like)

I'll try and dig out my torture tests that kept me from releasing my initial attempts at async http later tonight and test, but so far it looks promising...

**Comment by asmagill** [comment]
Ok, poking closer, and reviewing the code closer, I notice that no garbage collection is done regarding outstanding callbacks if Hammerspoon is exited or restarted (reload config)...  thus the following:

     a = function(...) print(inspect(table.pack(...))) end
     hs.http.asyncGet("http://10.0.0.99",{},a)

(or any ip address that doesn't exist on your network) followed by a "Reload config..." or `hs.reload()` within the 60 seconds it takes for this to timeout results in a crash of Hammerspoon.

This is the part that caused me problems as well...

Having a user setable timeout (rather than the default of 60 seconds) will mitigate this somewhat as except for a total network disconnect, one can usually guesstimate what a reasonable response time is before assuming failure, but ultimately, this should be addressed.

**Comment by asmagill** [comment]
Ok... I have found a way that seems to protect against callback crashes after a reload, but it requires removing the static declaration to MJLuaState in MJLua.m.

Then, change the callback functions in the URL delegate to something like this:

    - (void)connectionDidFinishLoading:(NSURLConnection *)connection {
      lua_State* L = self.L;
      NSString* stringReply = (NSString *)[[NSString alloc] initWithData:self.receivedData encoding:NSUTF8StringEncoding];
      int statusCode = [self.httpResponse statusCode];
        extern lua_State* MJLuaState ;

        if (self.L == MJLuaState) {
            lua_rawgeti(L, LUA_REGISTRYINDEX, self.fn);
            lua_pushinteger(L,statusCode);
            lua_pushstring(L,[stringReply UTF8String]);
            createResponseHeaderTable(L,self.httpResponse);
            int cbRes = lua_pcall(L,3,0,0);
            if (cbRes != LUA_OK){
              NSString* message = [NSString stringWithFormat:@"%s Code: %d", @"Can't call callback", cbRes];
              showError(L, message);
            }
        } else {
            NSLog(@"Active LuaState does not match callback LuaState... lua restarted?") ;
        }
    }
    - (void)connection:(NSURLConnection *)connection
      didFailWithError:(NSError *)error {
        NSString* errorMessage = [NSString stringWithFormat:@"Connection failed: %@ - %@", [error localizedDescription], [[error userInfo] objectForKey:NSURLErrorFailingURLStringErrorKey]];
        extern lua_State* MJLuaState ;

        if (self.L == MJLuaState) {
            lua_rawgeti(self.L, LUA_REGISTRYINDEX, self.fn);
            lua_pushinteger(self.L,-1);
            lua_pushstring(self.L,[errorMessage UTF8String]);
            lua_pcall(self.L,2,0,0);
        } else {
            NSLog(@"%@", errorMessage) ;
            NSLog(@"Active LuaState does not match callback LuaState... lua restarted?") ;
        }
    }


I don't like the change from static to non in MJLua.m, though, because it means an external module could really screw things up with something as simple as:

    extern lua_State* MJLuaState ;
    MJLuaState = NULL ;

If this fix for catching restarts in callbacks is approved, then I recommend instead that we add a function to MJLua.m which either takes an argument (L) and compares it against the local static MJLuaState returning a boolean, or a function which returns the value of MJLuaState, thus making it effectively read-only outside of the Hammerspoon core.

**Comment by cmsj** [comment]
@asmagill I'm not opposed to the idea of some core functions to inspect the MJLuaState, but I'm a little surprised we need that - I've not had a chance to closely examine the http extension yet, but would we not just call [NSURLConnection cancel] for each open connection in __gc methods?

**Comment by dereulenspiegel** [comment]
Exactly. Currently I cancel all NSUrlConnections in the gc method and dereference all callback methods. Yesterday I only did a quick test, but at least doesn't seem to break anything. But of course needs testing, especially in edge cases like restarting hammerspoon.

**Comment by asmagill** [comment]
I never did get cancel to work reliably with restarts, but if you have, I look forward to seeing the code.

**Comment by dereulenspiegel** [comment]
I don't now if the cancelation really works. But additonally I'm dereferencing the callback methods and make sure that the callbacks in the delegate don't try to call any lua callbacks. This should be sufficient. Could you probably explain how you exactly simulate edge cases like restarting? Have created a http server implementation which delays requests? Or do we have some form of automated testing for this?

**Comment by asmagill** [comment]
The simplest test I've got is to type the following into the Hammerspoon console and then wait about 60 seconds for it to time out:

    a = function(...) print(inspect(table.pack(...))) end ; hs.http.asyncGet("http://10.0.0.99",{},a) ; hs.reload()

Change 10.0.0.99 to some ip address that does not exist on your network but is in the same subnet (i.e. the first three numbers are the same) -- it's not sufficient for it to be a machine that isn't running an http server -- that responds immediately with a no connection error; instead we need it to timeout.

(the hs.reload() simulates selecting "Reload Config...")

**Comment by dereulenspiegel** [comment]
This test looks fine. I can't see any crash or error in the console and the callback is never called, just as expected. Although I admit that this test is probably not completely sufficient. Since the request times out after a quite long time and we immediately reload after the request has been fired we never run into a situation where Hammerspoon is reloaded as the delegate is putting parameters on the stack or the function pointer is set to LUA_NOREF after we already referenced the function and put it on stack.

**Comment by cmsj** [comment]
I guess another good test would be what happens if you hs.reload() in the middle of a long download

**Comment by dereulenspiegel** [comment]
This shouldn't break anything since there are no lua invocations while downloading. The only problem with large downloads could be that I keep everything in memory. But I will try and test it.

**Comment by cmsj** [comment]
@dereulenspiegel also, I wouldn't worry too much about the stack being constructed while hs.reload() is happening, or similar things - pretty much everything is happening on the main thread (which is something worth checking with the http extension, its callback handler should happen on the main thread. There's an example in extensions/wifi/watcher.m of how to use a callback wrapper that executes the real callback on the main thread, if this is an issue (I'm not sure offhand what the threading model of NSURLConnection is)

**Comment by asmagill** [comment]
FWIW, I confirm the latest changes don't crash with my tests.

**Comment by cmsj** [comment]
Woot! I'll try and get it reviewed soon (I'm in the last few days of my silly time crunch), but I think I'd also be happy with landing it based on a +1 from @asmagill :)

**Comment by dereulenspiegel** [comment]
Sounds great. I created a pull request with my current state of the extension for review. So it can be merged whenever you guys feel comfortable to.

**Comment by cmsj** [comment]
Apologies for the slowness. hs.http has landed on master and will be in 0.9.30 :)

**Comment by dereulenspiegel** [comment]
Very cool. Looking forward to moving back to a release version of Hammerspoon :)

**Comment by nocivus** [comment]
Hi guys, i'm still getting status 0 and empty response data for any requests i make. Any ideas? Thanks!

**Comment by cmsj** [comment]
@nocivus I'm guessing you're running 10.11? The new App Transport Security rules block http connections by default. I'll add the relevant exception to our Info.plist to allow insecure connections.

(If you test with https://google.com, do you get a 200?)

**Comment by nocivus** [comment]
Still 0 with https.

And yes, El Capitan beta 7.

**Comment by cmsj** [comment]
@nocivus odd. do you perhaps have an old version of the extension hanging around in ~/.hammerspoon/ ?

**Comment by nocivus** [comment]
Nope :)

ls -la ~/.hammerspoon/
total 16
drwxr-xr-x 3 void staff 102 18 Fev 2015 .
drwxr-xr-x 23 void staff 782 21 Ago 11:15 ..
-rw-r--r-- 1 void staff 5147 21 Ago 13:00 init.lua



Chris Jones wrote:

**Comment by cmsj** [comment]
@nocivus anything in Console.app when you do the hs.http.get()?

**Comment by nocivus** [comment]
I get this:

21/08/15 15:31:22,421 Hammerspoon[977]: 
tcp_connection_destination_perform_socket_connect 177 connectx to 
216.58.210.110:443@0 failed: [64] Host is down
21/08/15 15:31:22,629 Hammerspoon[977]: 
tcp_connection_destination_perform_socket_connect 178 connectx to 
204.79.197.200:80@0 failed: [64] Host is down

first one is google.com, second is bing.com

in case you're wondering, i do have a working internet connection :)

Chris Jones wrote:

**Comment by cmsj** [comment]
I'm going to continue my support-by-guesswork theme by guessing that you use Little Snitch. That error is exactly what you'd see if LS is blocking Hammerspoon from making connections.

**Comment by nocivus** [comment]
Could be. I am in the middle of a little snitch upgrade. Finished 
installing but couldn't take the time to restart yet.

I'll give it a try and let you know. Thanks!

Chris Jones wrote:

**Comment by nocivus** [comment]
An LS rule was indeed the problem. Thanks a million! :)

Chris Jones wrote:

**Comment by junkblocker** [comment]
Currently I need to use the ``curl --interface`` command as the only way I know to force traffic through a certain interface. It would be good if ``hs.http`` had an option to do the same. Please let me know if that should go in a separate request.

**Comment by cmsj** [comment]
@junkblocker yes please, a separate Issue would be appropriate for that. It may not be possible at the high level of API we use in hs.http, but let's at least figure that out :)

I think `hs.http` and `hs.network.ping` address the requirements of this issue, so I am closing it.
