### ISSUE TITLE
[Catalina Only] Crash - MJConsoleWindowController.m line 74

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2206]
See: 
https://fabric.io/latenite-films/mac/apps/org.latenitefilms.commandpost/issues/8f59448c1c99b28d8d46e41d516e26d6/sessions/latest

@cmsj - Also, probably unrelated, but still interesting, the log file is filled with:

```
hs.window::snapshot: ERROR: CGWindowListCreateImageFromArray failed for windowID: 2006
```

...maybe `hs.window:snapshot()` is buggy in Catalina?

**Comment by latenitefilms** [comment]
Maybe related to the `snapshot()` errors:

https://stackoverflow.com/questions/57957198/how-to-trigger-screen-recording-permission-system-modal-dialog-on-macos-catalina/58142253#58142253

**Comment by cmsj** [comment]
I don't immediately understand why this would be crashing, we're just asking an NSTextView to scroll itself.

I did notice in the crash report that there's an info text of `Refcount overflow in NSResponder or subclass. Too many unbalanced -retains!` - @asmagill do you think that [this block](https://github.com/Hammerspoon/hammerspoon/blob/master/Hammerspoon/MJConsoleWindowController.m#L71) should be working from a weak reference to `self`? I'm struggling to imagine it's important, since we log a lot of stuff, all the time and I don't believe we've ever seen this crash before.

**Comment by Vladimir-Nn** [comment]
Got similar issues:
https://stackoverflow.com/questions/59141491/nsresponder-tryretain-crash

I also found one more on the web.

**Comment by Vladimir-Nn** [comment]
Finally, I did find the "reason" and the "solution". https://stackoverflow.com/questions/59141491/nsresponder-tryretain-crash

Please, let me know if there is any news.

**Comment by latenitefilms** [comment]
Amazing - thanks for sharing @Vladimir-Nn !

That Stack Overflow discussion is above my knowledge, but hopefully it gives @cmsj or @asmagill some ideas.

FWIW - the `hs.window:snapshot()` bug mentioned in the OP is just due to the fact that Catalina now requires "Screen Recording" permissions for `:snapshot()`, and is unrelated to the actual crash.

**Comment by cmsj** [comment]
@Vladimir-Nn we don't use the group item method, so I'm not sure how to make use of the info you discovered, unfortunately.

@latenitefilms FWIW Hammerspoon is in my screen recording permissions prefs, so perhaps someone said no the first time and now gets errors?

**Comment by latenitefilms** [comment]
@cmsj - Yes, I believe that's what's going on with the snapshot error, which I believe is unrelated to the crash. I'm still seeing the crash pop up on Fabric though - which also has the "Refcount overflow in NSResponder or subclass. Too many unbalanced -retains!" information.

**Comment by Vladimir-Nn** [comment]
@cmsj as I can see you have a crashlog.

Could you try to wrap calls in the crashed call stack into @autoreleasepool block?

Example: https://stackoverflow.com/a/59191049/1401067

**Comment by latenitefilms** [comment]
FWIW - we've now seen 102 instances of this crash over 48 users in Fabric, so something's still up with this issue.

As far as I can tell, the line of code that's causing the crash is:

```objc
[self.outputView scrollToEndOfDocument:self];
```

...which is odd. I'm guessing maybe it's only happening during reloads, and it's simply a timing issue?

@asmagill - Did @cmsj's [earlier message](https://github.com/Hammerspoon/hammerspoon/issues/2206#issuecomment-540437309) give you any ideas?

I wonder if the fix is something as simple as:

```objc
- (void) setup {
    self.preshownStdouts = [NSMutableArray array];
    MJLuaSetupLogHandler(^(NSString* str){
        if (self.outputView) {
            [self appendString:str type:MJReplLineTypeStdout];
            if (self.outputView.visible) {
                [self.outputView scrollToEndOfDocument:self];
            }
        }
        else {
            [self.preshownStdouts addObject:str];
        }
    });
    [self reflectDefaults];
}
```

Thoughts @cmsj ?

**Comment by asmagill** [comment]
Sorry for being late to the party... @cmsj, reviewing http://www.idryman.org/blog/2012/11/22/arc-best-practices-and-pitfalls/ suggests that yes, we should be creating a weak reference for use within the block and then checking and assigning it to a strong one within. Since the weak reference being nil pretty much would mean that Hammerspoon or the OS is crashing, I don't know that we need to do much within the else clause (except maybe log ***WTF?***)

@latenitefilms unless I'm missing something subtle, I'm not sure that that will help with the specific issue since we're pretty sure the object exists -- it's that the retain count has gone through the roof (according to the objc runtime environment).

- - -

Unrelated, mostly, but digging into this made me wonder... how does ARC treat `id` objects? `retain` and `release` are part of the `NSObject` protocol, which `id` objects don't (necessarily) have to follow, so... does that mean that the "sender" to `scrollToEndOfDocument:` is ignored by ARC? In our case, it doesn't matter since `self` is retained elsewhere, but it could potentially be an issue within some of our other modules where I at least have mostly been thinking of `id` and `NSObject *` interchangeably when the compiler didn't otherwise complain...

**Comment by asmagill** [comment]
Eh, forget my aside above (though if you know of an official statement, I guess go ahead and link to it, I'd be interested); ARC does seem to handle `id` ok... to see my tests, you can look at https://github.com/asmagill/hammerspoon_asm/blob/coroutineFriendly/extras/internal.m#L32-L95

**Comment by latenitefilms** [comment]
Ok... so looking at the Fabric logs properly again, this crash only seems to happen to Catalina users with Screen Recording permissions disabled.

I'm only seeing these crashes on Catalina, and I'm only seeing these crashes on CommandPost 1.0.4 and earlier (in [CommandPost 1.0.5](https://github.com/CommandPost/CommandPost/releases/tag/1.0.5) we added a setup screen that forces users to enable screen recording permissions).
 
<img width="1467" alt="Screen Shot 2020-03-07 at 5 16 22 pm" src="https://user-images.githubusercontent.com/22286696/76138035-af900180-6097-11ea-992d-522ab8357c77.png">

I'm not sure WHY it's crashing - but given every crash report has the same error messages inside, for example:

```lua
hs.window::snapshot: ERROR: CGWindowListCreateImageFromArray failed for windowID: 13423
```

...the lack of Screen Recording permissions seems to be the cause.

Are you on Catalina @asmagill ? If so, if you disable screen recording permissions I wonder if you can reproduce the crash?

**Comment by asmagill** [comment]
I'll see if I can reproduce this on my iMac (it's still Catalina) later tonight.

**Comment by asmagill** [comment]
@latenitefilms, multiple variations of something like the following running on my Catalina iMac doesn't crash... it doesn't matter whether Screen Recording is enabled or not.

~~~lua
a = {} 
for i,v in ipairs(hs.window.allWindows()) do table.insert(a, v:snapshot()) end
c = {}
for i,v in ipairs(a) do
    table.insert(c, hs.canvas.new{x=(i - 1) * 100, y = 100, h = 100, w = 100}
                             :appendElements({ type="image", image = v }):show())
    print(i)
 end
~~~

Is this similar enough to what you're doing with `hs.window:snapshot`?

- - -

@cmsj, regarding `[self.outputView scrollToEndOfDocument:self];`... what would happen if we sent `nil` instead of `self` as the argument? In most cases the "sender" is never actually used and is just a convenience for cases where a different class's object is sending the message and the receiving method needs to know the sender.

It *shouldn't* matter, but... since we're at a loss for other ideas, and one of the messages we're seeing is about unbalanced retains, I figured I'd throw it out there.

**Comment by latenitefilms** [comment]
Given we're now in a macOS Sonoma world - I'm going to close this for now.
