### ISSUE TITLE
Upgrade to Lua 5.4

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2217]
@cmsj & @asmagill - Not sure if you've seen this yet:

http://www.lua.org/work/doc/

**Comment by cmsj** [comment]
I have, and I'll apply the update when 5.4 is actually released. the `/work/` tree is for things they're still working on. AFAIK 5.4 just had an rc2 release a few days ago, so it probably won't be very long until it's out properly.

**Comment by latenitefilms** [comment]
Awesome! Generational Garbage Collection sounds really interesting - it sounds like they've switching from Incremental Garbage Collection by default to Generational Garbage Collection by default?

For anyone else playing along, here's some of the other main changes:

- new generational mode for garbage collection
- to-be-closed variables
- const variables
- userdata can have multiple user values
- new implementation for math.random
- warning system
- debug information about function arguments and returns
- new semantics for the integer 'for' loop
- optional 'init' argument to 'string.gmatch'
- new functions 'lua_resetthread' and 'coroutine.close'
- string-to-number coercions moved to the string library
- allocation function allowed to fail when shrinking a memory block
- new format '%p' in 'string.format'
- utf8 library accepts codepoints up to 2^31

**Comment by asmagill** [comment]
Well, 5.4 has entered rc1 status, so... we're going to have to consider if, when, and how soon.

**Comment by cmsj** [comment]
I usually aim to get new versions of Lua integrated into HS as soon as possible after the release, so unless there are any breaking changes in it, which it doesn't seem like there are, I'd go ahead whenever I notice the final release.

**Comment by asmagill** [comment]
Assuming the list above is complete (I haven't looked myself yet, though probably will this weekend), here are my thoughts on the ones that I think *may* impact us to some, albeit probably minor, ways:
* `const variables` -- ideally, depending upon how these work, we should replace any use of `ls.makeConstantsTable`, though this shouldn't be a high priority issue because I doubt anything will be broken if delayed
* `new implementation of math.random` -- it would be interesting to compare this to our implementation in `hs.math`... but not really an issue, just curiosity
* `new semantics for the integer 'for' loop` -- as long as the old syntax isn't broken, this shouldn't be an issue; but if it is, we'll need to dig them out and its likely to impact our users to a limited degree in their own configs as well
* `optional 'init' argument to 'string.gmatch'` -- will require changes to `hs.text` (which hasn't landed yet) to maintain parity... so note to self, look into this sooner rather than later
* `new functions 'lua_resetthread' and 'coroutine.close'` -- have to see if this impacts our recent addition of coroutine support... I don't *think* it should, but I wonder exactly what `coroutine.close` does and whether it will require changes to `hs.applicationYield`... again, note to self to investigate
* `utf8 library accepts codepoints up to 2^31` -- unless macOS provides some changes to NSString, I'm not sure `hs.text` can be easily updated to match this... however, I'm not sure how likely it is to be an issue anytime soon because a quick (though admittedly not thorough) googling indicates that mostly this just allows for supporting code points that are not official Unicode code points... Unicode is officially limited to the constraints of UTF16 and while UTF8 and UTF32 *can* theoretically support more, they *don't* to maintain parity with UTF16... so if this becomes an issue, I suspect it will be a while as we won't be the only ones...

Just my two cents thrown out there... with the possible exception of the `for` syntax, I don't think our users will even notice the switch... assuming the list is reasonably complete, that is.

**Comment by latenitefilms** [comment]
FYI: @asmagill  - incompatibilities with the Previous Version can be found here:

https://www.lua.org/work/doc/manual.html#8

**Comment by latenitefilms** [comment]
Addressed here:

- 14d230d adds Lua-5.4.0
- fec701b switches to using 5.4.0
