### ISSUE TITLE
Visual Studio Code window have empty "title()"

### ISSUE THREAD

**Issue by sergei-dyshel** [Hammerspoon/hammerspoon#2249]
When accessing vscode (both Microsoft and OSS versions) windows as `hs.window`, they have empty `title()`.
HS 0.9.76, MacOS Mojave 10.14.6

**Comment by latenitefilms** [comment]
Working fine here?

```lua
> hs.application.find("Code"):mainWindow():title()
lazy.lua — CommandPost (Workspace)
```

**Comment by sergei-dyshel** [comment]
@latenitefilms 
Yet in my case:
```
> hs.application.find("Code")
hs.application: Code (0x600002785588)	hs.application: Code - OSS (0x6000027855b8)	hs.application: Code - OSS (0x6000027855b8)

> hs.application.find("Code"):mainWindow()
nil
```

**Comment by latenitefilms** [comment]
Do you have any documents open?

Can you share a screenshot?

**Comment by latenitefilms** [comment]
FWIW, if I have no documents open, the title is just "".

```lua
> print("'" .. hs.application.find("Code"):mainWindow():title() .. "'")
2019-12-03 12:02:45: ''
```

**Comment by sergei-dyshel** [comment]
@latenitefilms 
Of course I have documents open and window's titlebar reflects that. I'm still new to MacOS and didn't master XCode yet, it will take me some time to run HS in debugger. Right now I can only tell that window switcher tool I'm using ([Hyperswitch](https://bahoom.com/hyperswitch)) shows window titles properly, as well as MacOS built-in window switcher.

**Comment by sergei-dyshel** [comment]
It looks like the problem was introduced in VScode 1.40 when underlying Electron was upgraded to v6. Other apps that access window title via accessibility API report empty title as well (Contexts/Witch). *Hyperswitch* apparently uses other API. https://github.com/microsoft/vscode/issues/84195

**Comment by jpeeler** [comment]
@sergei-dyshel, do you know why this issue is still present with current vscode? It looks like the electron fixes have long been merged. (Currently on Code version 1.45.1 using electron 7.2.4)

**Comment by sergei-dyshel** [comment]
> @sergei-dyshel, do you know why this issue is still present with current vscode? It looks like the electron fixes have long been merged. (Currently on Code version 1.45.1 using electron 7.2.4)

Very strange.. Are you sure you still have it?
What does `hs.application.find("Code"):mainWindow():title()` prints?
Do you try running other apps that use accessibility API, like Witch or Contexts?

**Comment by jpeeler** [comment]
I'm not sure if this specific issue is still present, but I arrived here due to a message in the console mentioning this issue. Unfortunately, I can't reproduce it (the message) and didn't save the original output.

My problem might be a slightly different issue, but seems related as `hs.application.find("Code"):mainWindow():title()` works fine. What does not work is `hs.application.open("Code")` nor does `hs.application.open("Visual Studio Code")`. The latter at least opens the program, but does not return the expected application object.

I haven't tried any other apps as every other application I've tried in Hammerspoon has worked correctly, so it seems VSCode specific.

(Sorry for the slow response, was AFK for a week.)

**Comment by sergei-dyshel** [comment]
>My problem might be a slightly different issue, but seems related as hs.application.find("Code"):mainWindow():title() works fine. What does not work is hs.application.open("Code") nor does hs.application.open("Visual Studio Code"). The latter at least opens the program, but does not return the expected application object.

I think this unrelated problem and you should open a new issue on that.
