### ISSUE TITLE
Hs.drawing drawing in the wrong place on non-primary displays

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#231]
Coordinate system mismatch?

**Comment by lowne** [comment]
I know nothing about Objective C or Cocoa, but according to [this](http://stackoverflow.com/a/14228817) it seems to me that https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/drawing/internal.m#L65 should subtract from the height of the **primary** screen (instead of the drawing's screen).

**Comment by cmsj** [comment]
@lowne good call, thanks!
