### ISSUE TITLE
`hs.hints.windowHints()` takes several seconds to display hints

### ISSUE THREAD

**Issue by andrewhampton** [Hammerspoon/hammerspoon#2311]
Steps to repro:

1. In a terminal, `mv ~/.hammerspoon/init.lua ~/.hammerspoon/init.lua.bak`
1. Close all applications 
1. Open Hammerspoon and screen recording software
1. Open the console
1. Type `hs.hints.windowHints()` and hit enter

Expected results:

Hints show up quickly.

Actual result:

Hints take 5-10 seconds to show up.

I've tested on the last 4 versions and behavior persists. However, I suspect this is something weird that's happened on my system, because it just started 2 weeks ago.

[Here's a video demonstrating the problem](https://monosnap.com/file/2yz2tYghWfM1ApIApu3FKkKw2ECuRX).

**Comment by andrewhampton** [comment]
Restarting seemed to fix it. I'm dug around, but never found anything that might have been a root cause.

**Comment by latenitefilms** [comment]
Do you happen to remember what applications you had running when you took the screenshot?

We've found that some applications can cause the accessibility API to "lock up", and setting `hs.window.timeout(1)` can help things fail faster, which speeds things up.

@asmagill - I wonder if `hs.hints.windowHints()` could be a good candidate for attempting to rewrite using `coroutine`'s once your pull requests eventually land?

**Comment by asmagill** [comment]
I'll take a look at it later this week... I need to clean up axuielement and introduce it into core as well, since that's what a lot of the things that can be rewritten with coroutines will rely on.

- - -

*Related, sorta, thoughts:*

I've noticed some things that rely heavily on `hs.window` do start to slow down after a while... The window module has had a lot of extra checks and wrappers and such added to it over the years (it looks a lot different than what was originally imported from Mjolnir!) but nothing in the last couple of months, so maybe something in the latest macOS version has changed to exacerbate things, but that's just a guess at this point... I think some of the slowness may be in the lua code, so not sure what we can use to profile that specific code, but if anyone knows of a lua profiler, we should see how hard it would be to use it with Hammerspoon...

Just as an example, I had some code that looked like this to see if the Hamemrspoon window was currently visible:

~~~lua
     local conswin = window.get("Hammerspoon Console")
     if conswin and application.get("Hammerspoon"):isFrontmost() then
        ... do whatever ..
     end
~~~

Recently this was slowing down at random points, mostly when the window *was* actually open.  I replace it with:

~~~lua
    local hspoon = application.applicationsForBundleID(hs.processInfo.bundleID)[1]
    local conswin = hspoon:mainWindow()
    if conswin and hspoon:isFrontmost() then
        ... do whatever ..
     end
~~~

and it's been snappy ever since, so there definitely are some places that could benefit from a review of `hs.window` and/or `hs.application`, both of which could leverage `hs._asm.axuielement` for some of what they do.

**Comment by andrewhampton** [comment]
> Do you happen to remember what applications you had running when you took the screenshot?

I tried to close pretty much everything as part of my testing, and when I created the video in the description. Only random background processes would have been running, nothing that has a dock icon. Hammerspoon, Monosnap, and Fleetsmith (corporate software management tool that I can't shut down) were the only things I'm sure about. I probably had some docker containers running as well.

Here's what I commonly run:

- Kitty terminal
- Firefox nightly
- Slack
- Spotify
- Sequel Pro
- Keybase
- Docker
- Dropbox
- 1Password
- Little Snitch
- Signal

I've only had this issue once though. Signal is the only thing from that list that I've started running recently, that could line up with the timeline of the issue.

> We've found that some applications can cause the accessibility API to "lock up", and setting hs.window.timeout(1) can help things fail faster, which speeds things up.

I'll try this if I hit it again.
