### ISSUE TITLE
hs.screen:setBrightness() not working on an external screen

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2342]
I have an LG UltraFine 5K monitor connected to my MacBook Pro. If I use the screen brightness controls on my keyboard I can adjust the brightness, but if I use code, it has no impact.

For example:

```lua
> hs.screen.allScreens()[1]:setBrightness(0.1)
hs.screen: LG UltraFine (0x600022966a58)
```

...does nothing. Is this a known limitation/issue?

**Comment by latenitefilms** [comment]
As discussed [here](https://github.com/nriley/brightness/issues/11#issuecomment-612534557), it seems whilst [brightness](https://github.com/nriley/brightness) also fails, [ddcctl](https://github.com/kfix/ddcctl) works as intended, so hopefully someone smart like @asmagill or @cmsj can review [this code](https://github.com/kfix/ddcctl/blob/master/DDC.c) and see if any of it can be used to improve `hs.screen`?

**Comment by cmsj** [comment]
It is known, but since it last came up, I have acquired an LG 5k, so I’ll take a look when I get a chance.

**Comment by latenitefilms** [comment]
As per this [issue](https://github.com/nriley/brightness/issues/11#issuecomment-613194980) it looks like [brightness](https://github.com/nriley/brightness) has also been updated to support the LG 5K.

[This](https://github.com/nriley/brightness/commit/eb182a4857a063e254611b4d486b495c4c25a729) seems to be the relevant commit.

**Comment by cmsj** [comment]
Thanks @latenitefilms for tracking that down. Super helpful! I've just pushed an update to hs.screen:getBrightness() and :setBrightness() that uses the new API. It works for me on both XDR and LG 5K.

I haven't touched hs.brightness because I think we should remove it, its API is suuuuuper old, from Mjolnir days, and it makes no attempt to support multiple displays.

Furthermore, its only other feature, ambient light sensor reading, has never worked on external displays and now doesn't even work on newer MacBooks (see #1673), so.... it seems questionable how valuable it is to even keep that.

At best, I'd keep hs.brightness around as the ambient function for people with old hardware, and then map the get/set functions to call hs.screen's brightness methods on the primary display.

**Comment by cmsj** [comment]
@asmagill any objections to my hs.brightness plan in the previous comment?

**Comment by latenitefilms** [comment]
Sounds like a good plan to me! Ideally it would be awesome to add the ambient light sensor reading to `hs.screen`, but it seems like that might not be possible on Touch Bar models onwards. I'll keep my eye out on GitHub to see if anyone comes up with a clever workaround.
