### ISSUE TITLE
hs.uielement.focusedElement() not working in some apps

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#2362]
I need to use `hs.uielement.focusedElement():selectedText()` but it doesn't seem to consistently working in every app. Notably, in [some] web browsers. I have tried it in Brave, Chrome and Firefox. When you select some text in TextArea or inside an Input element, `hs.uielement.focusedElement()` returns nil.

Somehow Safari works just fine.  Can someone help me to investigate and maybe find a workaround. Thanks.

**Comment by cmsj** [comment]
Unfortunately, a lot of browsers (and therefore also apps that are built on things like Electron), don’t implement all of the UI mechanisms that would allow this to work - they simply aren’t presenting their web widgets as UI widgets that macOS can introspect.

That’s why it works properly in Safari, because Apple does do the work for that integration.

I’m honestly not sure if there is a workaround for this, other than emitting a CMD-c event to copy the text. Sorry!

**Comment by agzam** [comment]
My colleague suggested to use `hs.pasteboard.changeCount` before and after `Cmd+c` and compare the results, and that worked.
