### ISSUE TITLE
string:upper() doesn't work with some accented characters

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2367]
For example:

```lua
> test = "å"
> test:upper()
å
```

@asmagill - Is this something your fancy new `hs.text` extension can help solve?

**Comment by asmagill** [comment]
If only the code were stored somewhere available for testing... 😜

~~~lua
> hs.text = require("hs.text")

> help.hs.text.utf16.upper
Method: hs.text.utf16:upper([locale]) -> utf16TextObject

Returns a copy of the utf16TextObject with an uppercase representation of the source.

Paramters:
 * `locale` - an optional string or boolean (default ommitted) specifying whether to consider localization when determining how change case.
   * if this parameter is ommitted, uses canonical (non-localized) mapping suitable for programming operations that require stable results not depending on the current locale.
   * if this parameter is the boolean `false` or `nil`, uses the system locale
   * if this parameter is the boolean `true`, uses the users current locale
   * if this parameter is a string, the locale specified by the string is used. (See `hs.host.locale.availableLocales()` for valid locale identifiers)

Returns:
 * a new utf16TextObject containing an uppercase representation of the source.

Notes:
 * This method is the utf16 equivalent of lua's `string.upper`
 * Case transformations aren’t guaranteed to be symmetrical or to produce strings of the same lengths as the originals.

> test = hs.text.utf16.new("å")

> test
å

> test:upper()
Å
~~~

**Comment by asmagill** [comment]
(I am still working on the regex submodule (which won't be limited to to `hs.text.utf16`), but `hs.text.utf16` is basically at parity with lua's `string` and `utf8` libraries except where noted in the docs)

**Comment by latenitefilms** [comment]
Legend, thanks!

So, dumb question... if the text is coming from `hs.pasteboard.getContents()` is it "safe" to always convert it to UTF16?

**Comment by asmagill** [comment]
Assuming it's uncorrupted textual data, should be -- every method and function of CFStringRef and NSString work on a UTF16 representation of the data... its only when text is converted to NSData/CFDataRef that other encodings are even mentioned.

And just for reference, every time you pass a string to a function/method written in Objective-C (unless the Objective-C code is explicitly written to treat it as data and not a string), there is an implicit conversion from UTF8->UTF16 (and then back, if a string is returned to Lua)... usually it's not an issue, but it has caused headaches on more than one occasion because Lua/UTF8 breaks everything down into bytes but UTF16 doesn't.

- - -

Depending upon how large the data is in the pasteboard for your general use case, it may be worth creating another constructor for `hs.text` or `hs.text.utf16` that internally retrieves the data from the pasteboard directly... one of the reasons `hs.text` was even conceived was to reduce the need for passing large blocks of textual data back and forth between Lua and Objective-C.

**Comment by latenitefilms** [comment]
I’m basically just adding an “action” which allows the user to change the case of current pasteboard contents - so the pasteboard contents could be anything.

Adding a pasteboard constructor could speed things up, so sounds good to me!

**Comment by cmsj** [comment]
I don't think we're going to fix bugs in Lua's string methods, and it seems like `hs.text` does cope with this, so we're good and can close this?

**Comment by latenitefilms** [comment]
Yes, all good. Thanks!
