### ISSUE TITLE
Question: hs talking to itself via shell script timeout

### ISSUE THREAD

**Issue by myelsukov** [Hammerspoon/hammerspoon#2390]
Hello,

I have an unusual/weird setup:

* A hotkey in `hs` is bound to execute a shell script `S`
* Shell script `S` is calling `hs` CLI to bring specific window to the foreground.

When I press the hotkey I observe a long pause (default timeout 4 seconds?) then the script is executed and does what it is intended to do.

When I run `os.execute("S")` in the `hs` CLI, I am getting error: **_error communicating with Hammerspoon: receive timeout_** after the pause then CLI dies.

The reason for the weirdness of my setup is simple: the script `S` is a universal script that works for OS X and for Linux. So I have different ways of binding the same hot keys in Linux and OS X to the same shell scripts. I have a bunch of scripts like that :)

I can imagine what could cause the communication timeout... 

The script `S` could be as simple as:

```
#!/usr/bin/env bash
/usr/local/bin/hs -c "print(hs.execute('ls'))"
```

I have couple of questions:

* Is it a bug or is it a feature?
* If it is a feature, then what would be a suggested workaround?

Thanks

**Comment by asmagill** [comment]
It's a limitation of the way Hammerspoon works. Blocks of Lua code run till completion and only one block can be running at any given instant. The hotkey callback is one block and it's calling out the the shell to execute your script; the script invokes the `hs` command which attempts to connect to Hammerspoon to run a block of code (what you include after `-C` plus some wrapper stuff that's automatically appended and prepended to make it all come together cleanly)... but this new block of Lua code can't execute because the hotkey block is still "executing" on the main application thread, so `hs` times out, the hotkey block gets the error message and then completes.

It may be possible to use `hs.task` in this case because it returns immediately, allowing the hotkey block to complete; when `hs.task` is ready to actually execute the shell command, the hotkey block won't be running anymore. The down side is that you'll have to write your code to work with the results of `hs.task` within the `hs.task` completion callback, not the `hotkey` callback... it requires a little more thinking about how your code is organized, but usually it's not *that* much different.

The next release version of Hammerspoon will support lua coroutines, which is another way you might be able to address this (I haven't tried myself with this specific type of thing, but it should work) -- it will still require a slight re-organizing of your code, but would allow you to continue to use `hs.execute` rather then the slightly more complex `hs.task`. A simplified description of coroutines is that they allow you to pause an executing block to allow another block to execute before returning to complete the first block. Search recent issues here for `coroutine` and/or take a look at https://github.com/Hammerspoon/hammerspoon/wiki/Coroutines and https://github.com/Hammerspoon/hammerspoon/wiki/CoroutinesLeveraging if you're interested in this approach, but like I said, it will require a development build of Hammerspoon or waiting until the next release.

**Comment by asmagill** [comment]
To clarify about `hs.task`:

> ...when hs.task is ready to actually execute the shell command...

This does not mean that it occurs at some arbitrary time in the future -- it usually occurs milliseconds after the block which created the `hs.task` object completes, it's just queued so it will occur the next time Hammerspoon is free to start doing something new (when done executing a block of lua code or other internal housekeeping macOS applications require).

**Comment by asmagill** [comment]
Just to confirm, `hs.task` should be able to do it... just ran this in the Hammerspoon console:

~~~lua
> b = hs.task.new("/opt/amagill/bin/hs", function(c,o,e)
    print("Response Code:" .. tostring(c) .. "\nOutput:" .. o .. "\nStdErr:" .. e)
end, { "-c", "hs.inspect(_G, { depth = 1 })" }):start()

Response Code:0
Output:<1>{
  _G = <table 1>,
  _VERSION = "Lua 5.3",
  assert = <function 2>,
  b = <userdata 1> -- hs.task: /opt/amagill/bin/hs -c hs.inspect(_G, { depth = 1 }) (0x60800154c948),

-- ... cut for brevity ...

  tostring = <function 35>,
  type = <function 36>,
  utf8 = {...},
  xpcall = <function 37>
}

StdErr:
~~~

**Comment by myelsukov** [comment]
Cool, thanks!
Yes, the `hs.task` works just fine!
