### ISSUE TITLE
Feature Request: SF Symbols access

### ISSUE THREAD

**Issue by rsefer** [Hammerspoon/hammerspoon#2409]
It would be a bonus to be able to reference [SF Symbols](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) from the `hs.image.imageFromName` method - or any other way to easily reference symbol names. Possible pitfalls: licensing restrictions, font vs. image.

**Comment by dasmurphy** [comment]
`SF Symbols` should be accessible already when it is installed. But to get an `image` from it, you need to create a `canvas` object with the symbol as text in it. Otherwise i don't see any good solution currently, but it looks not too hard to me to solve it with a wrapper function for it.

**Comment by rsefer** [comment]
@dasmurphy I can't seem to figure out how to use SF Symbols at all (as a font or othwerise). Alas, I will keep trying!

**Comment by nonissue** [comment]
@rsefer Hope it's not too late, but I have a solution for you!

You can use [this](https://github.com/davedelong/sfsymbols) project to extract PDFs from SF Symbol, and they work perfectly for me (as menubar icons at least — they are transparent, and update when changing dark/light mode). 

Just FYI, I don't think `sfsymbols` project works with the latest version (2.0 Beta I think?) of SF Symbols. In order to extract, I had to use version 1.1. Last time I checked, you can find that [here](https://developer.apple.com/design/downloads/SF-Symbols.dmg).

Here's an example of the command I run to export all the icons as PDFs: 

`sfsymbols --format pdf --output ~/tmp/sfsymbols/light --font-weight regular`

You can change the font-weight to any of font weights listed in the actual SF Symbols app.

If you'd prefer, I don't mind doing the export and uploading them somewhere for you. Just let me know what font-weight you want. To my eye, for *most* cases in the menubar, bold looks best, but I do find it depends on the icon you want to use.

**Comment by rsefer** [comment]
@nonissue Nice solution - thank you!

P.S. There are some odd omissions in SF Symbols (and the new 2.0 beta). For example, they have icons for battery 0%, 100%, and 25% but not 50% or 75% ¯\_(ツ)_/¯

**Comment by nonissue** [comment]
Well that's obviously because you can do 50% with 2 x 25%, and 75% is just 100% - 25%! Just use composition 😂😂

**Comment by asmagill** [comment]
Not finding any kind of map for the SF Symbols in version 2 or 3beta, but it looks like they are stored in the private (i.e. local) UNICODE space (at least in the SF Pro fonts, maybe others as well).  The following worked for me to use them, though:

Using http://mathew-kurian.github.io/CharacterMap/ to examine the font (click on Select Font in the upper left and then browse to "/Library/Fonts" and select the "SF Symbool.ttf" file) you can figure out the codepoint for the symbol you like... it shows the glyphs of the font in groups of 200 at a time (select on the left; for my example, I chose the index range 11400-11599), then click on the symbol you are interested in. In the middle pane, the name will read something like "UNI100D8C.LARGE" -- the part you want is the hex number --> "100D8C".

Then in Hammerspoon, you can turn it into an image with something like this:

~~~lua
code = 0x100D8C -- change to the number you found in the process described above
char = hs.styledtext.new(utf8.char(code), { font = { name = "SF Pro", size = 12 } })
-- if you can use the symbol as a styled text object, then this is all you need

-- if you need it as an image, then also do the following
canvas = hs.canvas.new({ x = 0, y = 0, h = 0, w = 0 })
canvas:size(canvas:minimumTextSize(char))
canvas[#canvas + 1] = {
    type = "text",
    text = char
}
image = canvas:imageFromCanvas()
canvas:delete() -- won't auto collect yet
~~~

Now `image` contains the image object of the SF Pro glyph.

**Comment by asmagill** [comment]
Sorry, the font name to select when browsing is `SF-Pro.ttf` not `SF Symbol.ttf`.

**Comment by rsefer** [comment]
This works really well. Thanks @asmagill!
