### ISSUE TITLE
hs.eventtap.keyStrokes breaks when providing modifier table

### ISSUE THREAD

**Issue by YellowKirby** [Hammerspoon/hammerspoon#242]
Using 0.9.25, seeing the following behavior (using the Hammerspoon Console):

```
> hs.eventtap.keyStrokes({"alt"}, "t")
invalid key to 'next'
```

Providing an empty modifiers table appears to still work as expected:

```
> hs.eventtap.keyStrokes({}, "t")
```
Which puts the character 't' into the console input field.

Tried both of these commands in 0.9.24 and didn't have any issues.

Here's a stack trace when triggered from my config:
```
invalid key to 'next'
stack traceback:
	[C]: in function 'newKeyEvent'
	...n.app/Contents/Resources/extensions/hs/eventtap/init.lua:119: in function 'keyStrokes'
	.../.hammerspoon/winutils.lua:4: in function 'toggleMenuBar'
```

**Comment by cmsj** [comment]
Good catch, thanks! This will be fixed in 0.9.26, which I would expect to release in a few days.

**Comment by YellowKirby** [comment]
Awesome. Thanks for the quick fix!

If anybody needs a quick workaround, the following seems to work instead:

```
> hs.eventtap.keyStrokes({alt=true}, "t")
```

**Comment by cmsj** [comment]
@YellowKirby yep, that was the issue, the underlying function was looking for keys in the table, instead of values (when you do {"alt"} what's actually happening is Lua is implicitly making the table contain {1="alt"})

There are other functions/methods in hs.eventtap which are still using keys for the modifiers, which I think makes more sense (e.g. getting the flags on an event)
