### ISSUE TITLE
Create a Hammerspoon NSApplication subclass

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2460]
As discussed [here](https://github.com/asmagill/hs._asm.undocumented.touchbar/issues/1#issuecomment-687565138), to get around a weird macOS bug/issue related to the Touch Bar, we need to subclass `NSApplication` so that we can use this code as a workaround:

```objc
-(void) _crashOnException:(NSException *)exception {
    if ([exception.debugDescription rangeOfString:@"NSFunctionRow"].location != NSNotFound) {
        NSLog("_crashOnException override: %@", exception.debugDescription) ;
        return ;
    } else {
        [super _crashOnException:exception] ;
    }
}
```

**Comment by asmagill** [comment]
Re the touchbar issue, I think for now it's better served by swizzling the method in the module itself, since this is the only place we've confirmed it's an issue. See https://github.com/asmagill/hs._asm.undocumented.touchbar for current work in this direction.

However, are there other benefits or reasons we might want to consider subclassing NSApplication for Hammerspoon?

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as I think the swizzling method is the best workaround for the Touch Bar, but feel free to re-open this issue if the need to subclass `NSApplication` comes up in the future.

FWIW - Apple has some suggested "Methods to Override" [here](https://developer.apple.com/documentation/appkit/nsapplication?language=objc).

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - Sadly, we never found a solution to the `NSFunctionRow` crashes, and I still see a lot of crashes with `NSFunctionRow` in our crash logs - related to the Touch Bar. I'm assuming this is a bug in macOS, but given Apple has given up on the Touch Bar on the latest 14-inch and 16-inch laptops, I'm guessing it'll never be fixed. Given it's unlikely that `hs._asm.undocumented.touchbar` will make its way into the Hammerspoon core now - I was wondering how you'd feel about creating a `NSApplication` subclass, so we can try overriding `_crashOnException` on CommandPost as documented above? We don't have to override this on Hammerspoon obviously, but it would make things a lot cleaner/nicer for CommandPost if Hammerspoon had the sub-class, as opposed to use just changing it on our fork only.

FWIW - we still a lot of users using the virtual Touch Bar, even if they don't have a physical Touch Bar, because it exposes some functions/features in Final Cut Pro that aren't accessible in the main UI.

Thoughts?

**Comment by latenitefilms** [comment]
@asmagill - Random thought... I wonder if the reason [your swizzling method](https://github.com/asmagill/hs._asm.undocumented.touchbar/commit/28c08feea4908cc2ea704e8c2276bca760b39c4b) never work for me is because Sentry already swizzles the `_crashOnException` method? To be honest, I'm not really sure how Sentry works behind-the-scenes, or what order the swizzling would take place, etc. Thoughts?

https://github.com/getsentry/sentry-cocoa/blob/e254b733f7706d4c04c02093f5ad0715ced92443/Sources/Sentry/Public/SentryCrashExceptionApplication.h

**Comment by latenitefilms** [comment]
@asmagill & @cmsj - Did you have any thoughts on the above?

**Comment by asmagill** [comment]
It's been so long, I'd have to review things again...

While I don't have any objection to subclassing NSApplication, would it benefit Hammerspoon at all? How much work would it be?

As to the swizzling, I'll have to take a closer look at touchbar... I *think* that it *should* be implementing it's swizzle *after* Sentry, since Sentry is (probably?) loaded and setup before the lua state is created... and I'm pretty sure I would have written it to fall through to whatever the method's call was if it didn't match the exception we were looking for, which I would expect to be Sentry's, but... I really don't know.

Is there a method invoked before `_crashOnException` that maybe Sentry is tapping into instead? Might be worth looking a little closer at Sentry as well if it's not just an opaque blob... since I almost always run my own builds, I've never looked that closely at Sentry or how it's implemented -- it's not included in my builds 😜

**Comment by latenitefilms** [comment]
Hopefully this repo is of help: https://github.com/getsentry/sentry-cocoa/

**Comment by latenitefilms** [comment]
Dumb idea... I wonder if the crash could be solved by some added canary code? Maybe it's trying to update something when the Lua session is already destroyed?

FWIW - here's the Sentry logs:

https://sentry.io/share/issue/27a4f41cf6024f2abffb77b61457ffd2/

**Comment by latenitefilms** [comment]
Reminder, here's how BetterTouchTool gets around it - assuming it's the same crash:

https://twitter.com/LLo_ai/status/1302125004033863680?s=20&t=QsBb-TcibvMsw_EscqfT2A

**Comment by latenitefilms** [comment]
There might be some good clues in here as well:

https://github.com/pock/pock/blob/main/Pock/Private/TouchBarHelper.swift

**Comment by latenitefilms** [comment]
Closing in favour of:

https://github.com/asmagill/hs._asm.undocumented.touchbar/issues/5
