### ISSUE TITLE
Adding a way to only show hints for windows visible to the user

### ISSUE THREAD

**Issue by jgerman** [Hammerspoon/hammerspoon#247]
Hi,

I'm trying to switch from Slate to Hammerspoon as Slate doesn't recognize emacs windows for hints. Hammerspoon does, but the opening hints for every window whether actually visible to the user or not is too noisy. 

I was digging in and it appears that using the NSWindow property NSWindowOcclusionState is what I'm after, but not having Cocoa (or Lua for that matter) experience I'm not sure how to get that property through AXUIElement. It doesn't look like it would be too much trouble to add a window_isOccluded method to extensions/window/internal.m if someone could steer me in the right direction in reading that property.

**Comment by cmsj** [comment]
I wonder if using kAXVisibleChildrenAttribute would help here. There doesn't seem to be a direct attribute for "is this window occluded", but if a window ui element has any visible children, we could assume that the window itself is at least partially not occluded.

**Comment by cmsj** [comment]
(We can't directly real the NSWindow attribute, we don't get to talk directly to the objects in another app)

**Comment by jgerman** [comment]
Cool, I'll take a look.

**Comment by cmsj** [comment]
(for what it's worth, I think this is a good idea, and if we can make it work, we should :)

**Comment by jgerman** [comment]
It's a shame we can't get at least read access to the underlying Window. 

I'll fumble around with it a bit and see if I can get it working.

**Comment by cmsj** [comment]
Oh, one question that should have occurred to me - does Slate allow you to only hint windows that are visible? If so, we should be able to see how they are doing it, since it's open source.

**Comment by drifkin** [comment]
Slate calculates the coordinates of where it would place a hint for each window. It then checks that the topmost window under that label is in fact the window that belongs to the hint (otherwise it's considered "hidden", see [this link](https://github.com/jigish/slate/wiki/Global-Configs#windowhintsignorehiddenwindows) for a definition).

This seems to reasonably well in practice, though sometimes it can lead to a hint not showing up for a window, even though much of the window is in fact visible.

It looks like the code is around here: https://github.com/jigish/slate/blob/master/Slate/HintOperation.m#L133

**Comment by cmsj** [comment]
I still think this is a good idea, but we haven't managed to get to it for over 2 years, so I think it's unlikely to happen. I'm closing the issue, but if anyone wants to work on this, please feel free to do so :)
