### ISSUE TITLE
0.9.79  breaks window.switcher and redshift.start

### ISSUE THREAD

**Issue by aalexei** [Hammerspoon/hammerspoon#2482]
Hi, update 0.9.79 breaks on my config.

The following config line:
```
local switcher_space = hs.window.switcher.new(hs.window.filter.new({}):setCurrentSpace(true):setDefaultFilter{}, uiGlobal)
```
leads to
```
2020-09-21 10:31:22: *** ERROR: ...n.app/Contents/Resources/extensions/hs/window/filter.lua:1431: attempt to index a nil value (field '_element')
stack traceback:
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1431: in upvalue 'startAppWatcher'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1559: in upvalue 'startGlobalWatcher'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1649: in upvalue 'checkTrackSpacesFilters'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:592: in function <...n.app/Contents/Resources/extensions/hs/window/filter.lua:518>
	(...tail calls...)
	/Users/alexei/.hammerspoon/init.lua:160: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:702: in function 'hs._coresetup.setup'
	(...tail calls...)
```

commenting out that line and dependent ones, trips up later on:
```
hs.redshift.start(2700,'21:00','7:00','2h',false,wfRedshift, 6509)
```
with
```
2020-09-21 10:35:00: *** ERROR: ...n.app/Contents/Resources/extensions/hs/window/filter.lua:1431: attempt to index a nil value (field '_element')
stack traceback:
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1431: in upvalue 'startAppWatcher'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1559: in upvalue 'startGlobalWatcher'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1722: in upvalue 'start'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1913: in method 'subscribe'
	...n.app/Contents/Resources/extensions/hs/redshift/init.lua:345: in function 'hs.redshift.start'
	/Users/alexei/.hammerspoon/init.lua:442: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:702: in function 'hs._coresetup.setup'
	(...tail calls...)
```
I don't know enough about Lua to debug effectively, hope the above helps.

**Comment by asmagill** [comment]
@cmsj, the previous version of `hs.uielement` used a table as the watcher element, not a userdata, and apparently `hs.window.filter` (and others?) were accessing variables within that table directly rather than using the methods like they should have been...

Not sure what the cleanest fix here is...  a quick grep of the 0.9.78 source looks like only `tabs`, `uielement`, and `window` used the `newWatcher` method from uielement directly, so maybe it's relatively contained?

I'll see what I can come up with, but as I don't use `hs.tabs` and `hs.window.filter` myself, does anyone have a real quick example I can use to test that currently fails? Ideally something that doesn't require loading a lot of extra code to my configuration?

**Comment by asmagill** [comment]
Well the good news is the `hs.tabs` looks good. However, `hs.window.filter` is going to take some digging into...

**Comment by asmagill** [comment]
Consolidating this at #2474 as it's definitely `hs.window.filter` at fault here.
