### ISSUE TITLE
ERROR:   LuaSkin: hs.canvas:frame must be a table

### ISSUE THREAD

**Issue by razorbear3** [Hammerspoon/hammerspoon#2486]
Love Hammerspoon. Thanks for all the work you all are doing.

Since the latest release, I am getting the following error popping up a lot in my Hammerspoon console.
`ERROR:   LuaSkin: hs.canvas:frame must be a table`

Functionality-wise everything is working correctly in the scripts I am using canvases in, but my console gets filled with this error. 

I am passing tables into my hs.canvas.new() statements, and I am not directly calling the :frame() method.

It seems to be occurring when I switch windows, and several of my canvases show/hide depending on the focused window.

Any ideas where to start?

**Comment by asmagill** [comment]
So it's not occurring when you create the canvas objects, correct?But later on when switching windows? How are you determining when to show/hide the canvas objects -- through `hs.window.filter`? An `hs.application.watcher` other watcher?

Is you Hammerspoon config uploaded to github somewhere were I can review it (I understand if it's not, but I'm surprised sometimes how many users do)?

If not, can you outline in a general way what your config is doing with regards to the canvas objects (e.g. "when I switch to another application, a series of canvas objects are hidden and another series are shown") If possible, outline what canvas operations (other than `frame` which you say you do not use) *are* occurring.

Off the top of my head, no real ideas, but if I can replicate in some small way what you're doing, it will simplify troubleshooting.

**Comment by razorbear3** [comment]
@asmagill Thanks for your help! And I sorry, I didn't give you much to work with in terms of code. 

I was originally thinking maybe this had something to do with the recent update since it was an error from LuaSkin, but as usual, it was my own mistake. :) Maybe that is why I haven't posted my init on github.

I have a pseudo dark mode I've created for an application I work with. I do this by changing the screen's gamma values when the application is in focus. Then, when I switch to a different application, I temporarily place a fading dark overlay on all the screens to ease the transition from the dark mode to another application. The error was presenting itself during these application switches.

The offending code was the following:
```
  for k,v in pairs(restOverlayCanvas) do
    restOverlayCanvas[k][1] = {
      frame = { h = v.h, w = v.w, x = v.x, y = v.y },
      fillColor = { alpha = alpha, hex = color  },
      type = "rectangle",
    }
```

I was attempting to create an overlay layer on my canvas to the full size of the frame of the restOverlayCanvas canvas object I had previously created. However, I was forgetting to call the :frame() method first to get the height, width, and x/y positions. Mistakenly, I was attempting to grab these directly from the canvas object itself without first calling the :frame() method. 

For some reason, I was getting away with this oversight, and this actually continued to function normally, despite the error. (Why that is? I am guessing those w, h, x, y variables must be built into the object's table in some fashion).

Anyways, the corrected code as  is as follows:
```
  for k,v in pairs(restOverlayCanvas) do
    local f = v:frame()
    restOverlayCanvas[k][1] = {
      frame = { h = f.h, w = f.w, x = f.x, y = f.y },
      fillColor = { alpha = alpha, hex = color  },
      type = "rectangle",
    }
```

Thanks for your response and the help! It got me going in the right direction here.

**Comment by asmagill** [comment]
Glad you have it working... question, is `v` in your snippit an object from `hs.window.filter`? If so that would explain the issue (but to be fair, the error message should be made clearer)...

In 0.9.78, `hs.uielement` which is the primary underpinning of `hs.window.filter`, used tables with metatables to mimic userdata objects for windows, applications, etc... within this table, it cached information about the object and, though you weren't supposed to access them this way, you *could* get at certain elements of the object as if they were table keys... so `v.h`, etc. would have actual values... this would have technically been an undocumented "feature/bug", depending upon your viewpoint.

Now, `hs.uielement` is a proper userdata and no longer has values for these "keyed" entries... so in essence, your first snippit is now trying to set the frame to `{ x = nil, y = nil, h = nil, w = nil }` which would actually be `{}` or an empty table, not one that contains the parameters required.

So the error message *should* have indicated that it required a populated table, as opposed to complaining that it wasn't a table... The reason why it worked (albeit with the spammy error messages) is because if the frame field isn't present at all in a canvas element, it inherits the frame of the canvas itself, which I'm guessing also happens to be the same size as `v:frame()`

While its a low priority in comparison to some of the other issues we're tracking down with this latest update, I'll see if I can't go back and make some of the error messages clearer in the future.

**Comment by razorbear3** [comment]
I am actually not using any window filters, just using the hs.screen.allScreens() to get all the screens and then the screen's :fullFrame() method to get the frame to size the canvas' to the screen size.

What you are saying makes total sense. Very fascinating. I was very fortunate that this worked on either version. I lucked into it working.

No worries on the error messaging. This is the first time I have come across anything in 4ish years of use error-wise that I wasn't clear where it was occurring, and even then, found the problem with some debugging print statements to narrow down when it was occurring. The canvas message likewise at least told me it was something related to one of the canvases I was using, so that narrowed it down a lot.

You all are doing great work. Really appreciate it.

---

Here's the code, if it helps:

The "v" in the snippet above is just a canvas object. 

However, before this,  I am iterating through each screen on my desktop and creating a canvas for that screen, using the screen's frame for the sizing. These canvases all get put into a table. 

Then I iterate over the table of canvases and create the rectangles for the actual overlay (which is what I shared above). 

(Doh, looking at this code now, it looks like I could reduce this down to one loop rather than looping to create and then looping again.)

Finally, I put a delay in place before deleting and dimming out the overlay canvases.

```
local function displayDarkOverlay(removeDelay, fadeDuration, color, alpha)
  -- Put a temporary dim on the screens to let your eyes adjust back to light mode
  local allScreens = hs.screen.allScreens()
  local restOverlayCanvas = {}

  for k,v in pairs(allScreens) do
    restOverlayCanvas[k] = hs.canvas.new({x=v:fullFrame().x, y=v:fullFrame().y, h=v:fullFrame().h, w=v:fullFrame().w})
  end

  for k,v in pairs(restOverlayCanvas) do
    local f = v:frame()
    restOverlayCanvas[k][1] = {
      frame = { h = f.h, w = f.w, x = f.x, y = f.y },
      fillColor = { alpha = alpha, hex = color  },
      type = "rectangle",
    }
    restOverlayCanvas[k]:show()
  end

  -- Take away the temporary dim on the screen
  hs.timer.doAfter(removeDelay, function()
    for k,_ in pairs(restOverlayCanvas) do
      restOverlayCanvas[k]:delete(fadeDuration)
    end
  end)
end
```
