### ISSUE TITLE
Boolean to callback to hs.screen.watcher.newWithActiveScreen() reversed?

### ISSUE THREAD

**Issue by von** [Hammerspoon/hammerspoon#2499]
According to the documentation for [hs.screen.watcher.newWithActiveScreen()](https://www.hammerspoon.org/docs/hs.screen.watcher.html#newWithActiveScreen), its callback should receive a value that "will indicate if the change was due to a screen layout change (nil) or because the active screen changed (true)."

However, I believe I'm seeing is the opposite: `nil` for a change of active screen (i.e. moving the dock from one monitor to another) and `true` for a screen layout change (e.g. plugging in an external monitor). For example, the code below outputs `nil` if I change the active screen and `true` if I change the screen layout.

```
> function f(v) hs.printf(hs.inspect(v)) end
> w = hs.screen.watcher.newWithActiveScreen(f):start()
```

This is with 0.9.80.

**Comment by asmagill** [comment]
Just moving the Dock to another screen does not "activate" that screen until you actually click on an item in that Dock or a window on that screen. `nil` is appropriate for the moving of the Dock because it does change the effective "available space" on that particular screen (for example when you maximize -- not to full screen, but by zooming -- a window).

That said, I am now seeing both a `true` and separate `nil` callback whenever changing the layout (size) of a screen with the System Preferences -> Displays panel. I don't think I saw those with earlier macOS versions, but it has been a while since I looked that closely, so I couldn't say when it changed.

I'll look into this, but I don't think we can do anything about it -- the watcher relies on notifications posted by macOS to the global notification center and if Apple has changed when or how often it sends those particular notifications, we have to deal with it.

Perhaps the documentation can be updated to make it clear that `true` will be issued whenever the user does something active with an application on a new screen and `nil` whenever any aspect, even if it's used only internally by the macOS, of a screen's available layout changes.

**Comment by asmagill** [comment]
Should say `I don't think I saw *both* of those with...`

**Comment by von** [comment]
Thanks for the explanation. You are correct, I do see `nil` any time I change the size of the Dock. When I get back to my two-screen set up I'll play around to make sure I understand what you are saying about activation and probably propose a documentation change as you suggest.

**Comment by von** [comment]
I get it now and yes, the function is behaving as it should. I do often see both an active screen change and a layout change callback in series when I plug-in a monitor, probably because both are happening.

I take a closer look at the documentation and may do a PR with some suggestions, but agree no code change is called for.
