### ISSUE TITLE
Documentation on `hs.screen.setTint` is unclear

### ISSUE THREAD

**Issue by peterhajas** [Hammerspoon/hammerspoon#250]
When trying to replace f.lux with Hammerspoon, I noticed the documentation for `hs.screen.setTint()` is unclear:

    Function: hs.screen.setTint(redarray, greenarray, bluearray)
    Set the tint on a screen; experimental.

What are the types of `redarray` and friends? I tried a float (`0.5`), a table (`{0.5}`) and a multi-element table (`{0.5,0.5,0.5}`) but could not get `setTint()` to work. Perhaps the documentation could be clearer about this?

**Comment by cmsj** [comment]
Agreed, it's terrible atm. The underlying C is also terrible, in that it's completely unaware of multiple displays and has no way to save the current gamma states for later restoring. 

This is code that exists from two forks ago and TBH I've never actually used it, but replacing f.lux with some Lua is of interest to me, so I'll dig into the CoreGraphics API and figure out what this is supposed to be doing, and update the C part to be more useful, and we should be in a better place.

FWIW, the C part looks like it's expecting arrays of CGGammaValue floats, but I currently have no idea what they represent.

Sorry this isn't a more useful comment!

**Comment by cmsj** [comment]
Ok, I figured it out. The current API for this is pretty terrible, so I think I'm just going to remove setTint() entirely from the next release. It wants you to populate a table with 256 values for each of the R/G/B channels, to describe a gamma ramp. I think that's a fairly crazy thing to be forcing the user to do, and I very much doubt that anyone has ever actually bothered to use it - it always sets the gamma table on the primary display only, and many displays seem to have more than 256 values in their gamma curve.

Instead, I think what would be much more useful, would be to be able to set absolute R/G/B values for the white and black points of the gamma curve (using the same 0.0-1.0 range that we use in hs.drawing and that Quartz is using, rather than the more limiting 0-255 most apps seem to use), and use those to simply scale the original curve from the ColorSync profile for the display, thus retaining its shape.

I've got the basics of the code down, but I need to do some testing into things like adding/removing displays, screen mode changes, GPU switching, etc.

As a teaser (and mostly so I have a reference to it for later), this is the ridiculous (and inefficient!) test I have been using. It cycles the whitepoint of all displays simultaneously, through the full range of each R/G/B channel, with the other two channels clamped at 0.0 (i.e. you get to watch the screens' whitepoints go from dark red to pure red, then dark green to pure green, then dark blue to pure blue).

```lua
for value = 0.0, 1.0, 0.01 do
  for _,screen in pairs(hs.screen.allScreens()) do
    gamma = screen:getGamma()
    gamma["whitepoint"]["red"] = value
    gamma["whitepoint"]["green"] = 0.0
    gamma["whitepoint"]["blue"] = 0.0
    screen:setGamma(gamma["whitepoint"], gamma["blackpoint"])
    hs.timer.usleep(100000)
  end
end
hs.screen.restoreGamma()
for value = 0.0, 1.0, 0.01 do
  for _,screen in pairs(hs.screen.allScreens()) do
    gamma = screen:getGamma()
    gamma["whitepoint"]["red"] = 0.0
    gamma["whitepoint"]["green"] = value
    gamma["whitepoint"]["blue"] = 0.0
    screen:setGamma(gamma["whitepoint"], gamma["blackpoint"])
    hs.timer.usleep(100000)
  end
end
hs.screen.restoreGamma()
for value = 0.0, 1.0, 0.01 do
  for _,screen in pairs(hs.screen.allScreens()) do
    gamma = screen:getGamma()
    gamma["whitepoint"]["red"] = 0.0
    gamma["whitepoint"]["green"] = 0.0
    gamma["whitepoint"]["blue"] = value
    screen:setGamma(gamma["whitepoint"], gamma["blackpoint"])
    hs.timer.usleep(100000)
  end
end
hs.screen.restoreGamma()
```

@peterhajas how does this API look to you? I'm fairly certain that a combination of hs.timer, this API, and for bonus points, the sunrise/sunset calculator in hs.location, we could come up with a pretty decent replacement for f.lux.

**Comment by cmsj** [comment]
It's certainly not an efficient bit of code, and there's an extraneous commit moving a window shadow API to another extension in the middle, but https://github.com/Hammerspoon/hammerspoon/compare/459f77e8f7e2949a216a322ec80878df0dbba86c...54c67a2cd1d62eac16dee0792063d368f40c0dbb 
seems to be working pretty well. I've tested it across almost all of the display changes that can happen (notable exception: GPU switching, which I expect will not work at all well).
One particularly ugly feature is that the callback registered with CGDisplayRemoveReconfigurationCallback() currently re-applies gamma settings to changed display layouts after a fixed delay (3 seconds) because even though, at the point that callback is called with something other than a kCGDisplayBeginConfigurationFlag flag, the display reconfiguration is supposed to be completed, I am finding that if I immediately reapply the gamma, the screens refresh with their stock ColorSync profile. It would be nice to find a way around that!

**Comment by cmsj** [comment]
0.9.28 is now out, which includes the new fooGamma() function/methods. We can iterate on the gamma re-application callback delay, and try and figure out a way to handle GPU switching, later.
(on the GPU switching, I'd note that gfxCardStatus is open source and on github, and probably the best example one could hope for on how to interact with IOKit for getting GPU info. It also looks like a bit of a nightmare of whitelisting/blacklisting!).

So, I'm going close this issue out now, we can open up new ones if/when the above details become necessary to address.

**Comment by peterhajas** [comment]
@cmsj Wow, thanks for all the investigation on this (and your tenacious work on Hammerspoon). Much appreciated!

I think the current API looks pretty approachable. Thanks for changing it and doing the investigation!

**Comment by cmsj** [comment]
@peterhajas np! If you do get a useful f.lux replacement going, please let me know, I'd love to have that!

**Comment by peterhajas** [comment]
@cmsj First pass at that here: https://github.com/peterhajas/dotfiles/commit/05e9a63aac0dc5ce339fa6a39a8cfad0df8611c6

Next up - toggle switches and Redshift mode!
