### ISSUE TITLE
hs.urlevent.httpCallback broken in latest version

### ISSUE THREAD

**Issue by kgutwin** [Hammerspoon/hammerspoon#2508]
I have been using `hs.urlevent.httpCallback` for a while, something like this:

```
hs.urlevent.httpCallback = function(scheme, host, params, fullURL)
    hs.alert.show("clicked " .. fullURL)
end
```

With the latest update (0.9.80) any http link I click results in the following error:

```
2020-09-23 09:15:40: *** ERROR: ...oon.app/Contents/Resources/extensions/hs/window/init.lua:950: attempt to index a nil value (global 'uielement')
stack traceback:
	...oon.app/Contents/Resources/extensions/hs/window/init.lua:950: in metamethod 'index'
	/Users/kgutwin/.hammerspoon/init.lua:54: in function 'hs.urlevent.internal.httpCallback'
	(...tail calls...)
	[C]: in function 'xpcall'
	...n.app/Contents/Resources/extensions/hs/urlevent/init.lua:41: in function <...n.app/Contents/Resources/extensions/hs/urlevent/init.lua:34>
```

This may be related to the known issues with `hs.window` under #2488, but I'm not sure.

**Comment by asmagill** [comment]
Is this your actual callback, or a shortened version?  I ask because, yes, this is related to #2488, but maybe also to a larger concern about `hs.window` and functions vs methods.

In 0.9.78 and earlier, `hs.window` shared its module table with its object metatable and inherited some stuff from `hs.uielement`.  Sometime after 0.9.78, `hs.window` and `hs.uielement` were re-written to be more clearly separated... the specific `uielement` error you are getting above was because some of the code used in the old `hs.window` to fallback to checking `hs.uielement` if a function was missing hadn't been removed. This has been in the second part of #2488.

The *larger concern* I mentioned is the distinction between functions and metamethods. Functions are defined at the module level and are available without first creating an `hs.window` object for a specific window, e.g. `hs.window.focusedWindow()` which in fact *creates* an `hs.window` object. Methods are traditionally *only* available at the object level, not the module level, and would be invoked as something like `obj:isStandard()`.

However, in the earlier versions of `hs.window`, the module and the metatable defining metamethods *were the same table*. Strictly speaking there is no provision against this, but it's not a common practice, in my experience.

What this means in practice is that in 0.9.78 and earlier, the following were functionally identical:

~~~lua
obj = hs.window.focusedWindow()
print(obj:isStandard())
~~~

and

~~~lua
obj = hs.window.focusedWindow()
print(hs.window.isStandard(obj))
~~~

Now, the second one won't work because `hs.window.isStandard` is no longer in the metatable for `hs.window` objects. (I have used `isStandard` in my examples but this separation applies to all methods in the `hs.window` documentation that are identified as methods (e.g. have a colon rather than a period before the final component) as opposed to those identified as functions.

The reason I asked above if the example code you gave was actually the true callback or not is because there does not appear to be any use of the `hs.window` module in either `hs.urlevent` or `hs.alert`, so this function/module confusion can't be coming from these (at least not directly).

**Comment by kgutwin** [comment]
Thanks so much for the detailed explanation! I confess that I'm still not well-versed in Lua concepts, so I'll need to re-read your comment a couple times before I think I understand, but in the meantime, here's the full callback I have:

```
hs.urlevent.httpCallback = function(scheme, host, params, fullURL)
   local browser = "Safari"
   if string.find(fullURL, "meet.google.com") then
      browser = "Google Chrome"
   end
   if string.find(fullURL, "chime.aws") then
      browser = "Google Chrome"
   end
   local safari_app = hs.application.get(browser)
   local w = 0
   if safari_app == nil then
      w = 0
   else
      w = safari_app:allWindows()
      w = table.filter(w, hs.window.isVisible)
      w = #w
   end
   if (w > 0 or browser == "Google Chrome") then
      hs.alert.show("window on screen")
      hs.osascript.applescript(
	 'tell application "' .. browser .. '" to open location "' .. fullURL .. '"')
   else
      hs.alert.show("no window")
      hs.osascript.applescript(
	 'tell application "' .. browser .. '" to make new document with properties' ..
	    ' {URL:"' .. fullURL .. '"}')
   end
   hs.osascript.applescript(
      'tell application "' .. browser .. '" to activate')
end
```

The goal here is to intercept URLs that I click and do a couple of things:
* If the URL matches a certain string, direct a specific browser to open it, otherwise go to the default browser
* If the browser has any visible windows (or it's Chrome), then run a fragment of AppleScript to tell the browser to open the URL, otherwise run a different AppleScript fragment to open a new browser window.

The purpose here is straightforward -- first, some URLs are only supported by Chrome, but in general my default browser is Safari; second, I want Safari to open a new browser window when there isn't one visible, even if there is a browser window open on some other Space.

You can see that I'm using `hs.application.get` to get the application, then `app:allWindows()` to get a list of its windows, and then `table.filter(app_windows, hs.window.isVisible)` to count if there are any currently visible windows. If you have any suggestions on how to write this that doesn't trigger the error, it would be very helpful!

**Comment by asmagill** [comment]
I think the line in question is:

~~~lua
      w = table.filter(w, hs.window.isVisible)
~~~

First, `table` usually refers to the lua builtin library and it doesn't have a `filter` function... I know some luarocks extend it, so if you're using one, ignore this thought... or if you've done `local table = require("hs.fnutils")` in your code, it should also work, but is generally considered a bad idea because it blocks local usage of the original lua `table` library.

Second, this would have otherwise worked with 0.9.78 or earlier (and I've actually posed the question about possibly making it work again at https://github.com/Hammerspoon/hammerspoon/pull/2488#issuecomment-697943262) but to be absolutely safe, and to maintain the method/function distinction, (and more importantly to you, to work *right now*), it should be changed to:

~~~lua
      w = table.filter(w, function(o) return o:isVisible() end)
~~~

Or, assuming you aren't using a re-defined `table` library, I would code it as:

~~~lua
      w = hs.fnutils.filter(w, function(o) return o:isVisible() end)
~~~

**Comment by kgutwin** [comment]
Thanks for the guidance, this is super helpful. I think I understand now 😄 I'll give this a try in a bit.

**Comment by kgutwin** [comment]
I finally got around to testing this - this solved my problem, thanks!

**Comment by csteinlehner** [comment]
> I finally got around to testing this - this solved my problem, thanks!

Hi @kgutwin I want to do exactly the same, can you share your solution? It seems I don't even get the callBack. Do you want to share the full script?
