### ISSUE TITLE
`hs.reload` randomly crashes post-update

### ISSUE THREAD

**Issue by smackesey** [Hammerspoon/hammerspoon#2521]
Not sure if this is something specific to my (fairly complicated) configuration, but I've found that reloading hammerspoon's config (either by clicking the button in the console window or via `hs.reload`) randomly crashes Hammerspoon (maybe 20% of the time?) since updating from 0.9.78. Including a Crash Report from Console.app for your convenience:

[Hammerspoon_2020-09-26-145550-1_stm-mbp-2016.crash.txt](https://github.com/Hammerspoon/hammerspoon/files/5287388/Hammerspoon_2020-09-26-145550-1_stm-mbp-2016.crash.txt)

**Comment by asmagill** [comment]
Which version of Hammerspoon are you running (0.9.79 or 0.9.80)? There is a known crashing bug with `HSuicore.m` in 0.9.79 that should have been fixed in 0.9.80, so knowing the version will tell us if this has already been addressed or if this is something new.

If you're not sure, you can type `hs.processInfo.version` into the Hammerspoon console.

**Comment by smackesey** [comment]
0.9.80

**Comment by asmagill** [comment]
💩, that means its something new... or the last fix wasn't complete... it's only happening during a reload, correct? Do you happen to know what you're using in your code that utilizes a window watcher? `hs.window.filter` or something that uses it? a specific Spoon? one of your own custom callbacks?

From the crash log it doesn't look like the crash is occurring during the collecting and release of the outgoing Lua state, which is different... I'll take a closer look at `HSuicore` and see what might be able to persist through MJLuaDestroy (maybe an already queued callback? but the callback deref should scotch that...), as off the top of my head I can't think of anything that *should*.

**Comment by smackesey** [comment]
Yes, only during a reload (that I've observed). Though, I'm not 100% confident that it wouldn't happen in other conditions, as I've recently been changing config and reloading a lot.

The only code I'm aware of I have that uses a window watcher (I think this qualifies?) is below. Both of these functions are called on reload:

```
-- ----- APP

-- Listen for changes in the active application or application termination
-- events. On either of these events, refresh the `windowTap` (so that it is now
-- listening on a new application). When a new application is activated,
-- trigger the window change callback.
function m:makeAppTap()
  self.appTap = hs.application.watcher.new(function (name, eventType, app)
    local activated = (eventType == hs.application.watcher.activated)
    if activated then
      self.windowTap:stop()
      self:makeWindowTap(app)
      self.windowTap:start({hs.uielement.watcher.focusedWindowChanged})
      local win = app:focusedWindow() or nil
      self:broadcast{
        application=app:bundleID(),
        window=(win and win:title() or nil)}
    end
  end)
end

-- ----- WINDOW

function m:makeWindowTap(app)
  app = app or hs.application.frontmostApplication()
  self.windowTap = app:newWatcher(function (element, event, ...)
    -- when the last window for an app closes, but the app remains empty, el
    -- will be a raw `hs.uielement` object, which we don't want to deal with.
    self:broadcast(getmetatable(element).__name == "hs.window" and
    {window = element:title()} or
    {window = nil})
  end)
end

return m
```

**Comment by smackesey** [comment]
Here's another tidbit that might help. I just tested quitting and restarting HS several times, and I got crashes at about the same rate. So it apparently doesn't have to do with reloading per se, but rather something that happens on either startup or reload.

**Comment by smackesey** [comment]
More info: it appears that the `windowTap` in the provided code is the issue. If I never call `windowTap:start()`, I don't get any crashes.

**Comment by latenitefilms** [comment]
Just quickly skimming on my phone, looking here:

https://github.com/Hammerspoon/hammerspoon/blob/6ddf4e5fa2667ac53c26c2976d18669db5f12d5d/Hammerspoon/HSuicore.m#L317

...is the below missing?

`CFRelease(self.elementRef);`

**Comment by asmagill** [comment]
I think you're on to something... if I'm reading the code correctly, there are three cases where `-(HSuielement *)initWithElementRef:(AXUIElementRef)elementRef` is invoked without adjusting the retain count for the element (2 of them do adjust the retain count for the element being stored in another object, but unless we know with 100% certainty which object will go out of scope first, it's a less than ideal situation)...

The proper fix, as I see it, is to retain in the initializer, release in the dealloc, and adjust the one location that does pass in a retained element so it also releases (thus maintaining the balance).  I think I can have something for you to test shortly...

**Comment by asmagill** [comment]
@smackesey if you're able to build Hammerspoon yourself for testing, I ask that you do so with #2522 applied and let me know if it makes a difference.

I've tried a variant of what you're doing:

~~~lua
appTap = hs.application.watcher.new(function (name, eventType, app)
--     print(name, eventType)
    local activated = (eventType == hs.application.watcher.activated)
    if activated then
        if windowTap then windowTap:stop() end
        windowTap = app:newWatcher(function (element, event, ...)
--             print(getmetatable(element).__name)
            if getmetatable(element).__name == "hs.window" then
                print("Window Title:" .. element:title())
            else
                print("No Window")
            end
        end):start({hs.uielement.watcher.focusedWindowChanged})
    end
end):start()
~~~

both with and without the pull applied but can seem to get the crashes you are... I'll let it run for a while without the fix and see if I've just been lucky, or maybe don't have enough going on to trigger the issue to see, but since you're experiencing the issue, your setup will be the best testbed.

**Comment by smackesey** [comment]
OK, I've tested the problem with the branch you posted and it appears to be fixed. I also noticed that reloading was noticeably slower, but perhaps this is just a function of using a Debug build?

**Comment by asmagill** [comment]
I have been running a development branch for so long that I don't notice any more, but yes, I think it's very probable that it is a little slower because of Xcode features enabled during a Debug build that help with memory usage tracking and provide other profiling and debugging details.

Thanks for the update re the pull, and keep me posted if anything changes!

**Comment by asmagill** [comment]
@smackesey can we consider this issue closed?

**Comment by smackesey** [comment]
yes
