### ISSUE TITLE
Review testTabs and testFrontmostApplication tests on Catalina

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2527]
As discussed [here](https://github.com/Hammerspoon/hammerspoon/pull/2523#issuecomment-699804260), the `testTabs` and `testFrontmostApplication` are failing for @asmagill on macOS Catalina 10.15.7 with Xcode 12.0.1 (12A7300), whereas they're passing for me on macOS Mojave 10.14.6 with Xcode 11.3.1. Travis CI already skips these tests.

**Comment by asmagill** [comment]
Re `testTabs `, it's because Safari 14 handles tabs in a custom way... the existing code in `HSuicore.m` doesn't see them. Not sure yet of a work around (it's probably a different AXUIElement type we'll need to look for if the first check returns 0, not sure yet), but for now it's probably safe to say that if anyone is running Safari 14, the tab functionality of `hs.window` probably doesn't work.

Investigating.

**Comment by latenitefilms** [comment]
Ah, interesting. I was using Safari 13 on my MacBook Pro, but I've just updated to Safari 14, so I'll see if I can reproduce too.

**Comment by asmagill** [comment]
`testFrontmostApplication` appears to be a timing thing, at least when I manually try what the test does:

Given:

~~~lua
function testFrontmostApplication()
  hs.openConsole()
  local app = hs.application.frontmostApplication()
  app:activate()
  assertIsNotNil(app)
  assertTrue(app:isFrontmost())
  assertTrue(app:setFrontmost())

  return success()
end
~~~

I tried something like this:

~~~lua
> hs.hotkey.bind({"alt"}, "b", function()
  hs.openConsole()
  local app = hs.application.frontmostApplication()
  app:activate()
  print(app, app:isFrontmost(), app:setFrontmost())
end)
table: 0x606000b3c360
~~~

Now, if I tap `alt-b` when the Hammerspoon console is in the foreground, of course I get:
~~~
hs.application: Hammerspoon (0x606000941cf8)	true	true
~~~

But if I go to another application and *then* tap `alt-b`:
~~~
hs.application: Hammerspoon (0x60600029d238)	false	true
~~~

I can't recall the last time I ran the tests on my machine before the recent questions about them, so I can't say if this behavior is an artifact of changes we've made, because I'm running Catalina, because I'm using Xcode 12, or because my machine is older and thus a little slow compared to some.

**Comment by latenitefilms** [comment]
I think it's safe to close this issue then. Thanks!
