### ISSUE TITLE
What's the difference between Hammerspoon and AppleScript or JXA?

### ISSUE THREAD

**Issue by nomasprime** [Hammerspoon/hammerspoon#2556]
Apart from the language obviously.

**Comment by nomasprime** [comment]
[Similar question asked on HN](https://news.ycombinator.com/item?id=21801514).

Comments suggest it comes down to language preference, support, and maybe Hammerspoon can do more but not really any specifics.

The specifics are very relevant because it sounds like if you already know AppleScript, you're probably better off sticking with it.

**Comment by latenitefilms** [comment]
Hammerspoon, AppleScript & JavaScript, can all basically do exactly the same things - but depending on what you're doing something it's just easier and faster to use Lua and Hammerspoon, because a lot of the hard work has already been done in Hammerspoon's built-in extensions.

For example, the simple task of having global shortcut keys for things is easy in Hammerspoon, but a lot harder to do in AppleScript & JavaScript. If you need to work with websockets, or TCP/UDP sockets, or MIDI, or serial connections - Hammerspoon has tools that make this incredibly simple.

Hammerspoon is insanely powerful - we've built a whole app using it as the core - [CommandPost](https://CommandPost.io).

**Comment by nomasprime** [comment]
Thanks @latenitefilms, that's expressed the motivation nicely and the additional utility of the built-in extensions wasn't clear before, sounds good.

Will start spiking out some personal use cases 👍
