### ISSUE TITLE
How to find all opened windows for a App

### ISSUE THREAD

**Issue by akahanaton** [Hammerspoon/hammerspoon#2585]
Hi,
Is it possible to find all active window for a App?  For example, I opened two Google Chrome instance,  How to get the both the two Window handle?  The docs of "hs.window.find(hint)" says:  "one or more hs.window objects that match the supplied search criterion, or nil if none found". But only one window handle is reported in my scripts when I try 'hs.window.find("Google")' or 'hs.application.find("Google")'.
I also tried 'hs.application:findWindow("Google")', but an error reported
`[string "return hs.application:findWindow("Google")"]:1: attempt to call a nil value (method 'findWindow')
stack traceback:
	[string "return hs.application:findWindow("Google")"]:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:514: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:494>`.
Am I wrong in using that function?

Thank you so much.

Best regards,

**Comment by akahanaton** [comment]
Ok, "Google chrome" is a wrong example, there is only one instance even you opened two windows.
Please try hs.window.find("Finder") instead. thanks

**Comment by dasmurphy** [comment]
If you want to get all returned elements in one table, you can use this:

```lua
local result = { hs.application.find("Finder") }
```

This converts the results to a table which you can iterate. And you get an empty table when the result is nil. `#result` gives you also the count of the found items.

**Explanation**: The find function does not return a table itself, instead it returns as much values as it finds. The `{ }` around the function call converts all the results to a table. That is all. It is easy, but someone needs to know this stuff ;) I had a similar problem not long ago.

---

**Extra**:

You can also use this:

```lua
local result = table.pack(hs.application.find("Finder"))
```

Then you will have a `result.n` value which has the count of the table items in it, but i think this is not the best solution, because you cannot iterate on all elements, since the `n` is there.

I hope this helps with your programming.

**Comment by akahanaton** [comment]
Hi, thank you very much, it solved my problem.
