### ISSUE TITLE
Building HS just failed on Mojave

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#2618]
I just found that building HS failed on Mojave.  Is this expected?

```
make release
mkdir -p build
echo "Building Hammerspoon in Release configuration"
Building Hammerspoon in Release configuration
rm -rf build/Hammerspoon.app
xcodebuild -workspace Hammerspoon.xcworkspace -scheme Release -configuration Release clean build > build/Release-build.log
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Compile\ docs.json /Users/chdiza/Library/Developer/Xcode/DerivedData/Hammerspoon-adlzscacpnutjgcpsrpwvdewubqc/Build/Intermediates.noindex/Hammerspoon.build/Release/Hammerspoon.build/Script-4FC09F7A19F99E48007542A6.sh
(1 failure)
make: *** [build/Hammerspoon.app] Error 65
```

**Comment by chdiza** [comment]
A little digging reveals:

```
make[1]: scripts/docs/bin/build_docs.py: No such file or directory
make[1]: *** [build/docs.json] Error 1
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by chdiza** [comment]
The failed build is 1459fec9f923ababca09549, BTW.

**Comment by asmagill** [comment]
The latest builds require python3 for the documentation scripts. I think if you change the first line in `docs/bin/build_docs.py` to `#! /usr/bin/env python3` instead of `#! /usr/bin/python` and then make sure that you have `python3` installed via `brew` or similar, it should work for you (you probably also need to run `pip3 -r requirements.txt` or `python3 pip -r requirements.txt` the first time as well, I forget which syntax is preferred).

@cmsj, for portability reasons, in the Raspberry Pi world when they changed from python2 to python3 as the standard, most scripts began starting with `#! /usr/bin/env python3` instead of hardcoding the path to the python2 or python3 binary.

**Comment by chdiza** [comment]
> starting with #! /usr/bin/env python3 instead of hardcoding the path to the python2 or python3 binary

Indeed, that would've prevented the failure on my machine, since I do have a python3 on my $PATH (just not at `/usr/bin`).

**Comment by cmsj** [comment]
I kinda deliberately went with `/usr/bin/python3` so it uses the OS provided Python, rather than leaving it up to chance whether it's the OS one or a Homebrew/MacPorts/etc version. This does make it harder to build Hammerspoon on older versions of macOS that don't ship with Python 3, but the alternative is running the risk that CI gets even more broken if/when GitHub does something with Python in their macOS images.

**Comment by latenitefilms** [comment]
I'm still on Mojave, so also ran into this. Dumb question... is there a way to select the Python path based on the version of macOS you're running?

**Comment by latenitefilms** [comment]
Could you just remove the "shebang line" all together, and execute the "correct" version of Python from Xcode/release script directly?

**Comment by asmagill** [comment]
@latenitefilms there are a few syntactical differences between python2 and python3... not sure if our code stumbles into them or not, but in my experience, it's generally best to stick with one or the other and use separate scripts if you need to, rather than try to detect at run time which you're running within a given script.

@cmsj, my opinion on the matter is to move to the `#! /usr/bin/env python3` approach -- it's a well established practice in the Linux world and should still work with CI as long as they stay even close to the macOS layout for Catalina+ unless they're playing merry hob with PATH, in which case `/usr/bin/python3` might also be up for grabs. We can go the hard coded route if it's really more reliable with CI (which is already pretty #^%$#$@#%^ unreliable) when we shift to HS 2.0, since we're already discussing nixing pre Big Sur at that point. Just my 2 cents...

**Comment by latenitefilms** [comment]
Sorry, I wasn't suggesting you use `python2` on Mojave, I was more trying to think up a solution where the `python3` script will work nicely on both Mojave, Catalina & Big Sur - however, I think your suggestion of `#! /usr/bin/env python3` is the best one anyway. I didn't realise I needed up update all the requirements, `pip`, etc to work with `python3` on anyway - so after a bit of mucking around, I got it all working anyway - so all good.
