### ISSUE TITLE
Nominations for 0.9.83

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#2681]
Please propose things here for 0.9.83. No set time limit, but it's been ~3 months since the last release, so it's probably time to think about doing another to collect up some stuff.

**Comment by cmsj** [comment]
@asmagill anything you'd like to see land for 0.9.83? I'm happy to do the release whenever you're ready.

**Comment by asmagill** [comment]
I'm currently working on a fix for `hs.notify` that doesn't leak memory like a sieve... another day, two at the most? I also want to take a quick look at the other remaining pulls and see if any of them can be polished and made ready within a similar time frame.

**Comment by latenitefilms** [comment]
These should hopefully be pretty easy fixes:

- Crash/Freeze - `hs.json.encode()` #2673
- Console Auto-completion Bug #2276

This one, I'm pretty sure, was related to Screen Recording permissions being disabled, so should be fixable?

- [Catalina Only] Crash - `MJConsoleWindowController.m` line 74 #2206

I'm not sure if this one is fixable, given you're both now on Big Sur?

- Bug in hs.brightness.set() #2312

This one might just be a documentation tweak?

- Arrow keys return `fn` flag when using `hs.eventtap`? #2074

These should be pretty close to release, pending @asmagill's review:

- Added `hs.eventtap.event.newGesture()` #2512
- Add method to `hs.eventtap.event` to capture touch data for events of type `NSEventTypeGesture` (29) #2493

This one probably requires @asmagill's genius:

- Cannot withdraw notifications from previous session #2241

This one would be nice to have:

- Add function to check for "Full Disk Access" permissions #2383

**Comment by luckman212** [comment]
Selfishly, I'd love to see `hs.window` get some love 😊

- [hs.window:frame() returning stale / incorrect values? · #2671](https://github.com/Hammerspoon/hammerspoon/issues/2671)
- [Beachballin' (~5s) in LuaSkin when activating `hs.window.filter:subscribe()` during init · #2596](https://github.com/Hammerspoon/hammerspoon/issues/2596)

And if this one isn't too tricky:
- [Whitespace not on first line of a multiline string gets lost when passing to hs.alert · #2617](https://github.com/Hammerspoon/hammerspoon/issues/2617)

**Comment by latenitefilms** [comment]
This might be another relatively easy one to tick off @cmsj ?

- `hs.chooser` rows off by two when toolbar attached #2179

**Comment by dcai** [comment]
I cannot wait to see hs.screen:name issue got fixed in coming release: https://github.com/Hammerspoon/hammerspoon/pull/2676

Do we have a nightly or weekly build somewhere?

**Comment by latenitefilms** [comment]
No, however you can build it yourself relatively easily.

**Comment by jubr** [comment]
Perhaps a way to revive `hs.menubar:priority()` that broke since Catalina?

Edit: just found #2197, did anything change since then? Still on Catalina here btw.

**Comment by cmsj** [comment]
@asmagill Is there anything you have left you want to land for 0.9.83? I'm not sure I have it in me to properly fix #2179, but I'll take another look, otherwise we're at a point where we could release (with apologies to everyone who's asked for other stuff on here)

**Comment by asmagill** [comment]
@jubr unless Apple has introduced new methods regarding NSStatusItems or NSStatusBar, there is no longer a way to specify menubar item priority or even a reliable way to specify initial position. I don't think this is likely to change.

@cmsj unless you have any objections, #2691 is ready. As to chooser, my forte is with building display items by hand... using nib's and auto-constraints to enforce layout isn't something I'm familiar with, so I can't really help there.

@luckman212 hs.window.filter just needs to be completely re-written; that's not going to happen in time for this release, but maybe for the next. I'll see about incorporating it with #2554 (which should *not* be considered ready for this release, @cmsj).

Do we not have a check for full disk access? Huh, I thought that was already in there.

I'd like to see my notification changes landed, and maybe my gesture additions (I've noted this in their respective  conversations and the notification should have been pushed before this one). Otherwise I'm fine with a release going out sooner rather than later.

- - -

FWIW, I'm currently working on the following, but they won't be ready for this release:

* hs.host.sysctl -- allows accessing machine state info via sysctl, but I still need to document it and hope to add a few more conversion functions (it reports everything as raw data, so we have to use `string.unpack` to turn things back into human usable form -- it already has relative parity with the command line version, but am currently looking into conversions for the network related stats). Probably a couple of days.
* hs.host.iokit -- will allow for IOKit queries and some basic searching. I *think* this will have a watcher as well, which should simplify releasing things similar to our usb/fs watchers, etc. in the future) This is a precursor to...
* hs.battery -- needs to be rewritten to work with the M1 macs; the module has used functions that, while not quite deprecated, have been "not recommended" for a long time and finally don't work at all on M1 macs... *most* of the data can be found in consistent locations within the IOKit registry. Could be ready in a week or two, maybe.
* hs.axuielement -- Pull request #2554 in progress (and in conjunction with this, the hs.window.filter rewrite). No ETA, but hopefully within the month?

**Comment by cmsj** [comment]
Ok thanks. I'm going to consider the nominations period closed, and I think I have everything now associated with https://github.com/Hammerspoon/hammerspoon/milestone/15

**Comment by asmagill** [comment]
@cmsj, do you want me to land #2691, #2512, and #2493 or do you want to do it? I don't want to accidentally interfere with anything you might be working on during your automation tests.

**Comment by cmsj** [comment]
@asmagill yeah I’m sorry about all the commit spam on the automation stuff. I tried doing it on a fork, but it wasn’t working well. I’ll fry and figure out what that is about, so we don’t have quite so much noise here.

as for the landing, if I don’t get to it during the UK day today, please feel free to land them :)

**Comment by cmsj** [comment]
Landed all three.

**Comment by dhruvasagar** [comment]
`hs.application.hide()` no longer working.

**Comment by dhruvasagar** [comment]
Fixed! Thanks.
