### ISSUE TITLE
Stability idea

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#2687]
I've been looking through crashes in Sentry and it seems like a lot of them crash deep inside Lua after entering via a C callback.

I'm wondering if this is LuaSkin lifecycle related - eg we're reloading and C callbacks get triggered while we're in a weird state.

I have an idea for how to confirm this hypothesis - @asmagill do you see any issues with setting each module's refTable to REFNIL in the module-level __gc function? If I'm right, that would turn all of the crash reports into pushRef exceptions, and we can guard them all.

**Comment by asmagill** [comment]
No objections. Not all modules have the meta_gc defined, so expect to have to do so in at least some cases.

Will this make a difference with modules that are loaded by the initial `init.lua`? Even with clearing refTable, this will be reset as soon as the module is loaded again, even if the callback is in fact a holdover.

**Comment by cmsj** [comment]
Huh, that's a good point, we may actually be using a refTable that doesn't match the lua_State currently considered prime.

Any ideas for dealing with this more intelligently?

**Comment by cmsj** [comment]
This all suggests that having the bare `refTable` variables was a mistake.

@asmagill how about this:

 * instead of returning a Lua reference, the LuaSkin `registerFoo` methods store the refTable in a dictionary with the key being a UUID, and they return the UUID
 * modules now have to ask LuaSkin for the refTable value by passing it the UUID
 * any mismatch between the two is immediately visible and we can bail out.

The patch for implementing that would be pretty substantial, which makes this hypothesis quite expensive to test, but in theory we'd still be making ourselves more robust even if this doesn't shake out some of the mysterious Lua crashes.

Thoughts?

**Comment by asmagill** [comment]
The problem I can for-see with this is that independent blocks refer to `NSString *` and `const char *` by pointer... wouldn't that mean that changing the value when loading the module after a reload would change the value seen within the independent blocks?

We'd need to test it, but I fear we'd need to change every callback block so that it made a local copy of `refTable` and that would be... annoying.

What if we kept it an integer, but made it a random number over the entire `int` range and then dereferenced *that* against a lookup table within LuaSkin to get the actual regitry index?

Unless *all* variables within blocks are accessed by reference... is there any definitive documentation on this or do we need to craft some tests?
