### ISSUE TITLE
hs.axuielement causes Accessibility Popup on Startup

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2702]
I'm pretty sure we've had this discussion before @asmagill - but I'd suggest that `hs.axuielement` doesn't actually trigger `hs.accessibilityState(true)` on startup. The reason being, is that it kinda then makes `hs.accessibilityState()` useless, as the user will have already had the popup.

Thoughts?

```lua
if not hs.accessibilityState(true) then
    hs.luaSkinLog.ef("%s - module requires accessibility to be enabled; fix in SystemPreferences -> Privacy & Security", USERDATA_TAG)
end
```

**Comment by asmagill** [comment]
My thinking was that without accessibility enabled the module is pretty much useless. And you can still use the method to test, it's just that the possibility of popping up the macOS alert may have passed since Apple only allows that to occur the very first time an app requests access.

However, I'll go with the consensus, if it seems to be causing issues.

**Comment by latenitefilms** [comment]
You're probably right, the current behaviour is maybe more useful for the average Hammerspoon user. I'll just adjust for my specific use-case. Thanks for the fast reply!
