### ISSUE TITLE
`hs.application` constructors returning duplicate objects

### ISSUE THREAD

**Issue by joshkaplan** [Hammerspoon/hammerspoon#2720]
All `hs.application` constructors seem to be returning duplicate objects. I've tested `hs.application.get()` and `hs.window.focusedWindow():application()`.

```
> hs.application.get('Google Chrome')
hs.application: Google Chrome (0x600000f95938)

> hs.application.get('Google Chrome')
hs.application: Google Chrome (0x600000f03ff8)

> hs.application.get('Google Chrome')
hs.application: Google Chrome (0x600000fad6b8)
```

I have also noticed that `hs.application.isFrontmost` now always returns returns `false`. I suspect the two are related?

**Comment by joshkaplan** [comment]
If others are experiencing issues, a temporary workaround for determining the front most application would be to compare bundleIDs:
```
hs.window.focusedWindow():application():bundleID() == hs.application.get('Google Chrome'):bundleID()
```

**Comment by ash14** [comment]
+1, on Big Sur 11.2.1:

Version 0.9.82 (5614)
```
> app = hs.application.frontmostApplication()
2021-03-04 11:21:17: -- Loading extension: application


> app
hs.application: Hammerspoon (0x60000160c6b8)

> app:isFrontmost()
true
```

Version 0.9.83 (5819)
```
> app = hs.application.frontmostApplication()
2021-03-04 11:22:01: -- Loading extension: application


> app
hs.application: Hammerspoon (0x6000022d6f78)

> app:isFrontmost()
false
```

**Comment by dasmurphy** [comment]
I can confirm the bug also on MacOS 10.14.6. All tests from @joshkaplan and @ash14 have the same results.

**Comment by cmsj** [comment]
I rewrote isFrontmost() for 0.9.83 to try and make it more reliable. It seems like I missed something. Thanks for the reports, I'll investigate and probably push out a 0.9.84 quickly to at least revert it.

**Comment by gp42** [comment]
my apologies, opened a similar issue: https://github.com/Hammerspoon/hammerspoon/issues/2721

**Comment by cmsj** [comment]
So just to give a bit of background here, the `hs.application` objects being different C pointers is expected behaviour - hs.application objects are pretty lightweight Objective C objecst that don't contain any state of their own, so it's easier/simpler to create new ones as needed than it is to try and cache/reuse them. We provide Lua metamethods like `__eq` so that comparisons between the objects behaves as expected:

```
> foo1 = hs.application.get('Safari')
> foo2 = hs.application.get('Safari')
> foo1
hs.application: Safari (0x6000026c3e78)
> foo2
hs.application: Safari (0x6000029408b8)
> foo1 == foo2
true
```

The issue here is that `:isFrontmost()` was consistently failing in CI and I decided to rewrite it (24e0b05484fa8495e8af7b0fb2426995d76f008a) to use a different underlying strategy which passes CI, but it turns out that our CI tests for hs.application are not working as intended.

I'm reverting that patch in #2723 and I'll release a 0.9.84 brownbag later today.
