### ISSUE TITLE
macOS spaces identifier?

### ISSUE THREAD

**Issue by bviefhues** [Hammerspoon/hammerspoon#2725]
I am working with code which needs to identify macOS spaces.

`hs.spaces.watcher`unfortunaly does not return a space number to a handler, the handler alsways gets a `-1` argument (at least on Catalina).

There is ` asmagill / hs._asm.undocumented.spaces`which works well for the time being, of course. That's what I use right now. Just does not come with the Hammerspoon installer, requires an additional installation and approving the `internal.so` shared library. 

Is there any other reliable means of identifying the current macOS space?

**Comment by cmsj** [comment]
Unfortunately not - macOS doesn't provide any official API for interacting with Spaces, it's all stuff that happens internally in the Dock process. The `undocumented.spaces` module will probably never be merged into the main repo simply because it's using unofficial API that has already changed several times and could break at any moment.

**Comment by dmitrym0** [comment]
Sorry to dredge this back up, I imagine if it was difficult on Big Sur it's likely even harder on Monterey?
