### ISSUE TITLE
How can Hammerspoon access items in the system menubar?

### ISSUE THREAD

**Issue by joshkehn** [Hammerspoon/hammerspoon#2749]
This topic might be slightly overloaded, since I'm also using [Bartender for macOS](https://www.macbartender.com) to clean up my system menu bar. But, I can't seem to find a way to access the system menubar with Hammerspoon. There are some general system wide status indicators/behaviors I would like to automate which are present in the menu bar and nowhere else. For example, Camo has an "Apps using Camo" status which I would like to read. 

<img width="261" alt="Screen Shot 2021-03-09 at 11 09 37 AM" src="https://user-images.githubusercontent.com/272377/110501255-fc9e1d80-80c7-11eb-8740-08dfc749804d.png">

**Comment by cmsj** [comment]
I don't think there's a direct way for us to do that, but I'm also fairly sure that Bartender added AppleScript support recently, so it may be possible to do it via that?

**Comment by asmagill** [comment]
@cmsj, that's not 100% accurate... we can get at *some* of the menus and see their contents and select the menus via `hs.axuielement`, but it's very application dependent and a royal pain to explore because unlike regular menus, the axuielement objects don't exist until the menu is being displayed -- which means you have to use some tricks to take a snapshot to explore how they're organized. I've put together some initial tests and notes at https://github.com/asmagill/hammerspoon-config-take2/blob/master/_scratch/extrasMenus.lua.

While I agree that it is *way* too early to tell if this is something that can ever have all of the caveats and issues I list addressed well enough that this can be added to Hammerspoon's core, I have zero objections if someone else wants to play with it for a while and see what they can do with it. I probably won't get back to it for some time myself (likely months), so...
