### ISSUE TITLE
Hints enhancement request

### ISSUE THREAD

**Issue by atsepkov** [Hammerspoon/hammerspoon#275]
First of all, thank you. I just started using hammerspoon on my Mac, and was able to bring back about 90% of my Linux's tiling manager's functionality to my Mac as a result. I was also pleasantly surprised by how useful some features I've never considered before are, like window hints. Now, on to the request.

I typically have many windows open and vimperator style for hints works much better for me as a result (the automatic elimination of irrelevant windows is great when I have multiple IMs/emails open and try to drill down to the correct one). I wanted to ask for a couple additional customizations:
1. The app titles vimperator mode uses are great for consistency but are not always the best letters to represent the app. For example, all Google apps will begin with a G, all Microsoft apps will begin with M, iTerm2 uses I. Instead I'd prefer to be able to assign my own letters for frequently used apps ('T': 'iTerm2', 'L': 'Microsoft Lync', 'E': 'Microsoft Outlook', etc.) and have hints select from remaining letters for other apps as it does now.
2. Currently hints module allows a number-based threshold for deciding when to show window titles, is it possible to add a parent-app based threshold? For example, show window titles only when all windows belong to the same app.
3. Could hint rendering order be tweaked to render left-to-right based on coordinates of the hint? Sometimes an app with a long title completely blocks the hint for another app to the right of it. If the hint on the right would be drawn second, it would render on top of the title and having a portion of the title blocked is less of a problem than having the hint combination itself blocked.

Thanks

**Comment by cmsj** [comment]
Let's ping @trishume for his thoughts, since he wrote hs.hints :)

**Comment by trishume** [comment]
Thanks for the comments! Addressing in order:

1. You can kind of do this right now by binding keys that activate hints for all the windows of a certain app. For example I have `ctrl+k` shows me hints for all of my Emacs windows. If you want to do the lua hacking to make this for real be my guest but I think the result would be pretty gnarly.
2. Good suggestion, this is mainly what I actually use hint titles for anyways. Could make it do this for threshold of -1 or something.
3. Not sure how tricky this would be, but a good idea.

I've spent the last 4 months hacking on my Emacs and Hammerspoon setups (have a tabs module PR coming once I've tested it a while) and I just got around to actually doing some other programming with them so for now I don't think I'm up for making these improvements myself. I don't want to spend *all* my time improving my setup, so that I can be more efficient at improving my setup :neckbeard:.

**Comment by echiu64** [comment]
Look at PR #286 for (1), this might help... changes the title completely though and not just the key binding.

**Comment by atsepkov** [comment]
So the idea is to add something like this to my config?

hs.hints.titleRegexSub = 's/(Google|Microsoft)\s//'

Can I chain these so that I don't have to create an ugly cumulative regex to strip the leading 'i' from iTerm as well?

**Comment by echiu64** [comment]
Format is like this: { key = { pat="<gsub_pattern>", sub="<gsub_replace>" }, ... }

So you could break that into 2 with:
```
{ MSApps={pat="Microsoft%s*", sub=""}, Chrome={pat="Google Chrome", sub="Chrome"} }
```

**Comment by cmsj** [comment]
I'm afraid I'm going to close this issue out - it seems that nobody has the time to work on it, and having ~200 issues open is not really a reasonable situation for us to be in. If someone wants to work on it, please feel free to re-open :)
