### ISSUE TITLE
hs.websocket sends all messages as WebSocket Binary even when the message is a lua string

### ISSUE THREAD

**Issue by jeffmikels** [Hammerspoon/hammerspoon#2752]
If any of you are using ProPresenter, you probably know it uses a simple websocket interface for remote control.

`hs.websocket` used to be able to talk to it, but it doesn't seem to be working anymore.

I've done a fair amount of testing, and it seems like `hs.websocket` is working fine with every websocket server I've tested it with, but it is not working with ProPresenter for some reason. My guess is that hammerspoon is sending something different in the headers that causes ProPresenter to ignore the data.

Another option is that hammerspoon is having a problem accessing the ProPresenter websocket endpoint. ProPresenter serves web sockets over a subdirectory. Here's the url for my case:

`ws://192.168.10.50:60157/stagedisplay`

Can anyone confirm this problem? Is there a way for me to inspect or modify the websocket headers sent from hammerspoon?

EDIT:
See below... I've determined the problem seems to be that `hs.websocket:send` always sends websocket messages as WebSocket Binary (opcode set to 0x0010) instead of Text (opcode set to 0x0001). Some programs (like ProPresenter) expect Text messages and only listen to text messages.

**Comment by luckman212** [comment]
Sniffing the traffic is a good idea. I'd try https://github.com/ProxymanApp/Proxyman and see if it sheds any light on what's going on.

**Comment by jeffmikels** [comment]
Sniffing the traffic worked... hammerspoon is sending the message as a Websocket Binary message instead of a Websocket Text message. How can I change that?

**Comment by jeffmikels** [comment]
in https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/websocket/internal.m

we have the following:

```objc
/// hs.websocket:send(message) -> object
/// Method
/// Sends a message to the websocket client
///
/// Parameters:
///  * message - A string containing the message to send
///
/// Returns:
///  * The `hs.websocket` object
static int websocket_send(lua_State *L) {
    LuaSkin *skin = [LuaSkin sharedWithState:L];
    [skin checkArgs:LS_TUSERDATA, WS_USERDATA_TAG, LS_TSTRING, LS_TBREAK];
    HSWebSocketDelegate* ws = getWsUserData(L, 1);

    NSData *message = [skin toNSObjectAtIndex:2 withOptions: LS_NSLuaStringAsDataOnly];
    [ws.webSocket send:message];

    lua_pushvalue(L, 1);
    return 1;
}
```

I think the problem might be with `LS_NSLuaStringAsDataOnly`. This appears to set the opcode to Binary ( 0x0010 )

I want to be able to send my message with the websocket opcode set to Text ( 0x0001 )

However, if I change the source code to send as text, that might break someone else's websocket code.

Can you recommend an alternative?

**Comment by asmagill** [comment]
@latenitefilms needs to chime in on this one as he's the one that discovered we had issues with some websocket servers in the past by *not* sending the data as binary.

Assuming the current websocket POD being used supports passing in a message that is an NSString object (which is why we want his input -- I don't recall what changes he had to implement to get this working in the past), the most common approach we've used is to add an optional boolean argument to methods like this.  I'd probably do something like this:

~~~objc
...
    BOOL isData = (lua_gettop(L) > 2) ? (BOOL)(lua_toboolean(L, 3)) : YES ;

    if (isData) {
        NSData *message = [skin toNSObjectAtIndex:2 withOptions: LS_NSLuaStringAsDataOnly];
        [ws.webSocket send:message];
    } else {
        NSString *message = [skin toNSObjectAtIndex:2];
        [ws.webSocket send:message]; // not sure if the same method works or not; consult POD documentation
    }
...
~~~

I'd make sure to note in the documentation that forcing a text representation may alter the data if it contains invalid UTF8 character sequences (the default string behavior is to make sure everything is "printable" by converting invalid sequences into the Unicode Invalid Character sequence -- `utf8.char(0xfffe)` if I'm remembering correctly).

**Comment by jeffmikels** [comment]
@asmagill  Thanks for the quick reply.

**Comment by latenitefilms** [comment]
Yes, I [previously changed it](https://github.com/Hammerspoon/hammerspoon/commit/9d285d62dfe66cea150d7d174c6807ab63efa831) from `LS_NSPreserveLuaStringExactly` to `LS_NSLuaStringAsDataOnly` to make it work with all the websockets I was using.

Adding an optional `isData` argument sounds good to me.

@jeffmikels or @asmagill - feel free to submit a pull request with this change, otherwise, I'll try and do it myself in-between things today if I get a chance.

**Comment by jeffmikels** [comment]
@latenitefilms Awesome! Thank you.
