### ISSUE TITLE
hs.hotkey.bind() mis-handles nil parameter for message

### ISSUE THREAD

**Issue by luckman212** [Hammerspoon/hammerspoon#2761]
_(basically a dupe of #2344 which got closed without comments)_

The [docs for hs.hotkey.bind](https://www.hammerspoon.org/docs/hs.hotkey.html#bind) state that it expects the following params:

```
hs.hotkey.bind(mods, key, message, pressedfn, releasedfn, repeatfn)
                │     │     │          │           │          │    
                └─────┼─────┴──┬───────┼───────────┴──────────┘    
                      │        │       │                           
                      │        ▼       │                           
                      │    optional    │                           
                      │                │                           
                      │                │                           
                      └──▶ required ◀──┘                           
```

However, there seems to be some kind of off-by-one error going on (haven't looked at the code yet) where, if `nil` is passed for `message`, then keydown does nothing (nil), and instead your `pressedfn` function gets assigned to `releasedfn`. This is, as far as I can tell, unexpected behavior.

I also tried passing an empty string `''` to message, but that did not work.

**Comment by luckman212** [comment]
Ok I had a look. Yeah pretty obviously this

https://github.com/Hammerspoon/hammerspoon/blob/1d29cef4f5218201e267dbe5c78b8a0506d3ce25/extensions/hotkey/init.lua#L197-L200

**Comment by luckman212** [comment]
@cmsj or @asmagill any idea why that's there? Maybe for backwards compatibilty with some very old code before the `message` param was added?

**Comment by asmagill** [comment]
I don't know who added the message parameter, or when, but it *was* a later addition to the module. In my opinion, it should have been added as the *last* parameter because it would be extremely easy to detect -- if the last parameter is a string, it's a message; otherwise it's not.

By putting the message parameter in the middle we get this type of confusion... if the third parameter is `nil`, is it a nil message or a nil pressed function? For backwards compatibility with people who never used the message parameter (because it post dates their configurations), we have to assume it's the pressedFn parameter.

There is no solution where it is possible to pass in `nil` for message that doesn't break someone's configuration at this point... the documentation maybe needs to make it more clear, but the fact is that if you don't want a message, then just don't include the parameter at all.

**Comment by latenitefilms** [comment]
As the documentation says `hs.hotkey.bind` is just a wrapper for `hs.hotkey.new(...):enable()`, so really, the `hs.hotkey.bind` documentation should pretty much be identical to `hs.hotkey.new()`, with the added note of its enabled by default.

**Comment by luckman212** [comment]
@asmagill Ok I understand. Yeah that was an odd design choice by whoever decided to stuff that parameter right there in the middle. Guess as @latenitefilms suggests just a stronger mention in the docs might be helpful. Closing.

**Comment by cmsj** [comment]
@asmagill I've found myself wondering recently if, post-1.0, we should try and get rid of optionality on arguments. It's confusing and it makes argument parsing super annoying.

**Comment by luckman212** [comment]
I support the idea @cmsj - rip the band-aid off.

**Comment by asmagill** [comment]
@cmsj, you're talking across all modules? I'm... ambivalent. Filling in unneeded arguments is one the things I *don't* like about more structured languages like C (and Objective-C) and such... though I do agree it requires better documentation and can be harder to parse... I think this particular case just got past us as to the confusion it could cause.

Part of the parsing problem is that it requires a completely different approach lua side than it does Objective-C side. More than once I've found myself doing lua side parameters as `...` so I can stick them in a table and more easily determine how many were passed in and assign to local variables as I figure out which is which...

In my mind, `hs.hotkey.bind(mods, key, fn)` (which is the model I would wager *most* of our users have used most often) reads easier when reviewing code than `hs.hotkey.bind(mods, key, fn, nil, nil)` (or `hs.hotkey.bind(mods, key, "msg",  fn, nil, nil)` if you want to get pedantic about including the message).

However, I don't feel strongly about it, so I'll go with the consensus.

I would argue, though, that if we leave optional arguments in, hotkey should change so that the message goes at the *end*. Partially because it would be easier to check for, partially because I really wonder how many people use it (I don't, so I'll concede I may be wrong on this particular point), and the point of optional parameters is that less commonly used/included arguments should go to the left.
