### ISSUE TITLE
LuaSkin: This library is using an old registerLibrary method on LuaSkin

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2797]
@cmsj - I'm seeing a lot of these errors:

```lua
** Warning:   LuaSkin: This library is using an old registerLibrary method on LuaSkin
```

...which I'm assuming are all @asmagill's extensions, but wonder if there should be clearer error messaging to actually say which extension is using the old method?

**Comment by asmagill** [comment]
FWIW, I modified my local Skin.m file so that the method in question is as follows (around line 403, I think):

~~~objc
- (LSRefTable)registerLibrary:(const luaL_Reg *)functions metaFunctions:(const luaL_Reg *)metaFunctions {
    NSString  *fname = getCallerFileName() ;
    [self logWarn:[NSString stringWithFormat:@"The %@ library is using an old registerLibrary method on LuaSkin", fname]];
    return [self registerLibrary:"Unknown" functions:functions metaFunctions:metaFunctions];
}
~~~

I've since updated most (all?) of my modules and pushed the changes... if you find one I've missed, let me know.

**Comment by latenitefilms** [comment]
Amazing! Will update all the modules this evening!

**Comment by cmsj** [comment]
@asmagill maybe we should merge that difference into LuaSkin? I'm not sure how important it really is though, I don't have the sense that there are really any third party C modules other than yours.

**Comment by asmagill** [comment]
Your call -- that's why I hadn't pushed it myself -- as you can see, @latenitefilms was the first to notice and even he took a couple of weeks 😜

**Comment by latenitefilms** [comment]
I'm going to close this issue for now.
