### ISSUE TITLE
Crash on reload

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2874]
@cmsj - Not sure if there's anything useful in here?

https://sentry.io/share/issue/2ef5c36e237e411582099f6ebb99f51a/

**Comment by cmsj** [comment]
fwiw, changing the `[App Only | Full | Raw]` to `Full` shows a bunch more detail. It's crashing in `LuaSkin luaUnref` when we call `luaL_unref()` because the `freelist` item in `LUA_REGISTRYINDEX` is not an integer. I have no idea currently, how that is possible 😬

**Comment by cmsj** [comment]
We have a similar crash happening with hs.webview https://sentry.io/organizations/hammerspoon/issues/2395995882/?project=5220516

**Comment by latenitefilms** [comment]
It looks like it's crashing on [this line](https://github.com/CommandPost/CommandPost-App/blob/master/extensions/serial/internal.m#L1096)?

```lua
watcherDeviceManager.deviceCallbackRef = [skin luaUnref:refTable ref:watcherDeviceManager.deviceCallbackRef];
```

...although I have no idea why `hs.serial.deviceCallback` is being called on a reload.

**Comment by latenitefilms** [comment]
Ummmm, maybe related, but I'm also seeing a lot of these errors when I'm physically disconnecting and reconnect serial devices:

```lua
** Warning:   LuaSkin: LuaSkin has caught an attempt to operate on an object that has been garbage collected.
```

**Comment by latenitefilms** [comment]
Actually... I'm pretty sure it was caused by a bug in my Lua code - I think I was incorrectly connecting to the same port on two seperate `hs.serial` instances. However, I'm still not sure why this would bug out, as I can't see any obvious issues doing this in the Obj-C code?

Any ideas @cmsj or @asmagill ?

**Comment by cmsj** [comment]
So that message is displayed by the new canary stuff I added - the situation it's detecting is thus:

 * macOS delivers an event to Hammerspoon, which is scheduled to be delivered on a future obj-c runloop iteration
 * Lua is in the middle of doing something while that happens, and either intentionally, or as a side effect of Lua garbage collection, the object that the above event is for, is destroyed
 * the runloop iterates, our C callback for the event is triggered, we fetch the object and run a canary test on it and discover that it is no longer valid, and print that warning message

There are possibly other situations that can trigger that message, but I'm almost certain that any situation where the message can be triggered, is a bug in someone's Lua code.

For your specific case, it could be that by creating multiple objects, one of them was getting garbage collected, or it's possible that ORSSerialPort wasn't designed with the idea of having multiple objects representing a single serial port, and it's delivering the events to whichever object it finds first, even if that's not the one you were expecting it to be delivered to.

My current best guess is that we'll never completely be able to get rid of these messages - users will always be able to write Lua in a way that schedules macOS event callbacks *and* garbage collects the related Lua objects in a single runloop iteration. I was thinking earlier about maybe having the message include a link to our FAQ which explains this in more detail.

**Comment by latenitefilms** [comment]
I think I have my head around how the canary stuff works - however, I'm still confused as to how the error is being triggered, because in theory, each new `hs.serial` object, should have it's own canary ID - so I don't really understand how one object can cause garbage collection to trigger on another object? I'll do some more testing at some point to see if I can get my head around it better.

**Comment by cmsj** [comment]
the canary ID is not per object, it's per Lua instance. What we do is create a UUID every time Lua is created and then copy that string into the canary value in each object so we can tell in a callback if that object is linked to a previous Lua instance.
