### ISSUE TITLE
launchOrFocus("Atom") always launches new application

### ISSUE THREAD

**Issue by phiche** [Hammerspoon/hammerspoon#288]
For starters, awesome project! Feel like a kid in a candy store with no adults around!

I wanted to check with you about an issue I found with Github's Atom editor where the launchOrFocus function does not seem to detect the running application. It always launches a new one.

Something simple like this should produce it:
```hs.hotkey.bind(hyper, "a", function() hs.application.launchOrFocus("Atom") end)```

I guess it must be something odd with Atom itself, because the code works fine for all the other applications I've tried...

Incidentally, I discovered your toggle_application function which works fine with Atom (more awesomeness that I switched my key bindings to now anyway!)

Cheers!

**Comment by oschrenk** [comment]
I actually have the same issue with iterm2

```
hs.hotkey.bind(hyper, '1', function () hs.application.launchOrFocus("iTerm2") end)
```

spawns another instance of iTerm2.

**Comment by phiche** [comment]
What version of iTerm2 are you running? I think they dropped a "2" from the app name several months ago.

Mine works fine, but I use:
```hs.hotkey.bind(hyper, 'f', function() hs.application.launchOrFocus("iTerm") end)```

**Comment by oschrenk** [comment]
I'm pretty sure it's called iTerm2.

![iterm-app](https://cloud.githubusercontent.com/assets/52898/7446132/8fa5a4a2-f1ce-11e4-97a6-1782bc917599.png)
![iterm-menubar](https://cloud.githubusercontent.com/assets/52898/7446133/8fbce9fa-f1ce-11e4-8df3-6b0df6841c28.png)
![iterm-plist1](https://cloud.githubusercontent.com/assets/52898/7446135/8fcfac2a-f1ce-11e4-9783-e6832c111abb.png)
![iterm-plist2](https://cloud.githubusercontent.com/assets/52898/7446134/8fcf9578-f1ce-11e4-8b75-72e255b7b2a7.png)

Is there another identifier I should be aware of?

I test out two cases (in both cases no instance of iterm2 is running):

1. Open iterm2 manually form Applications dir. 
2. Open iterm2 directly with key binding.

if I then switch applications and open/focus iterm2 with the keybinding 

in case 1) a new instance opens
in case 2) iterm2 will be focused

**Comment by cmsj** [comment]
@phiche this is very likely because Atom reports itself as a different name to the OS than its application bundle. You can work around this by figuring out what those names are (inspecting hs.application.runningApplications() with hs.inspect, should help there) and then writing a little function that checks for the presence of a running Atom instance and either focuses it or launches a new instance if it's not running.

I'm not sure if this is something we should be handling - it would be nice to have things magically work, but I'm not sure if this is something we can easily detect and workaround (without maintaining an awful whitelist of applications that do this)

**Comment by asmagill** [comment]
It might be worth putting together a module of utilities like you suggest that help in tracking down/working around oddities... fodder for another thread to suggest what types of tools would be helpful?

**Comment by cmsj** [comment]
@asmagil sounds sane :)

**Comment by phiche** [comment]
@asmagill great idea!
thanks @cmsj!

**Comment by nklmilojevic** [comment]
Did anyone get around this? I'm using Atom, but considering to go back to SublimeText because of this.

**Comment by forestgagnon** [comment]
I ran into this issue suddenly (on OSX El Capitan), and it turns out there were some weird Atom processes running which didn't have any windows, which caused `hs.application.find` to pick up the wrong Atom instance. I fixed it by running `ps aux | grep Atom` and killing all Atom PIDs with `kill -9`.
