### ISSUE TITLE
hs.eventtap.keyStroke not reliable with Cmd-V

### ISSUE THREAD

**Issue by bviefhues** [Hammerspoon/hammerspoon#2889]
This simple keybinding does not work reliably:

```lua
hs.hotkey.bind({"cmd", "shift"}, "v", function()
    print(".")
    hs.eventtap.keyStroke({"cmd"}, "v")
end)
```
 
I really need to repeatedly and fastly type Cmd-Shift-v to get the paste action triggered, a single one never works. The "." on the console shows that the hotkey is triggered on each keypress.

This seems to be specific to the actual keyStroke. Testing with Cmd-, (opening preferences) works reliably.

Big Sur 11.4, Hammerspoon Version 0.9.90 (6030) (but have seen that behavor in earlier versions as well)

**Comment by cmsj** [comment]
I generally advise against trying to emit keyboard events while you're holding down keyboard keys - from the OS' point of view, it sees a Cmd V event, but you're still also holding down Shift, so depending on how it's checking the keys, it may not actually correctly interpret it.

`hs.hotkey.bind()` can take a function that will be called when the key is released, although that still might not do the trick since you're likely to let go of the `v` before the Cmd and Shift. What I would suggest is putting the `hs.eventtap.keyStroke()` call inside an `hs.timer.doAfter()` of about 0.5 seconds or so.
