### ISSUE TITLE
dlsym(0x600002c40700, luaopen_StatusOverview_internal): symbol not found

### ISSUE THREAD

**Issue by ProdigalKnight** [Hammerspoon/hammerspoon#2918]
I'm trying to create an internal module to run some code and after following [this guide](https://github.com/asmagill/HS_ModuleWalkthrough) everything compiles, but at runtime I get the following error

```
error loading module 'StatusOverview.internal' from file '/path/to/StatusOverview/internal.so':
    dlsym(0x600002c40700, luaopen_StatusOverview_internal): symbol not found
```

I have `luaopen_StatusOverview_internal` defined in my code with the proper spelling

```objc
extern int luaopen_StatusOverview_internal(lua_State *L) {
  LuaSkin *skin = [LuaSkin sharedWithState:L];

  [skin registerLibrary:"StatusOverview" functions:hostlib metaFunctions:nil];

  return 1;
}
```

Running `nm -g internal.so` shows that there is a `_luaopen_StatusOverview_internal` in the compiled output (other symbols omitted for brevity)

```
$ nm -g internal.so
0000000000002d70 T _luaopen_StatusOverview_internal
```

**Comment by asmagill** [comment]
That guide is quite old and I haven't reviewed it in ages, so I'm not 100% that everything in it is still current. That said, it *looks* like you've done things correctly -- couple of questions to rule out the basics:

* Is your code (the lua and source files) available online somewhere that I can review more closely?
* Are you doing this on an Intel or M1 mac? The Makefile in that walkthrough predates M1 and I use a different one now (you can view my current Makefile template at https://github.com/asmagill/hammerspoon_asm/blob/master/Makefile_universal_template)
* Are you using Apple's XCode (or the XCode Command Line tools) version of `clang`, or one from MacPorts/Homebrew? I haven't tested with anything other than Apple's XCode, so not sure if there might be differences or not...

I'll review the walkthrough later tonight and see if anything in there jumps out at me as being particularly wrong (and put up a note about it's age)... Probably can't do a re-write until sometime next month, but I'll let you know if I find anything glaring.

**Comment by ProdigalKnight** [comment]
My code is available [here](https://gitlab.com/prodigal.knight/hammerspoon-config/-/tree/master/StatusOverview) (and yes, I'm aware that the `hs.host` module has code to do what I'm attempting in that file, I'm seeing if I can fix some performance issues that I've been encountering).

I'm on an Intel mac, but I'm not sure if I'm using the XCode version of `clang` or a different one - I don't think I installed it via macports/homebrew, but I don't think I have XCode installed either.

**Comment by ProdigalKnight** [comment]
Somehow the issue has fixed itself now, I'm not sure if I even did anything different.

**Comment by asmagill** [comment]
Didn't have as much free time last weekend as I had hoped, so I haven't had a chance to look further into this. Since it seems to have fixed itself for you, let me ask a question -- did you restart Hammerspoon (or your Mac)? Because of the way Mac applications load external libraries, there is no official way to unload a compiled external dynamic library on a reload, so when trying out incremental changes in compiled code, you need to make sure to fully restart Hammerspoon after recompiling and reinstalling an in progress module... `hs.relaunch()` was added for this very reason -- it will fully terminate Hammerspoon and then relaunch it guaranteeing that all libraries are reloaded fresh.

Glad its working for you now, and let us know if you have any additional questions! I'm still hoping to update the module walkthrough in the next month (I have some down time in late August) so if you have any suggestions or thoughts feel free to share those as well.
