### ISSUE TITLE
Crash due to garbage collection

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2931]
Any ideas or suggestions on how I can prevent this from happening @asmagill or @cmsj ?

<img width="1998" alt="Screen Shot 2021-08-14 at 11 18 53 am" src="https://user-images.githubusercontent.com/22286696/129430289-13cd15f6-03bf-4ca2-8814-cd469de8bd1c.png">

**Comment by latenitefilms** [comment]
I'm not sure if this is the best way to do it, but here's my workaround:

```objc
if (type == kCGEventTapDisabledByUserInput) {
        return event;
    }
```

**Comment by asmagill** [comment]
Yeah, eventtaps can be stopped by the system for a variety of reasons, usually due to not responding to events quickly enough or because of some action taken by the user that is considered of higher import... and these messages will be sent to your callback, even if you didn't explicitly list them in the type mask when setting up the tap.

We check for this in `hs.eventtap` and restart the eventtap; not sure if restarting is appropriate in your case -- depends upon what you're using the eventtap for and for how long; See https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/eventtap/internal.m#L35-L42.
