### ISSUE TITLE
hs.layout.apply and multiple windows of same application

### ISSUE THREAD

**Issue by calvinwyoung** [Hammerspoon/hammerspoon#298]
It'd be great if we could pass rules to `hs.layout.apply` such that we can specify different positions for multiple windows of the same app without knowing their window title a priori. I like having 2 Emacs windows side-by-side, and I'd like to create a layout that sets their positions, but their window titles change based on the name of the currently open file.

Slate achieves this by allowing users to pass in a _list_ of positions that get applied sequentially to the different windows of an app. I miss this feature very much, and it'd be great to see it in Hammerspoon as well.

Also, if this is a feature people find useful, I'd be happy to submit a pull request as well.

**Comment by cmsj** [comment]
@calvinwyoung This is an interesting idea. The code for `hs.layout.apply()` is getting pretty hairy at this point, but I'll take a look and see if we can implement this reasonably. Thanks!

**Comment by calvinwyoung** [comment]
@cmsj Awesome, thanks for taking a look! Loving Hammerspoon so far :)

**Comment by kprav33n** [comment]
`hs.layout.apply` is a very handy routine. As @calvinwyoung pointed out, additional ways to select a window would definitely be useful. 

This is kind of orthogonal to what @calvinwyoung suggested. But, I was wondering if it is possible to support regular expression for window title! This would solve some of the cases. Please let me know if I should open a different issue for the regular expression support.

**Comment by cmsj** [comment]
@kprav33n the issue there is that Lua does not have great (or really any) support for regular expressions :/
In theory we could pull in a third party library, but I'm not convinced it's a good idea at the moment.

**Comment by wsmith323** [comment]
I'm a Lua noob and have only used it in Hammerspoon, but I was trying to solve this problem and came across Lua Patterns (http://www.lua.org/pil/20.2.html). Are they supported in Hammerspoon? If so, changing the way the window:title() string is compared and being able to pass a pattern would be very useful. I tried to hack something together, but couldn't make it work, probably due to my meager Lua skills.

**Comment by wsmith323** [comment]
Ok, this ended up being much easier than I expected. See https://github.com/Hammerspoon/hammerspoon/pull/538

**Comment by wsmith323** [comment]
Well, https://github.com/Hammerspoon/hammerspoon/pull/538 was merged, but had to be reverted because it broke backwards compatibility. I have submitted https://github.com/Hammerspoon/hammerspoon/pull/551 as a follow-up.

**Comment by cmsj** [comment]
I think this will also be more fully addressed by `hs.window.layout`, see #547 for some discussion of its features. Now would be a great time to hurl ideas on that issue :)

**Comment by warsaw** [comment]
One possible simple workaround would be for the window element of the table passed to `hs.layout.apply()` to also accept a window object or ID, instead of just a window title or nil.  Then what I could do is something like:

```
emacs_windows = hs.application.get('Emacs'):allWindows()
layout = {
    {'Emacs', emacs_windows[1], nil, nil, '...', nil},
    {'Emacs', emacs_windows[2], nil, nil, '...', nil},
}
```

It wouldn't be perfect and you'd have to repopulate the layout when you created or destroyed Emacs windows, but it would be a start.  Or maybe even just use a count, e.g.:

```
emacs_windows = hs.application.get('Emacs'):allWindows()
layout = {
    {'Emacs', 1, nil, nil, '...', nil},
    {'Emacs', 2, nil, nil, '...', nil},
}
```

It wouldn't be deterministic but it might be Good Enough.

Final thought would be to change `windowTitleComparator` to a more general `windowComparator` and pass it window object, which could then be used to decide which application window should go where.

**Comment by warsaw** [comment]
Oh!  I just noticed that the tables take a function.  That means a decent workaround is:

```
emacs_windows = hs.application.get('Emacs'):allWindows()
first = emacs_windows[1]:id()
second = emacs_windows[2]:id()

geo = hs.geometry.new

function emacs_geo(window)
   if window:id() == first then
      return geo('1920,243/955x1178')
   elseif window:id() == second then
      return geo('2876,243/963x1178')
   else
      return hs.geometry.rect(
         0, 0, window:frame().w, window:screen():frame().h)
   end
end

displays = {
   {'Emacs',             nil, nil, nil, emacs_geo,                  nil},
   {'Emacs',             nil, nil, nil, emacs_geo,                  nil},
}
```

It has the slightly annoying behavior that windows get re-ID'd in the wrong order when the config file is reloaded, but I can certainly live with this!

**Comment by cmsj** [comment]
The window argument can now also be either a single hs.window object, or a function that returns a table of hs.window objects :)
