### ISSUE TITLE
Can't send arguments from the command line to an IPC port

### ISSUE THREAD

**Issue by Thom1729** [Hammerspoon/hammerspoon#2989]
Sorry if this is a basic question, but I've read the docs and the [IPC source](https://github.com/Hammerspoon/hammerspoon/blob/005d208142642a00ce50b9acc09b2583994996ef/extensions/ipc/internal.m) and I can't figure out what I'm doing wrong.

I have the following in `init.lua`:

```lua
local ipc = require('hs.ipc')

function fooHandler(data)
    print('Hello, World!')
    print(data)
end

local port = ipc.localPort('foo', fooHandler)
```

I run the following command:

```sh
hs -m foo -c bar -- baz
```

The command output is:

```
-- Legacy mode enabled --
nil
```

And the Hammerspoon console output is:

```
2021-11-16 12:53:09: Hello, World!
2021-11-16 12:53:09: hs.ipc: foo, local (0x600000075478)
2021-11-16 12:53:09: Hello, World!
2021-11-16 12:53:09: hs.ipc: foo, local (0x60400006c4b8)
```

I would like to access the command line arguments `bar` and `baz` from the handler function. Sorry again if this is really simple, but I've spent hours on this to no avail.

**Comment by cmsj** [comment]
I'm not an expert on `hs.ipc`, so @asmagill may wish to contradict me here, but I don't think it's possible to do what you want to do here, hs.ipc is mostly intended for passing a chunk of Lua code to execute, rather than richly interacting with a specific Lua function.

There is one way you could cheat though, by pretending to be the internal IPC handler for the `hs` command. Below is an example of how to do this, deliberately written to be quite verbose so you can see what's going on, but the result is that you'll get a Lua table (`arguments`) which contains the entire command line, that you can do whatever you want with:

```lua
function fooHandler(_, msgid, data)
  if msgid == 900 then
    return "version:2.0a"
  end
  if msgid == 100 then
    print("fooHandler: received: "..data)

    local jsonPosition=string.find(data, '%[')
    print("fooHandler: found JSON at position: "..jsonPosition)

    local jsonString=string.sub(data, jsonPosition)
    print("fooHandler: found raw JSON string: "..jsonString)

    local arguments=hs.json.decode(jsonString)
    print("fooHandler: decoded JSON to table: "..hs.inspect(arguments))
  end
end
port = hs.ipc.localPort('foo', fooHandler)
```

**Comment by Thom1729** [comment]
Thanks. Maybe I'll write it up as a feature request at some point.

**Comment by ldelossa** [comment]
Hello. Came to this issue because i was also trying to use localPort to just pass some strings to my HS module. 

I understand the responses here. But wondering, what is the right way to get external data into my HS module? Is using a socket the best option?
