### ISSUE TITLE
Hi, I try to build the source with XCode 12.5.1 in Big Sur 11.5.2 and I got following error

### ISSUE THREAD

**Issue by bsdshell** [Hammerspoon/hammerspoon#3050]
#import <LuaSkin/LuaSkin.h> file not found
/Users/me/hammerspoon/hammerspoon/extensions/chooser/libchooser.m:2:9: 'LuaSkin/LuaSkin.h' file not found

**Comment by bsdshell** [comment]
Any help would be appreciated.

**Comment by cmsj** [comment]
So, you're going to find it challenging to build in older Xcode versions on older macOS versions, but it may work.

Did you perhaps open the `.xcodeproj`? You'd need to open the `.xcworkspace` so that LuaSkin gets built before Hammerspoon.

**Comment by bsdshell** [comment]
Yep, I open the .xcworkspace file on Xcode and build it but I still got lots of errors 
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by bsdshell** [comment]
Which XCode version and what version of macOS you use to build it?

**Comment by luckman212** [comment]
@bsdshell Not sure if it will help you, but I recently went through quite a journey (with eventual success) over on #3043

**Comment by cmsj** [comment]
I'm going to close this out, but as a general rule of thumb I am always running the latest versions of both macOS and Xcode, and those are the build target. I know that's difficult for a lot of people, but it's hard enough to keep Hammerspoon building across my machine and the CI environment, without also trying to extend support further.
For what it's worth, right now we can build at least in Xcode 13 on macOS 11, because that's the GitHub CI environment.
