### ISSUE TITLE
Feature Request: Persist variable across refresh

### ISSUE THREAD

**Issue by specter78** [Hammerspoon/hammerspoon#3063]
Refreshing the config file refreshes everything.

I would prefer if some variables can be persisted across refresh (eg. caffeine status).

Theoretically, this can be done using external file. But it would be much more convenient if this was built-in.

**Comment by latenitefilms** [comment]
Use http://www.hammerspoon.org/docs/hs.settings.html ?

**Comment by asmagill** [comment]
There has been discussion of this before and the general consensus in the past has been that this is by design -- a reload or restart is a "starting over".

As suggested, you can use `hs.settings` to save things that you want; I often use a construct like the following in my files so that a default exists if I haven't saved a preference before:

~~~lua
someVariable = hs.settings.get("someVariableLabel") or <default-value>
~~~

You can use `hs.shutdownCallback` to set a function which stores the variables you want to persist right before Hammerspoon restarts or terminates... I think you just assign a function to it like so:

~~~lua
hs.shutdownCallback = function()
    hs.settings.set("someVariableLabel", someVariable)
    ...
end
~~~

The down side is that your data (or changes this time around) is lost if Hammerspoon or your Mac crashes.

I have also used metatables to create "stores" which automatically save state via `hs.settings` whenever a value is set... a bare bones example:

~~~lua
local mVSmeta = {}
local actualVariables = {}
mVSmeta.__index = function(self, key)
    if actualVariables[key] == nil then
        actualVariables[key] = hs.settings.get(key .. "_value")
    end
    return actualVariables[key]
end
mVSmeta.__newindex = function(self, key, value)
    actualVariables[key] = value
    hs.settings.set(key .. "_value", actualVariables[key])
end
-- you could also add __len and __pairs, if you want to be able to iterate over the actual values, but the
-- full implementation depends upon your needs and is beyond the scope of this example

myVariableStore = setmetatable({}, mVSmeta)
~~~

Now, if you do `myVariableStore.a = "value"`, then `hs.settings` will automatically save "value" for the key "a". If you do something like `print(myVariableStore.b)` then it will check to see if the key has been set before; if not, it will try to load it with `hs.settings.get`.

If you're new to metatables, I suggest checking the documentation at http://www.lua.org/docs.html -- and if you want something more in the line of instruction, I initially cut my teeth on Lua with the Programming In Lua book they mention on that same page... I initially used the second or third edition (can't recall), but I imagine the 4th edition is just as useful.

**Comment by specter78** [comment]
Thank you @latenitefilms @asmagill.
