### ISSUE TITLE
Extend Mojave Support?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3066]
I know this has already been discussed in a few issues already (i.e. #3060, #3023) - but I was just wondering @cmsj & @asmagill what you think about leaving Mojave support for a few more months, until the next iteration of macOS is announced (or released)?

The reason is mostly selfish - there's a lot of people in the creative world (i.e. film and television, animation, music production, etc.) who are still on Mojave as certain software and hardware they use still doesn't work on Catalina, Big Sur & Monterey, and as a result, we have quite a few CommandPost users that are still on Mojave.

I realise that @cmsj has some things planned that will require removing legacy Mojave support - but I was just wondering how quickly those changes will come, and if it's worth holding off removing Mojave support until it's REALLY necessary?

No stress either way... just wanted to throw it out there. Thoughts?

**Comment by cmsj** [comment]
I think you know my stance by now on supporting older OS releases, but I do have to concede that you make a good point about the needs of your users.

I guess the tricky part is how we know when we've broken Mojave support - I don't have any Mojave machines, so I'm going to be plugging away in Xcode blissfully unaware that I'm breaking something, and we don't test Mojave in CI, so I won't even find out when I'm pushing up my PRs.

As an example, I strongly suspect that even just fixing the current huge number of build warnings, may break older OSes.

One thought that comes to mind is GitHub's ability to do matrix CI (ie run the same tests in multiply environments), except they only go back to 10.15, so that doesn't help us (also our CI still isn't 100% reliable for some tests, which makes it untrustworthy in any scenario, sadly).

I know this is a very big question to expect you to answer, but is there any sign that this need for Mojave is going to change? I'm guessing this is mostly the removal of 32bit support. Are the various tool/plugin authors actually migrating to 64bit? If the situation isn't great 2.5 years after the removal was announced, it's kinda hard to imagine that it will be resolved anytime particularly soon.

**Comment by cmsj** [comment]
I guess my one further thought is this - if people are staying on Mojave, they must be facing not being able to run newer versions of more and more of their software. They could just stay on a version of CommandPost that works on Mojave? Or am I being impossibly naive about the support window of commercial media software?

**Comment by asmagill** [comment]
I've been out of town for the last few weeks and didn't have as much access to the internet as I had hoped, but will be back next week and hope to spend some time reacquainting myself with Hammerspoon 😜

I don't have a Mojave machine to test against, but I do have a Catalina one that I want to keep using for awhile yet, so I intend to be doing some work to see what that might entail, including the possibility of creating a fork if the differences end up being significant enough that it would unnecessarily complicate the core code. @latenitefilms I'll keep you in the loop if a fork does end up happening -- in theory I could also set up a Mojave VM (I've done it before when we were straddling versions and had users not quite ready to make the jump), but really I'd need you or your users to test it beyond the basics.

**Comment by latenitefilms** [comment]
Thinking about it further... I think you're right @cmsj - it just complicates things if we still keep on supporting Mojave. All good - I'm happy to drop it from CommandPost when I eventually attempt to merge all the Hammerspoon changes across.
