### ISSUE TITLE
[Question about hs.menubar] How can I get all of the items in menubar ?

### ISSUE THREAD

**Issue by fakeYanss** [Hammerspoon/hammerspoon#3100]
I want to write a script about menuber icon hider, something like [Mortennn/Dozer](https://github.com/Mortennn/Dozer) or [dwarvesf/hidden](https://github.com/dwarvesf/hidden) .

And I have read hammerspoon API documents [Hammerspoon docs: hs.menubar](http://www.hammerspoon.org/docs/hs.menubar.html) . I found it is about to create new items in menubar, not to manage the existed items. Please tell me, how can I do it if I want hide items using hammerspoon.

I think it is able to use `hs.menubar:removeFromMenuBar()` to hide it if I get the lua object of menubar items before.

**Comment by fakeYanss** [comment]
anyone helps?

**Comment by MuhammedZakir** [comment]
> [Question about hs.menubar] How can I get all of the items in menubar ?

I don't think it is possible with this app. I don't know if it will work, but you can give AppleScript a try.

> I want to write a script about menuber icon hider, something like Mortennn/Dozer or dwarvesf/hidden .

See https://github.com/Mortennn/Dozer/issues/69#issuecomment-656076594. To edti plist, use `hs.plist`[1] or `defaults` cli app.

[1] http://www.hammerspoon.org/docs/hs.plist.html

**Comment by cmsj** [comment]
@MuhammedZakir is right, it's not possible with Hammerspoon to interact with menubar items from other apps. It would be an interesting feature to have, but it's not something I plan on working on (honestly, because I use Bartender and I don't think I could do anywhere near as good of a job as they do, especially with the amount of work it seems to require every year to stay compatible with newer macOS releases).

I'm going to close this issue, because I don't believe there is any work to be done on Hammerspoon, but please feel free to keep the discussion going if you want to :)

**Comment by fakeYanss** [comment]
Since I configuration Harmerspoon, I uninstall many application which I used before. Such as Alfred, dictionary and translater, and so on. So I try to do the same thiing with menubar items hider.
I really want to replace Bartender or Dozer with Harmerspoon ❤️

**Comment by cmsj** [comment]
@fakeYanss understandable, a big part of why Hammerspoon exists is to replace lots of tiny little utilities for me, but unfortunately I think the menubar item interaction is a bit too big of a job for us to tackle in a good way. Sorry!

**Comment by muescha** [comment]
I am also looking for an api to query the existing menu icons.

Since I have some icons and the most are overlay with the menu of an app it is complicated to find an app icon in the menu bar. Also some apps only open the GUI when I click on the menu item, but when I open the app via Raycast, there is no GUI shown.

I like to have a API to list of apps running and having an menu bar icon. I like to search in Raycast for the icons, and when I selected, then it should hit the menu bar icon so that the GUI opens.

Example Apps with this behaviour:

- Docker
- Mountain Duck
- Elgato Wave Link
- Hammerspoon
and more...

I have the workaround with the app "AccessMenuBarApps" but it is still complicated, because sometimes it hides the menu bar on the macbook screen (problem: no icons displayed left from the notch) or on the external screen (good, because icons are visible here). Sometimes the AccessMenuBarApps app is crashing.

I just want a search for the app and then simulate a click on the icon. when it clicked I can still use the keys to select an menu item from it.

**Comment by muescha** [comment]
Similar issue:

#3240 hs.menubar, is it possible to add .find()?

**Comment by muescha** [comment]
It would also ok to cycle through all running apps and check each `hs.Application` for an `getMenuBar` to return the `hs.menubar` object. 

Where I can do more things, like check if it is visible with [isInMenuBar](https://www.hammerspoon.org/docs/hs.menubar.html#isInMenuBar) or use the [frame](https://www.hammerspoon.org/docs/hs.menubar.html#frame) to simulate a mouseclick on the icon. Tthe best would be an `hs.menubar:click` to do a click on the icon

**Comment by muescha** [comment]
can we reopen this issue because it is not completed now :/
