### ISSUE TITLE
How to bypass  RM="$(which -a grm ..

### ISSUE THREAD

**Issue by tami5** [Hammerspoon/hammerspoon#3138]
So I'm trying to build hammerspoon from source to be able to contribute and this just stand in the way 😆 . Idk, set alias to grm, global alias and still. errors,

**Comment by cmsj** [comment]
Hmm, if you've installed `coreutils` from Homebrew, you should have `grm`.

I could make the script inherit an existing value for `$RM` if it's set, but FWIW the reason I'm specifically using GNU `rm` is because it has the options `--one-filesystem` and `--preserve-root` which are insurances against an error in paths causing something like `rm -rf /` to be executed.

**Comment by tami5** [comment]
Also, How can I skip things that doesn't makes sense in development environment like Sentry?

**Comment by cmsj** [comment]
Sorry, I had intended to figure this out a while ago. Hammerspoon had the build step for generating `docs.json` that was calling our `build.sh`, but that forces you to install deps. I'd actually already done the work to make `build_docs.py` run without any dependencies installed, so I've changed the build step to call that directly.

Hammerspoon now builds cleanly in Xcode from a fresh checkout on a machine with zero third party stuff installed. Thanks for the push to get that finished :)
