### ISSUE TITLE
Hammerspoon is listed as a browser in Systems Preferences for macOS Monterey 12.2.1

### ISSUE THREAD

**Issue by johnrm9** [Hammerspoon/hammerspoon#3156]
I rebuilt the Launch Services database (using the Cocktail app)  in the hope that only web browsers would be listed as a default browser in System Preferences (General tab) but Hammerspoon still appeared in the list.
 Thank
<img width="655" alt="Hammerspoon listed as web browser" src="https://user-images.githubusercontent.com/3129623/158071939-4421ef48-0183-4aad-aa6a-d44a964b889f.png">
s

**Comment by latenitefilms** [comment]
AFAIK this is intentional - some people want Hammerspoon to be triggered when you click on web links. For example, you might have a Lua script that opens a different browser depending on the URL.

**Comment by gineer01** [comment]
There is even a Spoon to help you take advantage of this feature: https://www.hammerspoon.org/Spoons/URLDispatcher.html

**Comment by cmsj** [comment]
Thanks @latenitefilms and @gineer01. This is indeed intentional and unfortunately there's no way for us to declare our support for opening URLs dynamically - it has to be hard-coded in our Info.plist for macOS to know that we can be used as a default browser.

I can definitely appreciate that it's annoying to have things in that list when you're not going to use them, but many of us are using it and there's no way for us to hide it, so I'm going to close this issue. Sorry!
