### ISSUE TITLE
IP Change Watcher

### ISSUE THREAD

**Issue by specter78** [Hammerspoon/hammerspoon#3183]
How to create a public IP change watcher? If there isn’t a built-in way, please consider this as a feature request.

**Comment by dasmurphy** [comment]
When you read this code, you can create your own watcher for the IP interfaces and check for the IP changes.

Just for reference and example:
[https://github.com/asmagill/hammerspoon-config/blob/master/utils/watchables.lua#L33-L51](https://github.com/asmagill/hammerspoon-config/blob/master/utils/watchables.lua#L33-L51)

The good @asmagill did wrote this and i think this works will now. I did not had the time to check it completely, but it looks fine to me.

**Comment by cmsj** [comment]
We don't currently have a mechanism for even discovering what your public IP is, only the IPs that are configured directly on the machine Hammerspoon is running on.

I'm not sure we even should implement such a thing, because it would mean relying on some third party service to tell us what the IP is, however, assuming that there is such a service which can tell you your IP with a simple HTTP request, it should be pretty easy to put together a "watcher" of sorts, that actually just polls that service every so often using a combination of `hs.timer` and `hs.http`, with a check to see if it's changed.

**Comment by cmsj** [comment]
@dasmurphy is right that `hs.network.configuration` would be the right place to look if you want to monitor changes of the IPs of the machine Hammerspoon is running on, and the key to monitor there would be `State:/Network/Global/IPv4`, but if it is indeed the external, routable, public IP address you're interested in, then `hs.network.configuration` probably isn't going to be of much use.
