### ISSUE TITLE
docs.css missing from local help page

### ISSUE THREAD

**Issue by lhemkendreis** [Hammerspoon/hammerspoon#3189]
My hammerspoon help page seems to be missing its docs.css. 

When I call  `hs.doc.hsdocs.help()`, the page opens, but it's all messed up.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/20543699/163691347-a8aaefcf-036f-4ff4-bb34-22438843600d.png">

When I display the source code in Safari, it tells me that the docs.css cannot be loaded. 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/20543699/163691458-5c65a752-1050-488b-9602-49b5da79de96.png">

I already replaced my hammerspoon.app file with a freshly downloaded one, but it didn't help. 

Please Help :'-/

Thanks :-)

**Comment by latenitefilms** [comment]
Pinging @cmsj - I assume the CSS file was just left out of the new method to copy across files into the app bundle. 

As a workaround you can copy manually copy the CSS file across from GitHub.

**Comment by lhemkendreis** [comment]
Thank you @latenitefilms. I managed to solve the problem using the workaround you suggested :-)

I'll leave this issue open as a reminder for the devs to fix it.

**Comment by asmagill** [comment]
@cmsj, during your changes to the build process, I think you left out copying the docs.css file into the `hsdocs` folder of the doc extension... in the original build process you can see this here: https://github.com/Hammerspoon/hammerspoon/blob/d2eb524a001e251e24d97eb43c1142d5ba7ecce7/scripts/copy_extensions_to_bundle.sh#L127

I'm not in a place to look at Hammerspoon in XCode at the moment... but I seem to recall you migrated these move statements directly into the Hammerspoon build process instead of as a separate script, correct?

**Comment by cmsj** [comment]
I believe this is fixed as of c576c7e4552330ec7fd7fd9e16ee80d33aa61db5 and should be included in 1.0.0
