### ISSUE TITLE
Documentation bug in hs.spaces

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3217]
@cmsj & @asmagill:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/22286696/169721834-63b35942-8ef5-4417-af8f-b288519fc01e.png">

**Comment by asmagill** [comment]
I think this is an issue with *all* of the embedded links in the latest documentation generated. That style, e.g. `[some text](#anchor)` is how you create links to anchors in the same "page" for Github MarkDown (and other MarkDown flavors?)... it looks like the current documentation generation scripts don't do that, either because it's not implemented, not enabled, or not really using a MarkDown processor.

@cmsj, that's your baby... I'm willing to take a look at it later this week, but you might be able to determine the fix faster.

**Comment by latenitefilms** [comment]
Pinging @cmsj - this is probably something else to look into prior to next release?
