### ISSUE TITLE
Upgrade Lua to 5.3.1

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#328]
The work for this is already done, afaict. I'm mostly creating this issue so I can ping folk (particularly @asmagill ) to test anything they particularly care about, before this gets released (I'm not super keen to push out a release, I just want to get this on the radar for some time in the next week or two if we don't find any issues).

**Comment by asmagill** [comment]
Since this will contain it's own implementation of the utf8 library (minus the additions in a pending pull request -- see #324), do we add ours to it, or does ours become hs.utf8 and only contain our additions?

**Comment by cmsj** [comment]
@asmagill I think eventually we should get to hs.utf8 with just our additions, with the docs pointing at Lua's utf8 library, but I'm not currently expecting that should hold up a release. Sorry, I know you've been looking at utf8_53 recently and I did mention turning it into hs.utf8. At the time I didn't realise how quickly I could muddle through an upgrade to Lua 5.3.1! (it helps that I'm the maintainer of the Lua cocoapod, so I could push that through ;)

**Comment by asmagill** [comment]
The additions to utf8 (converting codepoint to utf8 sequence) requires the bit32 module.  I think you can control this by adding the LUA_COMPAT_BITLIB flag to the lua pod, but I'm not sure what, if any, concerns this may raise.  Another alternative is to look at luarocks or another 3rd party module and include it in core.

**Comment by asmagill** [comment]
Or maybe I can use the newly supported >> and <<... is 5.3 a definite for the next release?

**Comment by asmagill** [comment]
check out latest pull for #330... utf8_53 should work either way now.

**Comment by cmsj** [comment]
I think that PR is the way to go, sorry, I realised I broke the build after I merged your PR, but then got called away for lunch :)

**Comment by cmsj** [comment]
So all of my testing is showing no further issues with 5.3, and our travis test shows that all the modules are loaded. I think we should let things simmer for a few days and then I'll pull the trigger on 0.9.32 if there is no dissent :)

**Comment by asmagill** [comment]
I'm working on modifying the utf8_53 module so that it only actually loads the compatibility module if you're not using the lua5.3 core...

  1. how likely/possible is it that we may end up putting off the migration or deciding to make it a compile time option -- basically should i prepare to ditch the internal.m portion all together?
  2. even without the C part of the module, a simple metamethod checks if a function or constant exists in utf8, so referring to things as hs.utf8_53.X still works. Or should this go as well and force everyone to distinguish between *our* utf8 functions, and the built in ones?  This will take us further away from Mjolnir, but honestly, we're pretty far away already.
  3. bite the bullet and drop the _53 altogether from the module name?

So far, whatever we decide here won't affect anything in core, I've already checked... but I'm not sure how much this library is used outside of my own configuration setup... at least I've not come across reference to it.  Should I post to the google group and see?

**Comment by cmsj** [comment]
1. It's possible to delay 5.3 support if we need to, and it's possible to delay releasing 0.9.32 until we're ready. I don't think there are any more regressions at this stage, but I don't mind holding off until we make some changes to hs.utf8_53
2. I don't mind diverging further from Mjolnir on this - I always saw utf8_53 as a "here are some fun things that are coming down the Lua pipe" and so I don't mind our release saying "ok, they're in Lua now, use them from there". I don't think it's worth having a compatibility layer to pass the functions down to Lua's implementation. Honestly, I doubt these functions are in widespread use, so I don't think the effort required is worth it.
3. I still think dropping _53 and the functions that Lua now provides, is the right answer, but I'm not pushing for that to happen immediately.

We're still pre-1.0, so maintaining lots of backwards compatibility shouldn't be too much of a concern/burden at this stage, IMO.

What are your thoughts?

**Comment by cmsj** [comment]
(also, @asmagill, for the record, I don't consider it your responsibility to take any action here if you have other things you want to hack on. AFAICT the module works as-is and I'm happy to add a deprecation note to its docs, telling people to migrate off it)

**Comment by asmagill** [comment]
Re lua 5.3 -- an audit should be done to identify things which should be integers versus numbers; for example:

    hs.application.applicationsForBundleID(hs.settings.bundleID)[1]:pid()

returns (for example): 65555.0

A process ID is never a float -- it is always an integer, and it should be returned as such.

A simple lua fix is to wrap these with math.floor(...), but existing code will fail until this is added because of 5.3's distinction between integer and number (lua_tonumber vs lua_tointeger).
