### ISSUE TITLE
How to create shortcuts which only apply to a certain app?

### ISSUE THREAD

**Issue by wenfangdu** [Hammerspoon/hammerspoon#3322]
I want to map `Command-J`/`Command-K` to `Control-Tab`/`Control-Shift-Tab` only when chrome is active, in Windows, it's quite simple to implement by using AutoHotkey:

```
#IfWinActive ahk_exe chrome.exe
  ^j::Send ^+{Tab}
  ^k::Send ^{Tab}
#IfWinActive
```

How to achieve this using hammerspoon?

**Comment by TheQuinbox** [comment]
Use some of the functions in hs.application. frontMostApp might do what you want. https://www.hammerspoon.org/docs/hs.application.html

**Comment by muescha** [comment]
you can do it with a modal hotkey: you have to create a watcher which enables your hotkey depending if the app is active or not, but then you have this script always running when you change an app.

you can also check on the keypress if the current app is your app - and if not send the original keystrokes to your app (don't forget to disable your hotkey before sending - otherwise you get an infinite loop):

Example:

```lua
function bindHotkeyOnlyTo(appname, modifier, key, message, callback, ...)
    hotkeyHandler = hs.hotkey.bind(modifier, key, message, function()

        local currentApp = hs.application.frontmostApplication():name()

        if (appname == currentApp) then
            callback()
        else
            hotkeyHandler:disable()
            hs.eventtap.keyStroke(modifier, key)
            hotkeyHandler:enable()
        end
    end)
end
```

if you like it more fancy - then this is maybe an code snippet for you:

https://github.com/muescha/dot_hammerspoon/blob/4d260328fcc6ee1c7e7c21f1f0d4c8895206eb51/Helpers/SendKeysOnlyInApp.lua#L77-L108
