### ISSUE TITLE
Recursion -> death loop -> beachball of death 

### ISSUE THREAD

**Issue by muescha** [Hammerspoon/hammerspoon#3326]
I have done a mistake and it becomes an infinite recursion. I was only to kill the hammerspoon app with the activity monitor.

My problem was there: i had for debugging some `print` statements, but the print statements in the console are not show while recursion loop. With the print statements it would be better to debug the problem. But there is no life cycle for the hammerspoon app to update the console with my print statements.

- it would be nice to have:
	- somehow the console should still responsive and print out my debug statements 
	- there should be stop button at console to "kill" a command softly
	- at least some command to "hs.console.flush" to update the console with pending print statements
	- like on Chrome when it's a long running script, then after a treshold time it can ask if i like to cancel the script?

**Comment by asmagill** [comment]
Making the console react to print statements immediately would have a performance impact that would likely be noticeable for things that generate a lot of output; however I do like the idea of a way to flush what is pending... I'll look into that when I have some free time over the coming holidays.

I thought there was a way to send messages to the system log (i.e. the Console application), but I'm not finding it right now... `hs.crash.crashLog` I think puts the message into a cache that only Sentry gets, but I'll look closer when I get a chance. If said function is only in my personal code (I have a few things in an extras module I play with sometimes before adding to the core application), I'll add it to one of the main modules here in the next few days.

I've been musing on adding a way to interrupt a run-away Lua script myself... the way Lua does it on the command line is by catching SIGINT (ctrl-C) and having it set a flag that is then detected by a hook function set via `debug.sethook` that looks for the flag and throws an error when it is set... while we could in theory track SIGINT in a similar way, it wouldn't be helpful because Ctrl-C isn't passed to full applications in the same way that it is when using Terminal or iTerm.

Putting a button on the console to interrupt things won't work because we run all of our Lua code in the main thread and the main thread is what handles all UI interaction -- the button press won't be detected till Lua "pauses", and when you're in an infinite loop, it doesn't pause...

So I've been playing with some code that checks which keyboard modifiers are being pressed...

Right now it seems a little flakey and only wraps code entered into the console. The flakiness I'm looking into... the reason I've limited it to the console at the moment is for two reasons:

1) some of the modifier keys are used internally with some non-printable key presses (e.g. when you press an arrow key, it internally also "presses" the secondary Fn key found on laptops) and we don't want other hotkeys (or even regular keyboard usage) to trigger an interrupt unintentionally while some regular process is being run via a timer or callback function, etc.
2) most of my personal situations involving runaway code is when I'm doing testing in the console for something I'm working on.

I'll likely add functions to turn the interrupter on and off so we can include it in callbacks, etc. on a selective basis for things that we know in advance might get out of control, but I want to figure out why I sometimes have to press my modifier combinations multiple times before it actually breaks out of the code first (i.e. what is making it flakey?).

You can take a look at what I've got so far at https://github.com/asmagill/hammerspoon-config-take2/blob/master/_scratch/interrupter.lua, but like I said, it's still in progress and a little flakey.

**Comment by cmsj** [comment]
I wonder if our minimum version is now new enough that we could use the newer `os_log()` stuff in macOS and let people stream lots of logging to Console.app?

As for the original question of being able to interrupt Lua, and/or get print output from Lua while it's executing, I think the correct way to do that would really be to move Lua onto a separate thread so it can't block the UI thread, but that brings a whole host of other complexities with it.

It's not a very satisfying answer, but I think given the level of sophistication required to use Hammerspoon, the right answer is probably "don't write Lua that loops infinitely" 😬

**Comment by muescha** [comment]
>  "don't write Lua that loops infinitely" 

Yes :)

after some app killing i figured out whats the problem - it was only annoying to kill it completly 


*and after this as a "side project" i dive deep into google got mobdebug with IntelliJ working and now i can debug it in the IDE :)*

**Comment by asmagill** [comment]
I should also note that adding a debug hook does add some overhead, so I think it should always be something explicitly enabled when debugging but disabled by default.

Migrating Lua off of the main thread would require a major code overhaul... if you're serious, we should probably revisit the plans to lock in a version 1 and slate it for version 2.

I'm going to bang on my script a little more over the weekend and maybe do a writeup in our wiki, but it should only be used when debugging for the various reasons listed above already.

(and I'd love to say that I *never* write infinite loops, but... well... bugs happen 😜)
