### ISSUE TITLE
build_docs.py: default path is not valid anymore

### ISSUE THREAD

**Issue by muescha** [Hammerspoon/hammerspoon#3327]
this path is not valid anymore:

https://github.com/Hammerspoon/hammerspoon/blob/ac3134075ee5c662ccf3a29f51526ee9ccfcc09d/scripts/docs/bin/build_docs.py#L765

_i think it is not used because it is always set_

**Comment by muescha** [comment]
maybe `/tree/master` ?

**Comment by cmsj** [comment]
The base URL itself doesn't need to be valid, because things are appended to it, for example if you look on http://www.hammerspoon.org/docs/hs.alert.html#defaultStyle you'll see the link to the source file/line is the `source_base_url` default with the rest of the URL appended.

Is the base URL being set to `blob/master/` breaking something for you?

**Comment by muescha** [comment]
> 
> Is the base URL being set to `blob/master/` breaking something for you?

all is fine 

just to say that it's an 404

**Comment by cmsj** [comment]
Got it, thanks. It's possibly confusing, but that 404 is actually fine :)
