### ISSUE TITLE
Python MatPlotLib windows: completely invisible to Hammerspoon!

### ISSUE THREAD

**Issue by jdtsmith** [Hammerspoon/hammerspoon#3337]
The MacOSX backend of Python's matplotlib plotting package includes a small application called "Python" that manages simple window canvases for drawing plots.  Remarkably, these windows are _entirely hidden_ from HS.  `allWindows`, `mainWindow`, `focusedWindow`... basically HS just cannot see those windows at all.  It can see the application, but no windows!

```
> hs.application.find("Python")
hs.application: Python (0x60000258f7f8)	hs.application: Python (0x60000258f7f8)
> hs.application.find("Python"):focusedWindow()
nil
> hs.inspect(hs.application.find("Python"):allWindows())
{}
```

The windows otherwise behave normally.  Mission Control can control them. They can be maximized, minimized, resized, dragged to other spaces, etc.  But to HS, they don't exist.  

I also fired up the Accessibility Inspector: also invisible to it.  So is it possible the matplotlib developers created an application somehow with no accessibility footprint whatsoever?  [Here is the code](https://github.com/matplotlib/matplotlib/blob/main/src/_macosx.m) in case it's an obvious oversight. In all my years of using HS, I've never seen this.

**Comment by cmsj** [comment]
Yep, it is possible to make macOS apps/windows that don't hook into the accessibility APIs at all, and that will typically cause them to be invisible to all of the "window manager" apps on macOS, since we all actually use the accessibility APIs under the hood.

Hopefully the matplotlib people would be willing to do whatever additional work is necessary, although it may be something lower level in Python that needs to change, but unfortunately without that there's really nothing we can do to be able to see those windows. Sorry!

**Comment by jdtsmith** [comment]
Thanks. I had opened an [issue](https://github.com/matplotlib/matplotlib/issues/24608).  Sounds like they are open to adding accessibility information. If you had any ideas I'm sure they'd appreciate. 

I also found the PyQT backend does expose this info and so it's windows can be manipulated by HS.
