### ISSUE TITLE
i want to keep image moving

### ISSUE THREAD

**Issue by pppaapp** [Hammerspoon/hammerspoon#3349]
here's the code i used

```
mouseCanvas = hs.canvas.new({ x = nil, y = nil, w = nil, h = nil })
mouseCanvas:show()
mouseCanvas[1] = {
	type = 'image',
	image = hs.image.imageFromPath(hs.configdir.."/4128244.png")
}

local function setMouseCanvasPosition()
	local position = hs.mouse.absolutePosition()
	local frame = mouseCanvas:frame()
	frame.w = 100
	frame.h = 100
	frame.x = position.x + 2
	frame.y = position.y + 15
	mouseCanvas:frame(frame)
end

hs.eventtap.new({
	hs.eventtap.event.types.mouseMoved
},setMouseCanvasPosition):start()
```

![CleanShot 2022-12-27 at 01 01 03](https://user-images.githubusercontent.com/31263588/209565958-9913865d-ec5c-414d-8606-28edb5c1e9eb.gif)

but after a few seconds, the movement stops....

**Comment by asmagill** [comment]
The problem is that you're not saving the eventtap in a variable so it is eventually getting garbage collected.

Simple fix:
~~~lua
ourTap = hs.eventtap.new({
	hs.eventtap.event.types.mouseMoved
},setMouseCanvasPosition):start()
~~~

For more details and other ways you can circumvent this, check out https://github.com/asmagill/hammerspoon/wiki/Variable-Scope-and-Garbage-Collection
