### ISSUE TITLE
feature request: get application/doc icons for use beyond hs.hints

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#336]
Maybe a separate module, maybe an extentsion to the hints API, but get reference to application and document icons for use as hs.drawing images, menubar icons, possibly even icons in menubar menus.

**Comment by cmsj** [comment]
I'm slightly torn on this. On the one hand I think having something like an hs.image that can load images from disk, or from app bundles, or from ASCIImage, into Lua userdata that can be passed to drawing/menubar/etc, would be nice, but I also then think that that's not really tremendously useful for users, so I tend to think that we should probably abstract out the common code in the C layer and re-use that in our extensions.

Anyway, I have some code to add app bundle icons to hs.drawing, I'm just a bit sidetracked ATM on fixing image resizing.

**Comment by asmagill** [comment]
Do we need some sort of distinction between end-user modules and developer modules/libraries?

I suppose if we can link against them once a module is loaded into Hammerspoon (can we? or is there some sort of isolation going on?  I haven't tried since pre-ARC Mjolnir...), then providing an include file like the the lua ones in the Resources directory would achieve the same thing -- I just don't want to require developers to do a lot of copy/paste of the same code in multiple places... wasteful of memory and effort.

**Comment by cmsj** [comment]
So we have extensions/hammerspoon.h now, which is intended to contain more common code over time. Longer term I'd like to move core Lua related common code into LuaSkin, and then common OS code into a Hammerspoon.framework (which doesn't exist yet).

**Comment by asmagill** [comment]
That works... So, is hammerspoon.h included in the lua header files being included with the app now?  And if I did want to add something to it, where should the code actually go?  I'm thinking about taking a crack at a more generic Lua-to-NSObject and NSObject-to-Lua function set again... variants are in use in hs.settings and a few other modules already, but it would be nice to have a simple common interface all developers can use.

**Comment by cmsj** [comment]
hrm, apparently I forgot to add hammerspoon.h to the app bundle. I'll take care of that now, but right now I'm not sure how useful it would be, because there's a Crashlytics include in there. For now I suspect the best thing to do for external module distribution that wants to use hammerspoon.h, is to build against a checkout of the Hammerspoon source.

At the moment the .h is very short, so I've just been putting code directly in there. Honestly, I'm really not sure how to smoothly get from where we are now, to a tree that has LuaSkin.framework and some kind of Hammerspoon.framework. I'm tempted to suggest that lua/NSObject bridging utils could go in their own .h until we figure out a better option.

**Comment by cmsj** [comment]
@asmagill do we still need/want document icons? If so, do you have any idea how we would get them?

If not, then I think we can close this out.

**Comment by cmsj** [comment]
(I don't think we need document icons, so I'm going to close this out. If anyone disagrees, please re-open :)
