### ISSUE TITLE
Is it possible to install a Lua 'Power Patch'?

### ISSUE THREAD

**Issue by gla23** [Hammerspoon/hammerspoon#3364]
I've been using Hammerspoon for some years now (love it) and I'm feeling the lack of simple arrow functions/lambdas. I found out that Lua has these "Power Patches" that can add features to the language. I'd love to try out [this one](http://lua-users.org/wiki/LuaPowerPatches#:~:text=Shorthand-,lambdas,-(5.4.2)) that adds lambdas within Hammerspoon!

I tried to find the Lua installation for Hammerspoon so that I can modify it, but I'm guessing it's bundled inside the app. Could you direct me to the right place if it's possible for me to try and hack it?

Thanks so much for your work on Hammerspoon, it is a delight to use!

---

Of course it may be that there is a simpler way of getting what I want. I'm just trying to do something like in JavaScript where you have `() => wait(100)` instead of needing to add all of: `function() return wait(100) end`. This gets quite cumbersome when you're using promises or writing command callbacks all the time. So far I've just been creating a partial for common functions e.g. 
```
function waitFn(time)
  return function()
    return wait(time)
  end
end
```
so that `function() return wait(100) end` becomes `waitFn(100)`. The downside of this is that you have to write a lot of these functions, and your parameters are evaluated beforehand rather than when the callback is run...

**Comment by Rhys-T** [comment]
Patches like that involve modifying the source code of the Lua interpreter itself. You could probably use them with Hammerspoon, but you'd have to rebuild at least LuaSkin.framework from source, if not the entire Hammerspoon app.

---

If you're just looking for partial function application, you could try something like this:

```lua
local select = select
local unpack = table.unpack
local function partial(fn, ...)
	local preArgs = {...}
	local preArgsN = select('#', ...)
	return function(...)
		local args = {unpack(preArgs, 1, preArgsN)}
		local postArgs = {...}
		local postArgsN = select('#', ...)
		for i = 1, postArgsN do
			args[preArgsN + i] = postArgs[i]
		end
		return fn(unpack(args, 1, preArgsN + postArgsN))
	end
end
-- example usage:
local printer = partial(print, 1, 'abc')
printer(2, 3, 'def') -- prints: 1	abc	2	3	def
```

---

For full lambdas with a shorter syntax than `function(x, y) return f(x)*g(y) end`, [there are a number of options](http://lua-users.org/wiki/ShortAnonymousFunctions). Some involve a modified Lua interpreter, like the patch you mentioned. Others use a piece of normal Lua code to translate Lua-plus-lambdas code into normal Lua and `load()` it, which would work in an unmodified Hammerspoon. (Remember that non-standard syntax like that could confuse the syntax highlighting, etc. in whatever editor you're using.) Then there are "string lambda" approaches that work without modifying the syntax at all, and let you do things like `L'wait(100)'` or `L'|x| wait(100 + 50*x)'`. Those would also work in an unmodified Hammerspoon. (But because they aren't parsed as part of the current function, they can't see any local variables.)

**Comment by gla23** [comment]
Thanks for this! I'll have a go with some of these lambda options and see which ones work best 😄

**Comment by Rhys-T** [comment]
Forgot to mention: A lot of the examples on there are based on older versions of Lua, and will need to be adapted to 5.4 to work in Hammerspoon. In particular, anything using 5.1's [`loadstring('…')`](https://www.lua.org/manual/5.1/manual.html#pdf-loadstring) will need to be changed to use [`load('…')`](https://www.lua.org/manual/5.4/manual.html#pdf-load) instead.

**Comment by gla23** [comment]
Thanks for the heads up. I worked that stuff out on the way though. I ended up using the source filtering style and creating my own syntaxes. I put the translation into the file reload function I'm using and it works great! Pity about it breaking the editor tools, but it's not too much of a problem as I don't use the new syntax in all the files 😊 

```lua
-- Simple lambda with alternate 'end' syntax
callback = || wait(100) end
callback = || wait(100) ‖   -- Equivalent of function() return wait(100) end

double = |x| x * 2 end
double = |x| x * 2 ‖
alert(double(4))

multiArg = |x,y| x * y ‖ 

-- Other fun lambda styles I experimented with
a = || alert("hi") ‖
a = ▶ alert("hi") ◀
a()

-- Get out of 'expression mode' using '|| do'. This just removes the return from the function.
b = |x| do alert(5) alert(6) end
b()
```

P.S. the partial function you gave has also been useful
