### ISSUE TITLE
Event:post does not trigger Modal bindings

### ISSUE THREAD

**Issue by mzelmanovich** [Hammerspoon/hammerspoon#3388]
I have recorded a series  of events for playback. Basically like a macros in Vim. I am able to confirm I can save the events and record their copies, using event:copy(). When I loop through the saved events replay them using the post method key bound to the current modal seem to be dropped. The key that is bound or  pressed function do not seem to execute. Is it possible to post events and trigger current Modal bindings?

All modals use the pressedfn an all events are keyDown.

**Comment by cmsj** [comment]
It's been a while since I last looked at something along these lines, but I have a vague memory that eventtap events don't get noticed by the app that posted them. @asmagill am I remembering that correctly?

**Comment by asmagill** [comment]
Hammerspoon *will* recognize posted events for key-up/down (try `hs.eventtap.keyStrokes("hello")` in the console and you'll get "hello" in the console's input line).

And we can even post registered hotkeys -- I first thought that we weren't posting them at a low-enough level for CarbonEvents to be triggered, but turns out we are: I have Cmd-Opt-Ctrl-R set to hide/show the Hammerspoon console and typing `hs.eventtap.keyStroke({"cmd","alt","ctrl"}, "r")` into the console does in fact hide my console as if I had typed the hotkey myself.

So, without seeing your actual code, what I think is happening is that Hammerspoon's application queue isn't advancing between the playback of the key sequences so they're all "happening at once" as far as Hammerspoon is concerned instead of sequentially as required for the modal hotkey to set the new keybindings to be acted upon.

I suspect you'd have to do something like the following (this is just a framework, and not a particularly scalable one at that -- I'd need to give it more thought to come up a more elegant solution) and it hasn't been explicitly tested, but I hope it gives you the idea):

Let's assume `Cmd-Ctrl-A` sets up a modal hotkey set and when invoked '1' will trigger some event.

For programatic invocation, you'd need to do something like:

~~~lua
hs.eventtap.keyStroke({"cmd", "ctrl"}, "a")
local t1 -- predeclare so it can be local but still be captured as an up-value to prevent garbage collection
t1 = hs.timer.doAfter(.1, function()
    hs.eventtap.keyStroke({}, "1")
    t1 = nil -- clear our up-value so it can be collected
    -- the following would be if you needed to do further keystrokes
    local t2
    t2 = hs.timer.doAfter(.1, function()
        hs.eventtap.keyStroke(...)
        t2 = nil
        -- etc nested as deep as you need to go
     end) -- end t2
end) -- end t1
~~~

By sticking each next step into a timer that is started only after its preceding step is invoked, we allow Hammerspoon's application queue to progress, so each action necessary actually has a chance to occur.

It's not always immediately obvious when you need to use a timer or coroutine to space out actions, but a general rule of thumb is that if it requires a state change within Hammerspoon itself or a visual change (like a drawing or canvas), then you'll probably need to give Hammerspoon a chance to advance it's application queue with tricks like this.

**Comment by Rhys-T** [comment]
Another way that doesn't require deeply-nested callbacks might be to use a coroutine, with [`hs.coroutineApplicationYield()`](https://www.hammerspoon.org/docs/hs.html#coroutineApplicationYield) between `keyStroke` calls:
```lua
coroutine.wrap(function()
	hs.eventtap.keyStroke({"cmd", "ctrl"}, "a")
	hs.coroutineApplicationYield()
	hs.eventtap.keyStroke({}, "1")
	hs.coroutineApplicationYield()
	hs.eventtap.keyStroke(...)
	hs.coroutineApplicationYield()
	-- etc.
end)()
```
This should work basically the same - `hs.coroutineApplicationYield` uses `hs.timer.doAfter` internally - but might make the code more readable.

**Comment by mzelmanovich** [comment]
I had to play around with the the timing to get it to work. .5 is what worked for me but 	`hs.coroutineApplicationYield()` seem to of worked better and made my code cleaner. Thanks for the response!

**Comment by asmagill** [comment]
@Rhys-T nice implementation with the coroutines... it gave me the idea of how to make a generic wrapper...

For this example, you need to know that I have `Cmd-Ctrl-Opt-Shift V` set to invoke `hs.grid.show()` which displays a grid and allows you to type letters specifying cells for where the frontmost window should be moved to.  With that in mind:

~~~lua
modalHotkeyPlayback = function(...)    
    local cr
    cr = coroutine.wrap(function(...)
        local tbl = { ... }
        local i = 0
        while i < #tbl do
            i = i + 1
            local step = tbl[i]
            local mods, key = {}, step
            if type(step) == "table" then
                mods, key = step[1], step[2]
            end
            hs.eventtap.keyStroke(mods, key)
            hs.coroutineApplicationYield()
        end
        cr = nil
    end)(...)
end


hs.hotkey.bind({"cmd", "alt", "shift"}, "h", function()
    modalHotkeyPlayback(
        { {"cmd", "alt", "shift", "ctrl"}, "v" }, -- invoke hs.grid.show()
        "2", -- set the upper left corner
        { {"shift"}, "b" } -- set the lower right corner
    ) end
)
~~~

Now when I hit `Cmd-Opt-Shift H`, it will move the window to the specified coordinates.

What this wrapper does is allow you to specify individual hotkeys and will then play them back in order. You should pass each key into `modalHotkeyPlayback` as either a table or as a string -- if it's a table, then the table should contain a table specifying modifiers followed by the string for the key being invoked; if it's a string, then the modifiers are assumed to be empty and the string specifys the lone key to press. String as many as you like separating each hotkey with a comma.

(I initially made the second "hotkey" `"f1"`, but realized that since that's considered a function key, it needs to be entered as `{ { "fn" }, "f1" }`, so switched to `"2"` to showcase that for this wrapper, a key with no modifiers can be specified simply as a string)
