### ISSUE TITLE
How to use a tcp server?

### ISSUE THREAD

**Issue by vvzvlad** [Hammerspoon/hammerspoon#3456]
I'm trying to make a tcp server that would accept some commands in hs. But I can't figure out exactly how to receive the data. There is no example in the documentation. I'm doing it the same way as with UDP (which works fine)

local function udp_handler(data, addr) print(data) end
hs.socket.udp.server(12345, udp_handler):receive()

In the same way, I'm trying to make a tcp server and I don't get any callbacks at all.

local function tcp_handler(data, tag) print(data) end
hs.socket.server(12345, tcp_handler)

**Comment by Rhys-T** [comment]
First, you'll want to make sure that you save the return value from `hs.socket.server` (or `hs.socket.udp.server`) somewhere, so that it doesn't get garbage-collected cause the server to get shut down. More info [here][gc1] and [here][gc2].

[gc1]: https://github.com/Hammerspoon/hammerspoon/discussions/3441
[gc2]: https://github.com/asmagill/hammerspoon/wiki/Variable-Scope-and-Garbage-Collection

Beyond that, I'm not really sure. Normally with the underlying Berkeley sockets API, you have one main socket that you use to listen on a TCP port, plus one 'sub-socket' for each connection that you've accepted, but I don't see anything corresponding to that in `hs.socket`. I'm not finding any way to get notified about a new connection being accepted, or any way to read/write on one particular connection, rather than on _all_ the connections currently open for that server…

**Comment by cmsj** [comment]
FWIW, the tests for `hs.socket` could function as examples for various ways of using it.
