### ISSUE TITLE
Placement issue for hs.alert

### ISSUE THREAD

**Issue by aymericbeaumet** [Hammerspoon/hammerspoon#352]
I face a problem with the `hs.alert` method.

Alerts are correctly centered when created from my main screen (MBP Retina: 2880x1800):

![image](https://cloud.githubusercontent.com/assets/569243/8432192/d2fb9912-1f3e-11e5-8735-644e932dbed1.png)

However, when creating them from my external screen (Apple Thunderbolt Display: 2560 x 1440), they appear in the bottom right:

![image](https://cloud.githubusercontent.com/assets/569243/8432081/14ef76be-1f3e-11e5-80ce-3e33b804c792.png)

Is there something I'm doing wrong?

[My configuration file](https://github.com/aymericbeaumet/dotfiles/blob/master/.shallow/.hammerspoon/init.lua)

**Comment by asmagill** [comment]
I have occasionally in the past seen odd placement of alerts, but it's kind of hard to replicate them (at least in my case) from the console... and I haven't seen them in  while, so I think/thought that they had been addressed.

Some questions so I can try and replicate this next time I'm hooked up to my external monitor...

 * how many monitors are active when you're using the external?  Both, or do you close the laptop lid?
 * I'm assuming, since it's not visible here, that these are alerts triggered by something and not manually invoked from the console, correct?
 * which screen has focus (i.e. the menubar is not greyed or dimmed)
 * what application has focus (Finder?), and does it have open windows on either monitor?
 * does it always appear in the wrong place on the external, or just sometimes?  And if sometimes, are you able to predict the pattern?

Anything else you can think of that might be unique or odd?  I'll take a closer look at your init.lua file next time I'm hooked up to multiple monitors and see if it suggests anything I can try out.

**Comment by aymericbeaumet** [comment]
- 2 / 2 monitors were active (lid open, one external screen connected)
- Correct! I trigger them via a call made to the Karabiner URL
- The screen shown in each image had the focus by the time the screenshot was taken
- finder had the focus in both cases, no open window
- it seems to always appear in the wrong place on the external screen

I think there is an odd behaviour when opening too many alerts from the external screen, will confirm it in more details tomorrow.

Could it be happening because the main screen resolution is bigger than the external screen resolution? It looks like elements are placed on the external screen by considering the main screen resolution

**Comment by cmsj** [comment]
@aymericbeaumet are you changing the primary screen at all? Or is the 2880x1800 screen always the primary? 

I have a very similar setup (15" rMBP running in the 1920x1200 mode, with a thunderbolt display attached) and my alerts only ever show on the rMBP screen (which is set to primary in the Displays system prefs)

**Comment by aymericbeaumet** [comment]
@cmsj The rMBP (2880 x 1800) is always running as the primary monitor.

The alerts shows up in the monitor containing the window I currently focus.

Note that my setup differs from yours in that my main monitor has a greater resolution than my external monitor. This may cause the issue.

**Comment by cmsj** [comment]
This is addressed by 617b5a7
