### ISSUE TITLE
Unable to make distinction between window types of most apps

### ISSUE THREAD

**Issue by lkrms** [Hammerspoon/hammerspoon#3535]
Apologies if this is documented somewhere and I've missed it, but just using Mail.app as an example, I haven't found a way to determine which window is the "main" window (which I want to always be in a particular location) and which is, say, a message window or even a settings window (which I don't want to fill the same space). They all return the same `role()`, `subrole()` and `isStandard()` values; `isMain()` simply follows the most recently active window; and `title()` varies with mailbox and/or subject in such a way that pattern matching wouldn't be reliable. I'm trying to figure out if anything else is surfaced to narrow down which window of an app I'm looking at, because aside from collecting the first window opened (which would be fragile because Hammerspoon may not run first and is reloaded arbitrarily) I can't see any viable options. Am I missing something?

Asked with heartfelt thanks for an outstanding tool I use hundreds of times a day ❤️

**Comment by Rhys-T** [comment]
I don't think you're missing anything. The problem is that the OS doesn't really have a concept of 'types of windows' as far as I know. Unfortunately, how much information you can get about the type of a window is going to depend on how exactly the application in question is implemented. I can think of a few possibilities you can try, but they're all somewhat messy:

### Using the Accessibility API ([`hs.axuielement`][])
Looking at a window using [`hs.axuielement`][] can give you more information about it than using [`hs.window`][]. You can use [`hs.axuielement.windowElement(someHSWindow)`][] and [`someAXWindow:asHSWindow()`][] to convert window references between the two APIs.

[`hs.axuielement`]: https://www.hammerspoon.org/docs/hs.axuielement.html
[`hs.window`]: https://www.hammerspoon.org/docs/hs.window.html
[`hs.axuielement.windowElement(someHSWindow)`]: https://www.hammerspoon.org/docs/hs.axuielement.html#windowElement
[`someAXWindow:asHSWindow()`]: https://www.hammerspoon.org/docs/hs.axuielement.html#asHSWindow

With Cocoa apps, basically every UI element (including windows) will have an `AXIdentifier` attribute that - from what I can tell - basically tells you what 'template' from the app's [NIB file/XIB file/storyboard/whatever they're using these days] was used to create that element.
```lua
local win = getSomeHSWindow()
local axWin = hs.axuielement.windowElement(win)
local windowIdentifier = axWin.AXIdentifier
```
The good news is that when the UI element is a window, `AXIdentifier` basically identifies what kind of window it is. A Mail viewer window[^viewer] will be made from a different template than a window for a specific email, for instance. The bad news is that this often isn't explicitly set by the app's developer, and will end up having a value like <code>_NS:<var>123</var></code> where <var>123</var> is the index of that window object in the NIB, which may be prone to changing if the app is updated. For instance, on my version of Mail, a viewer window[^viewer] is `_NS:9` while a 'single email' window is `_NS:15`. Sometimes it does have an actual value, though - e.g. normal Finder file browser windows have an `AXIdentifier` of `FinderWindow`.

Using `hs.axuielement`, you could also do things like "Does the window have _this_ button? _That_ sidebar? Does it have a URL for a document that it's associated with? If so, it must be _this_ kind of window."

To check what info is available this way, you can either use something like [Apple's Accessibility Inspector app][] (or the older [UIElementInspector][] version that can be downloaded separately from Xcode), or just poke around in the Hammerspoon console using <code>[hs.inspect][](someAXWindow:[allAttributeValues][]())</code>.

[Apple's Accessibility Inspector app]: https://developer.apple.com/library/archive/documentation/Accessibility/Conceptual/AccessibilityMacOSX/OSXAXTestingApps.html
[UIElementInspector]: https://developer.apple.com/library/archive/samplecode/UIElementInspector/Introduction/Intro.html
[hs.inspect]: https://www.hammerspoon.org/docs/hs.inspect.html
[allAttributeValues]: https://www.hammerspoon.org/docs/hs.axuielement.html#allAttributeValues

### Using AppleScript
Basically the idea is to get `theWindow:id()`, and then use AppleScript to ask about it:
```applescript
tell application "Finder"
	get class of window id 1234
	-- might return:
	--	`Finder window` (regular file browser window)
	--	`information window` (Get Info window)
	--	`preferences window`
	--	`window` (anything else)
end tell
```
This one is going to be even more app-specific. Some apps you're using might not even support AppleScript at all, and even if they do, they might not have terminology for specific window types - or you might run into all the other kinds of 'quirkiness' that AppleScript tends to have. For instance, Finder's dictionary has a class for `clipping window`s, but it doesn't seem to use it - if I open a clipping file, it's just a generic `window`.

Mail is even weirder: it uses the generic `window` class for everything, but each viewer window[^viewer] _also_ has an associated `message viewer` object. You can get to the `window` from the `message viewer`, but not the other way around. So to find out if a window is a viewer window, you have to ask something like:
```applescript
tell application "Mail"
	count (message viewers where id of its window is 1234)
	get result > 0
end tell
```
And if it's not, that still doesn't tell you whether it's a 'single email' window, the preferences window, or something else.

If you do decide to use this approach, you can either use [`hs.osascript.applescript(...)`][]:
```lua
local win = getSomeHSWindow()
local ok, windowClass = hs.osascript(([[
	tell application "Finder"
		get class of window id %d as string
	end tell
]]):format(win:id()))
```
or use [`hs.execute(...)`][] with an external `osascript` command, to avoid the memory leak described in #1980:
```lua
local function shellArg(x)
	return [[']]..gsub(x, [[']], [['\'']])..[[']]
end

local win = getSomeHSWindow()
local getWindowClassScript = ([[
	tell application "Finder"
		get class of window id %d as string
	end tell
]]):format(win:id())
local windowClass = hs.execute('osascript -e ' .. shellArg(getWindowClassScript))
windowClass = windowClass:gsub("\n$", '') -- strip trailing newline
```

[`hs.osascript.applescript(...)`]: https://www.hammerspoon.org/docs/hs.osascript.html#applescript
[`hs.execute(...)`]: https://www.hammerspoon.org/docs/hs.html#execute

---
If your window layout code is going to be making lots of decisions based on the 'types' of windows that could belong to multiple different apps, you might want to use something like this to manage the app-specific logic:
```lua
local windowTypeGetters = {
	['Finder'] = function(window)
		-- ...
	end,
	['Mail'] = function(window)
		-- ...
	end,
}
function getWindowType(window)
	local getter = windowTypeGetters[window:application():name()]
	if getter then
		return getter(window)
	else
		return 'unknown'
	end
end
```

[^viewer]: A 'viewer window' is what I'm guessing you're referring to as the 'main window' of Mail. Note that Mail does let you create more than one of these, or get rid of all of them, so there might not be a unique 'main window'.

**Comment by lkrms** [comment]
@Rhys-T I'm so sorry I didn't acknowledge your phenomenal response until now. I was so gobsmacked at the time I must have disappeared into the details at the expense of expressing gratitude. Thank you so much for all of that detail--above and beyond. 🙏

**Comment by lukewiebe** [comment]
Hey, just want to thank @Rhys-T for the incredible in-depth explanation. Using your response to guide me, I was able to target main windows in the Arc browser and move them to preset positions whenever they appear. You really did all the legwork, so thank you!

For future searchers, here's the little snippet I'm using for that:

```lua
ArcWindowWatcher = hs.window.filter.new("Arc")
ArcWindowWatcher:subscribe(hs.window.filter.windowCreated, function(win)
	-- https://github.com/Hammerspoon/hammerspoon/issues/3535 for details on this ID grab
	local axID = hs.axuielement.windowElement(win).AXIdentifier
	if axID == nil then
		return
	end
	local isBigArc = axID:find("^bigBrowserWindow") -- thanks Arc for labelling your window templates
	if isBigArc ~= nil then
		local frame = hs.geometry.rect(8.0, 46.0, 1496.0, 928.0)
		win:setFrame(frame)
	end
end)
```
