### ISSUE TITLE
hs.network.ping.ping blocks callback function of timer

### ISSUE THREAD

**Issue by jamesb93** [Hammerspoon/hammerspoon#3557]
I have this script which runs a timer every 5 seconds that is intended to do a single ping and measure it.

```lua
local timeStart = 0
local timeEnd = 0
local lastPingTime = 0
local menubar_item = hs.menubar.new(true, 'ping'):setTitle("🛜 "..lastPingTime)

function setPingTimeDisplay()
    local pingTimeDisplay = string.format("%.2f", lastPingTime)
    menubar_item:setTitle("🛜 "..pingTimeDisplay)
end

function setFailure()
    menubar_item:setTitle("🛜 🔴")
end

function doPing()
    hs.network.ping("8.8.8.8", 1, 0.001, 1, function(object, message, seqnum, error)
        if message == "didStart" then
            timeStart = hs.timer.secondsSinceEpoch()
        elseif message == "receivedPacket" then
            timeEnd = hs.timer.secondsSinceEpoch()
        elseif message == "didFinish" then
            lastPingTime = 1000 * (timeEnd - timeStart - 0.001) -- we have to subtract the time it takes to send the packet
            setPingTimeDisplay()
        elseif message == "didFail" then
            setFailure()
        end
    end)
end

doPing()
hs.timer.doEvery(5, doPing)
```

However, everytime that I run it it will do the first invocation of `doPing` and the timer never seemingly runs. If I remove the `hs.network.ping` code from the callback it works just fun. I'd like to understand if this is a bug or a misunderstanding in how I've programmed it. Any takers?

**Comment by Rhys-T** [comment]
The short version is that you need to save the objects returned by `hs.timer.doEvery(...)` and `hs.network.ping(...)` so that they don't get garbage-collected before they can do their job.

One quirk of Hammerspoon that often trips people up is that a lot of its objects have visible side effects when they are garbage-collected. Timers stop running, canvases and webviews close, event taps stop intercepting events, etc. To prevent that, you have to save a reference to the object somewhere, like a global variable, the return value of a `require`d module, or a table inside one of those. `hs.timer.doEvery`, `.doAfter`, and `hs.network.ping` need the same treatment, even though their names sound more like 'do something' than 'create something'.

What makes this more annoying is that garbage collection in Lua is non-deterministic: Objects aren't guaranteed to get GC'd immediately when the last reference goes away, but can stick around for a while until Lua decides it needs to free up some memory. So a `doEvery` timer might seem to be working, then randomly stop itself some time later. I'm actually surprised it's failing that consistently for you. [I run a GC pass at the very end of my config](https://github.com/Hammerspoon/hammerspoon/discussions/3441#discussioncomment-5499138) to make sure things break as quickly and consistently as possible.

See also: https://github.com/asmagill/hammerspoon/wiki/Variable-Scope-and-Garbage-Collection

**Comment by jamesb93** [comment]
Thanks for this – it makes sense to me. I'll assign them to some variables.

**Comment by jamesb93** [comment]
It worked. Thank you.
