### ISSUE TITLE
Print statements hanging Hammerspoon and triggering memory leak

### ISSUE THREAD

**Issue by gab-john** [Hammerspoon/hammerspoon#3565]
Hello, after I've upgraded from Sonoma 14.0 to 14.1, my script stops responding a few times a day. Hammerspoon becomes unresponsive, the console becomes blank, and the memory starts increasing indefinitely to several GB.

I've worked around the issue by removing all print statements, and now it no longer crashes, but I spent some time anyway trying to isolate the reason.

This snippet should reproduce the issue when pasted on the console:

```lua
hs.console.setConsole("")
local i = 1
local length = 0

T = hs.timer.doEvery(0.005, function ()
    print(i .. ": " .. string.rep(".", length))
    length = (length + 1) % 40
    i = i + 1
end)
```

On an M1 and on an Intel (both Sonoma 14.1), it hangs after 2000-3000 iterations.

Interestingly, it doesn't happen if all the strings after some point are the same length, such as with just `print(i)`. Then it crashes a few numbers after `10000` (because `i` changed from 4 to 5 digits). That holds true even if `i` starts at `-1000` or `-5000`, it would still crash a bit after `10000`.

It also doesn't happen when disabling the history limit with `hs.console.maxOutputHistory(0)` so it could be related to the characters being deleted on #3400.

**Comment by jkroes** [comment]
I've been having the same issue. Tried running your code for a couple minutes, and indeed HS hung and its memory usage suddenly shot up >1GB and rising.

**Comment by benediktwerner** [comment]
Also have been running into this issue, my hotkeys suddenly stop working and memory usage starts increasing rapidly (usually I catch it at ~10-50 GB but just now I only noticed it at several hundred GB).

I only have one print but I guess it's triggered on every focus change, I'll try removing it. Though HS also prints stuff every time hotkeys get enabled and disabled, which also happens quite often for me, hopefully that doesn't matter, since `hs.console.maxConsoleHistory(0)` doesn't seem like a great solution either.

**Comment by Write** [comment]
Can confirm the issue here.

Indeed if Toggling hotkey use the same function as print, I don't really have any workaround for that.
@benediktwerner I think you meant hs.console.maxOutputHistory(0). If set to 0, the output will be normal. Minimum required is 1. Which may trigger the issue too in the end.

For now I'm trying hs.console.maxOutputHistory(1), w/ a custom code to rewrite console to file

```lua
hammerspoonLogFile = assert(io.open('hammerspoon-console.log','a'))
hammerspoonLogFile:setvbuf("line")
-- Override Hammerspoon's print with print that logs to file, not just HS console
-- See print() definition in https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/_coresetup/init.lua
local old_print, tostring = print, tostring
local tconcat, pack = table.concat, table.pack
print = function(...)
    local vals = pack(...)

    for k = 1, vals.n do
      vals[k] = tostring(vals[k])
    end

    local l = tconcat(vals, "\t")
    hammerspoonLogFile:write(l, '\n')
    return old_print(l)
end
```

**Comment by Rhys-T** [comment]
> Though HS also prints stuff every time hotkeys get enabled and disabled, which also happens quite often for me

> Indeed if Toggling hotkey use the same function as print, I don't really have any workaround for that.

It's not documented[^notdoc], but there's actually an `hs.hotkey.setLogLevel` function that can control the enable/disable messages for hotkeys. (It's actually the [`setLogLevel`](https://www.hammerspoon.org/docs/hs.logger.html#setLogLevel) method of the `hs.logger` instance used by `hs.hotkey` internally. [`getLogLevel`](https://www.hammerspoon.org/docs/hs.logger.html#getLogLevel) is exposed too.) Enable/disable messages are logged at `info` level[^modal], so setting the logger's level to `nothing`, `error`, or `warning` should hide them.

(Also, by default, entering/exiting an `hs.hotkey.modal` is silent - as long as none of the hotkeys conflict with ones that were already enabled before the modal was entered.)

[^notdoc]: Or rather, [it _is_ documented in the source code for `hs.hotkey`](https://github.com/Hammerspoon/hammerspoon/commit/6de44c63c3206809776889dec7ce814f257c3e71), but it doesn't seem to be making it into [the rendered documentation](https://www.hammerspoon.org/docs/hs.hotkey.html) for some reason. The specifics of what gets logged at what level really aren't documented, though.

[^modal]: Or `debug` if the hotkey is being toggled as part of a modal.

**Comment by Write** [comment]
> > Though HS also prints stuff every time hotkeys get enabled and disabled, which also happens quite often for me
> 
> > Indeed if Toggling hotkey use the same function as print, I don't really have any workaround for that.
> 
> It's not documented[1](#user-content-fn-notdoc-5e95b07adf49e7d8040541ea07a11e1f), but there's actually an `hs.hotkey.setLogLevel` function that can control the enable/disable messages for hotkeys. (It's actually the [`setLogLevel`](https://www.hammerspoon.org/docs/hs.logger.html#setLogLevel) method of the `hs.logger` instance used by `hs.hotkey` internally. [`getLogLevel`](https://www.hammerspoon.org/docs/hs.logger.html#getLogLevel) is exposed too.) Enable/disable messages are logged at `info` level[2](#user-content-fn-modal-5e95b07adf49e7d8040541ea07a11e1f), so setting the logger's level to `nothing`, `error`, or `warning` should hide them.
> 
> (Also, by default, entering/exiting an `hs.hotkey.modal` is silent - as long as none of the hotkeys conflict with ones that were already enabled before the modal was entered.)
> 
> ## Footnotes
> 1. Or rather, [it _is_ documented in the source code for `hs.hotkey`](https://github.com/Hammerspoon/hammerspoon/commit/6de44c63c3206809776889dec7ce814f257c3e71), but it doesn't seem to be making it into [the rendered documentation](https://www.hammerspoon.org/docs/hs.hotkey.html) for some reason. The specifics of what gets logged at what level really aren't documented, though. [↩](#user-content-fnref-notdoc-5e95b07adf49e7d8040541ea07a11e1f)
> 2. Or `debug` if the hotkey is being toggled as part of a modal. [↩](#user-content-fnref-modal-5e95b07adf49e7d8040541ea07a11e1f)

Thanks, `hs.hotkey.setLogLevel("warning")` indeed works to hide hotkey message set at launch, and also for those set disabled / enabled dynamically. 

As for modal, indeed no message is shown.

**Comment by latenitefilms** [comment]
Related: 

Add setLogLevel documentation for each extension #2248

**Comment by Rhys-T** [comment]
Whoops. I just realized how recent that commit I linked was - it's not actually in a release yet, so of _course_ it's not showing up in the documentation.

**Comment by Write** [comment]
Hmm but hs.hotkey.setLogLevel("warning") indeed works for me and I’m using the regular release (or so I think)

**Comment by HerbCSO** [comment]
FWIW I had the same issue, reduced logging to almost nothing and at least it's not crashing anymore. Would still like to be able to get my logging back though. ;]

**Comment by muescha** [comment]
> Though HS also prints stuff every time hotkeys get enabled and disabled, which also happens quite often for me, hopefully that doesn't matter, since `hs.console.maxConsoleHistory(0)` doesn't seem like a great solution either.

I have created a helper to disable the logging for some hotkeys:
https://github.com/muescha/dot_hammerspoon/blob/master/Helpers/HotkeySilence.lua#L17-L22

https://github.com/muescha/dot_hammerspoon/blob/cfc737916419b7f7622054d73eaaa786f9981940/Helpers/HotkeySilence.lua#L17-L22

usage in:
https://github.com/muescha/dot_hammerspoon/blob/master/Helpers/HotkeyBindSafe.lua#L27-L29

https://github.com/muescha/dot_hammerspoon/blob/master/Helpers/SendKeysOnlyInApp.lua#L123-L125

**Comment by zgqq** [comment]
Same issue.

**Comment by lingium** [comment]
Same issue for me! and this seems only happens on apple silicon not intel based mac, any suggestions up to now?

**Comment by HerbCSO** [comment]
FWIW this is happening on my Intel Mac. I did manage to mitigate it by reducing the print/logging statements to almost nothing.

**Comment by cmsj** [comment]
So the behaviour here is really interesting. With the default console history length of 100,000 characters, I can also reliably repeat the hang using @gab-john 's test snippet, after about 2100 iterations. Dropping the history length to 50,000 characters raises the hang point to about 38,000 iterations, by which point Hammerspoon is using 20GB of RAM.

I think it's pretty clear that the current methodology for truncating scrollback is a complete disaster that will eventually fail at any length limit (although it looks like the scaling is non-linear, so a limit like 5,000 ought to hold crashes off for a very long time) because something is leaking.

I've quickly profiled a debug build and it looks like the majority of the RAM allocations are coming from text related classes in AppKit.

So, this is either a generic bug in AppKit that eventually an infinitely growing NSTextView will just hang, or there is something more subtle going on. One hypothesis I had was that because we just delete characters off the front of the underlying NSTextStorage, we would be confusing the fact that they were added as NSAttributedStrings, but I don't think that can be it because the hang doesn't seem to be happening very close to where that happens.

I'll keep poking at this and see what I can come up with.

**Comment by cmsj** [comment]
Ok, I've restructured the way text is written to the console, and it will now be batched up and only actually committed to the NSTextView every 0.2 seconds. I've also changed some settings on the NSTextView to turn off a lot of the fancy things that make no sense for a log viewer (things like spell checking) and while I'm not super happy with the RAM usage, the situation overall appears to be dramatically improved.

After 20,000 iterations of the snippet, with the default 100,000 character history limit, Hammerspoon is still running fine, and RAM usage has "only" grown to 1.9GB. I suspect there is still a hang lurking out there in the future, but it should now be far less likely to be hit in any reasonable session. I'll push the code up shortly and I'm hoping to get a release out in the next couple of days.

Thanks all for your contributions here, and apologies it's taken so long to address!
