### ISSUE TITLE
Bug: changing brightness via BetterDisplay causes Hammerspoon to get stuck

### ISSUE THREAD

**Issue by schlomo** [Hammerspoon/hammerspoon#3597]
Hi, I'm using
* [BetterDisplay](https://betterdisplay.pro/) Pro Version 2.2.1 Build 26344 to change the brightness on my Macbook displays and to manage external displays.
* [Hammerspoon](https://www.hammerspoon.org/) Version 0.9.100 (6815) with [this config](https://github.com/schlomo/hammerspoon-config).

Since switching to a new M3 Mac on Sonoma 14.3 I noticed that Hammerspoon gets stuck (rotating colour ball) when I use BetterDisplay to change the screen settings or brightness. On my old Mac with essentially the same Hammerspoon configuration I didn't have this problem, ever.

It seems like BetterDisplay makes Hammerspoon see a large amount of screen changes. I'm using `hs.screen.allScreens()` to watch for screen changes and dump that in my Hammerspoon console and see there hundreds (or thousands) of screen change notifications, even though only the brightness changes:

```
2024-02-05 09:49:24: allScreens = {
   [1] = "hs.screen: Built-in Retina Display (0x600003c297f8)";
   [2] = "hs.screen: LG Ultra HD (0x600003c2ab38)";
};

2024-02-05 09:49:24: allScreens = {
   [1] = "hs.screen: Built-in Retina Display (0x600003cd55b8)";
   [2] = "hs.screen: LG Ultra HD (0x600003cd55f8)";
};

2024-02-05 09:49:24: allScreens = {
   [1] = "hs.screen: Built-in Retina Display (0x600003cd5678)";
   [2] = "hs.screen: LG Ultra HD (0x600003cd56b8)";
};

2024-02-05 09:49:24: allScreens = {
   [1] = "hs.screen: Built-in Retina Display (0x600003c05a78)";
   [2] = "hs.screen: LG Ultra HD (0x600003c06578)";
};
```

The hex code behind the screen name is changing.

Any idea what could be the cause here? Any idea how to debug this problem? Any help would be much appreciated!

https://github.com/waydabber/BetterDisplay/issues/2615 cross-posting at BetterDisplay

**Comment by cmsj** [comment]
From looking at @waydabber's comments on the linked discussion, it seems like BetterDisplay is intentionally sending a ton of display configuration updates, so if you have configured Hammerspoon to react to display configuration updates, it's going to get a ton of calls, and apparently build up quite a queue of them.

We don't currently do any kind of rate limiting on these sorts of OS notifications, and I'm not sure that I want to do that (it being an essentially undefinable problem). @asmagill any opinions on this?

**Comment by waydabber** [comment]
Hmm. What notifications are we talking about?

Generally adding some rate limiting to notifications is indeed a good design. For example i tend to use something like this (the `NSApplication.didChangeScreenParametersNotification` calls `Display.screenParametersChanged()` but only four times every seconds not to overwhelm things:

```swift
    NotificationCenter.default.publisher(for: NSApplication.didChangeScreenParametersNotification)
      .throttle(for: .seconds(0.25), scheduler: DispatchQueue.main, latest: true)
      .sink { _ in Display.screenParametersChanged() }
      .store(in: &cancellables)
  }
```

macOS sends notifications like `didChangeScreenParametersNotification` in very high frequency as brightness changes when HDR content is on screen, this is all aside of BetterDisplay.

**Comment by asmagill** [comment]
The first thing I would ask is have you commented out the print statements in your callback to see if that helps? I recall earlier issues with the Hamemrspoon console updates causing extreme slowdowns in some cases; don't recall how (or if) that was resolved, though... I need to make some time to review and get caught back up!

@cmsj, I'm not *against* throttling in principle, but it should be a choice made by the user.

As to throttling, your example above is Swift, correct? At any rate, it's not Objective-C, and I've not come across a simple way to do this in Objective-C yet (though to be fair, I haven't searched before today, and only did a couple of google searches just now, so I don't by any means claim to have really looked yet).

I suppose we could implement some sort of throttling in:
 https://github.com/Hammerspoon/hammerspoon/blob/e0c79faa7363006179d4a8c629210e9cebb9e470/extensions/screen/libscreen_watcher.m#L38-L42

Track either time of last callback and drop if too soon, or the count of callbacks in a time period... either way, key it to `note` so each watcher had it's own "history".

In any case, I'd want it to be user adjustable (time or count or both) and probably disabled by default.

Not sure when I could get to it; @cmsj when are you planning on creating a new release after the recent merges? The next couple of days I'm limited, but I'll see if I can make some time after that.

Ideally, I'd like to see if it could be added to all of our watchers, but I think they're too distinct and spread out at present for that to be easily done.

**Comment by waydabber** [comment]
Yes, it is a swift code and uses the Combine framework for throttling, so it won't work in Objective-C. The alternate I used before swift/combine was what you just mentioned (storing timestamp of last call and drop processing further calls until a certain time elapsed from the time recorded in the timestamp while noting that there were at least one interim call and then process again one last time if there were interim calls after the period elapsed - it's indeed somewhat complicated). Alternatively there are some Objective-C throttling/debouncing libraries on GitHub to be reused.

But I am not sure what notifications we are talking about. BetterDisplay itself does not send such system notifications intentionally - if it's the `NSApplication.didChangeScreenParametersNotification` messages, those are super-frequent by design and sent by the OS itself whenever there is HDR content on screen (so the display is in EDR mode) and the brightness is changing - this is because this notification informs various apps to tone-map content to match the new brightness levels (brightness change for Apple displays influence the EDR headroom - the brightness range beyond normal SDR range available for the app to represent HDR-level content). This can be an issue especially when for example the ambient light sensor moves the brightness levels around constantly - this creates a heavy load on HDR aware apps and can indeed cause serious issues if there is no throttling implemented. I think the issue was mentioned in the context of running BetterDisplay only because with software brightness upscaling for XDR displays, the display is indeed in EDR mode (as the extra brightness causes the screen content to enter the EDR headroom (HDR) brightness range.

More info on this: https://developer.apple.com/documentation/metal/hdr_content/performing_your_own_tone_mapping?language=objc

**Comment by cmsj** [comment]
@waydabber yeah this is about `NSApplication.didChangeScreenParametersNotification`. Classically that's quite rarely called and we primarily offer it as a way to react to things like plugging/unplugging external displays.

I totally take your point about it being much more frequently used in some modern scenarios, but the challenge I think we would face with throttling is that Hammerspoon is so generic/flexible that we have no way of knowing what the user is trying to do with it, so we may drop events they actually did care about.

**Comment by cmsj** [comment]
(I'd also note that I am slowly trying to drag the codebase towards Swift, so using things like Combine would be possible in the future, although the hs.screen module where this watcher lives, is likely to be among the last to migrate, if we ever get that far, because it's so complex and intertwined with other modules!)

**Comment by asmagill** [comment]
FWIW, I have an idea about merging most of the `NSNotificationCenter` and `NSDistributedNotificationCenter` watchers into a single module (which could be objective-c or swift, doesn't really matter, though I know one and would have to learn the other 😜) and use Lua code as the actual dispatcher to the various other module defined watchers, which would make adding or customizing your own throttle function quite easy... but it's going to take some time to do and I'm not sure when I'll have it...

And in that vein, @waydabber could you try something like this with your watcher and see if it works/helps:

~~~lua
--- screen watcher callback setup
local lastSWReceived = 0
local rateLimit = 0.25 -- adjust as you see fit
local screenWatcherCallback = function()
    local timeStamp = hs.timer.secondsSinceEpoch()
    if timeStamp - lastSWReceived >= rateLimit then
        lastSWReceived = timeStamp
        ... whatever your current screen watcher callback function does ...
    end
end
~~~

and assign that as your callback function and let us know if that helps.

**Comment by cmsj** [comment]
@asmagill somewhere in our Issues we have something I added about an `hs.watcher` idea for exactly that - centralise all of the notification stuff and let multiple Lua things watch them. I'd definitely like to collaborate on that, and I think we should write it in Swift :)

**Comment by latenitefilms** [comment]
FWIW - It's also pretty simple to trigger Swift functions in Objective-C as short term solution as we slowly transition to Swift.

**Comment by schlomo** [comment]
Maybe Hammerspoon can simply silently ignore repeated identical events? My impression was actually, that it is a large amount of identical events that happen, without any actual change.
