### ISSUE TITLE
Hammerspoon does not respond/hang when the frontmost application does not respond

### ISSUE THREAD

**Issue by NightMachinery** [Hammerspoon/hammerspoon#3606]
Hammerspoon does not respond/hang when the frontmost application does not respond. I notice this most frequently with emacs, as emacs has terrible concurrency and does not respond to new events whenever it is doing sth heavy. This makes hammerspoon also not respond, which is terrible.

I have the following elisp code which "simulates" a hanged emacs:
```lisp
(defun night/busy-spin (&optional duration)
  "Busy spin for DURATION seconds."
  (interactive "nDuration (seconds): ")
  (let ((end-time (time-add (current-time) (seconds-to-time (or duration 30)))))
    (while (time-less-p (current-time) end-time)
      ;; Do nothing except consume CPU cycles.
      )))

(night/busy-spin 20)
```

Using this, the code that causes Hammerspoon to hang seems to be this:
```lua
function toggleFocus(appName)
    local launch_p = false

    local app = nil
    app = hs.application.get(appName)

    if app then
        if app:isFrontmost() then
            app:hide()
        else
            app:activate()
        end
    else
        if launch_p then
            hs.application.launchOrFocus(appName)
            app = hs.application.get(appName)
        end
    end
end
```

When `toggleFocus("org.gnu.Emacs")` is run and emacs is hanged, Hammerspoon will hang.

How do I solve this?

**Comment by cmsj** [comment]
Our hide/activate methods work via the Accessibility API, which means ultimately they are sending Apple Events under the hood. I would strongly suspect that because Emacs isn't replying, Hammerspoon is stuck waiting for some kind of ack/reply to its Event message. There's a reasonable chance that it will time out after a while, but right now there's nothing we can really do about this.

Down the road it may be possible to split these kinds of operations out into a separate thread, or an XPC helper, but really the solution here would be for weird hybrid macOS apps like Emacs to just behave better.

**Comment by NightMachinery** [comment]
@cmsj Can I work around this issue by using timers or sth?

**Comment by cmsj** [comment]
@NightMachinery not really no, because once the Apple Events are being sent, that's blocking the rest of Hammerspoon.
