### ISSUE TITLE
Create Helper apps with Hammerspoon and sell it?

### ISSUE THREAD

**Issue by muescha** [Hammerspoon/hammerspoon#3620]
Is it possible to create some helper apps and sell it?

- Is this idea compatible with the hammerspoon license?
- how I can package it in one app?
- there are some problems if I run my app (based on hammerspoon) and the "original" hammerspoon app?
- Can I sell it on MAS or only out of MAS?

Or should I use Hammerspoon for an MVP and later create a SwiftUI app?

**Comment by latenitefilms** [comment]
I forked Hammerspoon for my own purposes with CommandPost:

https://commandpost.io

Hammerspoon (and CommandPost) is MIT licensed.

Going down the Mac App Store route would require a lot of functionality to be removed due to sandbox requirements and the fact you can't use private APIs.

**Comment by muescha** [comment]
I looks very complicated to build the custom `*.app` with the `build*.sh` scripts :/

**Comment by cmsj** [comment]
If we can manage to get some momentum behind the Swift rewrite, part of that effort involved splitting out a lot of the core functionality into its own Framework. Part of the motivation for that was explicitly to make the creation of simple standalone utility apps easier.

As for the legality, you are totally fine to repackage Hammerspoon either commercially or non-commercially. You're right it's not very easy to build, ironically because of the need for other people to be able to do local unsigned/self-signed builds, as well as me being able able to do Apple-notarized release builds.

**Comment by latenitefilms** [comment]
I've learnt a LOT more about Swift in last 12 months so very keen to get back to pushing Swift rewrite further!

**Comment by muescha** [comment]
extracting functions into a framework would be very interesting.

Is there any resource where I can follow the current Swift rewrite process?

**Comment by latenitefilms** [comment]
It hasn't really started yet. Any work on this will be posted as pull request and issues in this repo. @cmsj has some proof of concept stuff already in a pull request.

**Comment by muescha** [comment]
Thank you for pointing that out. It seems the links you provided are focused on writing Swift extensions rather than Lua scripts. If I misunderstood your intention, I apologize.

What I’m aiming to do is bundle a few Lua scripts with Hammerspoon to create a new tool or app with one or two specific functions.
