### ISSUE TITLE
backspace key code?

### ISSUE THREAD

**Issue by halafi** [Hammerspoon/hammerspoon#3642]
a bit new to hammerspoon, I am looking for backspace key code

[keycodes.lua](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/keycodes/keycodes.lua#L67
)
am I missing something, I get this error:

` Invalid key: backspace - this may mean that the key requested does not exist in your keymap (particularly if you switch keyboard layouts frequently)`

more likely that backspace is registered as 51 but with hyper modifiers its not

Edit: after some more testing some keys don't get regstered with ctrl alt cmd shift pressed

**Comment by halafi** [comment]
seems mapping to keycode `51` works

**Comment by Rhys-T** [comment]
> a bit new to hammerspoon, I am looking for backspace key code

Hammerspoon uses the Mac names for keys: `delete` is the key that deletes the _previous_ character (what other systems call <kbd>Backspace</kbd> - this should be the one you need), while `forwarddelete` is the key that deletes the _next_ character (what other systems call <kbd>Delete</kbd>).
```lua
print(hs.keycodes.map['delete']) -- 51
print(hs.keycodes.map['forwarddelete']) -- 117
```

> Edit: after some more testing some keys don't get regstered with ctrl alt cmd shift pressed

Yeah, there are a few keyboard shortcuts with all four modifiers that are hardcoded into the system (mostly to trigger various diagnostic dumps from `sysdiagnose`), and can't be overridden by `hs.hotkey`. (See #616, #2557.) So far I've found mentions of <kbd>Hyper</kbd>-<kbd>.</kbd>, <kbd>Hyper</kbd>-<kbd>,</kbd>, <kbd>Hyper</kbd>-<kbd>/</kbd>[^slash], and <kbd>Hyper</kbd>-<kbd>w</kbd>[^w] doing this. Not sure if <kbd>Hyper</kbd>-<kbd>Delete</kbd> has anything like that or not.

If you need to take over one of those key combinations, your best bet is probably using something like [Karabiner-Elements](https://karabiner-elements.pqrs.org/) to remap e.g. <kbd>Hyper</kbd>-<kbd>.</kbd> to a completely different key, like <kbd>F19</kbd> (example config [here](https://xam.io/2020/macos-diag-shortcuts/)), before macOS ever sees it - then bind _that_ key in Hammerspoon instead.

Alternately, you might be able to intercept that shortcut from Hammerspoon using an `hs.eventtap` instead of an `hs.hotkey` - but that has its own limitations, some of which are described in https://github.com/Hammerspoon/hammerspoon/issues/2557#issuecomment-705416100. (It also won't work whenever you're using something that turns on [Secure Input Mode](https://www.hammerspoon.org/docs/hs.eventtap.html#isSecureInputEnabled), like a password field, or some terminal apps.)

[^slash]: Mentioned on <https://sayzlim.net/disable-sysdiagnose-key-combination/>. Not sure what this one does.
[^w]: Mentioned on <https://xam.io/2020/macos-diag-shortcuts/>. Does Wifi diagnostics.
