### ISSUE TITLE
Hammerspoon executes AppleScript not like the way Script Editor does

### ISSUE THREAD

**Issue by avegetablechicken** [Hammerspoon/hammerspoon#3646]
I add a menu bar item by hammerspoon called "PROXY", which is usually hidden by Bartender. I want to bind hotkey to show this menu. As Bartender cannot distinguish menus of the same app by their titles. Instead it uses position index to label them. So I write this AppleScript to get the right position index by a menu's title:
```lua
tell application "System Events"
	set cnt to 0
	repeat with mb in menu bar items of last menu bar of application process "Hammerspoon"
		if title of mb is "PROXY" then
			set itemID to "org.hammerspoon.Hammerspoon-Item-" & cnt
			tell application id "com.surteesstudios.Bartender" to activate itemID
			return
		else
			set cnt to cnt + 1
		end if
	end repeat
end tell
```
It works well in Script Editor. Strangely when it is executed by `hs.osascript.applescript`, the console says "System Events got an error: Can't get last menu bar of application process "Hammerspoon". Invalid index.'"
PS: Such situation occurs only when the app target is hammerspoon itself.

**Comment by Rhys-T** [comment]
My guess is that because `hs.osascript` (and most other HS modules) run on the main thread, Hammerspoon is busy - essentially frozen - while the script is running, and can't respond to Accessibility messages from the System Events app. So you end up with a deadlock, until System Events times out and decides that the menu bar doesn't exist. I can think of a few possible workarounds.

Note: I don't use Bartender myself, so any Bartender-specific info below is pieced-together guesswork on my part, and might not work without modification.

### Option 1: Skip Bartender, open the menu directly

Hammerspoon can [open the menu for a given `hs.menubar` object][popupMenu] at an arbitrary point on screen, regardless of whether the corresponding menu bar item is visible. You can even pop it up right below the cursor so you don't have to reach for it:

```lua
hs.hotkey.bind({'cmd', 'ctrl'}, 'p', function()
	proxyMenu:popupMenu(hs.mouse.absolutePosition())
end)
```

[popupMenu]: https://www.hammerspoon.org/docs/hs.menubar.html#popupMenu

### Option 2: Use Bartender's own hotkey system

As I understand it, Bartender has its own way of letting you set up hotkeys to show/open hidden menus. If it can track `hs.menubar`s reliably, that might be easier than trying to control it from an `hs.hotkey`.

### Option 3: Instead of guessing the ID, set it

I'm not sure how Bartender constructs the menu IDs, but the `Item-0` part looks suspiciously like an [`autosaveName`][]. Basically, every menu extra/status item has an internal name that is used to store the menu's position in the app's preferences. If the app doesn't set this name, it defaults to `Item-0`, `Item-1`, etc. If that really is what Bartender is using, you should be able to set it using the [`:autosaveName()`][] method (or the second parameter to [`hs.menubar.new()`][] when you first create it), and not have to care about its index:

```lua
proxyMenu:autosaveName("Proxy Menu")
hs.hotkey.bind({'cmd', 'ctrl'}, 'p', function()
	hs.osascript.applescript([[
		tell application id "com.surteesstudios.Bartender"
			activate "org.hammerspoon.Hammerspoon-Proxy Menu"
		end
	]])
end)
```

[`autosaveName`]: https://developer.apple.com/documentation/appkit/nsstatusitem/1644022-autosavename?language=objc
[`:autosaveName()`]: https://www.hammerspoon.org/docs/hs.menubar.html#autosaveName
[`hs.menubar.new()`]: https://www.hammerspoon.org/docs/hs.menubar.html#new

### Option 4: `hs.axuielement`

For some reason, Hammerspoon _doesn't_ deadlock when I use [`hs.axuielement`][] to make it talk to its own Accessibility interface - only when I make it use AppleScript and the System Events app. So you could do something like this:

```lua
-- Get a reference to Hammerspoon itself:
local axHammerspoon = hs.axuielement.applicationElement(hs.processInfo.processID)
local proxyMenuFrame = proxyMenu:frame()
local proxyMenuID
for i, axMenuBarItem in ipairs(axHammerspoon.AXExtrasMenuBar.AXChildren) do
	-- I'm not sure if the AXMenuBarItem's AXFrame is guaranteed to be an exact match for the hs.menubar's frame(), so…
	if hs.geometry(axMenuBarItem.AXFrame).center:inside(proxyMenuFrame) then
		-- Lua's indexes are 1-based - convert to 0-based
		local proxyMenuIndex = i - 1
		-- NOTE: If you have multiple screens, and have "Displays have separate Spaces" turned on, you might need to do:
		-- 	numberOfScreens = #hs.screen.allScreens()
		-- 	proxyMenuIndex = proxyMenuIndex / numberOfScreens
		-- because each menu appears multiple times - once for each screen / menu bar.
		proxyMenuID = ("%s-Item-%d"):format(hs.processInfo.bundleID, proxyMenuIndex)
		break
	end
end
if not proxyMenuID then
	error("Couldn't find proxy menu's ID")
end
local proxyMenuActivateScript = [[
	tell application id "com.surteesstudios.Bartender"
		activate "]]..proxyMenuID..[["
	end
]]
hs.hotkey.bind({'cmd', 'ctrl'}, 'p', function()
	hs.osascript.applescript(proxyMenuActivateScript)
end)
```

Note that if Bartender _is_ using the `autosaveName` (see option 3), and you have that set on any of your other `hs.menubar`s, that will throw off the index that this code comes up with.

[`hs.axuielement`]: https://www.hammerspoon.org/docs/hs.axuielement.html

---

Hope this helps.

**Comment by avegetablechicken** [comment]
Thanks a lot @Rhys-T . I tried option 3 & option 4. Both of them work perfectly!
