### ISSUE TITLE
Hotkey script results in garbled text on remote Windows server

### ISSUE THREAD

**Issue by xinxianwu** [Hammerspoon/hammerspoon#3649]
I wrote the following script. I expect that when I press Ctrl+Shift+W while remotely connected to a Windows server, it will input "Welcome1". However, I am getting a string of garbled text instead. I am not sure how to fix this.
```
hs.hotkey.bind({"ctrl", "shift"}, "w", function()
    hs.eventtap.keyStrokes("Welcome1")
end)
```
![image](https://github.com/Hammerspoon/hammerspoon/assets/50643550/e45c6984-09f1-46db-afb4-f2e1261e7356)

**Comment by Rhys-T** [comment]
Are you using Microsoft Remote Desktop to connect to the server? It looks like it's known to have issues with the key events generated by Hammerspoon: #1056, #2281. According to <https://github.com/Hammerspoon/hammerspoon/issues/2881#issuecomment-867655114>, changing Remote Desktop's 'Keyboard Mode' setting from 'Scancode' to 'Unicode' can work around the problem. If I understand correctly, this basically makes Remote Desktop send which _character_ is being typed, rather than which _key_.

`hs.eventtap.keyStrokes` seems to [set the character for the key events it sends](https://github.com/Hammerspoon/hammerspoon/blob/56b5835dc1bf7bb430dfea3f1662379cccec0c82/extensions/eventtap/libeventtap.m#L114-L141) (using `CGEventKeyboardSetUnicodeString`), but not the keycode, which means that the keycode stays at the default of 0 (the <kbd>A</kbd> key). So it looks to Remote Desktop like you keep pressing <kbd>A</kbd>, but in a different keyboard layout each time, mapping that 'key' to each character of the string you're trying to type. In Scancode mode, MSRD is ignoring that mapping and letting the Windows server decide what character to insert based on the keycode[^soh]… which isn't set correctly. If you switch it to Unicode mode, it should use the string set by HS instead. (But it will also start using your local Mac's keyboard layout rather than the one selected on the Windows server, if that's different.)

You can also send each key individually using [hs.eventtap.keyStroke](https://www.hammerspoon.org/docs/hs.eventtap.html#keyStroke) or [hs.eventtap.event.newKeyEventSequence](https://www.hammerspoon.org/docs/hs.eventtap.event.html#newKeyEventSequence), which should set the keycodes properly, but you'd need to figure out the correct combination of key + modifiers for each character yourself - Hammerspoon won't do it for you when using those functions.

[^soh]: Normally that would be `a` like in the issues I mentioned above. My guess is that since you still have <kbd>Control</kbd> (and <kbd>Shift</kbd>) pressed from the hotkey at that point, it's ending up as a <kbd>Control</kbd>-<kbd>A</kbd> character - a.k.a. **S**tart **o**f **H**eading, or [␁](https://en.wikipedia.org/wiki/C0_and_C1_control_codes#ASCII).

**Comment by xinxianwu** [comment]
I logged into the Windows server through Royal TSX and tried changing key presses to Unicode, but the garbled characters issue still hasn't been resolved.

![CleanShot 2024-07-17 at 12 52 51@2x](https://github.com/user-attachments/assets/c7c2f639-8edd-4335-825d-b43265d0703a)

**Comment by cmsj** [comment]
I'd be interested to know if `hs.eventtap.keyStroke()` works. Perhaps we need a variant of `keyStrokes()` which just sends key sequences (although then we have the interesting challenge of trying to transform a unicode input string into keycodes!)

**Comment by latenitefilms** [comment]
We need to merge in @asmagill's `hs.text` - that's what I use in CommandPost for unicode handling.
