### ISSUE TITLE
How do I get the "Caps Lock" status?

### ISSUE THREAD

**Issue by txl263** [Hammerspoon/hammerspoon#389]
I have viewed the API DOC, but didn't find how to get the "caps lock" status.

**Comment by asmagill** [comment]
What's the use case?  I ask because it may affect what is really needed...

Since we clean up the flags returned by hs.eventtap.checkKeyboardModifiers, I believe the only way to currently get this would be to create an eventtap on the event type "flagsChanged" and then invoke method getRawEventData on the object returned in the callback to see the raw value of the flag data and check bit 16 (NSAlphaShiftKeyMask)... of course that is only available when a flag changes, not for checking what it is at this precise moment.

The Apple docs are a little unclear on what the value of the flag will be when you have multiple keyboards... a quick test of the eventtap I suggest above suggests that the flag will represent whatever the caps lock state is on the last keyboard which had any flag change (ctrl, shift, fn, etc.) so even if this were added to checkKeyboardModifiers, it might not be consistently accurate...

If you're looking for a "Is the caps lock on ANY keybaord down" type thing, a quick google check suggests we'd need to dip into the HID manager API... none of the current modules do so.

I'll add the flag to checkKeyboardModifiers (and probably throw in a raw value for it's return as well, so we can do our own bitchecks without requiring a re-compile) so we can test it out, but I don't know how useful it will turn out to be with multiple keyboards... we'll just have to see!

**Comment by txl263** [comment]
Thank you for your response.
I just want display caps lock status from hs.alert, because I use caps lock instead of shift to change status between Chinese  and English input. I want to know which is in use, Chinese or English.
Now that is so complicated, new mind. Thank you again!

**Comment by asmagill** [comment]
Testing a modified version of hs.eventtap.checkKeyboardModifiers with capslock added...

What I've found is that it reports the capslock state *of the last keyboard touched*... so it's not a global check of all keyboards, but a check of the most recent keyboard used... would that be useful?  If so, I can submit a pull request and see about getting it into the next release.

**Comment by cmsj** [comment]
I just merged PR #390 from @asmagill, so this should now be possible in the next release :)
