### ISSUE TITLE
Interface to widthWithFont or sizeWithFont

### ISSUE THREAD

**Issue by jasonm23** [Hammerspoon/hammerspoon#394]
IIRC there is a text/font measuring API in cocoa.

Drawing text is much more powerful when we have access to these methods.

**Comment by jasonm23** [comment]
sizeWithAttributes I think is the method I am thinking of

**Comment by lowne** [comment]
+1

**Comment by cmsj** [comment]
So you'd want to be able to determine the size that some text would require, before instantiating the hs.drawing.text() object?

**Comment by jasonm23** [comment]
it's very useful to be able to determine the height and width on a fontified string, so containers can be positioned and sized properly

**Comment by asmagill** [comment]
sizeWithAttributes is a good start, and I have a version in testing that I will probably push later tonight.

It seems to predict the width as being off by exactly 4 every time, so I want to dig deeper and figure out where that 4 is coming from rather than just add 4 to w and be done with it.  I'm suspecting it's from something inherited like the frame of the nsview the textfield goes into, but I want to confirm this since I can't test every font/size combo... so far about 10 different variants always are off by 4, but...

What seems more useful -- taking a string, font, and size and telling you what size to make the box before you've ever made the hs.drawing.text object, or getting the value from an already defined hs.drawing.text object? We don't have getters for anything else in drawing, so I'm leaning to the first, but am open to thoughts.

Also, is there interest in adding support for clipping/wrap on char/wrap on word (paragraph style) and alignment to hs.drawing.text objects?  I lean towards yes, but if we can get accurate size results, these can be worked around... thoughts?

**Comment by jasonm23** [comment]
Paragraph styles and alignment are definitely helpful.  

While box sizing is probably the most common use-case, I think whatever we get out of a size property should be unprocessed.

I think I remember the mystery 4px width strangeness, and dismissed it as default container dimensions/leading space.  I must admit I didn't do a thorough investigation though.

**Comment by asmagill** [comment]
sigh... still don't have an answer to why sizeWithAttributes is regularly 4 pts off... and googling just shows lots of threads about "yeah, we know... use <insert other rendering path here>".  99 times out of a hundred (ok, I exaggerate, I haven't *really* tried it *that* many times) setting the alignment to "justified" will take care of it... I'm going to put into the notes section that it's an approximation and that you can adjust the alignment or use it as a minimum...

At any rate, I'll put up a pull shortly for review.

**Comment by jasonm23** [comment]
Good stuff!

**Comment by cmsj** [comment]
I think this is covered by #479 having landed - please re-open if not :)
