### ISSUE TITLE
Support window id when applying layout

### ISSUE THREAD

**Issue by blalor** [Hammerspoon/hammerspoon#406]
Perhaps related to #345, I think it'd be useful to have `hs.layout.apply` accept a window id instead of just a title (keeping support for both, ideally).  I'm working on something to preserve the position of windows when adding or removing a screen (basically updating an internal table with the position of each window on a per-screen basis and applying the last-known layout when the screen config changes).  Only supporting a window _title_ means -- I think -- that two windows with the same title will have their layout applied nondeterministically.

**Comment by cmsj** [comment]
Yeah I think this makes sense, although I wonder if it would be better/easier to just accept an `hs.window` object (and the same for the application argument). Any thoughts?

**Comment by cmsj** [comment]
This might actually be easiest if we delegate the window finding to `hs.window.find()` which can handle input in various forms.

**Comment by cmsj** [comment]
I've just added support for passing either a single `hs.window` object, or a function that returns a table of `hs.window` objects. I think that should cover this, because the function could turn a previously stored window ID into an object and return it in a table :)
This will be available in the next release.
