### ISSUE TITLE
Hammerspoon Remote iOS app

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#412]
From my phone, while on my home network, i want to be able to:
- Execute a series of pre-defined actions (defined in init.lua, the app should remain stateless)
- Get an IPC console

Breaking this down into a possible plan, we need to be able to:
- [ ] Serve HTTP(S?) via a Lua callback, with the server advertised using Bonjour (see #411)
- [ ] Bootstrap a secure connection between OS X and iOS. This might look like one of:
  - Mac generates an encrypted private key for iOS device, iOS device fetches it, Mac displays decryption passphrase
  - Mac generates a private key for iOS device, Mac displays it encoded as a QRcode, iOS device reads the code and imports the private key
  - ?
- [ ] Transfer commands/responses between devices securely (either TLS or encrypted payloads)
- [ ] Easily store key material in relevant device Keychains

**Comment by cmsj** [comment]
Actually, it turns out that the Multipeer Connectivity framework from iOS, is in OS X now. It would place minimum requirements at 10.10, a Mac from 2012 or newer, and an iOS device >= iPhone 5, but those seem like worth restrictions to avoid a huge pile of crypto code having to be written.

**Comment by asmagill** [comment]
Since we know of at least one person who has used Hammerspoon under 10.8, do you know if these new features will fail gracefully  (i.e. not crash) if the user isn't running 10.10?  Or are we finally at the point where Hammerspoon simply requires 10.10?

If it doesn't require a whole lot of extra code, I think I'd rather have individual modules which refuse to load if the OS isn't new enough, rather than the whole Hammerspoon environment, but other than a few wrappers I put into hs.sound, I've not much experience with version checking, so I don't know how hard this would be to enforce.  Thoughts?

**Comment by cmsj** [comment]
@asmagil I'm fairly sure that this would just fail to load the .so because dyld wouldn't be able to resolve all the symbols. I've had it before when I've messed up linking, and you just get an ugly error in the Console.

We could also add OS version info to hs.host and do a guarding check in init.lua before it require()s the .so.

**Comment by asmagill** [comment]
I like the version check in hs.host -- it allows for cleaner/more specific error messages.  I'll see about adding it soon.

**Comment by sdegutis** [comment]
:+1: for dropping less than 10.10, since it's probably a vast minority of users at this point and makes a lot of things easier.

**Comment by cmsj** [comment]
I don't realistically have time to work on this, so I'm going to close out this issue.
