### ISSUE TITLE
Odd line in image/internal.m

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#437]
I'm trying to track down the strange console traceback issue that's popped up recently on IRC, and I noticed the following line in extensions/image/internal.m:

305     luaL_unref(L, LUA_REGISTRYINDEX, 1);

@asmagill - am I missing some subtle magic here? That seems like it's just going to randomly unreference whatever the first thing we put into REGISTRYINDEX was?

**Comment by cmsj** [comment]
(I note that hs.image has no calls to luaL_ref(), so AFAICS, it shouldn't have any luaL_unref() either.

**Comment by asmagill** [comment]
Yeah, I noticed this last night and was going to try and figure out WTH I was thinking... I'm 99% sure it's completely unnecessary, rather than a 
typo, and have removed it to test this out in the last local build I made last night to test this morning.

If you agree, go ahead and remove it, otherwise I'll include it in a pull with some additions for hs.window later today.

**Comment by cmsj** [comment]
@asmagill thanks, I've removed it in 266a62b85acf36739936713f026e7d2730c5ec16
