### ISSUE TITLE
hs.grid.show and window where isFocused == false

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#462]
Trying out a new web browser, Qupzilla, and for some reason, its windows never register as focued for focusedWindow() or return true for isFocused().  I can pass in it's hs.window userdata for most hs.grid actions, and they work as expected, but hs.grid.show() doesn't accept an optional window argument... how hard would this be to add?  I glanced at the code and it wasn't imediately obvious, so before I dig into exactly what is happening, I figured I'd throw it out and see if someone more familiar with the code might have an idea.

Also, any thoughts as to why the windows don't register as focused?  I may look into that as well, but if anyone more familiar with hs.window's internal.m file has any ideas, I'd love to hear them as well.

Thanks!

**Comment by lowne** [comment]
I added (without publicising it) `hs.window.frontmostWindow()` in #456 - the plan is to substitute `focusedWindow` with `frontmostWindow` everywhere there's an optional window argument that defaults to the focused window, or things like hs.grid.show that just go for focusedWindow without any parameter; it's meant for those (imho) unintuitive cases where e.g. you hit cmd-w on your last terminal window, the previously obscured underlying Safari window pops up and you want to act on it, but it's not the focused window until you cmd-tab to it. It should also work for your case, unless Qupzilla somehow not only fails to set its own FocusedApplication/WindowAttribue, but prevents the previous app to unset it (so focusedWindow still points to it); this seems highly unlikely - can you confirm/deny?

About adding the optional parameter to hs.grid.show, it's doable ofc but not *completely* straightforward due to the way I structured the code. But this doesn't invalidate imo the advantage of having frontmostWindow.

As for why this happens, I think QT on OS X doesn't always play quite by the rules; kdiff3 also seems to behave weirdly (at least when invoked via git); I'll try to understand what's going on as it seems to affect other modules as well.
