### ISSUE TITLE
setFrame() doesn't work on window taller than resolution

### ISSUE THREAD

**Issue by drogers141** [Hammerspoon/hammerspoon#485]
Hey All,
Not sure if that is the only factor involved, but it appears to be the salient issue.
My use case:
My application:
https://github.com/drogers141/mac-hammerspoon

As part of this work, I can save the state of windows in a data structure that is also serialized to json.  The data structure maintains a queue for each "visibility context" that windows may be encountered in.  This is mainly the permutation of which desktop the window is in (ie Space), and on which screen.  The screens I use are currently either the laptop - a mbp - or a 26 inch Dell.  When I plug the laptop into the monitor, I can hit a key combination and any of the same windows by id from the last time the monitor was in use will be restored to their current position.  If they are not the same window, but from the same app, they will be restored to the last position of a window with that app title if there is one.  The procedure is the same when I unplug the mbp from the monitor.

I recently ported this application from Hydra to Hammerspoon and generally things work the same.  Except now it seems that when I go from laptop to monitor, everything is fine, but when I go from monitor to laptop windows which are taller than the screen resolution are ignored in the resizing process.  Once I have given them focus, I can hit the keybinding to restore state and they will be correctly resized.

Earlier today, I spent time working in the Hammerspoon console confirming this behavior.  Indeed, when I get a reference to a window that is taller than the screen and has not been given focus yet, a call to setFrame() returns the reference correctly, but does not resize the window.  But once it has been given focus, setFrame() works on the same window reference.  Note also that as a side effect of giving the window focus for the first time, the macbook automatically resizes the window to butt to the Dock, and I am not sure if the fact that it is shorter is why setFrame will then work.

Please let me know if I can give more details, thanks.
Dave Rogers - dave@drogers.us

**Comment by lowne** [comment]
@drogers141 can you confirm that the issue is *not* present in Hydra in your *current* system/OSX version?

**Comment by drogers141** [comment]
@lowne Sorry - forgot to add a watch on this - yes I can confirm that.  I am running OS X 10.9.5 and noticed the behavior shortly after porting over to Hammerspoon.

**Comment by lowne** [comment]
@drogers141 is there a way to reproduce manually? (i.e. without attaching/detaching screens) I briefly tried making a window 2x as tall as the screen manually, reloading HS, getting a window reference, and calling setFrame - works as expected.

**Comment by drogers141** [comment]
@lowne - sorry has been a while and I needed some time to allot to this as my Hammerspoon/Lua understanding is ok, but not great.  So I don't think the problem will occur in your context.  That is - if you set the frame on a window, you might as well bring it into focus - it will operate normally.  This truly is a Heisenbug.  Once you look it, it ceases to exist..  So it is the matter of acting on a window that hasn't been brought to focus yet and after changing screens that is the real problem.
Not sure if you want me to close out this issue and initiate another one that states that more clearly, or abandon the attempt altogether.  It is frustrating.  I have learned a couple of things from my latest experimentation, though.
1 - as before, if I go from small screen to large screen, there is no problem, ever.
2 - the problem doesn't always occur, but it doesn't seem to relate to the type of app, or whether it is an Apple app.  For instance I just made it occur with Firefox, Eclipse, and Preview windows.
3 - it appears that there is resizing from OS X occurring that is bringing the height nearly within the bounds of the screen (and the dock) but not quite.  For instance if 816 is the height that my program (or me the Hammerspoon console) is trying to set the frame to, the os has already resized it to something like 868 - and it was last 1000+ on the previous screen.  So it was definitely resized in between.
4 - From this last session, I found out that after I got a reference to a window and set the frame on it, frame() in the console reported that it was the new size, but the window's appearance hadn't changed - ie the change wasn't rendered.  When I then selected the window, then went back to the console and executed the setFrame() again, the change was rendered.  This was quite surprising.

**Comment by lowne** [comment]
For clarity, this is what I did:

1. in terminal, `pkill Hammerspoon`
2. manually make the window for this issue taller than the screen
3. switch focus to a bunch of other windows; the test window is now underneath (and still taller than the screen)
4. open Hammerspoon 
5. from the Hammerspoon console:

```
> w=window'setFrame'

> w
hs.window: setFrame() doesn't work on window taller than resolution (0x61000024ea28)

> w:frame()
hs.geometry.rect(675.0,128.0,706.0,2936.0)

> w:screen():frame()
hs.geometry.rect(0.0,23.0,3840.0,2133.0)

> w:setFrame'0 0 500 1000' -- i can see that the window DOES get resized at this point
hs.window: setFrame() doesn't work on window taller than resolution (0x61000024ea28)

> w:frame()
hs.geometry.rect(0.0,23.0,500.0,1000.0)
```

So yes, re-focusing a window will have the OS resize it, but I carefully avoided that, and Hammerspoon itself had no notion of the window ever having focus since it was started afresh. Therefore, as you said, the problem must be acting on a window that hasn't been brought to focus **after changing screens**; this seems to point to an OS-level problem.

About your point 4, could you test that again with `hs.window.animationDuration=0` and/or using `w:_frame()` instead of `w:frame()`? I wonder if the accessibility layer is just "lying" to Hammerspoon.

More intriguingly, I've had my own "restore proper layout" solution running for several months, and I've *never* seen such an issue; all my dozens of windows across 3 spaces get judiciously and correctly resized down to the laptop screen whenever I detach the 3 external monitors. All I can think of is:
- I have my dock set to autohide (on the bottom), maybe that's the source of "confusion" for OSX
- I'm on 10.10; maybe 10.9 had strange bugs
- make sure you let the OS "settle" (with its half-assed window resizes and whatnot) for a few seconds after changing screens, and only *then* apply your layout
