### ISSUE TITLE
Luadocumentor?

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#505]
(Warning: this is a _very_ high level overview of the topic - technical details and caveats are ignored for now pending consensual interest)

With the upcoming addition of moses #503 this might be a good time to consider adding support for [luadocumentor docstrings](http://wiki.eclipse.org/Koneki/LDT/User_Area/LuaDocumentor). The immediate benefit (for moses at least) is that ldoc to luadocumentor is straightforward.

Here's the [language definition](http://wiki.eclipse.org/LDT/User_Area/Documentation_Language) (required reading), whence the additional (and more important) benefits:
- the format is already strictly defined wrt **arguments, returns, their types, and usage examples**; the current scripts don't do that, and will require building a custom parser (iirc that's somewhere on the wishlist, if not on the todo list)
- the format allows defining and documenting **complex types** such as tables of tables (e.g. lists of lists like in hs.layout, or even simple structs like hs.geometry can be properly documented as _types_) - window.filter and window.layout make heavy use of these, and lengthy free-style paragraphs and handmade bulleted lists aren't the best way to formally describe them
- the execution environment that we'd get "for free" would make it 50x easier (not hyperbole) to write and maintain (Lua) modules in LDT with type-aware code assist and navigation, akin to static languages (same goes for users' configs, for those who use LDT)

Obstacles:
- while both systems can coexist, with each one taking care of HTML output for their own side, it's still necessary to build some coordination tooling (manual lists of what's what or detecting the foreign kind and skipping it) and "merge" the resulting index files into one
- this is a big one: no intermediate JSON representation for HS's internal help system; we could re-parse the HTML back (the ~~good old~~ days of `string.match(%u+ML)` parsers come to mind), or preferably add a JSON template along the HTML one

Thoughts?

**Comment by cmsj** [comment]
Being completely honest, I think catering to LDT is not a high priority for me, because I would expect people to be more likely to use Xcode to work on Hammerspoon.

However, our current doc system is not great, so I'd be interested in seeing results of other systems.

Some questions that immediately come to mind:
 * How big are the tools required to generate the docs - we need them to be included in our tree and easily runnable (I already dislike that we have an external dependency on the github-markdown ruby gem)
 * How would we get it to pull docstrings out of our C/ObjC files?
 * How would we generate docs.json? (You already mentioned that :)
 * How would we generate the SQL database for Dash?

**Comment by lowne** [comment]
- a lot of stuff:
> LuaDocumentor is based on popular lua libraries : lfs, metalua, lapp and template from penlight.

  - metalua alone is quite large
  - it also needs Lua ofc, I don't know if the one inside (I suppose) LuaSkin can be run standalone
- IIRC it works on C files too
- I would write a JSON template :/
- doesn't `gensql` work on the JSON output?

**Comment by cmsj** [comment]
Given #1155 I'm going to close this out. Sorry :)
