### ISSUE TITLE
no sample-extensions

### ISSUE THREAD

**Issue by bortels** [Hammerspoon/hammerspoon#516]
There does not seem to be a "sample-extensions" directory as indicated at https://github.com/Hammerspoon/hammerspoon/blob/master/CONTRIBUTING.md

This makes me a sad panda. 

Any recommendations of existing extensions that are simple enough to be used as a model? I was kinda thinking of doing something to talk to HID devices...

**Comment by asmagill** [comment]
Hammerspoon is currently undergoing a retrofit of the API recommended for module development and our docs/examples for contributions are behind.  That said, the traditional model for integrating external libraries into Lua do work -- the new API we're moving to just simplifies some of the process.

I would definitely look at the different modules in the extensions folder, https://github.com/Hammerspoon/hammerspoon/tree/master/extensions, to get an idea... traditionally most modules are divided into 2 files -- an init.lua which may be complete in and of itself or as simple as a wrapper to load the compiled code, and an internal.m file (Objective-C is the language of choice, though in theory others should work as well).  These modules are currently a part of the XCode project for Hammerspoon, so they don't have their own Makefiles, but most of them started as external modules and had one... as an example Makefile, you can look at one I use at https://github.com/asmagill/hammerspoon_asm/blob/master/wip/extras/Makefile; ignore the docs generation code, but otherwise it works for me no matter how many lua or objective-c files I have in the module and will install your test module in a proper path for including via the lua require command.

While you can install your module directly into a local clone of the Hammerspoon repository and compile from there, I find its quicker to keep the module isolated, at least at first, while testing.  I'm not that familiar with XCode myself -- I favor doing everything from the commandline, but check out the last entry in #468 for an idea of the process for integrating a new module's target.

You should also check out the Wiki at the Hammerspoon Git site... various links to the work of others can be found there and while some of it is dated, it should get you moving in the right direction.

The Google group and IRC channel mentioned at http://www.hammerspoon.org are also places to check out -- usually someone is available pretty quickly if you have questions.

If you're completely new to Lua or the Lua C-API, I personally found _Programming_In_Lua_, 3rd Edition very helpful -- it's lua 5.2 based, and we're at 5.3, but aside from there now being a distinction between numbers (floats) and integers, I've not found any changes necessary in the C side of my code.  (Check out http://www.lua.org/docs.html)

Hope this helps and isn't too confusing!  I'll see about pulling together some good examples for a walkthrough of the process I use -- everything is kind of in transition at the moment.

**Comment by asmagill** [comment]
@bortels, if you haven't already, check out https://github.com/asmagill/HS_ModuleWalkthrough.  It's a sample of how I generally code my modules when I'm testing things out.

**Comment by bortels** [comment]
awesome - I just last night cloned hs.usb and was using it as a kind of howto, so this should help a lot - thanks!
