### ISSUE TITLE
Adding methods

### ISSUE THREAD

**Issue by rtoshiro** [Hammerspoon/hammerspoon#532]
I'm getting error trying to adding methods:

function hs.screen.test(scr)
  hs.alert.show("hello")
end

hs.hotkey.bind({"cmd"}, "down", function()
  local win = hs.window.focusedWindow()
  win:screen():test()
end)

**Comment by cmsj** [comment]
@rtoshiro this would be because the Lua metatable for hs.screen objects is separate from the functions in hs.screen (this was a fairly recent change in Hammerspoon).

I don't think we currently have a way to inject things into the metatables for objects (@asmagill - am I wrong?). I'd like to know more about what your goal is here, to see if this is something we should look at changing.

**Comment by lowne** [comment]
`getmetatable(hs.screen.primaryScreen()).test=function(scr)...end`

**Comment by rtoshiro** [comment]
@cmsj @lowne Thank you for answers. 
My issue was happening just because I had updated Hammerspoon a long time ago, so my init.lua had a lot of hs.screen.xxx functions. 
No problem at all. I have replaced my calls. 
Thank you very much.

**Comment by cmsj** [comment]
Derp, thanks @lowne. For some reason I was thinking that would give us a copy of the table.

Also an option would be ```hs.getObjectMetatable("hs.screen").test=function(scr)...end```

**Comment by asmagill** [comment]
`hs.getObjectMetatable` is preferable as it doesn't create empty objects just for the sake of adding to the object methods.  In the case of getmetatable(hs.screen.primaryScreen()) this isn't an issue, but with things like timer and the watchers, it's just bad hackery (in my opinion at any rate) to create an object just for this purpose and then release it.  But it does work either way, so...
