### ISSUE TITLE
error in __gc metamethod

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#541]
In the last few days I've been noticing this in my Console:

```
error in __gc metamethod (attempt to call a userdata value)
stack traceback:
```

Very little info to go on, but perhaps someone else has seen this? If not, that might help isolate which extension it is.

**Comment by cmsj** [comment]
The one obvious module that I use which probably zero other people do, is `hs.milight` and looking at the code, I think the __gc method is in the wrong place (it's on the main library and not the object library), but I'm not convinced it should be causing this error.

**Comment by asmagill** [comment]
I started seeing it yesterday myself... I think it's related to hs.timer because it also showed something about "timer stopped to prevent repeated notifications of error" (or whatever the message is) but I haven't had a chance to track it down yet... and all of the timers I have running that I could think to check were still running at the time, though I didn't do a complete audit of my stuff yet...

Most of our __gc code uses the same macro used elsewhere in each module to wrap the verification and the dereferencing into one line... I've sometimes wondered what would happen if a __gc method actually returned an error because it was working on the wrong userdata type (or couldn't verify it for some reason) and luaL_checkudata tried to error out... could a userdata reference table be being released early for some reason?  Since I hadn't just done a reload, I don't think this could be the case, but... your thoughts?

**Comment by cmsj** [comment]
Could be, I do use hs.timer, although I just have one long-running one which shouldn't be GC'd in the lifetime of my config.

**Comment by asmagill** [comment]
I'm thinking its not timer anymore... it's __gc looks pretty clearcut to me, and I saw "error in __gc metamethod (attempt to call a userdata value)" again today without the accompanying timer stop message...

And for what its worth, I contrived a test where the __gc method for webview was replaced with drawing's, and got "error in __gc metamethod (bad argument #1 to '?' (hs.drawing expected, got userdata))" during routine garbage collection and the webview didn't go away... so that's a dead avenue...

**Comment by cmsj** [comment]
I guess we have some fun __gc auditing to do then :(

**Comment by cmsj** [comment]
I haven't seen this recently, so I think we can close this out. If anyone does still get that error, please re-open this :)
