### ISSUE TITLE
Crasher in unofficial Spaces module

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#555]
See http://crashes.to/s/d213def7a72 for the traceback.

@asmagill - not really sure what your support intention is for the unofficial Spaces module, so please feel free to close this if people get to keep all the pieces when it breaks :D

**Comment by asmagill** [comment]
I can only see one possible place for the crash to be occurring, but I can't fathom why its occurring because the index is hard coded and not user generated... The best fix is to wrap it and catch the exception at that place, but beyond throwing a lua error, I'm not sure what else can be done about it. The module really should be updated to use lua_pushinteger rather than lua_pushnumber and possibly a few other things as well...

And I was playing with the psuedo NSUserDefaults in com.apple.spaces and some of the other undocumented functions a while back to see about making it slightly more useful (maybe at least eak out a list of window ids on each space, but still no joy in actually moving or switching to them without the eventtap hack of posting key events to trigger the built-in processes), but I got distracted with LuaSkin and webview...

Yeah, I'll get to it since even our third party stuff shouldn't crash if possible, but it wasn't high on the list, so it might be a few days.

**Comment by asmagill** [comment]
source updated to wrap array methods with @try/@catch
