### ISSUE TITLE
hs.gris.set glitchy on 0.9.41 (was ok on 0.9.40)

### ISSUE THREAD

**Issue by jfchevrette** [Hammerspoon/hammerspoon#577]
https://youtu.be/NnLkjDFm4-c

As can be seen in the video, my test config is fairly simple. When moving the window around, the window seem to resize more than once for a single hs.grid.set.

This occurs wether the dock is at the bottom or side. Same if it's set to auto-hide.

If I press mod+LEFT many times, the window still shrink a bit then grow to the proper position even though it's already in the right position in the first place.

This did not occur on 0.9.40

**Comment by ztomer** [comment]
Can confirm, video:
https://youtu.be/o1QTlsV2ATE

**Comment by lowne** [comment]
This is the intended behaviour, and is meant to guarantee the correct result. The brief resizing is the only workaround to ensure that a window gets the desired size, because in some circumstances (namely when a window is along a screen edge, or straddling screens in certain ways, and trying to resize it just a little bit) the accessibility method for setting a window size will simply do nothing; see the updated docs for `hs.window:setFrame()` and `hs.window:setFrameInScreenBounds()`.

Downstream modules such as `hs.grid` now use `:setFrameInScreenBounds()` to ensure correct behaviour; perhaps we could add an option (in the modules themselves) to instead use `:setFrame()`, warning of the potential pitfalls. 

Thoughts?

**Comment by lowne** [comment]
In #574, behaviour restored to 0.9.40-like; you'll have to do `hs.window.setFrameCorrectness=true` to fix the stickiness bugs (but cause the "glitchy" thing)
