### ISSUE TITLE
10.11 — problems with eventtap leftMouseUp(?)

### ISSUE THREAD

**Issue by szymonkaliski** [Hammerspoon/hammerspoon#581]
I have this strange problem: on Yosemite I was successfully using function below, to move windows between spaces, on 10.11 it works, but if I run it, let's say move terminal window from space 2 to 3 (it works), I click ctrl-left to get back to space 2, once the space switching animation finished that terminal window appears. It helps if I click the titlebar, then the behaviour stops, so I suspect there's something wrong with `leftMouseUp`?

```lua
function moveToSpace(win, space)
  local clickPoint = win:zoomButtonRect()
  local sleepTime = 2000
  local mousePosition = hs.mouse.getAbsolutePosition()

  clickPoint.x = clickPoint.x + clickPoint.w + 5
  clickPoint.y = clickPoint.y + clickPoint.h / 2

  hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, clickPoint):post()

  hs.timer.usleep(sleepTime)

  hs.eventtap.keyStroke({ "ctrl" }, space)

  hs.timer.usleep(sleepTime)

  hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, clickPoint):post()

  hs.mouse.setAbsolutePosition(mousePosition)
end
```

**Comment by szymonkaliski** [comment]
bump :) can anyone at least confirm if this is an issue?

**Comment by lowne** [comment]
Can reproduce. I suspect it's a bug in El Cap, because

1. to "free" the target window from following along spaces, you have to click on the window's title bar. Clicking anywhere else won't suffice
2. Karabiner's EventViewer confirms that `leftMouseUp` is correctly posted

**Comment by szymonkaliski** [comment]
At least it's not just me :) 
I tried adding `hs.eventtap.leftClick` on the titlebar after the window is moved, but it didn't help, but I guess it's using the same logic (`leftMouseDown` + `leftMouseUp`) under the hood, so it makes sense... Anyone has any ideas for working around that?

**Comment by lowne** [comment]
Yeah, I tried various variations on that without any luck, but I found the bug: even manually, if you let go of the mouse button *before the space animation is over*, the window becomes sticky. So the fix is simply to `usleep(1000000)` before the mouseUp ;)

**Comment by lowne** [comment]
(also, this should probably deserve a radar, if anyone can be bothered)

**Comment by szymonkaliski** [comment]
Ok, few tests and here's what's working for me on El Cap, with shortest possible (but working!) times:

```lua
function moveToSpace(win, space)
  local clickPoint    = win:zoomButtonRect()
  local sleepTime     = 1000
  local longSleepTime = 300000
  local mousePosition = hs.mouse.getAbsolutePosition()

  clickPoint.x = clickPoint.x + clickPoint.w + 5
  clickPoint.y = clickPoint.y + clickPoint.h / 2

  hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, clickPoint):post()

  hs.timer.usleep(sleepTime)

  hs.eventtap.keyStroke({ "ctrl" }, space)

  hs.timer.usleep(longSleepTime)

  hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, clickPoint):post()

  hs.mouse.setAbsolutePosition(mousePosition)
end

```

**Comment by asmagill** [comment]
When I get a chance in a day or so, I'll check out the undocumented Spaces API again... most of it is arcane or unclear or just plan doesn't seem to work with the current way spaces functions since Mavericks, but I think I recall that it included a check to see the animation is currently active -- it's been a while so I'll have to check.

If so, I'll see if adding that to this allows for removing or shortening the timers, since they block Hammerspoon from other activity and really need to be kept as short as possible.

**Comment by szymonkaliski** [comment]
:+1:

**Comment by asmagill** [comment]
Update:  short answer, yes, the check exists and adding a while loop that checks this flag is a viable replacement for the second usleep...  

Longer answer: it requires a monitor identification string that (so far) I can't reliably determine just from the specific window being targeted (the string seems to be unique to Spaces and doesn't match anything I've found in NSWindow or NSScreen as of yet)... so I'm going to have to do some more digging later this week when I can get my second monitor hooked up again.

**Comment by szymonkaliski** [comment]
Sorry for bumping up this thread, but I have another problem, code above works fine when bound to left/right arrows, but if I want to move to specific space with it (bind to 1,2,3,4...) then it doesn't work somethow?

@asmagill — I've seen that you have something similar in your config, does this actually work for you: https://github.com/asmagill/hammerspoon-config/blob/e7ee39c19e5a61f9a9bb5d65f6eeefe03e71f34d/utils/_keys/spaces.lua#L130-L138 ?

**Comment by asmagill** [comment]
Mostly... I'm still working on the timing for raising a window (it is almost perfect if the window I select is currently the frontmost), and the version in that config is using some additions I've made to the hs.spaces module that aren't in core yet to determine if space animating is occurring (an attempt to remove some of the reliance on arbitrarily set timers).

Are you sure that the sequence ctrl-# is currently defined in your Keyboard Shortcuts in the System Preferences? I thought I was having issues once when I tried to jump to a space number that I hadn't used before and I found out that the key sequence wasn't defined in the Shortcuts yet (it seems they only appear up to the number of spaces available *right now* and aren't automatically assigned a key in some circumstances.  I had to assign 4-9 (they weren't assigned automatically for me):
![screen shot 2015-10-21 at 12 25 21 pm](https://cloud.githubusercontent.com/assets/8139480/10644723/c7444e2a-77ef-11e5-97cc-22c66680529e.png)

**Comment by szymonkaliski** [comment]
Hey, yes I have those spaces assigned, it works if I do it by hand (hold
the window, ctrl-number, and stop holding it), but somehow doesn't work
with this code. Binding this to left/right arrows works though, so it's bit
strange... Do you have any ideas how to debug this?

**Comment by szymonkaliski** [comment]
Ok, I figured it out, it works if I bind it to releasedFn, not pressedFn, like this:

```lua
hs.fnutils.each({ '1', '2', '3', '4', '5', '6', '7', '8', '9' }, function(space)
  hs.hotkey.bind(mod.cac, space, nil, function()
    moveToSpace(hs.window.frontmostWindow(), space)
  end)
end)
```

**Comment by asmagill** [comment]
I had forgotten that, but I can confirm that the space changing functions need to be bound on a key release, not on a key press... I assume its because when the key-pressed function is invoked, the keyboard modifiers you have pressed are still in effect, so the eventtap which is created to mimc the key sequence for spaces, or the system interpreting that particular injected event, is confused by the combination of the claimed (in the event) keyboard modifiers and the real keyboard modifiers and thus doesn't trigger... however, I never really dug any deeper into it.  A similar problem with needing to clear the modifiers is described at http://ianyh.com/blog/2013/06/05/accessibility/.

At any rate, since I got it to work, I didn't really dig much deeper!

**Comment by szymonkaliski** [comment]
Yeah, strangle left/right arrows work when bound to pressedFn! So it's only with numbers somehow... Either way, it's working :) Thanks!

**Comment by asmagill** [comment]
For those still following this thread -- I finally determined how to get the UUID that the undocumented CGSManagedDisplayIsAnimating function wants:  with CGDisplayCreateUUIDFromDisplayID which is in the ApplicationServices framework (ColorSync to be precise).  I'll see about wrapping it in a nice function so our space changing functions can check to see if animation is occurring, rather than setting a timer and hoping.

@cmsj - thoughts about putting this into hs.spaces?  It will be using an undocumented function, but its one that seems to have been around since Mavericks and it's just for querying... I don't believe we can break anything with it, as long as its fed the appropriate value from CGDisplayCreateUUIDFromDisplayID. I'm of two minds myself, so...

**Comment by lowne** [comment]
fwiw, +1 to have something like `hs.spaces.watcher.new(fnSpaceChangeTriggered,fnSpaceChangeCompleted)`

**Comment by asmagill** [comment]
Sticking with strictly non-private API's, the watcher works by looking for a message sent to the shared workspace notification center... it can't tell anything about the change except that it occurred.  With the recent changes I've made to `hs._asm.undocumented.spaces`, you can tell if animating is occurring (in progress), but without polling, I don't think even that can trigger an event when the animation is completed.

**Comment by lowne** [comment]
Yes, having `fnSpaceChangeCompleted` would rely on (very sparse) polling, say 0.3s after the trigger, and then at 0.1s intervals. It'd be useful for accounting for occasional system-level slowness.
