### ISSUE TITLE
drawing/text primitives

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#59]
I'd like to be able to create windows that are either drawn on top of all windows, or behind all windows.
Two specific use cases:
1. draw brightly coloured circles around the mouse pointer when a hotkey is pressed
2. replace geektool by drawing simple coloured shapes and rendering text on a window clamped to the desktop background

**Comment by ianclarksmith** [comment]
I'll second seeing a use for this functionality. My current use case: I have an eventtap in my config which allows constraining the cursor to an axis depending on distance from a mousedown event (could be anything) and the event's delta properties. It would be great if I could easily draw the axes on screen so that you don't need to guess where the initial event was triggered if you want to drag back and change axes.

What does the GeekTool/NerdTool provide here? (As an aside, I've found https://github.com/felixhageloh/uebersicht to be a more up to date replacement, but it works by adding NSWebViews)

Semi-primitive graphics would be most helpful in my opinion, addressing your first point and for augmenting Hammerspoon's other features.

**Comment by cmsj** [comment]
GeekTool provides text, image and little traffic light status symbols.

I'd like those and lines/boxes/circles, to start with.

**Comment by cmsj** [comment]
We now have the ability to draw circles, lines and text.

**Comment by cmsj** [comment]
Actually, I suppose I should re-open this until we have images too. bah :)

**Comment by cmsj** [comment]
TODO: Make all the methods return the object they are operating on, this was a terrible oversight on my part.

**Comment by cmsj** [comment]
Actually, let's make a proper TODO list:

 * [ ] Boxes
 * [ ] Images
 * [ ] Methods return the object they operate on

**Comment by cmsj** [comment]
Additional suggestions from elsewhere:
 * [ ] Shadows
 * [ ] Pattern (i.e. image fills)

**Comment by cmsj** [comment]
I'm going to close this out, hs.canvas now exists and is very powerful, if people need any additional features, let's file specific issues for them.
