### ISSUE TITLE
focusWindowWest oddity

### ISSUE THREAD

**Issue by ryfow** [Hammerspoon/hammerspoon#595]
If I have Chrome.app on the right side of my display and iTerm.app on the left side of the screen, `window.focusWindowWest()` will not move focus over to iTerm.app. I managed to get around this by focusing on the first window to the west that has a non-empty title, but I'm happy to troubleshoot more if you're interested. Here's my workaround:

```lua
        for k,v in pairs(hs.window.windowsToWest()) do
            if(v:title() == '') then
            else
                hs.window.focus(v)
                break
            end
        end
```

Forgive the terrible code, I've not programmed lua before and haven't even really researched the basics.

**Comment by lowne** [comment]
Perhaps the desktop is getting focused? (Finder in the menubar) 
If so, your workaround pretty much works; to be more exact, you can check for the window role:
```lua
for _,w in ipairs(hs.window.windowsToWest()) do
  if w:role()~='AXScrollArea' then return hs.window.focus(w) end
end
```
Or alternatively use the equivalent methods in hs.window.filter, which excludes the desktop.

@cmsj we've had other issues with the desktop being in allWindows() causing unexpected behaviour - after all it's not a "window", nor is its presence even documented; so far I've resisted filtering it out (because there might be valid use cases requiring it). Maybe a good solution would be to filter it out in :allWindows(), and provide access to it via a new :desktop() method?

**Comment by ryfow** [comment]
I have one visible Google Chrome window, but for some reason, Google Chrome is the first window to the west when the Google Chrome window is focused.

If I run this:
```lua
for k,v in pairs(hs.window.windowsToWest()) do
   log:d(v:application():title())
   log:d(v:role())
end
```

I get this output:
```
08:01:09     [init] -- table: 0x60800046bb00 Google Chrome
                    -- table: 0x60800046bb00 AXUnknown
                    -- table: 0x60800046bb00 iTerm
                    -- table: 0x60800046bb00 AXWindow

```

**Comment by lowne** [comment]
Ah, that must be chrome's status bar (AXUnknown); you can keep refining the :role() and :subrole() filtering (for every direction), or just use window.filter:
```lua
mywf=hs.window.filter.new():setCurrentSpace(true)

-- and then use (in hotkey.bind, presumably):
mywf:focusWindowWest(nil,false,true)

-- instead of
hs.window.focusWindowWest()
```

**Comment by lowne** [comment]
fwiw, this is my setup:
```lua
--- spatial window navigation
local wf_space=hs.window.filter.new(nil,'wf-SPACE'):setCurrentSpace(true):setDefaultFilter{}
bind(HYPER,'w','focus ↑',function()wf_space:focusWindowNorth(nil,true,true)end)
bind(HYPER,'x','focus ↓',function()wf_space:focusWindowSouth(nil,true,true)end)
bind(HYPER,'a','focus ←',function()wf_space:focusWindowWest(nil,true,true)end)
bind(HYPER,'d','focus →',function()wf_space:focusWindowEast(nil,true,true)end)
bind(HYPER,'q','send to back',function()hs.window.frontmostWindow():sendToBack()end)
```
Note I have the `frontmost` parameter set to `true`; I then use `sendToBack()` to switch between the different "layers" (i.e. access windows underneath) 
(I also have well-defined layouts via hs.window.layout - the solution above might not work very well for more anarchic situations :) )

**Comment by ryfow** [comment]
Nice! It might make to consider having `window.focusWindowWest()` use such a filter by default.

**Comment by lowne** [comment]
Well, the `hs.window` module should be agnostic, faithfully passing along what the OS provides, including all the idiosyncrasies, so that the user (or other HS modules) can have access to everything, if necessary.

`hs.window.filter` is meant to make it easy to work with the raw OS-level mess and get something sensible out of it, and as a particular case of this the default windowfilter (`hs.window.filter.default`) is a pre-populated windowfilter that's supposed to provide what the user likely wants in the vast majority of situations, such as your case above. 

So while I don't know why anyone would care about Chrome's silly status bars for `focusWindow...`, we shouldn't make it outright impossible (you never know!); but I'll see if I can improve the docs so that all this is clearly mentioned.

**Comment by ryfow** [comment]
Got it.

So I don't even need to create my own filter, I can just use `hs.window.filter.default` in most places I want to mess with focus. Seems like a great section to add to the getting started guide.

**Comment by lowne** [comment]
fwiw, #700 includes `hs.window.filter.focusWest()` etc as handy shortcuts:
```lua
bind(HYPER,'a','focus ←',hs.window.filter.focusWest)
```
but for these, the `frontmost` argument is set to false (as that should be the more common usage scenario)

**Comment by cmsj** [comment]
<lowne> gh#595 can be closed imo
