### ISSUE TITLE
hs.alert.show has wrong padding

### ISSUE THREAD

**Issue by ggustafsson** [Hammerspoon/hammerspoon#600]
I noticed that the padding around alert text is a bit off...

<img width="676" alt="screen shot 2015-10-10 at 17 12 24" src="https://cloud.githubusercontent.com/assets/595501/10411803/3d39f872-6f72-11e5-82a4-12836864770b.png">

Looked through the source code but I couldn't find anything odd (I don't know Objective-C).

**Comment by cmsj** [comment]
(This still applies to hs.alert as it stands today, having been rewritten in pure Lua)

**Comment by latenitefilms** [comment]
`hs.alert` should probably eventually be rewritten using `hs.canvas`.

**Comment by K6F** [comment]
The padding problem could be fixed by a little modify of size calculation. While I noticed that the `strokeWidth` of alert could affect displays too.   

<img width="599" alt="image" src="https://user-images.githubusercontent.com/2442194/95022465-1915d400-06aa-11eb-8d85-59afb006ffca.png">.  

I'm trying to fix it, although I won't rewrite it using `hs.canvas`.

**Comment by K6F** [comment]
This looks better to me.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/2442194/95023342-17024400-06af-11eb-8679-c2968b2eb192.png">

**Comment by asmagill** [comment]
This was probably made worse when `hs.drawing` was replaced with a wrapper to `hs.canvas` as canvas doesn't have quite the same issue with fudge factors for text that `hs.drawing` did.

I'll try to take a look at #2551 this week and see if I think it needs further adjustment or if it looks good as is... your screen shots certainly look better!

**Comment by K6F** [comment]
Hi, @asmagill
Since #2551 had been merged, I think this issue could be closed too.
