### ISSUE TITLE
hs.clearConsole or tabs for console output by "id"

### ISSUE THREAD

**Issue by bradparks** [Hammerspoon/hammerspoon#613]
Hey! I find the console super busy with messages from lots of things...

I'd love to be able to:
- programmatically and in the console window itself clear the console output
- have the console break into tabs optionally by "id", so if I did

```
local log = hs.logger.new("test")
log.showInTab()
```

then in the console window, there'd be a separate to for any outputs by log messages by id "test".

Maybe another simple way to get this would be to have a watcher for log events, so optionally an app could catch their own logs msgs, and do whatever they wanted with them?

**Comment by asmagill** [comment]
A certain amount of this already exists in hs.logger, but not all modules have been changed to take advantage of it yet.  I personally find the output from hs.hotkey a little overwhelming because it defaults to logging every registered key and when they are activated/deactivated, etc.  You can adjust this for hs.hotkey by putting something like this into your `init.lua` file:

      require("hs.hotkey").setLogLevel("warning")

where "warning" can be "nothing", "error", "warning", "info", "debug" or "verbose".

What other modules are you seeing a lot of output from?  Some of them may also be adjustable via hs.logger using a similar method, but not all of them have been converted yet... you can always take a look at making the updates yourself and submitting them for inclusion, or submit a specific list and we can try and address them as time and availability permits.


As to clearing the console, I've got a set of functions I've added in a third party module that can be found at https://github.com/asmagill/hammerspoon_console.  Specifically the `hs._asm.clearConsole()` function, but some of the others may be of interest as well. Currently I don't have a pre-compiled version available for download, because it relied on functions which weren't in the core application when I last worked on it, but I think it should be fine now... I'll see about getting a precompiled version up later today or tomorrow, or you can download it and compile it yourself.

--
A-Ron

**Comment by bradparks** [comment]
I just tried it and that custom console you have in your repo and it seems to work great! That plus the idea of turning off the hotkey logging will totally do all I want... thanks a bunch!

**Comment by asmagill** [comment]
@bradparks, can this be closed?

**Comment by cmsj** [comment]
Should we pull `clearConsole()` into the core? It might be interesting to people.

**Comment by bradparks** [comment]
I'm fine with it being closed anytime. I think having clearConsole in core would be a great idea, imho....

**Comment by asmagill** [comment]
simple enough to add... anything else in the module worth adding to the hs space? i'm biased so i leave it to the group to decide

**Comment by heptal** [comment]
+1

Also I think it would be really nice if `setHistory` and `getHistory` (perhaps everything in that module) were included and that [persistent console history](https://github.com/asmagill/hammerspoon_console#example-for-autosaving-and-retrieving-console-history-when-hammerspoon-starts) was enabled by default. I of course discovered this immediately after implementing persistent console history in a hacky way and looking for the 'right' way to do it:
```diff
diff --git a/Hammerspoon/MJConsoleWindowController.m b/Hammerspoon/MJConsoleWindowController.m
index e2ad25b..abcacb8 100644
--- a/Hammerspoon/MJConsoleWindowController.m
+++ b/Hammerspoon/MJConsoleWindowController.m
@@ -58,7 +58,14 @@ typedef NS_ENUM(NSUInteger, MJReplLineType) {
 - (void) windowDidLoad {
     [[self window] center];

-    self.history = [NSMutableArray array];
+    NSMutableArray *cachedHistory = CFBridgingRelease(CFPreferencesCopyAppValue(CFSTR("console.history"), CFSTR("org.hammerspoon.Hammerspoon")));
+
+    if (cachedHistory != nil) {
+        self.history = [NSMutableArray arrayWithArray:cachedHistory];
+    } else {
+        self.history = [NSMutableArray array];
+    }
+
     [self.outputView setEditable:NO];
     [self.outputView setSelectable:YES];

@@ -109,6 +116,7 @@ typedef NS_ENUM(NSUInteger, MJReplLineType) {

 - (void) saveToHistory:(NSString*)cmd {
     [self.history addObject:cmd];
+    CFPreferencesSetAppValue(CFSTR("console.history"), (__bridge CFPropertyListRef)(self.history), CFSTR("org.hammerspoon.Hammerspoon"));
     self.historyIndex = [self.history count];
     [self useCurrentHistoryIndex];
 }
```

**Comment by lowne** [comment]
In case anyone is interested in on-the-fly filtering: to enable it, some (or all) of what's discussed above should be implemented in `hs.logger` (easy enough, but `clearConsole` is required; and ideally we'd have a text field exposed to Lua for the filter string, performing `hs.filterConsole(filterString)` automatically); alternatively, if done in ObjC, logger would probably need to be modified to print the `id` on every line (filtering is possible without this, but the implementation would be less trivial).

**Comment by junkblocker** [comment]
:+1: for clearConsole. :+1: for on-the-fly filtering.

**Comment by asmagill** [comment]
I want to add a way to append an NSAttributedString to the console (sort of a "print with color") and then I'll make a list of things I think should maybe be added to core for consideration.  It will be in a different issue/pull, so I'm all for closing this particular thread whenever.

**Comment by cmsj** [comment]
I'm going to close this because I'm gardening the bugs and this has been open for ages with no further discussion, feel free to re-open it if there are specific things you want to do :)

**Comment by asmagill** [comment]
FYI see [hs.console.printStyledText](http://www.hammerspoon.org/docs/hs.console.html#printStyledText) if anyone searches for this later.
