### ISSUE TITLE
Cannot bind hotkey to colon

### ISSUE THREAD

**Issue by alxppp** [Hammerspoon/hammerspoon#616]
It seems one cannot bind functions to a hotkey triggered through a colon. I tried:
```
hyper = { 'cmd', 'alt', 'ctrl', 'shift' }
hs.hotkey.bind(hyper, ':', function()
  ...
end)
```

Error:
```
init.lua:325: Invalid key: :
stack traceback:
	[C]: in function 'error'
```
Any other key works in this configuration.

**Comment by lowne** [comment]
For a US layout, you would do `hotkey.bind(hyper,';'...)` - does your keyboard have `:` on a non-shift position?

**Comment by alxppp** [comment]
My keyboard looks like this:

![screen shot 2015-10-21 at 22 41 15](https://cloud.githubusercontent.com/assets/4237216/10649578/1c2aadc6-7845-11e5-926d-8ca6fb4fd45f.png)

**Comment by lowne** [comment]
Did you try `hyper,'.'`?

**Comment by alxppp** [comment]
Yes, this code works:
```
hs.hotkey.bind({'cmd', 'alt', 'ctrl'}, '.', function() ...
```
However, I want `{'cmd', 'alt', 'ctrl', 'shift'}` as hyper. When I do this:
```
hs.hotkey.bind({'cmd', 'alt', 'ctrl', 'shift'}, '.', function() ...
```
it doesn't work anymore. I though it was because of the shift, which makes the `.` a `:`, so I bound to `hyper, ':'`. But this results in the error described above.

**Comment by lowne** [comment]
Huh, from what I can gather from `extensions/keycodes/internal.m` the keycode map should take the keyboard layout into account; however just to be sure try this in the Hammerspoon Console:
`hs.eventtap.new({hs.eventtap.event.types.keyUp},function(e)print(inspect(e:getRawEventData()))end):start()`
then press `.`, and you'll see the associated key code (it's `47` here); try using that number instead of `.`, like so:
`hs.hotkey.bind(hyper,47,...)`

If that's not the issue, then make sure you don't use that hotkey elsewhere, in your own HS config (the console log should tell you if you're binding the same hotkey twice), in System Preferences/Keyboard/Shortcuts, or in some other application that registers global hotkeys.

**Comment by lowne** [comment]
Another keyboard layout-related test: with `hs.hotkey.bind(hyper,'.',...)`, did you try pressing all other non-alphanumeric hotkeys (e.g. `hyper-Ö`) to see if maybe your callback triggers on the "wrong" key?

**Comment by asmagill** [comment]
My first thought was to check hs.keycodes.map["."] and make sure it returns a number... if it doesn't, then this means that your keyboard layout isn't identified correctly and we'd need to dig into hs.keycode to figure out why.

However, seeing that your keyboard has the colon on the period key was niggling at the back of my head and I finally remembered that Cmd-Opt-Ctrl-Shift-Period (at least on my keyboard) is used by the system for capturing diagnostic information that might be requested by Apple Support...  http://krypted.com/tag/control-option-command-shift-period/ has a decent description of this.  It takes about 45-60 seconds after I hit the key to pop up the with the results on my laptop... have you noticed this in your testing?

At any rate, if it is the sysdiagnose process which is being triggered, I don't know that we can do anything about it... I had some luck intercepting and preventing system level keypresses by recreating hs.hotkey entirely with hs.eventtap, but doing so caused random dropouts of all keyboard activity in all applications (when hammerspoon got too slow, the eventtap was disabled internally, but until Hammerspoon actually received the eventtap disabled notification, all keyboard notification was suspended systemwide) so I decided the ability to override system defined hotkeys wasn't worth the trade-off.

If Cmd-Opt-Ctrl-Shift-Period triggers a system event, like the brightness fn keys do, it might be possible to use a more narrowly targeted eventtap like I do in https://github.com/asmagill/hammerspoon-config/blob/master/utils/_keys/brightness.lua; however, I have no idea if it does, so that might not work...

And a more general eventtap which watches for key presses would probably work, but you're likely to run into the same key-dropping problem that I did.

**Comment by alxppp** [comment]
@lowne, @asmagill Thank you very much for your support!

@lowne I checked the key code, it was also 47 on my keyboard.
@asmagill You are absolutely right. Cmd-Opt-Ctrl-Shift-Period triggered sysdiagnose to create a snapshot of relevant system logs and open them in a Finder window. Unfortunately I wasn't able to override this hotkey.

After all, I fixed it by changing my hyper to `hyper = { 'cmd', 'alt', 'ctrl', 'fn' }`. Then you can bind to `hyper + .` without any problems.

**Comment by lowne** [comment]
@alxppp iirc `hs.hotkey` cannot monitor `fn` (you'd need `hs.eventtap` for that), so what you're binding is just `cmd-alt-ctrl+.` - fn status is ignored.

**Comment by alxppp** [comment]
@lowne You're right, fn is being ignored. `cmd-alt-ctrl` works for me for now, just out of curiosity, could one use F19 as hyper? That way one wouldn't even need to rebind F19 to `cmd-alt-ctrl` in Karabiner.
