### ISSUE TITLE
Built-in auto-reload config on file change

### ISSUE THREAD

**Issue by dj-hedgehog** [Hammerspoon/hammerspoon#619]
I'd be great to be able to auto reload the configuration when changes occur.

You can easily place `hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", hs.reload):start()` inside your configuration but it doesn't work  anymore if an error occured.

So how about having this feature built-in.

**Comment by chdiza** [comment]
I wouldn't want that "feature".  If I'm making more than a trivial change to my config, I might hit "save" long before I actually want to attempt loading it.

**Comment by asmagill** [comment]
Most routines of this sort go into effect as they are evaluated... placing this command at the start of your init.lua file will likely work as you want for run-time errors.  For syntactic/load-time errors, your best bet is to reduce your init.lua file to the bare minimum, including this watcher, but with the last line requiring another file or files... then, as you edit the other files, the watcher will work as you want because the file it is in wasn't the one which contained the load-time error.

**Comment by cmsj** [comment]
@chdiza it would be an option, so you could just leave it disabled :)

I'm generally not opposed to this idea, but there are some details to be figured out - would we only watch for changes on init.lua, or on all .lua files under ~/.hammerspoon/ ? I would tend to think the former, with people needing the latter being able to rely on hs.pathwatcher.

**Comment by asmagill** [comment]
Because of the work-around I outlined above, my general opinion is that it's not worth adding, but I'm not opposed per se... just make it default to off so it doesn't suddenly affect those of us who don't want it (or more specifically want the flexibility that a pathwatcher gives us that a toggle doesn't) :-)

**Comment by cmsj** [comment]
I think I agree - with the addition of Spoons, it's ever more likely that Lua files will be showing up in ~/.hammerspoon/ in situations where a reload is not appropriate.
