### ISSUE TITLE
Add hs.pasteboard.watcher

### ISSUE THREAD

**Issue by heptal** [Hammerspoon/hammerspoon#634]
From doc: 

``` objc
/// hs.uielement:selectedText() -> string or nil
/// Method
/// Returns the selected text in the element
///
/// Parameters:
///  * None
///
/// Returns:
///  * A string containing the selected text, or nil if none could be found
///
/// Notes:
///  * Many applications (e.g. Safari, Mail, Firefox) do not implement the necessary accessibility features for this to work in their web views
```

The fact that many applications do not implement the necessary accessibility features really cripples this in my opinion. For example, I have an Alfred hotkey that replaces `my sample selected text` with `"""my sample selected text"""` to make verbatim Google searches fast and easy. It works everywhere in Alfred, but only in the address bar using `hs.uielement.selectedText` due to the aforementioned issue with web views (it seems silly on Apple's part not to include accessibility features in web views since they are so widespread). 

I poked around in Alfred's framework binary (w/ Hopper, a great disassembler app along with the classic `strings`) and found that their 'Get Selected Text' method constructs a literal `⌘C` key event using `CGEventCreateKeyboardEvent` along with their pasteboard manager class to determine when the text is copied (by polling it appears...obviously I have limited visibility) before passing it along to your workflow.

I can crudely simulate this with the following (although it is much faster than Alfred and doesn't do odd UI flashing like Alfred and restores the pasteboard unlike Alfred):

``` lua
hs.hotkey.bind(hyper, "'", function() 
        local oldText = hs.pasteboard.getContents()
        hs.eventtap.keyStroke({"cmd"}, "c")
        hs.timer.usleep(100000)
        local text = hs.pasteboard.getContents()
        hs.pasteboard.setContents(oldText)
        hs.eventtap.keyStrokes('"""' .. text .. '"""')
    end)
```

Of course, the key event itself is very fast while the actual copying operation takes a non-zero amount of time. As far as I can tell there is no way to be notified upon system pasteboard events, requiring the use of `hs.timer` (otherwise the pasteboard contents can get mangled if the operations aren't finished).

Does anyone else consider this useful enough to integrate the core idea (`⌘C` key event with timer, backing up old pasteboard contents, returning text then restoring pasteboard) into `hs.uielement.selectedText`?

**Comment by cmsj** [comment]
I'm not sure if we necessarily need to build it into the app, and I'm certain we shouldn't build it into `selectedText()`, but we can certainly do something to make it easier. The main issue with your code is the `usleep()` - that blocks Hammerspoon execution, which is something we should try to avoid.

Unfortunately it is certainly the case that we have no choice but to poll the Pasteboard for changes, there are no notifications that can tell you when it changes. However, we could build an official hs.pasteboard.watcher that does the polling for you and calls a callback function when new pasteboard data is found.

Maybe a final version like this would be nice:

```
local oldPasteboardContents = nil
local pasteboardWatcher = nil
local pasteboardTimeoutTimer = nil

hs.hotkey.bind(hyper, "'", function()
  oldPasteboardContents = hs.pasteboard.getContents()
  pasteboardWatcher = hs.pasteboard.watcher.new(function(newPasteboardContents)
    hs.eventtap.keyStrokes('""'..newPasteboardContents..'""')
    pasteboardWatcher:stop()
    hs.pasteboard.setContents(oldPasteboardContents)
    oldPasteboardContents = nil
  end)
  pasteboardWatcher:start()
  hs.eventtap.keyStroke({"cmd", "c")
  pasteboardWatcher:stop()
  pasteboardTimeoutTimer = hs.timer.doAfter(3, function()
    pasteboardWatcher:stop()
    pasteboardWatcher = nil
    pasteboardTimeoutTimer = nil
  end):start()
end)
```

This is more code, partly because it's now asynchronous, and partly because it should really be defensive about making sure the watcher doesn't run past a reasonable timeout, in case the ⌘C doesn't actually manage to copy any data.

It would also be possible to do this using the application menus, replacing the ⌘C line and following lines, with:

```
  local result = hs.application.frontmostApplication():selectMenuItem({"Edit", "Copy"})
  if ~result then
    pasteboardWatcher:stop()
  else
    pasteboardTimeoutTimer = hs.timer.doAfter(3, function()
      pasteboardWatcher:stop()
      pasteboardWatcher = nil
      pasteboardTimeoutTimer = nil
    end):start()
  end
```

but that runs into the issue of localisation.

I think my preferred route would be to add `hs.pasteboard.watcher` and then add some part/combination of the above snippets, to the Getting Started Guide. How does that sound?

**Comment by heptal** [comment]
Sounds like a great idea to me. After I had posted I realized that `hs.pasteboard` should be the place where this functionality should be implemented, since `hs.uielement` is a separate API domain and shouldn't be concerned with this.

**Comment by cmsj** [comment]
I am going to close this because I think it would be a great candidate for being a Spoon. Perhaps someone could file an issue on the Spoons repo suggesting it? (or better yet, write it and submit a PR :)
