### ISSUE TITLE
HS steals window focus on launch and won't give it back

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#651]
HS, when launching is completed, gets itself in the following situation:

Whichever app was the active app (Name in upper-left of menubar) is still active, but none of its open windows have focus.  Not even the window that had focus prior to launching HS.

Example: HS is not active (quit it first).  iTerm is open, and has one open terminal window in which I am typing (so this window has focus).  I type 'open -a hammerspoon.app', and HS launches.

Expected behavior: HS finishes its launch, and that iTerm window still has focus; I can keep typing without clicking in the window first.

Actual behavior: Though iTerm is the active app, its window lacks focus.  I can't give that window focus even by doing Cmd-backtick, or by hitting Cmd-Tab and then Cmd-backticking and releasing.  Only two things will get focus back on that iTerm window: mouse clicking in it, or Cmd-tabbing to a different app, and then redoing the Cmd-tab to go back to iTerm.

There's nothing special about iTerm here, it's just an example.

Also, my init causes no windows to be launched or focused.  The console is not set to always show, the menubar is off, the dock icon is off.

Also, I see this even with a blank init.

Also, I tried to hack around this by capturing the hs.window.frontmostWindow() in the init file, and then at the end of the init file telling that window to focus().  This only half works.  The window (e.g., iTerm) gets focused very briefly (so fast I can barely see it), but then loses it again.  This, too, can happen with an init that's totally empty apart from requiring hs.window and the commands to employ this trick.

**Comment by cmsj** [comment]
In theory we should be able to stop this by setting LSUIElement=1 in the Info.plist, but a quick experiment with that didn't have any effect, so either OS X didn't notice that setting, or something else in our startup code is forcing the app to become active.

Seems worth investigating, this is an annoying behaviour

**Comment by cmsj** [comment]
I think the only way around this would be to completely restructure the app to be a genuinely LSUIElement-free app, and have things like the prefs/console windows run as separate binaries. As it stands right now, Hammerspoon is an app with a menubar and proper windows, so it gets treated as such, however annoying that may be.

**Comment by chdiza** [comment]
Neither Hyrda nor Mjolnir had this problem, FWIW.

Couldn't HS be made to hide itself?  I tried checking that box in the loginwindow items pane of System Preferences, but it had no effect.

**Comment by latenitefilms** [comment]
You could probably add something in Objective-C land that works out what is the current frontmost window before Hammerspoon loads any of the menu items, etc. store that value, then change the focus to that window once Hammerspoon is ready to start loading `init.lua`?

**Comment by latenitefilms** [comment]
@chdiza - FYI: this seems to work for me:

```
local frontmostWindow = hs.window.frontmostWindow()
hs.timer.doAfter(1, function() frontmostWindow:focus() end)
```

**Comment by asmagill** [comment]
FWIW, and it may be because of the complexity of my particular setup, I got more consistent results by putting `local frontmostWindow = hs.window.frontmostWindow()` at the top of my `init.lua` file and `hs.timer.doAfter(1, function() if frontmostWindow then frontmostWindow:focus() end end)` at the end, interspersing the rest of my config in between the two.

**Comment by chdiza** [comment]
@latenitefilms @asmagill Thanks for the suggestions.  I'll try them out tomorrow.  I have a feeling that idea won't cover the case where HS is itself a loginitem, because I have a feeling that when login occurs there is no frontmost window---just an empty desktop.  But I'm eager to try.

**Comment by chdiza** [comment]
@asmagill Just out of curiosity, how come the `frontmostWindow:focus()` is wrapped in a timer?  If it's the last line of the `init.lua`, why not just call it directly?

**Comment by asmagill** [comment]
Re your question about what happens when HS is a login item, what behavior would you want?  I've added a check to make sure frontmostWindow isn't nil, so I expect it to behave the way it always has, but I haven't actually tried it yet.

Re the timer, mostly because it didn't work without the timer (I tried it).

I suspect it's because the end of `init.lua` isn't the end of Hammerspoon's processing of things... `init.lua` is called from `hs._coresetup` which then returns to MJLua.m which does a few more things before actually entering Hammerspoon's runloop.

**Comment by asmagill** [comment]
If you have a particularly quick load, you could change the time to something smaller (it will take floating point numbers).  The point of wrapping it in a timer is to create a queued event which will be sent to Hammerspoon's runloop; `init.lua` is processed before the runloop is started... everything that is a callback get's queued and processed in the order they are submitted to the runloop *after* the runloop is started.

**Comment by cmsj** [comment]
I've been up and down the stack of ways I can find to either prevent, or resign active status, and I have yet to find a single way to reliably stop HS stealing focus when it starts. I would love it if someone with more clue about these details could help figure out what we're doing that's triggering it, but I'm afraid comparisons with Mjolnir/Hydra aren't helpful - we've diverged so far from those codebases that I don't think there's any useful amount of diffing that can be done, sort of stepping through every single line of code that's executed on startup (and even that might not be enough, since this could be an artifact of some XIB/AppInfo setting) 😔

**Comment by chdiza** [comment]
@cmsj I appreciate you tackling this.  In mentioning Hydra/Mjolnir, I didn't mean to suggest a diff or a comb-through, or other painstaking work.  I only meant to suggest that because the desired behavior is possible (since some app has it), having a prefs window/menubar doesn't by itself automatically doom HS.  For all I know, something *else* dooms HS to have the undesired behavior, and for all I know, that something is the groundwork of a bunch of other desirable stuff and thus shouldn't be modified, even if it could be identified.

I'm confident that some version of the suggested workaround will do just fine.

**Comment by cmsj** [comment]
Sorry, I think my message came across very differently from how I meant it, and reading it back I could have worded it very differently. I didn't mean to suggest you were being actively unhelpful, I just meant that there's too much divergence to be able to see what we've done to change this behaviour.
Thanks for your efforts, I'm sorry we haven't been able to track this one down!

**Comment by chdiza** [comment]
@cmsj I felt pretty sure you didn't mean it in the bad way, but I also saw that my "FWIW, Mjolnir doesn't do this" could've been read in such a way that made me seem snotty, when that wasn't my intention at all.  So, on the off chance I had offended, I erred on the side of caution.  :)

Also, thanks for HS.  For me, it has completely replaced both Slate and GeekTool, combining their duties into one app.  And in the case of replacing GeekTool, HS does the job better than the original.  (It quite possibly Slates better than Slate, too, I just stopped messing with it after I got Mjolnir/HS to replicate the parts of Slate important to me.)

**Comment by chdiza** [comment]
> The point of wrapping it in a timer is to create a queued event which will be sent to Hammerspoon's runloop;

@asmagill OK, thanks for the explanation.  That makes sense.

> Re your question about what happens when HS is a login item, what behavior would you want?

What I would want is that after HS is launched as a loginitem and the beachball subsides, the active app will be Finder and I will be looking at just my desktop.  Should I choose to hit Shift-Cmd-D or Shift-Cmd-H, those Finder keyboard shortcuts will work like normal.  I'm about to try the workaround when I get to my work computer, but what I often see is that the active app is Hammerspoon even though my HS is set to have no windows, no menu bar, and no dock icon, and those Finder keyboard shortcuts don't do anything because Finder isn't the active app.

BTW, I'm not complaining about the beachball.  Over the last 14 years of OSXing I've noticed that loginitems tend to beachball even when those same apps don't beachball when not used as loginitems.  It just seems to be an Apple-imposed cost of doing loginitem business, and I can live with that.  When not used as a loginitem, HS will sometimes beachball (even with an absolutely clean `init.lua`), but not nearly as frequently as when invoked as a loginitem.

**Comment by chdiza** [comment]
@asmagill @latenitefilms Thanks for the workaround.  A day and a half of testing and it looks pretty good.

**Comment by asmagill** [comment]
Thinking about wanting login items to leave you in the finder... that's been an annoyance to me for a while now, and it's not just Hammerspoon that seems to prevent it... I think Apple made some changes underneath and now about half of my login items (not just Hammerspoon) have a chance of maintaining focus rather than allowing it to end up with the Finder.

I haven't tried setting the timer to specifically focus the finder yet when the captured window object is nil, (just made the change, so I'll know more over the next few hours/days), but that means that *any* time a reload occurs and it can't identify a window the Finder gets focused, not just on login... not sure if we can detect that the launch came from logging in or not yet... never tried or looked into it yet.

**Comment by chdiza** [comment]
In my experiments so far I haven't needed to handle the case of a nil window object.  HS is so far doing the right thing.
