### ISSUE TITLE
In-app documentation viewer

### ISSUE THREAD

**Issue by sdegutis** [Hammerspoon/hammerspoon#655]
Playing around in the Console is really fun. But I have my browser window open in another window pointing at the docs. It'd be nice if I could see the documentation live inside Hammerspoon somehow? Maybe even navigate it with a hierarchical UI that lets me easily backtrack and jump around (maybe a tree-view on the left)?

**Comment by cmsj** [comment]
We have a `help()` which either takes a string (so `help("hs.drawing")`) or can be indexed (so `help.hs.drawing`) which can drill down through all of the same docstrings that end up in the Dash/web docs, but it's a long way from a tree browser!

Given that we ship the docstrings JSON file, it shouldn't be too hard to have a native doc viewer. Any volunteers to write it? :)

**Comment by asmagill** [comment]
This suffers from lacking a native sqlite module and requires the uncompressed version of the docset, but I threw this together a while back as a proof-of-concept for providing a webview interface to the Dash documentation:  https://gist.github.com/asmagill/633c8515e6ace3335d31

**Comment by asmagill** [comment]
While I wouldn't mind seeing a sqlite module added at some point, re a native help viewer, check out `hs.doc.hsdocs`, which displays help in an `hs.webview` which allows selecting a module name from the toolbar, or typing in a module name to jump directly to a module/function... it's not a true search because you have to type in a full path (e.g. "hs.logger.printHistory" as opposed to something like "printHistory") to jump to a specific module/function, but I think it addresses the original intent of this issue, even if it opens up a new one about sqlite..

I'm fine with closing this one.
