### ISSUE TITLE
fn key as modifier?

### ISSUE THREAD

**Issue by yoavg** [Hammerspoon/hammerspoon#689]
I guess this is an OS level issue, but still worth asking: the current API does not allow using the 'fn' key as a modifier. As this is practically the most useless key on the laptop's keyboard (well, aside from the power button), it would be really nice if it could be dedicated to hammerspoon shortcuts... is the fn key even catchable at the level hammerpsoon operates on? the eventtap module docs seem to suggest that it is.

(the usual solution of mapping cmd-alt-shift-ctrl to some other key is OK, but I rather have a solution in which I can still use extra modifiers on top -- it is easier for me to remember things this way.  For example, I'd like to have fn-h move the window, fn-shift-h resize it, etc.)

**Comment by szymonkaliski** [comment]
`fn` modifies some keys and hs can catch it, for example I have some mapping with arrow keys:

```lua
  hs.fnutils.each({
    { key = 'pageup',   direction = 'up'    },
    { key = 'pagedown', direction = 'down'  },
    { key = 'home',     direction = 'left'  },
    { key = 'end',      direction = 'right' }
  }, function(object)
    hs.hotkey.bind({ 'ctrl', 'cmd' }, object.key, bindWin(window.focus, object.direction))
  end)
```

So actually cmd+ctrl+fn+arrow sends proper event...

**Comment by asmagill** [comment]
I tried writing a hotkey replacement at one time which used eventtap for hotkey captures instead of RegisterEventHotKey, which is what hs.hotkey uses; using eventtap, you can use the fn key as a modifier and it was possible to reliably replace some of the system default key mappings that sometimes crop up as "un-replaceable" with the current implementation, but it had its own issues, primarily that if Hammerspoon was slow for any reason, keyboard entry dropped completely system wide until Hammerspoon could respond.

So, it's more or less abandoned, but I poke at it every so often if I think of something new to try.

You're more than welcome to take a look at it:  https://github.com/asmagill/hammerspoon_hotkey.  There is a lua_only branch, and master, where I moved almost everything to increase responsiveness, but... I never could get around keyboard dropouts, though the master branch does suffer from less of them.  It's a little old now, so there may be a few things in hs.hotkey that might need some tweaking, but it should be close to a drop in replacement (that was the goal at the time).

**Comment by asmagill** [comment]
It also occurs to me that you could add something like this to your hotkey function:

~~~lua
if hs.eventtap.checkKeyboardModifiers().fn then
    -- do whatever when fn key is down
else
    -- do whatever when fn is not down
end
~~~

but you're still left with the fact that the key+modifiers without the fn key will trigger this function as well and not be passed on to the rest of the system... not sure if you could inject the key with `hs.eventtap.event.newKeyEvent`, or if that would create an effective infinite loop... I might have to look into that...

**Comment by asmagill** [comment]
Actually,

~~~lua
xyzzy = hs.hotkey.bind({}, "j",
    function()
        if hs.eventtap.checkKeyboardModifiers().fn then
            hs.alert.show("FN is DOWN!!!")
        else
            xyzzy:disable()
            hs.eventtap.keyStroke({}, "j")
            xyzzy:enable()
        end
    end
)
~~~

seems to work.

Of course, if you add other mods and/or don't care about passing through the keys you don't do anything with, the example above is simpler.

**Comment by yoavg** [comment]
great, thanks! I need to see if there is a noticable lag for this, don't want my usual typing to be slowed down.

**Comment by cmsj** [comment]
That's an...interesting solution... :D

If it was me, I'd use Karabiner to remap the Fn hotkeys to something that Hammerspoon can intercept, or a URL event (see our Getting Started Guide) :)

**Comment by asmagill** [comment]
I'm curious how they do it, but this seems to work well for me and I haven't noticed any side effects yet.

**Comment by cmsj** [comment]
@asmagill Karabiner is a kext, they hook in at a much lower level than us :)

**Comment by viogus** [comment]
as 0.9.52 released, any update on this?

**Comment by Mike-NetCode** [comment]
Bump :)

**Comment by cmsj** [comment]
@Mike-NetCode I'd suggest re-opening issues if you think there is work to be done, rather than bumping a closed issue :)

As for using Fn for hotkeys, the way that hs.hotkey currently works means it cannot support Fn, but we have hs.eventtap which should work fine :)

**Comment by lizardcobra** [comment]
@cmsj, I'm very confused as to what the suggested solution actually is. How would remapping using Karabiner work? From what I can tell, hs.hotkey.bind only supports the standard modifier keys and a single non-modifier key. So what could a key like 'fn' be mapped _too_ that would allow it to function as a modifier key?

It seems like you suggest there is a better method than the solution offered by @asmagill , but you also say that hs.eventtap can be used to solve this?

Is there a full working example of this somewhere?

**Comment by NightMachinery** [comment]
Is Karabiner still using a kernel extension? I vaguely remember that kernel extensions were deprecated …
