### ISSUE TITLE
Time Machine controls / hs.task() sudo capability

### ISSUE THREAD

**Issue by herrbischoff** [Hammerspoon/hammerspoon#707]
Today I have moved from ControlPlane to Hammerspoon and will not look back. Another GUI application rendered unnecessary — I love it!

So far however, I have been unsuccessful in duplicating a simple disable/enable Time Machine function for Hammerspoon. This is, I suspect, due to `hs.task()` being unable to run tasks as root. To change the current Time Machine status you need root privileges.

Is there possibly something I overlooked? Searching through the API reference and closed issues here did not reveal anything resembling my approach. I'll appreciate any pointers. Thanks!

**Comment by asmagill** [comment]
It looks like this will work (though it will prompt you each time):

~~~lua
n = hs.task.new("/usr/bin/osascript", function(...) print(hs.inspect(table.pack(...))) end, { "-e",  [[do shell script "/bin/ls -la /var/root" with administrator privileges]]}):start()
~~~

You could probably also use a SUDO_ASKPASS program if you have one in mind (I can't seem to find ssh-askpass in the default OS X install, which is what I have used under linux in the past) with something like the following (untested, so the arguments might need tweaking):

~~~lua
n = hs.task.new("/usr/bin/sudo", function(...) print(hs.inspect(table.pack(...))) end, { "-A", "/bin/ls" "-la", "/var/root" })
t = n:environment()
t.SUDO_ASKPASS = "path-to-gui-prompt-program"
n:setEnvironment(t)
n:start()
~~~

We first get the environment and then add to it because the setEnvironment command is not additive.  We can usually ignore this because the environment defaults to the Hammerspoon one unless you use setEnvironment, which we need to do in order to add the SUDO_ASKPASS variable.

A future update to `hs.task` will allow setting the stdin (user input) for a task, but a quick test with a development version of Hammerspoon shows `sudo` giving an error because the task isn't on a tty... I don't see an obvious work-around atm, but I haven't dug too far yet.  Will update if I find more, but hopefully one of these will help in the meantime.

**Comment by cmsj** [comment]
I would configure /etc/sudoers to give my user the ability to run the time machine commands without a password. Let me know if you need help crafting the relevant config :)

**Comment by cmsj** [comment]
I might as well just paste some `sudoers` stuff while I'm here.

First things first, you should only ever edit `/etc/sudoers` by way of the `visudo` command, since it will check the syntax for you, and make sure you aren't about to accidentally disable your ability to sudo at all, because you typed something wrong :)

Here are two suggested entries, depending on what you want.

1. passwordless access to `tmutil enable` and `tmutil disable` (`cmsj` is my username, so you'll need to change that to your username)

```
cmsj ALL=(root) NOPASSWD: /usr/bin/tmutil enable
cmsj ALL=(root) NOPASSWD: /usr/bin/tmutil disable
```

2. passwordless access to all of `tmutil`:

```
cmsj ALL=(root) NOPASSWD: /usr/bin/tmutil *
```

Generally speaking, it's best practice to grant the minimum possible sudo power, so if you literally just want enable/disable, then go with the first option. However, if you want to start doing more complex stuff with tmutil, consider the second option. Hope that helps :)

**Comment by asmagill** [comment]
Yes, I had forgotten about that approach... that will prevent the need for a password at all for specific commands... however, there are some things I'd rather not have quite that easily accessed in case someone else is using my machine... knowing how to do both has its place.

**Comment by cmsj** [comment]
So, looking at the Control Plane source, they have a Helper Tool, which is a separate process from the main app, authorised to run as root. I don't currently think this is something we're considering doing (it certainly makes me very nervous, security-wise!), so I'm going to close out this issue with the recommendation that you use the sudoers method I outlined for giving yourself passwordless sudo access to the specific commands you need.
If anyone wants to disagree, please feel free to re-open this issue, or start a new one for discussions of a helper tool :)

**Comment by asmagill** [comment]
FWIW, for the record, the method using the SUDO_ASKPASS environment variable works.  You can do something as simple as a shell script which echo's the password and set SUDO_ASKPASS to that shell scripts path.   Or, if you want Hammerspoon to have stored/retrieved/whatever the password from somewhere, use a script like:

~~~bash
#! /bin/sh
/usr/local/bin/hs -c 'return functionToGetPasswordFromWhereEver()'
~~~

But I agree; Hammerspoon is a "swiss-army-knife" and we don't know what the end user might want to do... giving them an official helper with administrative access would by it's nature either have to be extremely limited (not the goal of Hammerspoon) or an enormous security hole allowing what amounts to an arbitrary string to be executed.

Between editing /etc/sudoers, the osascript example above, and the SUDO_ASKPASS environment variable option,  I think most situations should be covered or at least can be worked around.

**Comment by cmsj** [comment]
I wouldn't encourage using a script that echo's your passphrase, that is also an arbitrary root exploit waiting to happen.

Agreed that a helper tool which runs arbitrary commands is not a good idea. 

I really want to stress that, short of typing your passphrase every time, careful and specific passwordless commands in sudoers is the most secure option here. 

We could explore the idea of a helper tool that can be configured to run specific commands of the user's choice, but at that point you're no different to using sudoers, you just have lots of less well tested code doing the job :)

**Comment by asmagill** [comment]
While I agree with you that a script that does so is a risk and shouldn't be encouraged per se, all we are doing is using the `sudo` command with the -A option and it's corresponding environment variable *in the way it was designed to be used*.

The sudo helper script can do its own thing to prompt for a password, look it up in a database, whatever you design it to do (see `ssh_askpass` on any linux machine, and maybe brew?; but unfortunately not in stock OS X or I would have recommended it); but at the end of the day, `sudo` expects the password on `stdout` from the script it invokes.

So, I will clarify -- my examples provided here were proof of concept that the process will work as `sudo` expects.  However, the specific example of a script simply doing an echo is a **very bad security practice.  Don't do it.**

I thought about this a while back, but ultimately came to the conclusion that we shouldn't worry about a helper application -- these three options use functionality built into the operating system already and have been around and used on various Unix like systems (with the exception of `osascript`) for a very long time.  I don't see them going away any time soon.  And while they have their risks, any option does.

I do want to eventually figure out if we can pass it via stdin with hs.task (btw, is that working yet? see 
#682)... that way we could retrieve the password via our own mechanism (I've been playing with hs.webview for user input) and pass it along keeping it in memory only as long as required and never writing it to disk, etc.  but I suspect it will require adding psuedo-tty support to hs.task, and I don't have a clue what that entails yet, just that I hate it when it bites me in the @#$# with ssh...

**Comment by herrbischoff** [comment]
Please excuse my late reply, I have been vacationing — badly needed.

@cmsj: Yeah, I believe that password-less sudo just for the relevant Time Machine commands is the way to go here. I'd also speak out against a helper tool, as this would add complexity and security considerations best left to the OS itself. As we all know, complexity is the antagonist to security. And inserting plaintext passwords into commands is a gigantic no-go anyway. Every process/user able to run `top` would be able to see (and possibly log) that.

Knowing about that helper tool, I'm even happier to drop ControlPlane now.

Thanks for all the suggestions!

**Comment by herrbischoff** [comment]
Adding to that, I cannot seem to get the `sudo` approach working. It appears to be what @asmagill mentioned about sudo not being run in a TTY. Here's the output/error:
```
sudo: no tty present and no askpass program specified
```

Any ideas?

**Comment by cmsj** [comment]
@herrbischoff it's saying that because it's trying to ask you for the passphrase, but it's not running in a terminal, and SUDO_ASKPASS isn't set in the environment with some program it can use to ask for a passphrase.

**Comment by herrbischoff** [comment]
@cmsj: So there's currently no way to get this working securely without manually entering the password every time?

**Comment by cmsj** [comment]
@herrbischoff if you've set up an entry in `/etc/sudoers` and you're getting that error, I would suspect that the sudoers entry might not quite be right. I can definitely run passwordless sudo things with `hs.task`:

```
$ sudo -l | grep getblockall
    (root) NOPASSWD: /usr/libexec/ApplicationFirewall/socketfilterfw --getblockall
```

```
> foo = hs.task.new("/usr/bin/sudo", function(stdout, stderr) print("stdout: "..stdout) ; print("stderr: "..stderr) end, {"/usr/libexec/ApplicationFirewall/socketfilterfw", "--getblockall"}):start()

stdout: 0
stderr: Block all DISABLED! 
```

**Comment by cmsj** [comment]
(`sudo -l` is a great way to get sudo to tell you what it thinks you have access to, currently)

**Comment by herrbischoff** [comment]
@cmsj: Thanks, now it works. :) `sudoers` was already correctly set up. From what I gather, I simply forgot to add `:start()`... or some other mistake along those lines. D'oh!
