### ISSUE TITLE
Trackpad gesture support?

### ISSUE THREAD

**Issue by franzwr** [Hammerspoon/hammerspoon#721]
What is the possibility of adding gesture support to Hammerspoon? I couldn't find support for it in the documentation.

BetterTouchTool was mentioned as a solution in #322. However BTT [will soon not be free anymore](http://www.boastr.net/bettertouchtool-may-switch-from-free-to-a-pay-what-you-want-model-early-next-year/), and I'm personally more of a fan of free tools.

If there's anything I can help with in regard to the feature, I'd love to.

**Comment by asmagill** [comment]
hs.eventtap now includes labels for choosing to receive gesture event notifications, but to my knowledge no one has yet played with it enough yet to determine if this is sufficient or if more support is required.  I kind of suspect more will be needed because what I've read suggests that gestures are a series or collection of events, rather than a single event by itself.

This is something I've wanted to work on at some point, but have not had the time yet.  I'm more than happy for someone with experience working with gestures to jump in, but I hope to look into it myself sometime in the coming months if no one else does.

**Comment by cmsj** [comment]
So, I'd just like to clear one thing up here - Hammerspoon should not be about explicitly offering a free alternative to other tools that are not free. BTT will always be a much better tool for gesture recognition than we could become, because that is its sole focus and its author has years of experience working on that stuff. If people need the best gesture tool, they should probably stump up the $3 for BTT.

One of my biggest worries with Hammerspoon has always been that we end up hurting several/some/many independent software developers.

I'm going to re-open #322 and mark it as an extension suggestion bug.

**Comment by iliyang** [comment]
I see your point @cmsj but on the other hand the main reason I use Hammerspoon is precisely because it replaces so many other specialized tools. It's not about the money, it's about consolidation and greater flexibility. If I can currently use 10 different tools that cost $50 total, I'd be happy to spend even more than that on a single tool that gives me all their functionality. Makes my life (and configuration backup) way easier!

Just my 2c.
