### ISSUE TITLE
Disable spaces animation?

### ISSUE THREAD

**Issue by phoenixanimations** [Hammerspoon/hammerspoon#722]
Hi, sorry if this can be easily answered, I tried going through the docks. But is there anyway to disable animations when you do ctrl left and right? Do I have to merge the spaces doc?

https://github.com/asmagill/hammerspoon_asm.undocumented/

Or is there a simpler way?

**Comment by asmagill** [comment]
Apple does not publish details about how the Spaces API works... at present, there is no known way to modify or adjust the animation that is built in to the space changes if you use the OS methods (Ctrl-#, Ctrl-Arrow, trackpad gesture, etc)

[hammerspoon_asm.undocumented.spaces](https://github.com/asmagill/hs._asm.undocumented.spaces) is a third party (i.e. external) module which adds functions to perform what little is known about the Spaces API picked up from the work of others in trying to reverse-engineer how the Spaces API works, but even it has its limitations -- there is a a function provided by the module which will allow for almost "instant" space changing (i.e. without animation), but even that is an imperfect solution because it is necessary to reset the Dock by issuing a `killall Dock` terminal command in order for the space change to become permanent -- without this reset and the subsequent screen flash that accompanies it, the Dock, which manages spaces for OS X, is not aware of the new space layout and when it does attempt to manage space changes again (i.e. you use one of the built in Ctrl-key combinations or use a trackpad gesture) it suddenly reverts to what it (the Dock) believed was the previous state and not what was actually in place (e.g. if you skip resetting the Dock after using one of the module's functions, and then try to use Ctrl-Left arrow, there is a quick flash to the space you were originally at -- before using the module function -- and then moves "left" from *that* space, not the space you were using after the module function was used.

Resetting the Dock is the only way currently known to me to cause the Dock to forget what it thinks it knows about the layout and re-learn what changes other Applications (e.g. Hammerspoon) might have made to the spaces.

Mention has been made that TotalSpaces2 has a work around for this, but beyond the belief that they are using code injection to accomplish this (Hammerspoon doesn't), we don't know how this is being done (and since it's not open source...)  Code injection has become increasingly more difficult with each release of OS X because of changes in how application and system security is implemented, so it's not a direction likely to be added to Hammerspoon, certainly not in the core application.

**Comment by phoenixanimations** [comment]
Hey thanks for the detailed response. That's a real shame, it's kind of odd how cryptic spaces is. As far as I'm aware TotalSpaces2 requires El Capitan to go into safe mode and disable the new security feature Mac installed. 

Spaces to me seems kind of odd, as the previous version we were able to do a grid, and now we are limited to 16 (an arbitrary number?) desktops.

I'm not sure how much help this would be to you, but the people at slate tried to reverse engineer spaces too: https://github.com/sdegutis/mjolnir/issues/297#issuecomment-170211294

But the good news is I got it to work (using the extension you made)! Two questions:

1. Is killing the Dock all the time bad? 
2. And how do I grab the IDs of the spaces around me? I thought it was spaces.layout() but the only output I get is: table: 0x7ffe3dfd14e0?

**Comment by asmagill** [comment]
I've never had a problem resetting the Dock, but to be honest, I can't say... it's the standard suggestion whenever setting "hidden" options with `defaults write com.apple.Dock bla-bla-bla`, and I've never seen any suggestion to "make sure such-and-such is saved/done/whatever first", so...

But we are sending a SIG_TERM signal to a running application by doing it.

As for `spaces.layout()`, it's returning a table where each key is a monitor's UUID, and each value is an array (in lua, a table) of that monitor's spaces, so you'll need get your screen UUID (see `spaces.mainScreenUUID()` and `spaces.spaceScreenUUID(#)`) and iterate over its entry to find the current space ID's index and then look at the elements to the left and right of it.  To see the results in the console, you can type `hs.inspect(spaces.layout())`

I hadn't seen that specific issue (sdegutis/mjolnir#297) regarding spaces before, though I have perused some of the stuff attempted by people involved with Slate and Mjolnir and the like on occasion.  Glancing at that link, the missing piece seems to be `CGSSpaceSetFrontPSN`, but a quick google search didn't turn anything up.  However, it is a new thing I will keep an eye out for.

**Comment by phoenixanimations** [comment]
Excellent, thanks for your help I'll close this now.
