### ISSUE TITLE
When do we 1.0?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#729]
This is a very vague issue, but it occurs to me that we're generally pretty API stable, and I'm not quite sure why we're not at 1.0 yet.

Part of me thinks that a worthy 1.0 goal would be to rewrite a large number of the extensions so they're all using common patterns, taking full advantage of LuaSkin, etc. However, I'm not sure how much it's worth it, and whether it would be worth all the regressions we'd introduce (vs rewriting them individually as we feel the need to).

We seem to also be pretty stable code-wise, the crash reports that we get are inscrutable and either mean we have one or two very fundamental memory bugs somewhere, or we have users with dodgy RAM/installs.

What do people actually think we should put on a roadmap to get us to 1.0?

**Comment by asmagill** [comment]
Regarding the inscrutable crashes, one thing I added in the recent LuaSkin update that I haven't really mentioned before is a lua_atpanic function which logs the error message at the top of the stack, prefixed with "LUA_AT_PANIC:" via CLS_NSLOG, so hopefully some of the crashes which occur somewhere in the lua internals may become slightly less inscrutable...

As to the issue itself, I would like to see in 1.0:

* Finally removing any reference/need for hammerspoon.h... this will mean all internal modules (those that need external Hammerspoon functionality, at any rate) will be utilizing LuaSkin (and its delegate) to some degree, even if they aren't fully taking advantage of all of the utility or protections LuaSkin offers.
* A once over (or even a twice over) of all of the documentation -- we still have some typos and a few items which aren't fully described clearly.
* Modify hs.webview and hs.console so that they no longer offer `:asHSDrawing()` -- rather use it internally to wrap the drawing methods which are safely compatible -- I've found that even with the checks for drawing type in most of hs.drawing's methods, there are still a few which could still crash if used on a "drawing" which is really a mimicry of another object, and it seems cleaner to fix webview and console, since they are the interlopers. (this is on my list for next week, so this is more of a reminder to myself)

I plan to do a rewrite of hs.pasteboard and hs.sound at some point, and will certainly fully utilize LuaSkin when I do, but from the users perspective, it should only be additions, and I don't know exactly when I'll get to it, so I don't think this should be a show stopper for 1.0.  I have no specific plans for the other modules, so "if and when" seems sufficient, and while I do have a couple of additions in the works, I hope to have them ready for review in a week, give or take.

**Comment by cmsj** [comment]
Oh yeah, losing hammerspoon.h is a great point. Really all it does is logging, so I'll look at ripping it out and moving everything over to LuaSkin's logging.

Documentation is a good idea too, I think there are still some modules that aren't (fully) converted to the current docstrings format.

Something I'd add is that we're long overdue figuring out what to do about the trifecta of window/application/uielement.

**Comment by heptal** [comment]
As far as the API/docs go, I think some more consistency can be achieved at reasonable cost. Here I've just run `ipython` from the repo and done some basic consistency checking.  Perhaps the docs.json metadata generated could be made more descriptive. For example Parameters/Returns/Notes/etc could be parsed into their own fields in the resulting JSON, making it easier to see what methods return instances of themselves(and make sure they support chaining if possible) and cross-link documentation. Signatures like [`hs.window:frame() -> hs.geometry rect`](http://www.hammerspoon.org/docs/hs.window.html#frame) in a module doc being able to hotlink to the actual definition of [`rect`](http://www.hammerspoon.org/docs/hs.geometry.html#rect) or `point` or whatever.

```python
import json, itertools

def markdown_table(l):
	print " | ".join(l[0].keys())
	print " | ".join(['---' for x in l[0].keys()])
	for i in l:
		print " | ".join(i.values())

with open('./build/docs.json') as f:
    docs=json.loads(f.read())

names=[[{'module':module['name'], 'type': item['type'], 'name':item['name']} for item in module['items']] for module in docs]
flat_names=list(itertools.chain(*names))
```

There are only a few places that use under_scores instead of camelCase, the convention in this app:
```python
markdown_table([x for x in flat_names if '_' in x['name']])
```
type | name | module
--- | --- | ---
Constant | docstrings_json_file | hs
Function | _applescript | hs.applescript
Constant | state_paused | hs.itunes
Constant | state_playing | hs.itunes
Constant | state_stopped | hs.itunes
Function | _javascript | hs.javascript
Function | services_enabled | hs.location
Constant | state_paused | hs.spotify
Constant | state_playing | hs.spotify
Constant | state_stopped | hs.spotify


Modules with Methods but no specified Constructor:
```python
modules_with_constructors=set([x['module'] for x in flat_names if 'Constr' in x['type']])
modules_with_methods=set([x['module'] for x in flat_names if 'Method' in x['type']])
for module in (modules_with_methods - modules_with_constructors): print "* " + module
```
* hs.audiodevice.datasource
* hs.task
* hs.httpserver
* hs.logger
* hs.audiodevice
* hs.uielement.watcher

These `new` Functions should be called Constructors perhaps, taking care of a few of the above:
```python
markdown_table([x for x in flat_names if 'new' in x['name'] and 'Constructor' not in x['type']])
```
type | name | module
--- | --- | ---
Function | new | hs.httpserver
Function | new | hs.logger
Function | new | hs.task


More stuff
```python
markdown_table([x for x in flat_names if 'get' in x['name'].lower() and 'get' != x['name'][0:3]])
```
type | name | module
--- | --- | ---
Function | tagsGet | hs.fs
Function | asyncGet | hs.http
Function | cliGetColors | hs.ipc

**Comment by cmsj** [comment]
I'm also thinking about other things to audit - eg I'm fairly sure that hs.screen is inconsistent after a reload - there are things set up in luaopen_ that don't get cleared/reset in _gc

**Comment by cmsj** [comment]
@heptal excellent surveying, and those are all things we should fix :)

**Comment by asmagill** [comment]
@heptal, @cmsj: some of the methods starting with _ are wrapped in their lua portion with a name that doesn't... if we truly wish to get rid of them it's simple enough to store the function in a local variable and then set the _ version to nil in the module table or the object metatable, whichever is more appropriate... the one possible exception to make I know of is for hs.applescript (and maybe hs.javascript?).  In this particular case, I remember that the underscored version does no cleanup of the results of the applescript call, while the "friendlier" version attempts to do so for at least a few return data types... the "raw" version was left in so people could parse it themselves, and as an encouragement for someone who knows more about the scripting support in Objective-C to provide a better parser, but I haven't seen much interest...

@lowne - I don't want to replicate the full range of possible inputs that `hs.geometry` supports, but do you still want LuaSkin's tableToNSPoint, tableToNSSize, and tableToNSRect to accept 2 and 4 element array's as well as the keyed tables currently expected? (Note that the push versions would still create keyed tables).

And since this is the time with a roadmap for 1.0 being defined, I'll open the question about hs.drawing.color again... should an array of 3 or 4 numbers be converted to an RGB(A) color (3 would assume an alpha of 1.0)?  I know @lowne's opinion, and I'll admit I'm not as convinced of its utility, but what do the rest of you think?  This would be in addition to the keyed tables already accepted.

**Comment by cmsj** [comment]
@asmagill also a good point about the methods that are wrapped in Lua, but there are still plenty of doc things to fix up.

As for the non-keyed tables, I've never been a particularly big fan of them, but they are a lot more convenient than the keyed tables.

**Comment by cmsj** [comment]
Ok, so hammerspoon.h is dead and gone now :)

I've tested a fair amount of the patch, but many of the calls were in error conditions that are extremely hard to simulate, so it's somewhat unknown if even the old code was tested.

If people could bash on current master a little, and report and regressions, I would very much appreciate it :)

**Comment by cmsj** [comment]
In removing hammerspoon.h, I've become even more convinced that all of the logging stuff should not be happening in Lua. At some point before 1.0 I'll be replacing at least showError() with a C implementation. I'm just not comfortable with the idea that in an error situation, possibly inside an inconsistent Lua state, we're going to start calling a Lua function that does three or four simple things that end up mapping back to C anyway. I also consider it a possibility that I'll rewrite hs.logger in C and unify it with LuaSkin's logging framework.

**Comment by asmagill** [comment]
5 of the 8 crashlytics reports I've reviewed this morning had either just loaded hs.notify or had "	-[ourNotificationManager getOrCreateUserdata:] line 87 $ hs.notify: creating new userdata for orphaned notification" within the last few log messages...

Guess I get to look at that bugger again as well.

FWIW,  most of the issues I've seen are with code that always assume that a call to one of the LuaSkin convertor/import functions will return a valid value (i.e. that invalid data would be caught and never be returned with luaL_error or the like) and couldn't return nil... now that we return nil, rather than create a weird state with a long jump, my suspicion is that most of the time the lua state is probably fine, but the code using LuaSkin isn't handling a nil/NULL response well.  However, wrapping or having at least some of the log levels solely use C  could help in determining if this is in fact the case...  I just want some log levels, at least, that can dump to the console but be turned off easily during/after debugging... it's not always convenient to switch between the HS console and the OS X Console and match up timestamps, etc.

**Comment by cmsj** [comment]
FWIW, there's no reason at all why the C logger couldn't be outputting to the console - in fact that's exactly what I would do :)

**Comment by cmsj** [comment]
(but that's a super interesting insight about the crash reports, I'd missed that. I'll have a quick read of hs.notify and see if anything jumps out at me, but I guess the fact that we have that log message at all, suggests that something is still not right in that module. It's very weird that that one in particular has proven so hard to deal with the lifecycle issues)

**Comment by lowne** [comment]
(after quickly skimming the thread, so apologies if I'm just repeating stuff)
My 2c on what'd be good to have before 1.0:
- everything @heptal said (about documentation, I brought up #505 a while ago)
- improve API consistency; as an example, I'd like that everything that returns e.g. a window frame/point on screen etc. would return it already wrapped in a `geometry()` object, and vice versa anything that accepts a frame/point would wrap the parameter, so you can just pass a geometry constructor argument (if I'm not mistaken, I think I even overoptimistically promised as much in the docs)
- simple array for RGB(A) colours 😀
- sort out console/logger/history:
  - persistent history
  - on-the-fly filtering via native searchbox at the top of the window
  - FWIW I agree with @cmsj (but I'm sure I've missed most of the relevant discussion) that *errors* down in C shouldn't call into Lua (for safety)
  - if better integration with the console window happens, it seems easier to just do everything in C
  - logging is a low-level facility anyway, so I'm philosophically in favour of moving everything to C anyway (easy to say when I wouldn't be the one actually doing it); it'd also help with performance I guess (e.g. windowfilter logs *a lot* of verbose stuff under the hood, and I have dozens of those (now that it's mostly stable, I could probably ease up on the logging, but that's a different matter))
- (haven't seen this mentioned) I think it'd be (if only psychologically) important to have some sort of deprecation facility in place (see #608), in order to minimise the feeling of "can't touch it" after the big 1.0 if/when the chance for a more streamlined API emerges while revisiting/expanding a module

**Comment by cmsj** [comment]
@lowne so the deprecation stuff is interesting. If we follow the strict letter of Semantic Versioning, we're pre-1.0, so we can break any API we like without having to do anything exciting to the version number.

I think we should audit the API and fix stuff up, but I don't want to drag out lots of API breakage over many 0.9.x releases, so I think it should happen in one go. I think it might be a good idea to add SUAllowsAutomaticUpdates=NO to our Info.plist so people have to read the release notes, where we can call out any significant API changes.

**Comment by asmagill** [comment]
Maybe not a 1.0 holdup, since nothing requires it yet (note to self: check that... a couple of places may have a loop in the module because of this...), but depending upon how long it takes us to get to 1.0, I'd like to see the following added at some point, whether it's 1.0 or later:

* Add NSValue support to the LuaSkin `pushNSObject:` types so NSRect, NSPoint, NSSize, etc. in dictionaries and arrays can be pushed without iterating through the dictionary/array outside of LuaSkin.

**Comment by cmsj** [comment]
I think addressing #753 is critical before 1.0

**Comment by cmsj** [comment]
I just came across https://github.com/lua-stdlib/lua-stdlib for the first time and looking through their API docs, I can't help but wonder if we should migrate a lot of the core Lua functions we've added, to lua-stdlib versions. They seem to have covered most of the same ground as us, and gone a lot further

**Comment by cmsj** [comment]
I'm going to close this out because I think we're a fair way from being able to reasonably declare a 1.0.

We have a milestone tag for 1.0, so I suggest that people start making sure that things they care about are filed as issues, and milestoned against 1.0.
