### ISSUE TITLE
Proposal: standardise C struct for userdata

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#735]
Right now we have a mishmash of different C objects being used as userdata objects. Sometimes naked ObjC objects, sometimes pointer-to-ObjC objects, sometimes custom structs.

I think we should move to a struct type defined in LuaSkin, with standardised functions to create instances of the struct, etc. The two struct members that I'd put in initially would be `char *userdataTag` and `id someCleverName`. LuaSkin would provide a method to fetch the userdata from the Lua stack and return `someCleverName`.

I think the naked ObjC class pattern is dangerous, the double pointer pattern is confusing and the custom struct pattern is overly repetitive.

**Comment by asmagill** [comment]
Huh... I actually think the naked objc class pattern makes the most sense in an ARC environment... plus its easier to add fields by creating a sub class -- imho, structs with -> are ugly compared to dot notation and synthesized getters/setters.  And it makes it possible to use the LuaSkin registered helpers in the constructors...

However, I've pretty much come to terms with working with all three of the major forms I've encountered, so whatever the standard is, I can adapt -- I think they all have their strengths and weaknesses.

**Comment by cmsj** [comment]
@Asmagill do you mean the double pointer classes? They are safe and the most RAM efficient, I just find them confusing. If we can abstract that all away with LuaSkin, which I suspect we can, I'm fine with going for that option.

If you mean single pointer classes, I'm sure that's not safe, but I'd love to hear why I'm wrong!

**Comment by asmagill** [comment]
I should clarify objc objects as those which are sub-classes of NSObject, so in every case I can think of off the top of my head, those that are stored as bridges to void**.

I'm not sure we can safely come up with a "one size fits all" solution, however I'd be more than happy to be wrong and/or help in trying... Core Foundation objects (those that are represented as CFTypeRef), and the few cases where a structure truly makes more sense than an object (though that's often more of a style decision than a coding one) don't simplify that easily in my opinion, but as I said... I'd love to be proven wrong!

Yeah, the double pointers are confusing at times... I need to find a good in-depth explanation of exactly what the compiler does with them... The solution I came up with for the hs.image problem recently makes sense when I think of the nested parenthesis as "casting" the value for the expectations of the next outer layer, but it's not quite intuitive to me yet.  It probably would have gone unnoticed for some time if hs.pasteboard's setImageContents had been using LuaSkin's checkArgs at the time, since I could only replicate the crash by passing in an argument that wasn't an hs.image userdata.

**Comment by cmsj** [comment]
I'm working on a proof-of-concept for the struct paradigm. I've added a few methods to LuaSkin and converted hs,chooser (since a) that is my most modern module, b) it deliberately keeps nothing other than the ObjC pointer in its userdata struct) over. I'll pick a CoreFoundation based module next and modernise it, then throw up a PR for your reaction :)

**Comment by cmsj** [comment]
(see #747 )

**Comment by cmsj** [comment]
I'm going to close this on the basis that there's no reasonable chance of making the change and converting all the modules, any time soon. It's still something I'd like to do, but I'd also like to walk on the moon, so there we go ;)
