### ISSUE TITLE
Investigate eventtap type

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#751]
At the moment we install taps at kCGSessionEventTap which is the same level we post events at. Maybe we should install taps at the HID layer so we can distinguish between events we synthesised, and user events.

Perhaps we should make the level for both, configurable.

**Comment by asmagill** [comment]
`kCGHIDEventTap - Specifies that an event tap is placed at the point where HID system events enter the window server.`

and

`Only processes running as the root user may locate an event tap at the point where HID events enter the window server; for other users, this function returns NULL.`

Because of the root requirement, I've never really messed with this tap location, though I have been curious what it might gain us.

**Comment by cmsj** [comment]
ah yes, I'd forgotten that detail. I did have hs.eventtap.event emitting on the HID tap for a while, and it seemed to work really well for me, but it didn't work at all for @lowne - I suspect that may have been because Xcode was involved, and/or I'm an admin user, or something.

I've not played with kCGAnnotatedSessionEventTap though. I also wonder if we could use 
CGEventCreateSourceFromEvent to determine that the source of an event was the private source we create, and thus ignore the event.

**Comment by cmsj** [comment]
I don't think we actually need to do anything here.
