### ISSUE TITLE
More hs.image systemImageNames values

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#752]
There seem to be quite a few undocumented image template names:

http://hetima.github.io/fucking_nsimage_syntax/

We should include them :)

**Comment by asmagill** [comment]
I looked for such a list when first writing the module but didn't find a good one... I'll take a look later and see about including them... my main concern would be if any are OS version specific and whether that might cause a problem... I think since they're compiled in as strings, the concern is more with the compiling machine version than the running machine version (if you request an image name that doesn't exist, it either returns nil or an empty image -- forget which, but I know it doesn't crash).
