### ISSUE TITLE
Document test harness

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#753]
As I just mentioned on #747 I think we have an urgent problem re testing. 0.9.44 got out the door with some terrible regressions, all of which I think were my fault, but regardless, we're changing lots of stuff, and we have a big set of interdependent APIs now, and almost no automated testing.

Since we've proven that my manual testing is insufficient, and few enough people are running at the tip of master to surface the regressions early, I think it's now imperative that we build up our test infrastructure and actually have some tests. Given the nature of Hammerspoon's interaction with the OS, I think it's unlikely that we'll be able to get super complete coverage, but we need more than the "do all the modules load?" and "does some very very simple window moving work?" we have at the moment.

I know almost nothing about testing frameworks in Lua, but [luaunit](https://github.com/bluebird75/luaunit) looks fine - anyone care to chime in on that front? (I know Habbie likes [busted](http://olivinelabs.com/busted/)).

Some thoughts:
- We could skim docs.json to determine if all of the constants/variables/functions actually exist (but we probably can't do methods automatically)
- I think we should include a unit testing harness as a module
- I don't know where the tests for each module should live - in the module itself with some predictable name, or all collected together in the test harness module?

**Comment by asmagill** [comment]
I have no experience with implementing a testing framework, but will be happy to help in any way I can...

My thoughts:

In my experience, the largest number of crashes I experience are either with object creation or object destruction, so testing should include creation and destruction, both intended (for objects with a `delete` or similar method) and automatic (garbage collection at reload or when setting an object variable to nil), of all objects.

Other crashes I routinely see are out-of-bounds conditions, but these mostly throw an exception that is obvious once you look at the logs.

More nuanced interactions are probably beyond something automatic, though specifically tailored per-module tests might be useful on a case-by-case basis... this will probably be one of the weaker areas, since we'll need to know what the special combinations or conditions are before we know such a test needs to be added.

Watchers... can they be artificially triggered in the same manner that the OS will generate the notification?  If not, the test will be partial at best.

**Comment by asmagill** [comment]
Do we want to consider a "beta" or "pre-release" branch and an additional flag in the preferences for people who want to have automatic updates which include these releases?  I know that we're considering all of this "beta" in the sense that the version number is still < 1.0, but there is still a difference between a release we are comfortable with and one that probably should be considered more of a "pre-release"... I know you like regular releases, so this would allow a track for people willing to be on the cutting edge without having to compile it themselves, and a slower, more tested release for those who just want something that works.

**Comment by cmsj** [comment]
@asmagill I've actually been very seriously thinking about doing the pre-release branch and not updating the main appcast.xml until we get to 1.0.

For me, this next little period is probably going to be the biggest test of Hammerspoon as a project - we've had a lot of fun doing 48 releases since October 2014 and the userbase was always small enough that we could get away with being a bit loose with our QA, but we now seem to be comfortably into the thousands of users (it'll take a while for confirmation, updates tend to take a couple of weeks to roll out through the userbase, but 0.9.43 had over 3000 downloads) and I think that raises the bar for us as maintainers.

I do like regular releases, but it is possible that the time has come to end that pattern for the bulk of the userbase. Pre-release releases could be very regular (even nightly, if there are new commits). That would also allow us to proceed with the refactoring things that I think need to happen, without disturbing most users. If we go down this route, I would suggest we do one or two more normal releases (if nothing else, we need to add in the option and mechanism for following the pre-release branch) and then have a big release notes entry telling people that we're going to go quiet on them until 1.0, unless they switch branch.

It's interesting that you're experiencing crashes - I very rarely get them, but my config is probably simpler than yours, and also doesn't change very much. I have the impression from the crash logs that a lot of the weird ones correlate with reasonably long running instances of Hammerspoon, where a crash doesn't happen until a reload tries to GC things and stumbles over broken pointers. I would never see those crashes because I'm rebuilding HS many times a week.

(One final thing, watchers should be testable, ultimately they're just the OS calling a function/method with some data - we ought to be able to mock that data up for most things, and call the relevant function)

**Comment by cmsj** [comment]
(I suppose I should also note that out of those 3000 downloads, we only received reports of 179 crashes across 36 users, but that's still higher than it should be)

**Comment by asmagill** [comment]
I'l clarify my crashes -- they mostly occur when I'm working on something new (usually, but not always, an in progress module, but sometimes just a combination that hadn't occurred to me before)...  When I leave things alone for a while, it's generally pretty stable.

Even then, I don't see many any more, so if I gave the impression otherwise, I apologize.  But the ones I do see, tend to follow the patterns I outlined above.

Thousands, huh?  I'm both happy and frightened by the prospect!  😀

**Comment by lowne** [comment]
+1 to committing to dev branch and later merging old, "stable" tags to master, regardless of beta releases; and +1 to beta releases to try and increase the testing footprint (he says, while running on a month-old master 😀).

**Comment by cmsj** [comment]
As of yesterday we now have a test harness that can run Lua tests from objc so everything appears nicely in Xcode's testing UI. Now we need to write tests.

I hope everyone will start writing even simple tests to increase our code coverage. I'm certainly going to, before I do very much more feature work :)

**Comment by cmsj** [comment]
I'll write up some docs for CONTRIBUTING.md today

**Comment by cmsj** [comment]
This was done.
