### ISSUE TITLE
autocomplete doesn't like _

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#765]
the new tab-auto complete doesn't like the "_" character in component names.

e.g.

``` lua
a = { b= { c = { d = 4}}}
runstring

a.
mod: a
remnant: 
parents: { "a" }
a.b
mod: a
remnant: b
parents: { "a" }
a.b.
mod: a.b
remnant: 
parents: { "a", "b" }
a.b.c
mod: a.b
remnant: c
parents: { "a", "b" }
a.b.c.
mod: a.b.c
remnant: 
parents: { "a", "b", "c" }
a.b.c.d
mod: a.b.c
remnant: d
parents: { "a", "b", "c" }
a.b.c.d
mod: a.b.c
remnant: d
parents: { "a", "b", "c" }
a.b.c.d
mod: a.b.c
remnant: d
parents: { "a", "b", "c" }
a.b.c.d
mod: a.b.c
remnant: d
parents: { "a", "b", "c" }
```

versus

``` lua
_a = { _b= { _c = { _d = 4}}}
runstring

_a
mod: 
remnant: _a
parents: {}
_a.
mod: _a
remnant: 
parents: { "_a" }
_b
mod: 
remnant: _b
parents: {}
_b.
mod: _b
remnant: 
parents: { "_b" }
_b.
mod: _b
remnant: 
parents: { "_b" }
_b.
mod: _b
remnant: 
parents: { "_b" }
_b.
mod: _b
remnant: 
parents: { "_b" }
```

Whatever is passing the value into hs.completionsForInputString appears to be truncating the input at the _ character.

**Comment by heptal** [comment]
I have some autocomplete enhancements that I had locally and was investigating this part as well. Unfortunately this morning the SSD straight up died in my 15" retina (on a replacement while they ship it off) and I lost some stuff, but it's easy to recreate. Currently waiting for a dozen or so gigs of developer tools to download, heh.

**Comment by heptal** [comment]
Unfortunately the OS X completion API doesn't, as far as I know, allow you to customize whatever it uses to determine what a 'completable word' is. Underscores seem to force a new word, where thing like opening parens don't. It seems their completion API is really intended for natural language rather than code. If this creates enough issues for us we may need to create our own handler instead of using `textView:completions:forPartialWordRange:indexOfSelectedItem:`, and have tab call our custom function. Or we could ignore what `forPartialWordRange` tells us within that function and do our own parsing to determine what is sent to the Lua completion function.

And although their completion dropdown looks nice, personally I prefer a bash-style where it will list all the completion choices in the console.

**Comment by cmsj** [comment]
I do think a fully custom solution would serve us better. The question for me is whether we have the bandwidth to create and maintain it at a high enough standard (which raises the question of whether the sort-of system we have now, is actually better than nothing).

(It also has me asking follow up questions about whether most of the core app/UI is up to scratch, but that's probably too big to tackle any time soon)

**Comment by cmsj** [comment]
I'm going to close this because I'm gardening the bugs and this has been open for ages with no further discussion, feel free to re-open it if there are specific things you want to do :)
