### ISSUE TITLE
Crash in LuaSkin pushNSDictionary

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#784]
See http://crashes.to/s/2f4bae0d899 (seems like somehow there's a nil key maybe? nil is certainly involved somehow. Perhaps `obj` itself is nil?)

**Comment by asmagill** [comment]
What's odd is that line 811 is `NSArray *keys = [obj allKeys];` in the `pushNSDictionary` helper method which is only called from `pushNSObject` after checking (1) to see if `obj` is not nil, and (2) that it is in fact an `NSDictionary` or subclass... and an `NSDictionary` by definition cannot have a `nil` key... it *can* have an `[NSNull null]`, but then so can the array which is returned by the `allKeys` method.

Unfortunately, I think I need to see what the item being retrieved from the user defaults (i.e. `hs.settings`) is to debug this further because unless I'm misunderstanding something, this shouldn't be possible unless that contains corrupted data.

I suppose we could wrap the detection code in `pushNSObject` with @try/@catch/@finally so we can log the data causing such exceptions, but (1) this raises some privacy concerns, and (2) this method is recursive -- I'm not sure if that complicates the recovery path of an exception or not... have to read up on exceptions some more.

**Comment by cmsj** [comment]
This doesn't seem to be occurring with any significant frequency, so I'm closing.
