### ISSUE TITLE
Save screenshot to Desktop

### ISSUE THREAD

**Issue by petobens** [Hammerspoon/hammerspoon#840]
I'm trying to capture a screenshot of my focused window and save it to the desktop. I went over some of the example `init.lua` files and according to [this line](https://github.com/heptal/dotfiles/blob/master/roles/hammerspoon/files/imgur.lua#L7) I believe I am calling `saveToFile` correctly. However the following code:

```lua
hs.window.focusedWindow():snapshot():saveToFile(os.getenv("HOME") .. "/Desktop/blah.png")
```
returns:

>[string "return hs.window.focusedWindow():snapshot():s..."]:1: ERROR: incorrect type 'userdata' for argument 1
stack traceback:
	[C]: in method 'saveToFile'
	[string "return hs.window.focusedWindow():snapshot():s..."]:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:251: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:245>

What am I doing wrong?

**Comment by heptal** [comment]
Works for me. You can also say `:saveToFile("~/Desktop/blah.png")`. Are you using latest release or master?

**Comment by asmagill** [comment]
The last release should work, and the latest master should work, but there was a push in between that had an issue that prevented proper userdata identification for a handful of methods... I believe image was one of them.

Can you try a new build with the latest code, or revert back to the last release and let us know if that makes a difference?

**Comment by petobens** [comment]
I installed it with `brew cask install hammerspoon`. I will try the latest release if I cannot build master. Are  there build instructions somewhere?

**Comment by heptal** [comment]
I would not recommend cask for Hammerspoon (or for many packages as cask does not have an update mechanism like brew itself - even though Hammerspoon itself has an update mechanism, the cask definition is not officially maintained). Detailed build instructions are in `CONTRIBUTING.md` but it should be as simple as opening the `.xcworkspace` (not the `.xcodeproj`) and hitting 'play'. Hammerspoon is careful to be an easily buildable project so if you still have issues you should ask an XCode-related channel for help. Otherwise just get the latest release and put it in `Applications`.

**Comment by petobens** [comment]
@heptal thanks. I will try your build instructions or wait for the next release.

**Comment by cmsj** [comment]
@petobens what does this return, in the Hammerspoon console: `hs.inspect(hs.window.focusedWindow():snapshot()` ?

**Comment by petobens** [comment]
@cmsj: 
```
-- Loading extension: inspect
<userdata 1> -- hs.image:  (0x7fe15dc40a68)
```
One extra question: will there be a new release soon? (I don't know the timings of your release cycle)
Thanks!

**Comment by petobens** [comment]
Fixed with latest release.
