### ISSUE TITLE
Build failed with Xcode 7.3

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#843]
I put the error messages in [this gist](https://gist.github.com/da97c94553ed64209a67).

**Comment by asmagill** [comment]
Glancing at the Gist, at least one of the errors will go away with #825, since I'm removing support for currently unused NSValue types; I'm working on a Lua-Side solution for types other than NSRect, NSPoint, NSSize, and NSRange that's promising.

I'm in the process of downloading XCode 7.3 right now (did the 10.11.4 upgrade last night) and will let you know how it fares later tonight when I have it installed.

Once I address any compilation issues with the latest XCode and OS X, I think #825 is ready -- the other NSValue types can wait till I work out the generic NSValue conversion in Lua with string.pack, since nothing currently uses them.

**Comment by cmsj** [comment]
I am also in the middle of downloading Xcode 7.3, but it's telling me it's going to take another 20 hours, so... yeah. Might be looking at this one tomorrow :(

**Comment by asmagill** [comment]
Applying #825 to your source should build under 7.3 now.  Pending a review by @cmsj, I hope its added to core soon, but if you want to compile sooner, give it a go.

**Comment by asmagill** [comment]
Oh, I'm sure you probably know this already, but I got bit by it, so just a reminder...  make sure to clear out the derived data folder first... the errors are just all over the place if you forget that after an XCode update :-)

**Comment by chdiza** [comment]
>  make sure to clear out the derived data folder first

Yeah, that's the first thing I did.  Will try #825 when I get a chance.

**Comment by junkblocker** [comment]
#825 seems to build and work fine.

**Comment by chdiza** [comment]
Yeah, it does seem to work.  Thanks!
