### ISSUE TITLE
How to bind hs.hotkey.modal to any key press?

### ISSUE THREAD

**Issue by talha131** [Hammerspoon/hammerspoon#848]
Is possible to bind any key press to `hs.hotkey.modal`? The use case I have in mind is like this,

1. User presses hyper+R key to enter a mode

```lua
k = hs.hotkey.modal.new(hyper, 'R', 'Red Shift mode')
```

2. In this mode, only key 1 and 2 are valid. 

```lua
k:bind('', '1', function() flux('1') end, function() k:exit() end)
k:bind('', '2', function() flux('2') end, function() k:exit() end)
```

3. Pressing any other key will exit the mode or show an alert that "*an invalid key has been pressed*".

```lua
k:bind('', 'ANY OTHER KEY', function() k:exit() end)
```

How can I do it? 

One way is to pass all pressed keys to a function that will decide what to do. But for this I will have to bind "Any key press". 

As far as I can tell from the documentation, bind method can only be used with a single key.

**Comment by cmsj** [comment]
@talha131 it's not possible with hs.hotkey (or hs.hotkey.modal) to bind to multiple/all keys. The underlying OS X API we use for this cannot do that.

You could implement something similar though, which uses hs.eventtap. You'd bind a hotkey that, instead of entering an hs.hotkey.modal state, starts an eventtap configured to listen for keyboard events. The callback for that could then decide what to do based on the key that was pressed, then disable itself.

**Comment by talha131** [comment]
Thank you.

**Comment by theicfire** [comment]
Example of what cmsj mentioned:

```
function runTap()
    evtap = hs.eventtap.new({hs.eventtap.event.types.keyDown}, function(e)
        if e:getKeyCode() == hs.keycodes.map['c'] then
            hs.application.open('Google Chrome')
        end
        evtap:stop()
        return true -- Stop event from propogating
    end)
    evtap:start()
end
hs.hotkey.bind({'alt'}, 'space', function() runTap() end)
```
