### ISSUE TITLE
hs.redshift and screen wake-ups

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#854]
When the screen goes to sleep (screen saver kicks in) there is a period of time after wake up before any gamma adjustments which are supposed to be in effect are re-applied to the screen(s).

I suspect that use of `hs.caffeinate.watcher` could minimize/remove this, but I haven't looked too closely at the code yet.  I throw this out so the original coder who is more familiar with it can weigh in.

**Comment by cmsj** [comment]
That would be @lowne :D

**Comment by lowne** [comment]
The delay is intentional, by virtue of a generous `timer` after `screen.watcher`; this is something that I've done for all my modules, because I've found that OSX often takes quite a while to properly sort out the screens (after connect/disconnect, which iirc includes sleep). Namely right after `screen.watcher` fires sometimes one or more `screen:allScreens()` will be in a weird state with invalid data (such as the screen frame).
It's worth noting that my setup might very well be the worst case scenario, as I regularly connect/disconnect 12 megapixels across 3 monitors on a 1st gen rMBP which may or may not have a buggy GPU (sometimes the main screen sort of flickers for a while, or sleeps/wakes a couple times, after connecting it).

I used to have a `screenwatcher` module to deal with all this; I think the best solution here (which would also benefit windowfilters etc) is to wrap `screen.watcher` itself Lua-side, by 
1. adding a `delay` field to the module defaulting to say 0.5s, which may work fine for the majority of users, while others with multi-screen setups can increase it
2. `timer.delayed` the wrapper callback, which will 
3. check `:allScreens()` and re`:start(1)` the `delayed` if it finds bogus userdata

**Comment by cmsj** [comment]
I suspect this is going to be moot in a few months - rumours suggest that 10.12 will include "Night Shift", like iOS 9.3 did.

**Comment by lowne** [comment]
@cmsj as long as 'dark mode' remains the joke that it is (which it will forever, because even if Apple suddenly decided they wanted to enforce proper dark themes they couldn't, since nobody cares about being in the MAS anymore) I'll keep using redshift, simply because it works properly with inverted colours - and even discounting all of the above, the iOS implementation of Night Shift simply switches off when inverting colours, which is *extremely* jarring and extremely wrong imo.

However my suggestion above about screenwatcher would benefit *all* modules using it (basically modules doing anything ui related), so it'd go well beyond redshift. I wanted to know if there are any objections before working on it.

**Comment by cmsj** [comment]
@lowne yeah I think the screenwatcher idea is fine :)

**Comment by spro** [comment]
I'm not entirely sure that this is the same issue, but since using Redshift I have had a few times where the screen doesn't revert to normal after waking up...

* Plug in the computer (closed) to power and two screens
* Open the computer
* One of the screens is maybe de-redshifted, at least one is still redshifted

I can't fix it with `hs.redshift.toggle` but if I go into System Preferences > Displays > Color it goes back to normal.

**Comment by cmsj** [comment]
I'm going to close this out because it doesn't seem to have any traction. Please feel free to re-open if you want to work on it.
