### ISSUE TITLE
hs.window.switcher issues

### ISSUE THREAD

**Issue by heptal** [Hammerspoon/hammerspoon#868]
Paging @lowne for this :)

1) Window switcher is hardcoded to use `hs.screen.primaryScreen()`. It should probably use `mainScreen()` and not cache the screenFrame. I've noticed that mainScreen does not always report the currently active screen, but that's a separate issue.

2) The default preview UI is too large. I'm only calling `hs.window.switcher.new(myWindowfilter)` without any UI-changing args. On my primary screen (Retina Pro), the mini window previews at the bottom are pushed out of view:
![](http://i.imgur.com/fzGET6om.png)

3) On my 'main' screen (which has lower resolution - modified source to use mainScreen instead of primaryScreen), it is still too large but they are only partially cut off. What I want to show here is that the window labels are not consistently aligned or truncated. 'thing' doesn't need to be rendered as 'thi...':
![](http://i.imgur.com/r5fxRk7l.png)

4) The differences between `hs.screen.switcher:next()/nextWindow()` and `previous/previousWindow()` are not clear. The docstrings are identical for each pair, but the behavior is different. `next/previousWindow` will ignore the windowfilter you set up the switcher with so that it switches on all windows, but it is not clear why (from an API perspective - it's clear from the code why - it creates a new default switcher with no args so that a default windowfilter is used). It seems that `next/previousWindow` should simply be removed?

**Comment by lowne** [comment]
1. it's hardcoded because 1) cmd-tab always shows on the primary screen, and I think most people would expect windowswitcher ("cmd-tab replacement") to be consistent with that and 2) all the frames are cached across invocations and rebuilt only when necessary to minimise the delay before the UI shows up; the 2nd point would be moot if HS used LuaJIT, but alas that's not the case. It would of course be possible to cache the frames per-screen, but that's a non-trivial change to the code.
2. fixed as per #856 
3. see point 1 (caching - so just changing to `mainScreen` doesn't work)
4. `nextWindow` and `previousWindow` are "static" methods on the module that can be called/referenced directly for those who don't need to customise the windowfilter (which, I presume, would be the majority of users), so wrapper lambdas aren't needed. Contrast:
```lua
hotkey.bind(...,window.switcher.nextWindow)
```
vs
```lua
myws=window.switcher.new(...)
hotkey.bind(...,function()myws:next()end)
```

**Comment by heptal** [comment]
1) Makes sense
2) Cool, it's much better now
3) n/a
4) I see. Perhaps the docstrings should make this distinction more clear? 

The titles are still overly truncated:
![](http://i.imgur.com/9Sgq55R.png)

Perhaps the titlePadding calculation is not necessary? Here i've just set `titlePadding=0` instead of the calculation and it looks much better to me:
![](http://i.imgur.com/pLu5BCZ.png)

Not sure why the selected title text's kerning is all jacked, tho.

**Comment by cmsj** [comment]
I'm going to close this issue because it doesn't seem to be getting any traction. Anyone please feel free to re-open it if you want to work on this.
