### ISSUE TITLE
Add LS_NSConversionOptions option for preserving nils?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#880]
@asmagill what do you think about adding a conversion option that preserves a Lua nil into a simple ObjC nil, instead of NSNull?

**Comment by asmagill** [comment]
If you've a use case for it, go ahead... It's been awhile, but I think my reasoning for [NSNull null] being the default has to do with the fact that container classes (NSDictionary, NSArray, etc.) can't use nil as a key or value, but they can use [NSNull null]; however, when you know you're not working with such a container, nil can be easier to work with.

**Comment by cmsj** [comment]
Take a look at hs.distributednotifications - there are a couple of points where I'm processing optional Lua args that could be a single toNSObject instead of a few lines of conditionals around lua_isnoneornil()

**Comment by asmagill** [comment]
It wouldn't be too hard to add level detection in toNSObjectAtIndex: so that if it hasn't recursed yet (i.e. descended into a table), it returns a regular `nil` and if it has, then it returns `[NSNull null]`... I don't think that would break anything we currently have in place.  Maybe add options for *not* doing the detection... it would keep the code in the module simpler (you wouldn't have to remember to add an option when you're just getting your arguments, only when you know you want to do something "abnormal").

Which would you prefer?

**Comment by cmsj** [comment]
Ooh, I like the idea of having it be magically done when we're not inside a collection type. I'm ever-so-slightly nervous about changing the behaviour, however, I think it's very unlikely that there are any cases where a non-collection conversion to NSNull is useful, so I think having it convert to nil by default, if it hasn't recursed yet, is fine. I'm not even sure it's necessary to have an option to override that, but I would not be opposed to adding it such an option.

**Comment by cmsj** [comment]
@asmagill this can be closed now, right?

**Comment by asmagill** [comment]
I'd forgotten about it and nothing has blown up, so I'm closing it.
