### ISSUE TITLE
Include @asmagill's Spaces module

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#883]
Yes, it's undocumented-API-tastic, however, it's something we get asked about a lot, and if people are going to just use that module anyway, maybe it would be better to have it in the app.

I note that other apps are starting to use those APIs (e.g. Phoenix's latest release) and we will get a nice long window to test its compatibility with `macOS 12` after WWDC, so I am inclined to include it, with a limitation that it only be loaded on 10.11 for now.

@asmagill thoughts?

**Comment by asmagill** [comment]
No objections...

If you've looked closely at the way I've written it, I've isolated the raw functions so that some of them aren't easy to get to unless you first set a flag with hs.settings or load the internals file directly because its amazingly easy to get into weird or screwed up displays if you're not careful.  I'd recommend sticking with that, and probably not even document their existence in the Dash docset... since we're almost at the point where we can provide our own documentation at run time, I'd probably keep the advance stuff something you have to explicitly request through the internal documentation.

It may also be possible to pair it down somewhat so that the basic functionality that's immediately available is all that we incorporate and keep the full module with the experimental features a third party addition... I'll give it a look and see if limiting the set of internals in such a way isn't too limiting (I can think of at least a couple of internal functions which can be made read only without limiting the basic features... there may be other protections/limitations that can be added as well)
 
As to the version limiting, I can see preventing its automatic inclusion for post 10.11 OSX until we can see what's changed/broken with 10.12, but I do know that what's already in place has worked since 10.9 (not sure about 10.8)

Re Pheonix, etc., do you know if they've found a way around the need to reset the Dock application?  That's the one thing I've never really liked about this module.

**Comment by cmsj** [comment]
Hmm, not sure. Their code is https://github.com/kasper/phoenix/blob/master/Phoenix/PHSpace.m (also the screen and window .m's)

**Comment by cmsj** [comment]
I just remembered this is targetted for 0.9.47, but I think I'll bump it to .48 so we can do final Sierra testing.

**Comment by cmsj** [comment]
I'm not sure we're ever going to get to this, but it doesn't really need its own issue anyway.
