### ISSUE TITLE
Is it possible to control menu items in dock context menus?

### ISSUE THREAD

**Issue by fkling** [Hammerspoon/hammerspoon#887]
I fear the answer is "no", but since I don't have any experience with OS X APIs I thought I'd ask.

Context: Pandora is implemented as an Adobe Air (or whatever it's called) application, and its top bar menu doesn't provide any way to control the app. The dock menu does though:

<img width="282" alt="screen shot 2016-04-28 at 1 36 13 pm" src="https://cloud.githubusercontent.com/assets/179026/14895361/37d06f98-0d46-11e6-83ce-76d2926dc00a.png">

I tried `p:findMenuItem('Play')` from the console, but that returns `nil`.

P.S.: I searched the issues before but couldn't find any related questions to this.

**Comment by asmagill** [comment]
ATM, I don't think so (but chime in, anyone, if I'm wrong) but I have been giving thought to adding support in `hs.menubar` so that Hammerspoon could add a menu to its Dock icon; initial research into this indicates that Dock menus are built from the same type of `NSMenu` object as the menus found in the menu bar, so I suspect its just a matter of finding the right AXUIElement parent to search from.

Hopefully this may spur an idea for someone more familiar with the menu search code; otherwise, I'll make sure to look into it myself when adding Dock menu creation support, hopefully in May.

**Comment by asmagill** [comment]
I'm less certain getting the menu list for Dock items will be quite that easy after looking at http://stackoverflow.com/questions/35821506/how-to-get-an-array-of-axmenuitems-from-axmenu/36115210#36115210...  According to this and the Accessibility Inspector, it looks like the accessibility object for a Dock items menu doesn't actually exist until its visible...

However, I do have a module I've been working off and on with that deals with AXUIElements directly... it needs a lot of cleanup and documentation and I haven't figured out how it fits in with the core modules yet, but it looks like it might be a step in the right direction if you (or anyone following this) wants to take a look... the module code can be found at https://github.com/asmagill/hammerspoon_asm/tree/master/axuielement... with it, I was able to pop up the menu for the Dock item for the System Preferences with (haven't tried selecting an actual menu item yet, as I'd need to write a function, rather than just use the console, since the menu takes focus away from the console):

~~~lua
axuielement = require"hs._asm.axuielement"
SPDockItem = axuielement.applicationElement(hs.application("Dock")):elementSearch{title="System Preferences"}[1]
SPDockItem:doShowMenu()
~~~

![screen shot 2016-04-28 at 11 47 39 pm](https://cloud.githubusercontent.com/assets/8139480/14908355/b163357a-0d9b-11e6-8622-4422fdc9e787.png)

Looking at the code in the first link I gave above, I suspect that if this is followed with code to iterate through the children of SPDockItem (`SPDockItem:children()`), it should be possible to find a specific menu item and then act on it.

I'll clean up the AXUIElement module and document it next week... it may be time to figure out where it fits in with Hammerspoon after all...

**Comment by asmagill** [comment]
Update: yeah, I think some variant of this needs to be added to Hammerspoon

~~~lua
axuielement = require"hs._asm.axuielement"
SPDockItem = axuielement.applicationElement(hs.application("Dock")):elementSearch{title="System Preferences"}[1]
SPDockItem:doShowMenu()
SPDockItem[1]:elementSearch{title="General"}[1]:doPress()
~~~

Note that elementSearch returns a list, which is why we add [1] after the `elementSearch` method call; the above causes the General System Preferences panel to be opened under Hammerspoon control.

I think something like this will do what you want if you change the two `elementSearch` parameters.

**Comment by asmagill** [comment]
FYI, I've finally provided some documentation and a precompiled binary for the axuielement module. If you're interested, check out the Reference.md file in the repository folder.

**Comment by cmsj** [comment]
@asmagill is axuielement in shape for inclusion? :D

**Comment by asmagill** [comment]
Not yet... I realized recently that it leaks memory (not a lot, but it will add up)... I added code to allow direct comparison of the userdata objects and their use as keys in a table to help detect loops during traversal on the Lua side and didn't realize until recently that this code prevents the objects from ever being collected.

And it still needs better documentation, so while I hope to add it into core at some point, it won't happen until the next release, I'm afraid.

**Comment by cmsj** [comment]
I'm going to close this out since it will either be solved or not by the fate of axuielement :)
