### ISSUE TITLE
hs.redshift.toggleInvert() gamma issue when adjusting screen brightness

### ISSUE THREAD

**Issue by wvierber** [Hammerspoon/hammerspoon#917]
**How to reproduce**:
- Invert  screen colours with `hs.redshift.toggleInvert()`
- Adjust (manually) the screen brightness (sometimes more than one step is required)

**Issues that occur by changing the screen brightness**:
- The colours are re-inverted
- There seems to be iterated over false gamma settings until after a short while a normal non-inverted screen is restored. (if you wait some time (in the order of minutes), this might happen again)
- (When you are writing an issue about this, the screen might invert again to the proper inverted colours 😃 )

Toggling  `hs.redshift.toggleInvert()` again restores the proper non-inverted screen. So while all above happens, `redshift` stays in the inverted mode.

**Update**:
Seems to happen (most often) when `hs.redshift.start` is called, but 'undone' by `hs.redshift.toggle()`.

**Comment by cmsj** [comment]
@lowne this one may be relevant to your interests :)

**Comment by asmagill** [comment]
FWIW, I had some issues with redshift when the screensaver would kick in or the machine went to sleep/was awoken... it could sometimes take as long as 5 minutes (usually closer to 2, though) before the inversion/shift level was restored... in my case, I just added a caffeinate watcher to stop redshift when the screen saver starts or the system goes to sleep, and restart it for the reverse.

**Comment by lowne** [comment]
tbh I still haven't tested this specifically (my main laptop is 24/7 desk-bound these days, and I'm so starved for time that the hastily-ported `init.lua` for my new 2016 MacBook has been broken since day 1 and *I've never even fixed it* 😭 (I have to click around with the trackpad! Unbelievable)), but I remember some occasional issues with pulsating and/or wrong or "intermediate" gamma states when plugging/unplugging screens; unfortunately the dependency chain of my (back then) intended improvements for redshift ended up on the scary shores of #775... (via screenwatchers)

But yes, I'll have to look into it...

**Comment by cmsj** [comment]
I'm going to close this out because I don't think we're going to be able to work on it. I still think we should deprecate hs.redshift because Night Shift is part of macOS now and is Good Enough™
