### ISSUE TITLE
caffeinate not working on 10.12

### ISSUE THREAD

**Issue by mikker** [Hammerspoon/hammerspoon#924]
Nothing gets logged nor reported. It just doesn't keep the computer alive. Sorry I can't give any more info.

**Comment by asmagill** [comment]
Do any of the following report true when you've "set" the appropriate sleep setting?

~~~lua
hs.caffeinate.get("displayIdle")
hs.caffeinate.get("systemIdle")
hs.caffeinate.get("system")
~~~

I don't have 10.12 yet, so can't test myself;  this will at give us an idea as to if the problem is in the way we're setting it or if it's in the OS honoring it...

**Comment by mikker** [comment]
@asmagill First one is `true`, when caffeinate is on. Other two are `false`.
@cmsj Enabling changes  `displaysleep` from just `10` to `10 (display sleep prevented by Hammerspoon)`.

**Comment by mikker** [comment]
It maybe working anyway. Seems turning it on and off does the trick. Will report back if anything changes.
