### ISSUE TITLE
Feature Request: Indefinite Uptime for hs.alert

### ISSUE THREAD

**Issue by cwre** [Hammerspoon/hammerspoon#930]
I'd love to be able to have this up indefinitely. My usage is to notify I'm in a prefix mode. Currently I have it up for 100 seconds, but leaving it up until I have exited the prefix mode would be awesome.

Thanks!

**Comment by asmagill** [comment]
By prefix mode, are you talking about modal hotkeys?  Under that assumption, your question intrigued me... we actually no longer need `hs.alert` to be an objective-c module at all, so I whipped up a potential lua/hs.drawing only version that I will be testing and possibly replacing the core one with down the road.

I've also added the ability to this test version to set an alert to display indefinitely and to remove it when requested.

If you want to test it as well, setting it up initially is a little tricky, since we want to make sure that the stock hs.alert is never loaded, so... do the following:

* Copy the file at https://github.com/asmagill/hammerspoon-config/blob/master/_scratch/alerts.lua to somewhere in your Hammerspoon configuration directory (I'll assume you save it as `~/.hammerspoon/newalerts.lua` for the rest of this writeup)
* add the following to the *top* of your Hammerspoon init.lua file before **ANY** use of the `hs.alert` module or possibly including any file which may include it (you can see mine, with a slightly different path of course, at https://github.com/asmagill/hammerspoon-config/blob/master/init.lua#L21):
~~~lua
local R, M = pcall(require,"newalerts")
if R then
   print()
   print("**** Replacing internal hs.alert with experimental module.")
   print()
   hs.alert = M
   package.loaded["hs.alert"] = M   -- make sure require("hs.alert") returns us
   package.loaded["hs/alert"] = M   -- make sure require("hs/alert") returns us
else
   print()
   print("**** Error with experimental hs.alert: "..tostring(M))
   print()
end
~~~
* Now, you use it normally, but if you save the return value for `hs.alert(..., true)` or `hs.alert.show(..., true)`, you can use that return value as an argument to `hs.alert.closeSpecific(...)` when you want to close it.  The `true` argument to the `hs.alert.show` command is optional -- you can still specify a duration, and using `hs.alert.closeSpecific` will close it early instead of waiting for the normal timeout.  You can see an example where I'm using it at https://github.com/asmagill/hammerspoon-config/blob/master/utils/_keys/applications.lua.

I will warn you that this is still experimental... I just created it today, so I'm going to play with it as my `hs.alerts` module for a while before possibly replacing the core one, but I welcome feedback for testing if you also want to give it a whirl.

**Comment by cwre** [comment]
I am talking about modal keys, and I'll take a look at this!

**Comment by asmagill** [comment]
Just noticed, you may see some errors in the Hammerspoon console about `natural` being an invalid baseTextDirection setting... this is actually an error in `hs.styledtext` that I've corrected in a pull request I've got pending.  You can safely ignore this message, if you see it... you may not, depending upon whether or not you've changed the Hammerspoon default log level for display... I have mine set to show almost everything, so I forget what the defaults are :-)

**Comment by cwre** [comment]
I can't see it, and my implementation of alert() works perfectly with what you've got replacing alert. I'll give you my implementation as soon as I figure out how to copy with neovim... It won't yank to my clipboard!

**Comment by cwre** [comment]
I'm also incredibly lazy, don't want to look... Is there a way to display this like an OSX notification rather than a center drawn object?

**Comment by heptal** [comment]
@cwre `hs.notify`

**Comment by cwre** [comment]
Will that allow me to keep it up indefinitely?

**Comment by heptal** [comment]
![](http://i.imgur.com/A4zHg9g.png) It's a per-app OSX setting - it may be possible to programmatically make it an 'Alert' but I'm not positive.

**Comment by asmagill** [comment]
The current hs.notify honors the application settings (default to banner, which is temporary, unless you change it in the system preferences shown above)

There are private APIs that were floating around for 10.9 to "force" a notification into a type other than what was chosen by the user's preferences, but there was little interest at the time of incorporating them into the module... I have no idea if the private methods would still work under 10.11/10.12 or not... the problem with private API's is that they change/disappear with no notice, which is why we decided against it at the time.

**Comment by cwre** [comment]
This is great to know! Thank you!

**Comment by cwre** [comment]
Is there an ETA for a PR?

**Comment by cwre** [comment]
Seems like they do work with 10.12. I'm on Beta 2 currently.

**Comment by asmagill** [comment]
@cmsj, should I push the hs.drawing based hs.alert I've been using now for the last few weeks?  It supports "indefinite" alerts in addition to being fully backwards compatible with the existing module.  On the one hand it adds a feature, on the other hand it completely replaces something that's working fine as is... though the replacement is solely lua code.

**Comment by cmsj** [comment]
@asmagill do it, let's see how it goes :)
