### ISSUE TITLE
Feature request: Allow __call metatable backed module in hotkey binds

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#932]
Playing with metatables for that first time, I am trying

```lua
-- foo.lua
local module = {}

function module.show()
    print("FOOBAR")
end

return setmetatable(module, { __call = function(_, ...) return module.show(...) end })
```

but something like

```lua
-- init.lua
local foo = require "foo"
foo() -- <= works
hs.hotkey.bind({'cmd', 'alt'}, 'f', foo) -- <= wants a real function
```

causes

```
FOOBAR
*** ERROR: ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:325: At least one of pressedfn, releasedfn or repeatfn must be a function
stack traceback:
	[C]: in function 'error'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:183: in function 'hs.hotkey.internal.new'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:325: in function 'hs.hotkey.internal.bind'
	/Users/xxxx/.config/hammerspoon/init.lua:3: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:467: in function 'hs._coresetup.setup'
	(...tail calls...)
```

**Comment by cmsj** [comment]
This is an interesting idea. My concern is that it would involve a lot more work on the ObjC side. Right now we just check if `lua_type()` on the arguments, is `LUA_TFUNCTION`. We'd have to also check for `LUA_TTABLE` and then start poking inside the table to gets metatable table, and then see if that table has a `__call` entry of type `LUA_TFUNCTION`. This is quite a bit of extra code!

I'm not entirely opposed to the idea, but I'm also not sold yet. Let's see what @asmagill thinks :)

**Comment by asmagill** [comment]
I'd think testing and wrapping the table in an anonymous function on the lua side would be easier. i do know that hs.hotkey.new is already wrapped in hotkey's init.lua, so not sure what this addition would do to that logic, but i still think should be easier there.

**Comment by cmsj** [comment]
@asmagill makes a good point about the functions being wrapped. @junkblocker take a look in `extensions/hotkey/init.lua` you'll see that we wrap each of the functions passed from the user. You can probably do what you want with a patch in there. If it works and doesn't hurt anything else, I wouldn't object to landing it :)

**Comment by junkblocker** [comment]
@cmsj , https://github.com/Hammerspoon/hammerspoon/pull/962 posted. Works for me with limited testing.

**Comment by junkblocker** [comment]
@cmsj, Just tried this with ``hs.hsdocs`` and I'm seeing this error. Let me know if you want a separate issue.

```
********
08:22:49 ERROR:   LuaSkin: hs.hotkey callback error: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:218: attempt to index a nil value (local 'self')
stack traceback:
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:218: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:217>
********
 ```

**Comment by cmsj** [comment]
Hmm

I wonder if the problem here is that we're storing a reference to the `__call` function when we should be storing a reference to the object, and calling the object as the hotkey callback?

**Comment by cmsj** [comment]
@junkblocker fancy trying again? :)

**Comment by junkblocker** [comment]
Didn't work

```lua
hs.hotkey.bind({'cmd', 'alt'}, 'f', hs.hsdocs)
```

```
*** ERROR: ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:211: bad argument #3 to '_new' (function expected, got table)
stack traceback:
	[C]: in function 'hs.hotkey._new'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:211: in function 'hs.hotkey.new'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:341: in function 'hs.hotkey.bind'
	/Users/xxxx/.config/hammerspoon/init.lua:590: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:467: in function 'hs._coresetup.setup'
	(...tail calls...)
```

**Comment by cmsj** [comment]
Oh, duh, the type signature is checked again in objc. I think we can probably skip that now, since the Lua side is inspecting pretty carefully

**Comment by cmsj** [comment]
ok, I'm officially confused now. I removed the type checking on the objc side, but now `lua_pcall()` objects to being given a table, so perhaps it's just not possible to call a `__call` metamethod from C? seems very unlikely, but I've yet to find anything in google about specifically this case.

**Comment by cmsj** [comment]
@asmagill any bright ideas here? I think I'm going to have to back this out for now unless someone saves me ;)

**Comment by junkblocker** [comment]
This should be reopened due to the reverts.

**Comment by asmagill** [comment]
I'll try and take a look later tonight... what error does `lua_pcall` generate when the callback is triggered?  `lua_pcall` is a wrapper to `lua_call` which is itself a wrapper to some esoteric lua internal stuff that should bear the sign "this way lies madness" (I hate when I have to troubleshoot and it leads me into the internals of lua itself...), but I see no mention one way or the other if it supports metamethods...

I supposed LuaSkin's protectedCall method could check the function argument position and see if it's a table... if so, get the metatable, and if it isn't do a lua_getfield on "__call" and if it is swap the function for the table... but it would be really nice if one of the lua functions did it for us since we'd have to make sure to keep clean up the stack after our checks.

**Comment by asmagill** [comment]
It just struck me... I haven't looked at the code for the pull yet, so forgive me if you're already taking care of this, but I had a thought... you're not just using the __call function in place of the hotkey function, are you?  That won't work because they have different argument signatures... the first argument to __call is *always* the table it is a metamethod for (the rest match, but in hotkey's case, there are no arguments.

So, it should be wrapped on the lua side as 
~~~lua
function()
    return getmetatable(originalTable).__call(originalTable)
end
~~~
and *that* is the function which should be passed on to the Objective-C methods... so the obj-c side still sees it as a function type.

I mention this in case it suggests a quick fix to one of you who have already worked on it... I won't have time myself until tomorrow sometime.

Note that this will create an upvalue to the original table which is held by the function reference held by the hotkey... the original table can never be fully garbage collected until the hotkey replaces/releases the function... but for hotkey's this is seldom an issue... they are *usually* either expected to be long-lifers that generally only go away on a restart, or they are really short-lived within a modal hotkey or timer based situation.

**Comment by junkblocker** [comment]
Confirming that that works. Here's the change applied  to the original commit.

```
From 41ca1abce854b98796330a05debf5a7f409a57b2 Mon Sep 17 00:00:00 2001
From: Manpreet Singh <junkblocker@yahoo.com>
Date: Wed, 24 Aug 2016 20:52:51 -0700
Subject: [PATCH] Allow __call metatable backed module in hotkey binds. Closes
 #962 Closes #932

---
 extensions/hotkey/init.lua | 20 ++++++++++++++++++--
 1 file changed, 18 insertions(+), 2 deletions(-)

diff --git a/extensions/hotkey/init.lua b/extensions/hotkey/init.lua
index 5b4b654..0b18cf1 100644
--- a/extensions/hotkey/init.lua
+++ b/extensions/hotkey/init.lua
@@ -143,6 +143,19 @@ local function getIndex(mods,keycode) -- key for hotkeys table
   key=key and supper(key) or '[#'..keycode..']'
   return mods..key
 end
+
+local function getFunc(f)
+  if f == nil then return nil end
+  if type(f) == 'function' then return f end
+  if type(f) == 'table' then
+    local m = getmetatable(f)
+    if m and m.__call and type(m.__call) == 'function' then
+      return function() m.__call(f) end
+    end
+  end
+  return nil
+end
+
 --- hs.hotkey.new(mods, key, [message,] pressedfn, releasedfn, repeatfn) -> hs.hotkey object
 --- Constructor
 --- Creates a new hotkey
@@ -176,10 +189,13 @@ function hotkey.new(mods, key, message, pressedfn, releasedfn, repeatfn)
   local keycode = getKeycode(key)
   mods = getMods(mods)
   -- message can be omitted
-  if message==nil or type(message)=='function' then
+  if message==nil or getFunc(message) then
     repeatfn=releasedfn releasedfn=pressedfn pressedfn=message message=nil -- shift down arguments
   end
-  if type(pressedfn)~='function' and type(releasedfn)~='function' and type(repeatfn)~='function' then
+  pressedfn = getFunc(pressedfn)
+  releasedfn = getFunc(releasedfn)
+  repeatfn = getFunc(repeatfn)
+  if not pressedfn and not releasedfn and not repeatfn then
     error('At least one of pressedfn, releasedfn or repeatfn must be a function',2) end
   if type(message)~='string' then message=nil end
   local idx = getIndex(mods,keycode)
```

**Comment by junkblocker** [comment]
<~~greedy~~consistent> It would be nice to have this change for ``hs.menu``'s ``fn``s also 😄  ... maybe everywhere the API accepts functions.</~~greedy~~consistent>

**Comment by cmsj** [comment]
@junkblocker I agree it would be nice to have it be consistent, but I think if we're going to do that, we should teach LuaSkin's `protectedCallAndTraceback` so it can work everywhere without us having to make sure every single function-accepting part of the API is wrapped in Lua.
I support  doing this, but not this close to release. Do you fancy filing a new issue and targetting it for 0.9.48?

**Comment by junkblocker** [comment]
Thanks, @cmsj . Filed issue https://github.com/Hammerspoon/hammerspoon/issues/971
