### ISSUE TITLE
Make documentations portable

### ISSUE THREAD

**Issue by thewhitetulip** [Hammerspoon/hammerspoon#935]
It'll be great if we have portable documents like pdf or html like Python documentation has.

Hammerspoon is simply fantastic!!

**Comment by asmagill** [comment]
I posted to the google groups, thinking it was in response to this:

> The next release of Hammerspoon will have a built in web server which can serve the documentation on `http://localhost:12345` (by default -- this can be changed) or retrieved in a built-in `webview` by typing `hs.hsdocs()` into the Hammerspoon console.  If you're comfortable building the Hammerspoon application yourself locally, the current master repository at https://github.com/Hammerspoon/hammerspoon has this already addition.
> 
> The documentation is actually built from the same template that is used for the Dash docset, and the ultimate goal is to be able to build the docset entirely within Hammerspoon without need for external tools, but currently it doesn't support streaming the resulting HTML to a file.  I'm not sure about output to a PDF file, but my current work on another module suggests that this might be easier to add then I once feared.

I will amend this to add, apparently Apple has not provided a good way to go from a WKWebview to a PDF -- even the print subsystem doesn't work well with the WKWebView class, apparently.   I'm hopeful that 10.12 might change this -- there were features added to it in 10.11 that people had reported were missing to Apple, so hopefully this trend will continue. Until then, using the built-in web browser will be possible in the next formal release of Hammerspoon, and at some point adding a way to output those pages to an HTML file, rather than served as a web page will be added, but PDF is probably a ways off.

**Comment by thewhitetulip** [comment]
If we provide a way to run documentation via localhost that'll be a better option really

**Comment by cmsj** [comment]
Well, we already have the ability to spit out the API docs as HTML - I use it every release to update http://www.hammerspoon.org/docs/ - see `make build/html`. Given that we have the online HTML docs, the Dash docs, the internal `help()` function for the Console, and now @asmagill 's webserver, I'm really not sure that adding PDF is particularly necessary, so I'm going to close this issue.

Please re-open if you disagree!

**Comment by thewhitetulip** [comment]
It's great if we have html documentation with the source code. No pdf required.
