### ISSUE TITLE
Do not show preference window on startup

### ISSUE THREAD

**Issue by moiraine-sedai** [Hammerspoon/hammerspoon#937]
I've enabled hamerspoon to launch at login, but that lead to the hammerspoon perference window to show up everytime I power on my laptop. Is it possible to change this behavior? Or what can I put into my init.lua so that everytime hamerspoon finishes loading, it will automatically close the preference window? Thanks for the nice work!

**Comment by rhys-vdw** [comment]
Why did you close this issue? Is there a solution for this?

**Comment by asmagill** [comment]
There are two reasons the preferences pane will show up on startup:
* you have just installed a new version, either manually, or through the auto-update mechanism
* you have not enabled Accessibility for the Hammerspoon application in your security settings.

If it's the former, just close the window and it shouldn't re-appear automatically again until Hammerspoon is again updated to a newer version.

If it's the later, you can easily tell because at the bottom of the preferences window the button "Enable Accessibility" will not be greyed out and the round indicator to the right of this button will be red.  Click on the button, or open up "System Preferences" and click on the "Security & Privacy" icon.  Then select the "Privacy" pane and select "Accessibility" in the list that appears to the left. You will need to click on the lock at the bottom of the System Preferences window and enter your password when prompted.  Once this is unlocked, scroll the right pane until you see the Hammerspoon icon and make sure that the checkbox next to it is checked (click on it if it isn't).  If it was clicked before, you might click it once to un check it and then click on it again to put the checkmark back -- I do recall a time when someone mentioned that their settings had become corrupted and this reset it for them.  At any rate, once you have made sure that is is checked, close the System Preferences and verify that the indicator in the Hammerspoon preferences window is now green instead of red.

Hope this helps!

**Comment by rhys-vdw** [comment]
@asmagill Thanks! Yeah, it was the accessibility settings. Thought I'd already configured them. I was just looking through the checklist for "show preferences at startup" and couldn't find it. Thanks for the detailed response.
