### ISSUE TITLE
Watch scroll wheel events?

### ISSUE THREAD

**Issue by thalesmello** [Hammerspoon/hammerspoon#938]
I'm interested in creating some scroll wheel based mappings in order to enable horizontal scroll in my terminal emulator.

I was wondering if it's possible to create a watch for ScrollWheel events using hammerspoon.

I so far haven't found anything like this. Thanks in advance.

**Comment by heptal** [comment]
[`hs.eventtap`](http://www.hammerspoon.org/docs/hs.eventtap.event.html#types) has a `scrollWheel` event.

**Comment by thalesmello** [comment]
@heptal Is there any example on how to **watch** scroll events?

**Comment by asmagill** [comment]
~~~lua
z = hs.eventtap.new({hs.eventtap.event.types.scrollWheel}, function(e)
    print(e:getProperty(hs.eventtap.event.properties.scrollWheelEventDeltaAxis1),
          e:getProperty(hs.eventtap.event.properties.scrollWheelEventDeltaAxis2))
end):start()
~~~

There are other properties that might apply as well... check `help.hs.eventtap.event.properties` or https://developer.apple.com/library/mac/documentation/Carbon/Reference/QuartzEventServicesRef/index.html#//apple_ref/c/tdef/CGEventField.

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Comment by sheldond** [comment]
I'm interested in tracking a single mouse wheel scroll event (imagine a clicky mousewheel, not a Mac trackpad). And I'd like to distinguish the direction of the scroll (up or down). However I couldn't find a way yet. @asmagill's example will always print `0	0` regardless of which direction I scroll, I've looked at all properties starting with "scrollWheelEvent". This may be a Mac limitation, not Hammerspoon? Any ideas? Thanks! 😄

**Comment by asmagill** [comment]
If the hardware or driver for the mouse is converting the scroll wheel actions into something else (arrow keys, pageUp/pageDown, etc.) then it may not be possible for us to get at these events since they've been changed into something else.

Off the top of my head, if none of the scrollWheel events or properties are providing any data, then my suspicion is that we may not be able to do anything about it.

What is the make and model of the mouse?  A quick google search may show if people have found a way around this for your specific model... or at the very least allow us to start a list of known problematic hardware.

**Comment by sheldond** [comment]
Thanks for your reply! I tested two mice, both results the same:
- Logitech Wireless Trackball M570 
- Razer DeathAdder 2013

I noticed that if I scroll many times quickly, then the numbers will begin to change to something like
```
0	0
0	0
0	0
0	0
0	0
-1	0
-4	0
-7	0
-10	0
``` 
So I can detect when lots of quick scrolling is happening, but not individual events.

**Comment by weitzj** [comment]
If anyone is interested to use the Trackball of the M570 as a vertical/horizontal Scrollwheel in Hammerspoon: https://github.com/tekezo/Karabiner/issues/814
