### ISSUE TITLE
(feature request) watch for event: magic mouse/trackpad connected

### ISSUE THREAD

**Issue by moiraine-sedai** [Hammerspoon/hammerspoon#940]
a particular problem I'm trying to solve: I've hidden the bluetooth icon in the menu bar, but whe the  mouse's battery is low, macos shows up a low battery warning and the bluetooth icon appears in the menu bar, and it does not go away after changing the battery. I'm writing a script so that on mouse connect, if batterylevel>10% and icon in menubar then remove bluetooth icon.

**Comment by asmagill** [comment]
I know that bluetooth notifications are sent by OS X at various times which we can catch with hs.distributednotifications, but I haven't really used it for such yet, so I'm not sure if the normal messages will contain the information you want or not.  You could use some code like this:

~~~lua
watcher = hs.distributednotifications.new(function(n,o,i)
    ...code to determine if we care and what to do about it...
end, "com.apple.bluetooth.status"):start()
~~~

When invoked, the function arguments will contain something like the following:
* `n` - com.apple.bluetooth.status - this is the notification itself; if the watcher was setup to capture all notifications, we could check this to see if it's a notification we care about.  In this case, since we specified what we wanted to watch, you can ignore this argument.
* `o` - "com.apple.bluetooth.status" - notifications are "sent" by something, and this will be a reference to that, in this case, it appears to always be sent by the bluetooth infrastructure itself, so not really useful in this case either.
* `i` - this will be a table which contains more details about the notification... I haven't really had a chance to parse and understand it for com.apple.bluetooth.status yet, but it should contain something like this:
~~~lua
{ A2DP_CONNECTED_DEVICES = 0, A2DP_CONNECTION_COUNT = 0, ACL_CONNECTION_COUNT = 0, ADDRESS = "XX-XX-XX-XX-XX-XX", CONNECTED_DEVICES = { { ADDRESS = "XX-XX-XX-XX-XX-XX", NAME = "XXX’s Mouse", PRODUCT_ID = 781, SNIFF_ATTEMPTS = 2, VENDOR_ID = 1452 } }, CONNECTED_DEVICES_COUNT = 1, CONNECTED_HID_DEVICE_COUNT = 1, DISCOVERABLE = 0, ESTIMATED_BANDWIDTH_UTILIZATION = 25, HARDWARE_NAME = 15, HID_OPERATION_HISTORY = { { ADDRESS = "XX-XX-XX-XX-XX-XX", NAME = "XXX’s Trackpad", OPERATION_ERROR_STATUS = 4, OPERATION_TYPE = "PAGE_END", REMAINING_PAGE_DURATION = 0.0, TIMESTAMP = 1468877076 }, { ADDRESS = "XX-XX-XX-XX-XX-XX", NAME = "XXX’s Trackpad", OPERATION_TYPE = "PAGE_START", PAGE_DURATION = 6.25, REMAINING_PAGE_DURATION = 0.0, TIMESTAMP = 1468877069 }, { ADDRESS = "XX-XX-XX-XX-XX-XX", NAME = "XXX’s Mouse", OPERATION_ERROR_STATUS = 0, OPERATION_TYPE = "PAGE_END", REMAINING_PAGE_DURATION = 6.25, TIMESTAMP = 1468877069 }, { ADDRESS = "XX-XX-XX-XX-XX-XX", NAME = "XXX’s Mouse", OPERATION_TYPE = "PAGE_START", PAGE_DURATION = 6.25, REMAINING_PAGE_DURATION = 6.25, TIMESTAMP = 1468877066 } }, NAME = "XXXXXXX", ONE_SNIFF_ATTEMPT_HID_CONNECTION_COUNT = 0, PAGEABLE = 2, POWER_STATE = 1, PRODUCT_ID = 33299, SCO_CONNECTED_DEVICES = 0, SCO_CONNECTION_COUNT = 0, TWO_SNIFF_ATTEMPT_HID_CONNECTION_COUNT = 1, VENDOR_ID = 1452 }
~~~

Not a complete answer to your request, but maybe it will help in some way!

**Comment by moiraine-sedai** [comment]
Thanks! That would be helpful.

**Comment by cmsj** [comment]
(I'm not sure there is any work to be done here in Hammerspoon - bluetooth stuff like this is generally not exposed via APIs we can use, so I'm going to close this issue. Please re-open if anyone disagrees!)

**Comment by gingerbeardman** [comment]
This would be another case for #3392 

You'd watch for a device with the following HID Device Info

```
productName: Magic Mouse
vendorId:    0x004C (76)
productId:   0x0269 (617)
opened:      true
```

**Comment by asmagill** [comment]
FWIW, I have code at https://github.com/asmagill/hs._asm.undocumented.touchdevice/blob/master/watcher.m that detects when the Magic Trackpad or Force Touch Trackpad are attached/detached from your machine... haven't tried it with the Magic Mouse.

It was added to a module I was experimenting with that uses undocumented APIs to detect low-level information about individual touches, but IIRC, the watcher itself doesn't rely on any of the undocumented stuff.

I'm not at a point where I can wrap it into something separate that can be integrated into Hammerspoon, but if anyone is interested, feel free to copy the code and do what you want or can with it.
