### ISSUE TITLE
What is the command for reloading the config from command line?

### ISSUE THREAD

**Issue by nikitavoloboev** [Hammerspoon/hammerspoon#947]
I want to be able to reload the config from the command line tool, can I do that? In 'getting started' there is only the example with hotkey I believe. 

Thank you for any help.

**Comment by asmagill** [comment]
I think what you're looking for is `hs.reload()`.

If you want to do it strictly from the command line (Terminal), try `hs -c "hs.reload()"`

**Comment by nikitavoloboev** [comment]
Does not work : 
![2016-08-01 at 00 17](https://cloud.githubusercontent.com/assets/6391776/17279764/5c972dfe-577d-11e6-965e-3cab034d1081.png)

**Comment by asmagill** [comment]
Take a look at the documentation for `hs.ipc`... If you don't have Dash or don't want to use the web pages, you can type `help.hs.ipc` into the Hammerspoon console.  Probably the most relevant portion is:

~~~lua
> help.hs.ipc.cliInstall
Function: hs.ipc.cliInstall([path][,silent]) -> bool

Installs the `hs` command line tool

Parameters:
 * path - An optional string containing a path to install the tool in. Defaults to `/usr/local`
 * silent - An optional boolean indicating whether or not to print errors to the Hammerspoon Console

Returns:
 * A boolean, true if the tool was successfully installed, otherwise false
~~~

`hs.ipc.cliInstall` creates symbolic links to the `hs` binary and `hs.1` man page included in the Hammerspoon application bundle at the path you specify... if you're only using the Hammerspoon releases or always install Hammerspoon when you build it to the exact same location, you should only need to run this once.  Or, like some do, it's safe to put it into your `init.lua` file -- this will cause error messages to appear in the console when you start Hammerspoon if it can't match existing links to the currently running version of Hammerspoon.

**Comment by asmagill** [comment]
Oh, and I should probably clarify this in the docs at some point -- the path assumes that binaries go into `path .. "/bin"`, and man pages go into `path .. "/share/man/man1"`, so just include the prefix (i.e. "/usr/local", not "/usr/local/bin") if you want a location other than /usr/local.

**Comment by nikitavoloboev** [comment]
I am not quite sure what I should write to get the cli commands working. Typing in `help.hs.ipc.cliInstall` says that command is not found. It seems that I do not have the 'hs' command at all on my system.

**Comment by asmagill** [comment]
The commands needs to be typed into the Hammerspoon console.  If you have the Hammerspoon icon in your Dock, click on it, and then when it is the active application, tap Command-R to bring up the console.

If you don't have the Dock icon, but do have the Hammerspoon icon in your status menus, click on the icon and select "Console..." from the menu.

If you've disabled both in the Preferences, in the Terminal application type `open -a Hammerspoon`. This will either open up the Hammerspoon console (it should, if Hammerspoon is already running), or if it appears to do nothing, try tapping Command-R before clicking on anything else.

One of these methods should give you a screen that looks something like:

![screen shot 2016-08-01 at 3 39 59 am](https://cloud.githubusercontent.com/assets/8139480/17288243/a9f2c6be-5799-11e6-9e57-efd8618e8811.png)

The text field highlighted in blue at the bottom is where you should try typing in commands like `help.hs.ipc` and `help.hs.ipc.cliInstall`.

Hope this helps!

**Comment by nikitavoloboev** [comment]
This makes sense, I didn't think you would need to type it in the console. 

I have run the command in the console and get this  : 

![2016-08-01 at 10 54](https://cloud.githubusercontent.com/assets/6391776/17288604/501992ca-57d6-11e6-85f9-0025b554b897.png)

I would suppose then typing `hs -c "hs.reload()"` would work from my bash terminal prompt. Or am I misunderstanding something?

**Comment by asmagill** [comment]
You left off `()`

Without the parenthesis, lua sees this as a request to show the value of `hs.ipc.cliInstall`, which it has -- it's a function.  Add the parenthesis, and it will execute the function.

**Comment by asmagill** [comment]
And yes, once installed, that command line should reload your hammerspoon configuration.  I should also point out that you will want to add `require("hs.ipc")` in your init.lua file somewhere... or `hs.ipc.cliInstall()` -- as I mentioned earlier, running this each time you load won't cause a problem and might even warn you if the links to the command or man page get out of sync with your Hammerspoon installation (shouldn't happen unless you work with development builds, but you never know!)

The reason for adding some reference to `hs.ipc` in your init.lua file is to make sure that it loads the necessary backend support -- Hammerspoon has to open up a Mach port for the external command to access -- loading the `hs.ipc` module, either with `require("hs.ipc")` or by taking advantage of Hammerspoon's module autoload feature with `hs.ipc.cliInstall()` makes sure that this happens every time you start up Hammerspoon.

**Comment by nikitavoloboev** [comment]
Thank you a lot. This works. :)
