### ISSUE TITLE
I want to show a line from some file in hs.alert.show, I want some help

### ISSUE THREAD

**Issue by nikitavoloboev** [Hammerspoon/hammerspoon#948]
I have a text file in my Documents that I use to show my tasks in the menu bar with use of [BitBar](https://github.com/matryer/bitbar).

It is a simple text file, in my case named 'todo' placed in ~/Documents/app/bitbar' with the content of  : 

```Bash
#!/bin/bash

echo some text
```

The 'some text' part changes. How can I pass just what is after the echo command into my hammer spoon hs.alert.show command. 

This would be incredible if I can do that. Thank you for any help on this.

**Comment by asmagill** [comment]
The following should work, if the script is in your PATH or if you give the full path to the shell script:

~~~lua
hs.alert.show( ( hs.execute("shellscript") )
~~~

The extra ( and ) around `hs.execute(...)` is because hs.execute actually returns 4 arguments... the output of the script and the same 3 arguments that the lua builtin `os.execute` returns indicating execution success/failure (try just the `hs.execute(...)` portion in the console to see what I mean).  The extra parenthesis cause lua to only pass the first argument (the output) into `hs.alert.show` and ignore the other 3.

**Comment by nikitavoloboev** [comment]
Thank you so much asmagill, this is really great. Is it possible to specify the location where alert.show popup shows?

**Comment by asmagill** [comment]
With `hs.alert`, no, though you can craft your own visual display items with `hs.drawing`.  `hs.drawing` objects don't go away on their own, however -- you'll need some additional code to handle that.

As an example, you can take a look at https://github.com/asmagill/hammerspoon-config/blob/master/_scratch/alerts.lua, which is an answer to #930 requesting an indefinite display time for `hs.alert` dialogs... while it doesn't address your question about alert location, it does show how to mimic the visual aspect of alerts completely through `hs.drawing` and could serve as a starting point for developing something that addresses your specific needs.

**Comment by cmsj** [comment]
@nikitavoloboev you could also use hs.notify, to get a normal OSX notification in the top right :)

(I'm going to close this issue because I don't think there is any work to be done in Hammerspoon here. Please re-open if you disagree!)
