### ISSUE TITLE
hs.pasteboard.readImage() cannot be opened / displayed

### ISSUE THREAD

**Issue by skamsie** [Hammerspoon/hammerspoon#954]
The ```hs.image``` returned by `readImage()` cannot be opened or saved as a regular image file. 

Copy an image file on your computer using the keyboard or mouse and then in the console:

```
> pic = hs.pasteboard.readImage()
> hs.inspect(pic)
<userdata 1> -- hs.image:  (0x7fa41b017e28)
> pic:saveToFile('/tmp/1.jpg')
true
```

Open the image on the computer:

![screen shot 2016-08-18 at 10 42 59 am](https://cloud.githubusercontent.com/assets/7014744/17767575/c661cc74-6530-11e6-8ebe-4102a79c82e9.png)

The same happens if you try to display the image or add it to a chooser window

**Comment by asmagill** [comment]
If you are selecting a file on your computer in the Finder and then selecting "Copy..." from the Edit menu, then this is the expected behavior -- what is being put on the clipboard is a file URL reference, an icon for the file URL reference, and the text of the file's name (see `hs.inspect(hs.pasteboard.allContentTypes())`).

If you're wanting to see the contents of the file, you should either load it with `hs.image.imageFromPath("/path/to/file.jpeg")`, pull the file path from the file URL reference with something like `hs.image.imageFromPath(hs.pasteboard.readURL():match("^file://(.*)$"))`, or open it up in an application like Preview, select the entire image ("Select All" in the Edit menu) and then copy it to the clipboard ("Copy" in the Edit menu).  Then `hs.pasteboard.readImage()` will work as I think you're expecting.

**Comment by skamsie** [comment]
Thanks! The confusion came from the fact that hs.image.imageFromPath(..) and hs.pasteboard.readImage(..) both return the same type ```hs.image``` and I was expecting both to behave the same.

**Comment by asmagill** [comment]
The results of `hs.pasteboard.readImage(..)` is an image... it's just an image of the file's icon... try selecting a different file from the Finder (your hard drive, or a text document, etc.). Select "Copy" from the Edit menu, and then in Hammerspoon, try `pic:saveToFile('/tmp/1.jpg')`... you'll see an icon representing whatever you selected and copied in the Finder... But I do agree, it can be a little confusing at first as you learn how OS X does some things behind the scenes that we often take for granted.

**Comment by cmsj** [comment]
(I don't think there is any action to be taken here, so I'm going to close the issue. Please re-open if you disagree!)
