### ISSUE TITLE
autoreload code is not working

### ISSUE THREAD

**Issue by brandondrew** [Hammerspoon/hammerspoon#977]
The code given for auto-reloading of `init.lua` does not work, at least in the latest version of Hammerspoon (version 0.9.47).

*If*, however, you change this

```
hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", reloadConfig):start()
```

to 

```
hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/init.lua", reloadConfig):start()
```

then it will work (at least for that single file—almost certainly not if you have multiple `.lua` files and you change a different one).

**Comment by asmagill** [comment]
The latter one will likely eventually fail as well because of the way Lua handles garbage collection.

hs.pathwatcher returns an object which represents the internal (objective-c code) which is doing the actual watching.  When that object is collected, the Objective-c code assumes that it should shut down to release the memory used and stops the watcher before deleting itself.

The proper fix is to assign the watcher object to a global variable which will not go out of scope... as long as it remains in scope, the watcher is never collected, so it never stops.

Something along the lines of

~~~lua
configWatcher = hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", reloadConfig):start()
~~~

should do the trick.

**Comment by cmsj** [comment]
Damn, this was a bug in the docs. You need to capture the return value of `hs.patchwatcher.new()`, otherwise it's available to be garbage collected at some (unpredictable) point in the future. Something like this would do:

```lua
local myWatcher = hs.patchwatcher.new(...):start()
```

Sorry about that, I have fixed the docs now.

**Comment by asmagill** [comment]
Actually, unless that local value is referenced as an upvalue by something which won't be collected, eventually it will be as well... If you truly want something that will persist no matter what, you wither have to store it in something global or do something like this:

~~~lua
local watcher
watcher = hs.pathwatcher.new("path", function()
    local myWatcher = watcher
    hs.reload()
end):start()
~~~

Now `watcher` can't be collected even when it's out of scope because it's an upvalue to a function which can't be collected because it's referenced in the internal registry used by module callback functions.
