### ISSUE TITLE
autoreload feature in preferences instead of init.lua

### ISSUE THREAD

**Issue by brandondrew** [Hammerspoon/hammerspoon#978]
Although it is pretty cool that we can add code to `.hammerspoon/init.lua` to trigger a reload of configuration whenever the `init.lua` changes, it would be preferable if this could be handled by the Hammerspoon app itself instead.  There are several reasons for this:
1. currently, if your latest change to the file contains an error, it breaks your configuration and aborts the ability to auto-reload, until you correct the error and manually reload.
2. when you've got an error in your Lua code that you need to fix, that's when you _really_ want to be able to autoreload, so you can avoid constantly switching to the mouse and back just to test your latest change (especially for those of us who have learned Lua just to use Hammerspoon)
3. this is a very widely useful option, and it would make sense for it to be easier to enable than by pasting code into `init.lua`.
4. the [code in the Getting Started guide](http://www.hammerspoon.org/go/#fancyreload) is [broken](https://github.com/Hammerspoon/hammerspoon/issues/977)

**Comment by cmsj** [comment]
I've tended to resist adding it as a core app feature, since it's possible in Lua, but maybe we need to think about it some more. @asmagill - any preferences in either direction?

**Comment by asmagill** [comment]
While I will certainly defer to the general consensus concerning this (or almost any issue wrt Hammerspoon), let me give you the counter argument (which I happen to subscribe to)...

Reloading Hammerspoon stops *everything* that Hammerspoon is currently doing -- any menus you have created, any watchers you have started, any timers which are running, any webview's, any drawings, any *anything*... they are all deleted and purged... and then restarted *if and only if* they were defined in one of the files referenced from your `init.lua` file... anything you've started from the console itself is gone until you type it in again.

Then there is the argument about file types... the watcher you've defined in #977 will reload Hammerspoon for *any* file which changes in your hammerspoon configuration directory.  I have tools which create text files in there, I install modules I'm testing or debugging in there, etc.  Not all of them should trigger an automatic reload.

For these reasons, my watcher is actually the following:

~~~lua
return require("hs.pathwatcher").new(
    hs.configdir,
    function (changedfiles)
        local function is_lua_file(filename)
            if string.match(filename, '%.lua$') then print(filename) end
            return string.match(filename, '%.lua$')
        end
        if not require("hs.fnutils").every(changedfiles, is_lua_file) then return end
--        hs.reload()
        print("you might wanna reload!")
    end
):start()
~~~

You can see that I used to reload as well, but got tired of the interruption when making multiple modifications that I wanted to get in place before triggering a *single* reload of *all* of my changes.

While I agree that the edit-reload-error-fix-edit-reload-error... cycle can be annoying, it's probably a good one (in my opinion) because otherwise a loop can occur if your code is broken in just the wrong way, especially if you are writing to any files during start up (I have some notification watchers that might).

By having the watcher written in Lua, you can add any criteria you want... wait until a certain number of files have changed, ignore certain files based on name or extension, etc.

A built in watcher would have to be limited to a specific set or type of changes and wouldn't be changeable (even if we added the ability to add your own hooks to the process to add/suppress criteria, it would still come down to lua code which could be broken itself)... and anyone who wanted something more complex would be out of luck -- or have to disable the built in one and end up writing there own anyways.

**Comment by junkblocker** [comment]
What @asmagill said. I have a custom watcher doing a lot of checks. My config is also in non-standard ``~/.config/hammerspoon`` and the files therein are symlinked so I resolve the paths watch the original directory they are linked from. A general reloader is only going to hinder.

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
