### ISSUE TITLE
Invalid hotkey

### ISSUE THREAD

**Issue by quaritexa** [Hammerspoon/hammerspoon#984]
Sometimes i've got this error:
*** ERROR: ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:325: Invalid key: `

On this code:
hs.hotkey.bind({"cmd", "alt"}, "`", function()

**Comment by asmagill** [comment]
When you say sometimes, do you mean that sometimes it works and sometimes it doesn't?  If it does accept the command sometimes, does the hotkey do what its supposed to when you type it?

Hotkeys are only valid for the keys defined for your currently active keymap, so if you use different keymaps at different times for alternative keyboard layouts or different keyboards, that could be the culprit... type `hs.keycodes.map["`"]` into your Hammerspoon console and see if it returns a number... if it doesn't, then the ` key isn't defined for the currently active keymap.  If this is the case, check out the documentation for `help.hs.keycodes.inputSourceChanged`.  You can use this to change hotkey mappings when your keyboard map changes.

**Comment by quaritexa** [comment]
I bind hs.hotkey.bind({"cmd", "alt"}, 10, and have no errors.

**Comment by asmagill** [comment]
On my machine, `hs.keycodes.map[10]` returns § and not `

Are you able to bind the apostrophe sometimes?  Or does it always generate an error?
Do you use multiple keyboard layouts at different times, or just one?

**Comment by quaritexa** [comment]
I have two layouts: 
![cfsisg8i](https://cloud.githubusercontent.com/assets/886676/18531210/c5378f4c-7add-11e6-8dad-80e300783fc0.png)

But why hs.keycodes.map["`"] sometimes returns nil?

```
> hs.keycodes.map["`"]
nil
> hs.keycodes.map["ё"]
10
> hs.keycodes.map["ё"]
10
> hs.keycodes.map["`"]
10
> hs.keycodes.map["`"]
10
> hs.keycodes.map["`"]
10
> hs.keycodes.map["ё"]
10
>
```

**Comment by asmagill** [comment]
Every time your active keyboard layout changes, `hs.keycodes.map` updates to reflect the currently recognized keys and their internal keymap code.  Only one of your keyboard layouts has a reverse apostrophe character, so when the other layout is active, `hs.keycodes.map` doesn't recognize the character.

If you want the same physical key location on your keyboard to trigger the action, then use the number 10 instead of the specific character when defining the hotkey binding -- it's why the `hs.hotkey` functions can accept a number in the `key` field... for when it's the physical location of the key on the keyboard, rather then the text of the key, that you wish to match. 

If you want to change the binding (enable/disable it, change to a different physical key location entirely, etc.) then you will need to put something like this into your `init.lua` file (note: I haven't actually tested this since I only use one keyboard layout, but something like this should work with minimal (no?) modifications other then the labels mentioned in the comments):

~~~lua
-- create the bindings for each layout, but don't activate either one yet
-- note that `keyboardlayout1` and `keyboardlayout2` are just example place holders...
-- you should  replace them with the output from `hs.keycodes.currentLayout()` for
-- each layout you want to support.
local bindings = {
  ["keyboardlayout1"] = hs.hotkey.new({"cmd", "alt"}, "`", function() ... end),
  ["keyboardlayout2"] = hs.hotkey.new({"cmd", "alt"}, "ё", function() ... end),
}

-- create the function which activates the right one
local assignHotkeyFunction = function()
    for k, v in pairs(bindings) do
        if k == hs.keycodes.currentLayout() then
            v:enable()
        else
            v:disable()
        end
    end
end

-- reassign the key when the keyboard layout changes
hs.keycodes.inputSourceChanged(assignHotkeyFunction)

-- assign the key based on the initial keyboard layout
bindings[hs.keycodes.currentLayout()]:enable()
~~~

**Comment by quaritexa** [comment]
Thanks for а detailed explanation. Now I see why my script sometimes get error. It happens when Hammerspoon starts with other layout activated.

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Comment by quaritexa** [comment]
Why hs.keycodes.map does not updates when i switch the layout from script and does when i switch it from cli?
