### ISSUE TITLE
Question - Preloading Extensions?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#992]
I've noticed that there's a few extensions that load as soon as I launch Hammerspoon, however there's a lot of extensions that load dynamically as needed.

Does this slow things down? Is there a way to pre-load extensions? What's the recommended practise?

Here's a look at my console:

```
START OF SCRIPT
-- Loading extension: pathwatcher
-- Loading extension: alert
-- Loading extension: hotkey
22:12:27     hotkey: Enabled hotkey ⌘⌥⇧F19
-- Loading extension: application
-- Loading extension: uielement
********
22:12:27 ERROR:    hotkey: The hotkey was deleted, cannot enable it
********
             hotkey: Enabled hotkey ⌘⌃⌥T
END OF SCRIPT
-- Done.
-- Loading extension: appfinder
-- Loading extension: osascript
-- Loading extension: drawing
-- Loading extension: geometry
-- Loading extension: timer
********
22:12:53 ERROR:    hotkey: The hotkey was deleted, cannot enable it
********
********
22:12:59 ERROR:    hotkey: The hotkey was deleted, cannot enable it
********
```

Thanks in advance!

**Comment by asmagill** [comment]
In my experience, module load time has not been a problem.  When loading a module with the `require` command, Lua will only load the module once -- every future `require` command for that module will simply return the already loaded table (result) from the first load.

What you're seeing in the console is a message that the module was not explicitly required, but was instead referenced by it's full name from the global variable space of Lua.

The gory details, if you're interested:

In lua, module names and where you store a modules constants are not necessarily the same thing... by convention, we name all of our modules as `hs.something`, and I name most of my custom (i.e. not automatically included) modules as `hs._asm.something`.  But this is strictly a naming convention that really only has an impact on where Lua looks for the files that define the module when the module is loaded.

A module is loaded with the `require` command.  For example:

~~~lua
local inspect = require("hs.inspect")
~~~

This puts the `hs.inspect` module into the local variable `inspect`.  Local would apply to the function or lua script that this line was found in -- if you type this into the console, it will in fact assign the module to the local variable `inspect`, but the local variable would go out of scope as soon as control returned to the console, so it in effect appears to be a no-op (each time you hit the `return` key, what you've typed into the console at that time is treated as an independant scope).

However, even if `inspect` has no value, what `require` did was first check the global variable `package.loaded` for a key of "hs.inspect".  If `package.loaded["hs.inspect"]` exists, its value is returned and the `require` command is complete.  If that key does not exist in `package.loaded`, then the `package.path` and `package.cpath` strings are examined for paths where modules may be found.  The `?` at each possible path in the two variables is replace with the module name requested (in this case "hs.inspect") where every period is changed to a `/` (e.g. "hs/inspect").  When one of the templates matches, that file is loaded, executed, and usually returns a table.  This table is then stored in `pacakage.loaded["hs.inspect"]` and the table is also returned and the require command completes.

What the `hs` global table represents is a convenience so that script writers don't have to explicitly require the modules they want... the trade off is that they have to spell out the module name in its entirety so that the `hs` table, which has a metamethod for __index (check any lua reference for more info on metamethods) can automatically require the module for you.  When this automatic `require` is done for you, it prints out a message on the console whether it actually loads the module or just gets a reference to the table already in `package.loaded` -- remember require will actually load the module only the *first* time it is requested ... every other require is more accurately an assignment or reference.

(It should also be noted that this autoloading feature only works for the core modules... you can't type `hs._asm.axuielemnt` into the console and expect it to autoload since it's not in the core modules.)

There is a school of thought that says that writing your code so that any module you need is stored in a local variable is faster... technically this is true because local variables are searched before global variables are, and looking for `hs.hotkey.bind` for example means that the search occurs as follows: local variables are searched for `hs`.  It's not found, so the global name space is searched for `hs`.  It's found, then `hotkey` is searched for in the `hs` table.  Then `bind` is searched for in the `hotkey` table of the `hs` table.  If you had typed `local hotkey = require("hs.hotkey")` and then tried to use `hotkey.bind`, then the local variables are searched for `hotkey`.  When found the `hotkey` table is searched for `bind` -- 2 searches rather than 4.

I say "technically" in the previous paragraph because on a modern computer, the speed difference is measured in micro or even nano seconds.  Unless you have something that is iterating millions of times, this won't be what's causing your script to be slow.  But, every little bit does add up, so... YMMV.

I personally like to require everything in my scripts and put them into local variables because I think it's cleaner.  I see an autoload statement as an example of me forgetting or mistyping something in my script; but that's me.  Others like the convenience of having one consistent name for something that never changes in any of their scripts... when you store a module's reference in a local variable, you pick the variable name, so if I'm inconsistent in my naming, `inspect` in one script might refer to a completely different module or function in another.

I do (usually) try to use the "full" name for things when I add them to issues or explanations on the web site, however, because that way everyone knows exactly what module I'm referring to and can type it in themselves and get the same behavior as I am describing.

Confused?  It can be a lot to take in.  If you want the convenience of the `hs` autoloading core modules, then by all means do so.  If you want a more traditional Lua, rather than Hammerspoon specific, experience, then explicitly load the modules you want into your own local or global variables so you know what you have loaded and how you want to access it.

In either case, Lua won't do the actual loading of a given module more than once, no matter what route you take or even if you mix them.

**Comment by latenitefilms** [comment]
Thank you so much for such an amazingly detailed reply! HUGELY appreciated!

This information should really go in the FAQ - it's very helpful!

Because my Hammerspoon scripts are intended to be shared around (i.e. not just to be used on my individual system) - what's the best to add some error checking to detect whether or not a custom module exists?

**Comment by latenitefilms** [comment]
@asmagill - Curious... Is there anyway to stop the **-- Loading extension:** messages from appearing in the console?

**Comment by latenitefilms** [comment]
@asmagill & @cmsj - Looking at the Hammerspoon code, it doesn't look like it's possible to stop the **Loading extension** messages. As a feature request, it would be great to have a setting to do this in a future Hammerspoon release. Maybe something like **hs.console.setLogLevel(1)**?

**Comment by latenitefilms** [comment]
Solved, with a pretty dodgy workaround:

```
local oldPrint = print
print = function(value)
	if (value:sub(1, 21) ~= "-- Loading extension:") and (value:sub(1, 8) ~= "-- Done.") then
	    oldPrint(value)
	end
end
```
