### ISSUE TITLE
Invoking hotkeys on lock screen

### ISSUE THREAD

**Issue by prohtex** [Hammerspoon/hammerspoon#993]
I'm having trouble getting my hotkeys to work on the lock screen. They seem to work fine otherwise. Any ideas?

**Comment by asmagill** [comment]
To my knowledge, no hotkey binding or eventtap for any application works when the screen is locked or you are at a login screen (if you use fast user switching for example).  I don't believe its something we can do anything about.  From a security standpoint it makes sense -- I don't want *any* application watching what I type; otherwise it could capture my password without my knowledge.

**Comment by prohtex** [comment]
Karabiner did, but Sierra broke it.

**Comment by cmsj** [comment]
I am firmly of the opinion that Hammerspoon should never be in the business of including a kext, it's too much responsibility!

Karabiner is currently being rewritten to be compatible with Sierra and already works for very simple 1:1 key remappings (see Karabiner Elements).

I'm going to close this issue, because I don't think there is anything for us to do here. Please re-open if you disagree!

**Comment by prohtex** [comment]
Unfortunately Karabiner-Elements is far from supporting complex key remapping. I've been working with Hammerspoon over the past few weeks and am really enjoying it. I've rewritten all my macros and everything works great. The only thing I'm wondering about is the lock screen. Is there any hope of getting this to work? @asmagill I understand there's the potential for a keylogger, but wouldn't it be possible to simulate keystrokes without capturing them? I need my key remapping to stay intact while I'm typing a password. Currently it works with Hammerspoon everywhere, except on the lock screen.
