### ISSUE TITLE
General slowness of window management in Sierra

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#995]
Sorry to offer such a vague report, but my functions and bindings for moving windows around a la Slate---which haven't changed in months, maybe even over a year---are suddenly sluggish on Sierra.

This is so even after using Sierra for a while and waiting for caches to build up.  (I have Spotlight indexing disabled, so it's not because a giant indexing operation is hogging resources that HS would otherwise enjoy).

If I move a window or several windows in succession, the ones after the first one are snappy.  If I go a couple of minutes without using HS to move a window, then the next time I try it, the first one has a noticeably annoying delay.

**Comment by cmsj** [comment]
Does `hs.window._timed_allWindows()` reveal anything useful?

**Comment by chdiza** [comment]
Well, I don't know what it's supposed to be showing.  It's not on hammerspoon.org/docs.

I can tell you it does show:
```
took 0.18s for com.apple.notificationcenterui
took 0.18s for com.apple.loginwindow
took 0.19s for com.apple.ViewBridgeAuxiliary
took 0.18s for com.apple.AirPlayUIAgent
took 0.20s for com.apple.dock
took 0.18s for com.apple.Safari
took 0.19s for com.apple.FolderActionsDispatcher
took 0.18s for com.apple.systemuiserver
took 0.18s for com.apple.dock.extra
took 0.18s for com.apple.coreservices.uiagent
took 0.19s for com.apple.cloudphotosd
took 0.18s for com.apple.Spotlight
took 0.19s for com.apple.wifi.WiFiAgent
took 0.20s for com.apple.finder
took 0.19s for com.apple.nbagent
```
Subsequent calls don't display any results.  It only shows things like `table: 0x60000167a700`.

**Comment by asmagill** [comment]
Just a thought -- I noticed a slowdown in Hammerspoon for *everything*, not just window movements, that got worse over time when I was running a 10.12 beta but Hammerspoon had been compiled on a 10.11 machine with Xcode 7.  I never really did figure out why, and I'd almost forgotten about it since it's gone away since I've started compiling Hammerspoon with Xcode 8 under 10.12 instead.

If you're not using a locally built Hammerspoon compiled with Xcode 8, are you able to build one?  I'd be curious to see if it makes a difference.

If it does make a difference, I guess we'll need to test an Xcode 8 build under 10.11 to see if that causes problems before we formally switch for the releases.

**Comment by chdiza** [comment]
I am already running a locally-built HS (that's all I ever do).

I just installed Xcode 8 on ElCap, so later today I can test whether a resulting HS build is also sluggish.

**Comment by agzam** [comment]
So, guys? I'm curious is it manageable? Or painfully slow? I still have not upgraded, but I'm thinking about it. Should I switch to Sierra?

**Comment by cmsj** [comment]
I tend to find that things only feel sluggish if they are loading a module for the first time. Do any other folks want to chime in with opinions?

@asmagill how much would your head explode if I suggested we start just linking all of the .so files into the main binary? :D

**Comment by asmagill** [comment]
@cmsj, I'd have to think about it to give a full answer, but off of the top of my head, it would mean that we could no longer provide an override to a core module by sticking it into the users ~/.hammerspoon directory during testing/debugging... instead the whole app would have to be recompiled every time a tweak or fix was made and needed to be tested.

Unless you're just talking about code in `hs._coresetup` which simply does a require of each module it finds... I'm assuming, however, that you're talking about linking them in at compile time.

At the very least, I'd hope that compile time linking was disabled for debug builds... it would still limit the ability to provide a test module for people with the release app to test (at least for core module modifications), but wouldn't penalize those of us who would otherwise have to recompile the application multiple times.

Re general slowness, most of what I'm noticing now is when I have multiple eventtaps running simultaneously.  I have an idea for a replacement in mind, but its going to be a while before I can properly implement and test it.

**Comment by agzam** [comment]
Ok, good to know that Hammerspoon is quite compatible with Sierra. Now, I just need to wait when Karabiner guys make it compatible too. I guess multiple eventtaps issue @asmagill is talking about might also be related to things that made Karabiner incompatible.

**Comment by chdiza** [comment]
It's manageable, but it hasn't gone away.  I wonder if AppNap is being a jerk.  (It shouldn't, since I believe I have globally disabled it.)

**Comment by latenitefilms** [comment]
Curious... was Hammerspoon 0.9.52 built on Xcode 8 running on macOS 10.12, or was it built on Xcode 7 still? I'm currently running a forked version of Hammerspoon on my local machine, (macOS 10.12.2 and Xcode 8.1) - but it still seems to have the same lagging issue after a certain amount of time.

We've found that Sierra definitely has some quirks. A lot of the issues I'm having in Sierra, simply don't happen in El Capitan (see: #1178 & #1180).

Our script has LOTS of `hs.hotkey` and `hs.eventtap` instances - and we're definitely seeing cases where having Hammerspoon open for long periods of time seems to eventually cause keyboard lagging (see: #1223).

@asmagill seems to be on the case for solving the `hs.eventtap` problems, which is awesome and very much appreciated!

I know I've already mentioned this a few times on other threads, but I wonder if the [PFiddlesoft PFEventTaps Framework 1.5.2](http://pfiddlesoft.com/frameworks/index-downloads.html) would be of any use to improve `hs.eventtap`? It's not open source, but it is "Free for Personal Use and for Use With Free Products". Thoughts @cmsj ?

**Comment by cmsj** [comment]
0.9.52 was definitely built with Xcode 8 on 10.12.

as for PFEventTaps, I'm generally opposed to us including non-open stuff for core features. We have to live with it for things like Crashlytics because there are no open source alternatives, but we could  remove it at any time without affecting our functionality, and we've taken steps to make sure it's only included in release builds. If we make a fundamental part of our feature set rely on something closed source, we're binding all possible users and forkers to that choice.

**Comment by cmsj** [comment]
@asmagill it's just something I've been thinking about recently - moving all of the OS interaction code out of the .so files into the main binary. It would indeed prevent people from being able to drop replacements into ~/.hammerspoon/.

I don't actually think it's a serious fix for performance issues, because it could only speed up loading C modules.

As for the performance lagging, my experience (which I think is similar to the others here) is that it tends to feel a little sluggish after it's been running for a while. We don't do very much caching, we don't keep a lot of complex data structures around, so my guess is that it's one of two things:

1) Lua is slowing down (maybe its memory allocator, maybe its data structures)
2) Less active parts of Hammerspoon are getting swapped to disk and cause a pause when they need to be paged back into RAM

I'm not currently aware of a good way to prove either of these hypotheses.

**Comment by latenitefilms** [comment]
> as for PFEventTaps, I'm generally opposed to us including non-open stuff for core features.

No worries - I completely get that. 

I would still be curious to see if using PFEventTaps would solve some of the issues we're currently seeing with `hs.hotkey` and `hs.eventtap` - but maybe that's just something I need to experiment with myself at some stage in the future, once I get my head around Objective-C a bit more. If nothing else, if using PFEventTaps does make a big different, at least then we know that the problem lies somewhere in the `hs.hotkey` and `hs.eventtap` code, as opposed to elsewhere in the app.

> As for the performance lagging, my experience (which I think is similar to the others here) is that it tends to feel a little sluggish after it's been running for a while.

This is a tricky one. It doesn't SEEM like Hammerspoon as a whole is slowing down. In my case at least, it only feels like the keyboard is laggy, and hotkeys take a few seconds to actually take effect.

Next time it happens, I'll see if Reloading Hammerspoon (as opposed to quitting the application and restarting) makes any difference. As far as I can remember, it doesn't - so I would ASSUME that as I'm pretty sure when you "reload" Hammerspoon it creates a completely new Lua instance, that it's not the Lua instance that's slowing things down - it's either something in the core Hammerspoon app, or maybe macOS is just too overloaded with Hammerspoon requests, that it just ignores Hammerspoon until you restart?

**Comment by cmsj** [comment]
@latenitefilms yeah that's a good idea actually, reloading the config destroys Lua and creates a completely new instance

**Comment by cmsj** [comment]
I'm going to close this issue out because it doesn't seem to be getting any traction. Anyone please feel free to re-open it if you want to work on this :)
